### ISSUE TITLE
Отчет о регистрации/перерегистрации

### ISSUE THREAD

**Issue by susloparov77** [shtrih-m/fr_drv_ng#10]
Здравствуйте не могли бы вы дать пример полный отчета о регистрации/перерегистрации?

**Comment by swex** [comment]
Нужно воспользоваться следующими методами:
В таблице **Фискальный Накопитель**(её номер отличается для разных моделей, его необходимо получить динамически)
```c++
ci->Set_ModelParamNumber(classic_interface::DPE_FsTableNumber);
checkError(ci->ReadModelParamValue());
auto fnTableNumber = ci->Get_ModelParamValue();
```
Записать требуемые значениями тегов.
Далее вызвать `FNBeginRegistrationReport`,
По желанию добавить теги к документу методом `FNSendTLV`
Сформировать документ методом `FNBuildRegistrationReport`.

**Comment by susloparov77** [comment]
Можете прислать любой пример или подскажите место в документации где есть этот пример?

**Comment by susloparov77** [comment]
Как записать параметры регистрации данные о магазине с помощью FNSendTLV:
-Наименование пользователя
-ИНН пользователя
-Адрес расчетов
-Место расчетов

ну и тд для ККТ:
- Заводской номер ККТ
- Регистрационный номер ККТ

**Comment by susloparov77** [comment]
Подскажите получили auto fnTableNumber = ci->Get_ModelParamValue();
Как записывать теги правильно?
Можно так:
    m_ci.Set_TagNumber(__tag);
    m_ci.Set_TagType(7); //Тип "строка"
    m_ci.Set_TagValueStr("12345");
    execute(std::bind(&classic_interface::FNSendTag, &m_ci));

**Comment by swex** [comment]
большинство тегов пишутся через таблицу fnTableNumber, через FNSendTag нужен только если хотите добавить к документу регистрации тег которого нет в таблице ФН

**Comment by susloparov77** [comment]
Как писать с помощью FNSendTag в таблицу fnTableNumber :
-Наименование пользователя
-ИНН пользователя
-Адрес расчетов
-Место расчетов
Что нибудь дайте как пример((?

**Comment by swex** [comment]
Нельзя записать в таблицу в помощью `FNSendTag`.
В таблицу пишется методом `WriteTable`
```c++
ci->Set_TableNumber(fsTableField); // номер таблицы фискальный накопитель
ci->Set_FieldNumber(7); //Наименование пользователя, например
ci->Set_RowNumber(1);
//ci->Set_ValueOfFieldInteger(123); // для числовых полей
ci->Set_ValueOfFieldString("Хороший пользователь");
checkResult(ci->WriteTable());
```

**Comment by susloparov77** [comment]
Супер)
ci->Set_FieldNumber(7); //Наименование пользователя, например
ci->Set_RowNumber(1);
 А где смотреть за что какое поле отвечает для этой таблицы?

**Comment by swex** [comment]
Посмотрите в [общем руководстве](https://www.shtrih-m.ru/docs/download.php?file=28010&iblock=21) и вообще посмотрите раздел Скачать->Документация :
https://www.shtrih-m.ru/catalog/onlayn-kassy/shtrikh-smartpos-f/

**Comment by Mzales** [comment]
Пример проверен, но не на КЯ.
```c++
    //к этому моменту должна быть закрыта смена в ФР и ФН, состояние ФН сброшено
    uint32_t adminPassword = 30;

    //заполняем таблицы
    //Наименование пользователя
    ci.Set_TableNumber(18);
    ci.Set_RowNumber(1);
    ci.Set_FieldNumber(7);
    ci.Set_ValueOfFieldString("new user");
    ci.WriteTable();

    //ИНН пользователя
    ci.Set_TableNumber(18);
    ci.Set_RowNumber(1);
    ci.Set_FieldNumber(2);
    ci.Set_ValueOfFieldString("000000000000");
    ci.WriteTable();

    //Адрес расчетов
    ci.Set_TableNumber(18);
    ci.Set_RowNumber(1);
    ci.Set_FieldNumber(9);
    ci.Set_ValueOfFieldString("new address");
    ci.WriteTable();

    //Место расчетов
    ci.Set_TableNumber(18);
    ci.Set_RowNumber(1);
    ci.Set_FieldNumber(14);
    ci.Set_ValueOfFieldString(u8"new place");
    ci.WriteTable();

    //Начать формировать отчет о регистрации ККТ
    ci.Set_Password(adminPassword);
    ci.Set_ReportTypeInt(1);//шифрование
    ci.FNBeginRegistrationReport();

    //Сформировать отчет о регистрации ККТ
    ci.Set_INN("000000000000");
    ci.Set_KKTRegistrationNumber("0000000837030527");
    ci.Set_TaxType(32);//ПСН
    ci.Set_WorkMode(1);//шифрование
    ci.FNBuildRegistrationReport();
```

**Comment by susloparov77** [comment]
Спасибо

**Comment by susloparov77** [comment]
Скажи или лучше пример как правильно записать 1BIN?

**Comment by susloparov77** [comment]
И не подскажете ci.Set_KKTRegistrationNumber("0000000837030527"); 
Запись в ci.Set_FieldNumber(3); Это один и тот же номер?

**Comment by swex** [comment]
Все методы, начинающиеся с `Set_` - это просто сеттеры свойств. В общем случае они ничего не делают. Ответ нет.

**Comment by susloparov77** [comment]
Про Set и get я знаю спасибо, дайте плиз пример как правильно записать 1BIN? Какой set... Вызвать и как его сформировать?

**Comment by susloparov77** [comment]
Как мне сохранить в Кя: режим 1056, 1056,1002,1001, 1109, 1110, 1108
    ci.Set_TableNumber(18);
    ci.Set_RowNumber(1);
    ci.Set_FieldNumber(6);
    ci.Set_... ЧЕГО???
    ci.WriteTable();

**Comment by susloparov77** [comment]
Я правильно понял пишу в десятичном виде битовую маску функцией Set_ValueOfFieldInteger ?

**Comment by susloparov77** [comment]
В документации нет тега 1036 куда его писать?

**Comment by Mzales** [comment]
Про [KKTRegistrationNumber](../wiki/Properties#group___properties_1ga222bf2fe1ebe04dd720ef0d67671d285).
 Есть два места, где он должен быть записан:
1) В 3-ем поле Таблицы 18
2) В параметре [KKTRegistrationNumber](../wiki/Properties#group___properties_1ga222bf2fe1ebe04dd720ef0d67671d285) функции [FNBuildRegistrationReport](../wiki/Methods#group___base_methods_1ga4c9c962a4a14b89e7e7fd88ab1ec0ba2).

Причем они должны совпадать, иначе ФР вернет ошибку 51 при вызове [FNBuildRegistrationReport](../wiki/Methods#group___base_methods_1ga4c9c962a4a14b89e7e7fd88ab1ec0ba2). 
В Таблице 18 на моем ФР это поле не редактируется. То есть вызывать [WriteTable](../wiki/Methods#group___base_methods_1ga83df009f846e41e399a47f4e2c843a97) бесполезно. Скорее, если Вы не знаете свой KKT, Вам нужно его из этой таблицы извлечь и положить в параметр  [KKTRegistrationNumber](../wiki/Properties#group___properties_1ga222bf2fe1ebe04dd720ef0d67671d285)
```c++
    \\читаем поле 3 таблицы 18, строковое значение кладем в переменную RNM
    ci.Set_TableNumber(18);
    ci.Set_RowNumber(1);
    ci.Set_FieldNumber(3);
    ci.ReadTable();
    auto RNM = ci.Get_ValueOfFieldString();

    //Начать формировать отчет о регистрации ККТ
    ci.Set_Password(adminPassword);
    ci.Set_ReportTypeInt(1);//шифрование
    ci.FNBeginRegistrationReport();

    //Сформировать отчет о регистрации ККТ
    ci.Set_INN("000000000000");
    ci.Set_KKTRegistrationNumber(RNM);
    ci.Set_TaxType(32);//ПСН
    ci.Set_WorkMode(1);//шифрование
    ci.FNBuildRegistrationReport();
```

**Comment by susloparov77** [comment]
ООО Спасибо огромное

**Comment by susloparov77** [comment]
Регистрация не проходит не подскажите что может быть?
[fr_drv(0).log](https://github.com/shtrih-m/fr_drv_ng/files/2542447/fr_drv.0.log)

**Comment by olefard** [comment]
На команду записи таблицы вернулось: > Get_ResultCodeDescription() -> `Table is undefined`
Номер таблицы надо получать через:
```
ci->Set_ModelParamNumber(classic_interface::DPE_FsTableNumber);
checkError(ci->ReadModelParamValue());
auto fnTableNumber = ci->Get_ModelParamValue();
```

**Comment by susloparov77** [comment]
А как узнать версию кассового ядра?

**Comment by olefard** [comment]
Через драйвер можно узнать так:
```
ci.GetECRStatus();
auto version = ci.Get_ECRSoftVersion();// версия ПО ККТ
auto build = ci.Get_ECRBuild();// номер сборки ПО ККТ
auto date = ci.Get_ECRSoftDate();// дата сборки ПО ККТ
```

**Comment by susloparov77** [comment]
Теперь мистика, как быть у меня в таблице 13 Фискальный накопитель теги, в полях ИНН пользователя 2 и регистрационный номер ККТ 3 - в обоих нет данных, записать туда их я не могу поскольку по документации эти поля только чтение.  Я подаю 0 одни долго ругалось на число знаков сначала сделал для инн 10 нулей, а для ккт 16, сделала 0:     
    ci.Set_INN("000000000000");
    ci.Set_KKTRegistrationNumber(RNM);
теперь новая ошибка:  51 "ККТ: Некорректные параметры в команде" "ККТ: Некорректные параметры в команде <0x0033000B: неверный РН ККТ (не совпадает контрольное число)>

Лог прилагаю, что делать?
[ffr_drv.log](https://github.com/shtrih-m/fr_drv_ng/files/2543007/ffr_drv.log)

**Comment by swex** [comment]
А что вы **пытаетесь** сделать?
1. ИНН не может быть нулями
2. РНМ содержит контрольное число, считается это число с использованием ЗН
3. Прописан ли заводской номер? Что в первом поле таблицы ФН?

**Comment by susloparov77** [comment]
Еще вопросик теперь ошибка 94 "ККТ: Неверная операция" "ККТ: Неверная операция <0x005E000E: в ФН открыт текущий документ 12h Отчет об изменении параметров регистрации в связи с заменой ФН, что не соответствует команде FF06H ФР> Что с ней делать?

**Comment by susloparov77** [comment]
Лог прилагаю
[fr_drv.log](https://github.com/shtrih-m/fr_drv_ng/files/2543165/fr_drv.log)

**Comment by swex** [comment]
Попробуйте вместо `FNBuildRegistrationReport` вызвать `FNBuildReregistrationReport`

**Comment by susloparov77** [comment]
Новая 51 "ККТ: Некорректные параметры в команде" "ККТ: Некорректные параметры в команде <0x0033001A: в параметре Код причины перерегистрации значение 2, 3 или 4>

**Comment by susloparov77** [comment]
Лог прилагаю
[fr_drv.log](https://github.com/shtrih-m/fr_drv_ng/files/2543236/fr_drv.log)

**Comment by olefard** [comment]
Для FNBuildReregistrationReport надо заполнить Set_RegistrationReasonCode.

**Comment by susloparov77** [comment]
подскажите чем записать 
Поле 5 : *ФН: код системы налогообложения, 1062 
Поле 6 : *ФН: режим работы, 1056,1002,1001, 1109, 1110, 1108**
 И правильно ли я пишу разряды, старшие справа:
        QString agent( QString::number(__fiscalize->m_agent_bit6) +
                       QString::number(__fiscalize->m_agent_bit5) +
                       QString::number(__fiscalize->m_agent_bit4) +
                       QString::number(__fiscalize->m_agent_bit3) +
                       QString::number(__fiscalize->m_agent_bit2) +
                       QString::number(__fiscalize->m_agent_bit1) +
                       QString::number(__fiscalize->m_agent_bit0) );
        if(!writeFiscalInt(agent.toInt(nullptr, 2), fnTableNumber, 16)) return;

**Comment by olefard** [comment]
Разряды пишете правильно, старшие слева.

Собственно:
 - бит 0 = 1
...
 - бит 6 = 64

**Comment by swex** [comment]
из "Общее руководство по настройке ККТ"
![image](https://user-images.githubusercontent.com/1026241/48055805-77d22a80-e1c1-11e8-99dd-ea1809f77bb0.png)
![image](https://user-images.githubusercontent.com/1026241/48055834-8b7d9100-e1c1-11e8-80e5-d7d20a9d67ae.png)

**Comment by susloparov77** [comment]
Да это все понятно я так и сделал)). Но :
    m_ci.Set_TableNumber(__table);
    m_ci.Set_RowNumber(__row);
    m_ci.Set_FieldNumber(__field);
    m_ci.Set_ValueOfFieldInteger(__value);
    return execute(std::bind(&classic_interface::WriteTable, &m_ci));
Так писать нельзя они readonly Чем записать? Какая функция

**Comment by swex** [comment]
TaxMode

**Comment by susloparov77** [comment]
Скажите есть tag 1036 - номер автомата он есть в sdk у вас?

**Comment by swex** [comment]
на СМАРТПОСе его можно передать командой `FNSendTag`.

**Comment by susloparov77** [comment]
У меня получилось сделать отчет о перерегистрации, вот мой код:

        //Начать формировать отчет о регистрации ККТ
        m_ci.Set_ReportTypeInt(1);
        if(!execute(std::bind(&classic_interface::FNBeginRegistrationReport, &m_ci))) return;
        //Сформировать отчет о регистрации ККТ
        m_ci.Set_INN(__fiscalize->m_inn.toStdString());
        m_ci.Set_KKTRegistrationNumber(__fiscalize->m_regNumberKKT.toStdString());
        m_ci.Set_TaxType(taxType.toInt(nullptr, 2));//ПСН
        m_ci.Set_WorkMode(modeWork.toInt(nullptr, 2));//шифрование
        m_ci.Set_RegistrationReasonCode(1);
//        if(execute(std::bind(&classic_interface::FNBuildRegistrationReport, &m_ci)))
        if(execute(std::bind(&classic_interface::FNBuildReregistrationReport, &m_ci)))
        {
            qInfo() << QObject::tr("Успешная регистрация ФН для KKT Smart...");
        };
На чеке печатается "отчет о перерегистрации".
Скажите как сделать отчет о первичной регистрации? на чеке должно печататься "отчет о регистрации"???

**Comment by olefard** [comment]
Вот так делается отчет о регистрации:
```
//Начать формировать отчет о регистрации ККТ
m_ci.Set_ReportTypeInt(0);// 0 = Отчет о регистрации КТТ
m_ci.FNBeginRegistrationReport();

//Сформировать отчет о регистрации ККТ
m_ci.Set_INN(__fiscalize->m_inn.toStdString());
m_ci.Set_KKTRegistrationNumber(__fiscalize->m_regNumberKKT.toStdString());
m_ci.Set_TaxType(taxType.toInt(nullptr, 2));//ПСН
m_ci.Set_WorkMode(modeWork.toInt(nullptr, 2));//шифрование
m_ci.FNBuildRegistrationReport();
```

**Comment by susloparov77** [comment]
Спасибо закрываем).
