### ISSUE TITLE
Changelog версий драйвера

### ISSUE THREAD

**Issue by kaverdo** [shtrih-m/fr_drv_ng#100]
Имеется ли возможность публиковать список изменений, выполненных в очередной версии драйвера?

Одновременно с обновлением драйвера с 1.4.4-7 до 1.4.4-12 стали регулярно возникать потери связи драйвера с ККТ (ошибка -1) при регистрации позиции (метод FNOperation). Более подробную информацию с fr_drv.log пытаемся собрать.

Возможно ли, что в версиях между 1.4.4-7 и 1.4.4-12 были связанные с проблемой изменения?
Есть ли информация, правилось ли что-то связанное с этим между 1.4.4-12 и 1.4.5?

Спасибо!

**Comment by swex** [comment]
Changelog можно посмотреть в сообщении к [коммитам](https://github.com/shtrih-m/fr_drv_ng/commits/master) в этом репо.
