### ISSUE TITLE
Тест нативного драйвера 1С: сумма оплаты >> суммы чека [LINUX][1C nativ]

### ISSUE THREAD

**Issue by surfernsk** [shtrih-m/fr_drv_ng#103]
Добрый день, подключили тестовую версию нативного драйвера 1С-Linux.
Обнаружена следящая ошибка:
в чек добавлен товар стоимостью 28.00 руб
```
02 2e ff 46 1e 00 00 00 01
40 42 0f 00 00 00
f0 0a 00 00 00
f0 0a 00 00 00
ff ff ff ff ff
08
01
04
01 
d1 e0 f5 e0 f0 ed fb e9 20 ef e5 f1 ee ea
```
Закрытие чека в 1С, оплата 28.00 руб (безнал)
```
Команда:
02 76 ff 45 1e 00 00 00 00 00 00 00 00 c0 45 04
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 98 3a 00 00 e8 08 11

Ответ:
02 03 ff 45 4d f4
```
Сумма оплаты в команде [c0 45 04 00 00] - 280000 коп (2800 руб)
также при оплате наличными, только чек закрыт успешно ( с подсчетом сдачи 2772.00)
![doc0446](https://user-images.githubusercontent.com/2264893/79196293-05578680-7e5a-11ea-96a2-d87090d428f7.png)

**Comment by olefard** [comment]
А можете выложить лог с этим чеком. Он в файле fr_drv.log или можно указать путь, если задать переменную окружения FR_DRV_LOG_PATH.

**Comment by surfernsk** [comment]
Лог 
[fr_drv.log](https://github.com/shtrih-m/fr_drv_ng/files/4473908/fr_drv.log)

**Comment by swex** [comment]
Поправлено в 1.5.0 можно забрать в релизах.

**Comment by surfernsk** [comment]
версия 0.1.2.74 - полет нормальный
версия 0.1.2.78 - Ошибка!

0.1.2.78:
![43234234](https://user-images.githubusercontent.com/2264893/79414991-51c7d100-7fd6-11ea-9dab-4060f4490db6.png)

**Comment by olefard** [comment]
В 0.1.2.78 сменили progid и название на более "красивые". Похоже ошибка из-за этого.

Попробуйте или в существующем устройстве поменять драйвер на "ШТРИХ-М:ККТ с передачей данных в ОФД (54-ФЗ) **NG**" или создать новое.

**Comment by surfernsk** [comment]
Ошибка получения описания драйвера
{ОбщийМодуль.ПодключаемоеОборудованиеУниверсальныйДрайверКлиент.Модуль(3113)}: Поле объекта не обнаружено (ВерсияДрайвера)

![23232](https://user-images.githubusercontent.com/2264893/79431352-85b1ef00-7ff4-11ea-9d9a-bfaec8887096.png)

**Comment by surfernsk** [comment]
версия 0.1.2.79 - полет нормальный.
спасибо

**Comment by swex** [comment]
one_s 0.1.2.79 в [релизах](https://github.com/shtrih-m/fr_drv_ng/releases) это закрываю
