### ISSUE TITLE
Как получить данные из последнего напечатанного чека

### ISSUE THREAD

**Issue by rbvrbv** [shtrih-m/fr_drv_ng#104]
стоит задача получить данные из последнего напечатанного чека - систему налогообложения, название и адрес организации, физическое место расчетов, значение QR-кода.
Какими методами API это сделать?

**Comment by surfernsk** [comment]
Получите номер последнего документа, и далее получите документ по номеру

**Comment by rbvrbv** [comment]
Вот результат команды

**Comment by rbvrbv** [comment]
Вот результат команды FNGetDocumentAsString
НОМЕР ФН:9999078902004760
РЕГ. НОМЕР ККТ:0000000001032078    
ИНН ПОЛЬЗ.:6608003052  
НОМЕР ФД:258
ДАТА, ВРЕМЯ:28.04.20 16:59:00
ФП ДОКУМЕНТА:680441687
НОМЕР СМЕНЫ:61
НОМЕР ЧЕКА ЗА СМЕНУ:2
ПРИЗН. РАСЧЕТА:Приход
СУММА РАСЧЕТА В ЧЕКЕ(БСО):3.00 rub.
ВЕРСИЯ ФФД:2
КАССИР:КАССИР 310852 BORIS RYAPOSOV
АДР. САЙТА ФНС:www.nalog.ru
ПРЕДМ. РАСЧЕТА
 НАИМЕН. ПРЕДМ. РАСЧЕТА:Товар со свободной ценой
 ЦЕНА ЗА ЕД. ПРЕДМ. РАСЧ.:3.00 rub.
 КОЛ-ВО ПРЕДМ. РАСЧЕТА:1
 СТОИМ. ПРЕДМ. РАСЧЕТА:3.00 rub.
 СТАВКА НДС:1
 СУММА НДС ЗА ПРЕДМ. РАСЧ.:0.50 rub.
 ПРИЗН. СПОСОБА РАСЧ.:4
 ПРИЗН. ПРЕДМЕТА РАСЧ.:1
ПРИМЕН. СИСТ. НАЛОГООБЛОЖЕНИЯ:ОСН
СУММА НДС ЧЕКА 18%:0.50 rub.
СУММА ПО ЧЕКУ НАЛ (БСО):3.00 rub.
СУММА ПО ЧЕКУ ЭЛЕКТРОННЫМИ(БСО):0.00 rub.
СУММА ПО ЧЕКУ БСО ПРЕДОПЛ.:0.00 rub.
СУММА ПО ЧЕКУ БСО ПОСТОПЛ.:0.00 rub.
СУММА ПО ЧЕКУ БСО ВСТРЕЧН. ПРЕДОСТ.:0.00 rub.

Данные о вышеуказанных данных отсутствуют.
Как их можно получить?

**Comment by surfernsk** [comment]
Каких данных нехватает?

**Comment by rbvrbv** [comment]
"...систему налогообложения, название и адрес организации, физическое место расчетов, значение QR-кода."

**Comment by surfernsk** [comment]
@rbvrbv каких конкретно данных нет?

**Comment by rbvrbv** [comment]
"...систему налогообложения, название и адрес организации, физическое место расчетов, значение QR-кода."
Не знаю, как еще объяснить

**Comment by surfernsk** [comment]
@rbvrbv 
> ПРИМЕН. СИСТ. НАЛОГООБЛОЖЕНИЯ:ОСН

> значение QR-кода.

В соответствии со статьей 4 Федерального закона 54-ФЗ онлайн кассы должны обеспечивать возможность печати на кассовом чеке QR-кода. Размером кода должен составлять не менее 20 x 20 мм.

QR-код содержит в кодированном виде реквизиты проверки кассового чека (БСО):

1. дата и время осуществления расчета;
2. порядковый номер фискального документа;
3. признак расчета;
4. сумма расчета;
5. заводской номер фискального накопителя;
6. фискальный признак документа.

Главная функция QR-кода – предоставлять возможность покупателям проверять чек, а также сообщать о выявленных нарушениях в налоговую.

**Comment by surfernsk** [comment]
@rbvrbv обязательно ознакомтесь с [Описание кассового чека при реализации товара с использованием ФФД 1.1](http://www.consultant.ru/document/cons_doc_LAW_302551/25d926a9828d5d14e4b41a8250b5b6e7e9e4a5ee/)

**Comment by swex** [comment]
добавлю сюда то что ответил @rbvrbv в чате:

> Реквизиты "наименование пользователя" (тег 1048), "ИНН пользователя" (тег 1018), "адрес сайта ФНС" (тег 1060), "адрес электронной почты отправителя чека" (тег 1117), "номер автомата" (тег 1036), "адрес расчетов" (тег 1009), "место расчетов" (тег 1187), должны быть включены в состав кассового чека (БСО) при его передаче ОФД в электронной форме в случае, если указанные реквизиты ранее не были переданы ОФД в составе отчета о регистрации или отчета об изменении параметров регистрации.


чтобы найти документ регистрации можно использовать методы `FNFindDocument` или `FNGetFiscalizationResult`
и далее получить документ по номеру как и раньше `FNGetDocumentAsString`

**Comment by olefard** [comment]
Система налогообложения выдается:
```ПРИМЕН. СИСТ. НАЛОГООБЛОЖЕНИЯ:ОСН```

В QR-коде сожержится следующий текст:
```t=<ДАТА, ВРЕМЯ>&s=<СУММА РАСЧЕТА В ЧЕКЕ(БСО)>&fn=<НОМЕР ФН>&i=<НОМЕР ФД>&fp=<ФП ДОКУМЕНТА>&n=<ПРИЗН. РАСЧЕТА>```

Для чека выше в qr-коде будет:
```t=20200428T165900&s=3.00&fn=9999078902004760&i=258&fp=680441687&n=1```

**Comment by swex** [comment]
добавлю еще: если используете ККТ на основе КЯ - то в таблице 11 есть 3 поля:
- 18 QR-данные последнего закрытого чека 1
- 19 QR-данные последнего закрытого чека 2
- 20 QR-данные последнего закрытого чека 3
