### ISSUE TITLE
В macOS не подключается библиотека classic_fr_drv_ng

### ISSUE THREAD

**Issue by id-thx1138** [shtrih-m/fr_drv_ng#106]
Не получается подключить библиотеку к проекту. В линуксе, аналогичный способ сборки работает, а с версией 'darvin' не очень понятно, что подключать, .dylib есть только с Qt, а нужна библиотека, которая просто реализует 'classic_interface.h'. 
По аналогии с linux, пробую подключить `darwin_1.5.0.536/x86_64/classic_fr_drv_ng.framework/Versions/C/classic_fr_drv_ng`, но во первых система почему-то определяет данный файл как исполняемый, а во вторых gcc просто не находит библиотеки.
Подключаю такой командой в Makefile:
```
LIB_PATH=./../darwin_1.5.0.536/x86_64/classic_fr_drv_ng.framework/Versions/C
g++ -std=c++11 $(INCLUDEPATH) ./src/main.c -L$(LIB_PATH) -lclassic_fr_drv_ng -o fr_test

```
получаю ошибку линковки:
```
ld: library not found for -lclassic_fr_drv_ng
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [manual] Error 1

```
При этом аналогичная команда gcc в linux отлично работает.
Система macOS Catalina.

**Comment by surfernsk** [comment]
@id-thx1138  по этому пути: `LIB_PATH=./../darwin_1.5.0.536/x86_64/classic_fr_drv_ng.framework/Versions/C`
есть библиотека с которой происходит линковка?

**Comment by id-thx1138** [comment]
Очевидно, что нет) там находится исполняемый файл, назначение которого мне не известно.
Смотрите, я взял 'fr_drv_ng_darwin_x86_64_1.5.0-2-g235484c.zip' из релиза https://github.com/shtrih-m/fr_drv_ng/releases/tag/1.5.0-2-g235484c, распаковал его, и собирал проект аналогично тому, как я делал это в linux. 
Структура папок ./../darwin_1.5.0.536 такая же как в архиве из релиза, можете посмотреть что там есть, я не смог найти там никакой другой библиотеки кроме как 'libqclassic_fr_drv_ng.dylib' - которая, очевидно, зависит от Qt и реализует другой интерфейс, а именно 'qclassic_interface.h' 
Не могли бы вы указать мне где находится cpp библиотека, реализующая именно 'classic_interface.h'?
Возможно, ее как-то забыли включить в релизную сборку...

**Comment by surfernsk** [comment]
@id-thx1138 
> Очевидно, что нет) там находится исполняемый файл, назначение которого мне не известно.

Это библиотека

 ```
file dist/darwin_1.5.0.536/x86_64/classic_fr_drv_ng.framework/Versions/Current/classic_fr_drv_ng
classic_fr_drv_ng: Mach-O 64-bit x86_64 dynamically linked shared library, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK|NO_REEXPORTED_DYLIBS|HAS_TLV_DESCRIPTORS>

**Comment by id-thx1138** [comment]
Как в таком случае ее слинковать с проектом? Мой путь правильный, т.к. Current это ссылка на папку "C", но компилятор не находит библиотеку, если подключать ее как -lclassic_fr_drv_ng

**Comment by id-thx1138** [comment]
Я пробовал добавить эту библиотеку в проекте Xcode - там можно явно указать подключаемую библиотеку, там тоже не получилось подключить библиотеку
`dyld: Library not loaded: @rpath/classic_fr_drv_ng.framework/Versions/C/classic_fr_drv_ng`

**Comment by surfernsk** [comment]
@id-thx1138 библиотеку или framework?

**Comment by id-thx1138** [comment]
Честно говоря я не знаю как это устроено в Xcode - нужно было подключать фреймворк?

**Comment by id-thx1138** [comment]
Проблема решена, оказалось, что нужно в настройках проекта Xcode установить у импортированного фреймворка значение  `Embed Without Signing`

https://stackoverflow.com/questions/24993752/os-x-framework-library-not-loaded-image-not-found
