### ISSUE TITLE
Данные о неотправленных чеках в ОФД

### ISSUE THREAD

**Issue by dimailn** [shtrih-m/fr_drv_ng#107]
Здравствуйте! Не смог найти пример, как получить через sdk данные о неотправленных в ОФД чеках. Интересует в первую очередь количество неотправленных чеков и дата первого неотправленного чека.

**Comment by surfernsk** [comment]
Здравствуйте, FNGetInfoExchangeStatus() разве не подходит?

**Comment by dimailn** [comment]
Да, то что надо, спасибо!
