### ISSUE TITLE
Проблема при команде Connect()

### ISSUE THREAD

**Issue by ConsperSerj** [shtrih-m/fr_drv_ng#108]
Всем привет. Ребята нужна помощь. 

Железка PAX A930 - android девайс

Пытаюсь получить подключение. Ответ -1. Connect fail

Почитав ранее ваши ответы сделал следующее: Подключил девайс через шнур, прописал ему для дебага api через adb. После этого отключил железку от шнурка. У меня студия видит железку и я могу компилить свою прилу

По коду:
const val SYS_ADMIN_PASSWORD = 30L
const val IP_ADDRESS = "127.0.0.1"
const val TCP_PORT = 12345 
const val TIMEOUT = 30000
const val PROTOCOL_TYPE = 2 

 Set_Password(1)
 Set_SysAdminPassword(SYS_ADMIN_PASSWORD)
  Set_ConnectionType(Tcp)        
 Set_UseIPAddress(true)    
 Set_IPAddress(IP_ADDRESS)     
  Set_TCPPort(TCP_PORT)         
Set_Timeout(TIMEOUT)          
Set_ProtocolType(PROTOCOL_TYPE) 

 val code = Connect().toLong() 

По логе:
V/fr_drv_ng: [2020-05-14 16:57:55.352] [4487] [classic_interface_0x95f03c80    ] [T] Set_Password(`1`)
V/fr_drv_ng: [2020-05-14 16:57:55.353] [4487] [classic_interface_0x95f03c80    ] [T] Set_Password() ok
V/fr_drv_ng: [2020-05-14 16:57:56.414] [4487] [classic_interface_0x95f03c80    ] [T] Set_SysAdminPassword(`30`)
    [2020-05-14 16:57:56.414] [4487] [classic_interface_0x95f03c80    ] [T] Set_SysAdminPassword() ok
V/fr_drv_ng: [2020-05-14 16:57:56.847] [4487] [classic_interface_0x95f03c80    ] [T] Set_ConnectionType(`Tcp`)
D/fr_drv_ng: [2020-05-14 16:57:56.848] [4487] [classic_interface_0x95f03c80    ] [D] updated ConnectionURI:tcp://192.168.137.111:7778?timeout=15000&protocol=v1
V/fr_drv_ng: [2020-05-14 16:57:56.848] [4487] [classic_interface_0x95f03c80    ] [T] Set_ConnectionType() ok
V/fr_drv_ng: [2020-05-14 16:57:57.292] [4487] [classic_interface_0x95f03c80    ] [T] Set_UseIPAddress(`true`)
D/fr_drv_ng: [2020-05-14 16:57:57.293] [4487] [classic_interface_0x95f03c80    ] [D] updated ConnectionURI:tcp://192.168.137.111:7778?timeout=15000&protocol=v1
V/fr_drv_ng: [2020-05-14 16:57:57.293] [4487] [classic_interface_0x95f03c80    ] [T] Set_UseIPAddress() ok
V/fr_drv_ng: [2020-05-14 16:57:57.718] [4487] [classic_interface_0x95f03c80    ] [T] Set_IPAddress(`127.0.0.1`)
D/fr_drv_ng: [2020-05-14 16:57:57.718] [4487] [classic_interface_0x95f03c80    ] [D] updated ConnectionURI:tcp://127.0.0.1:7778?timeout=15000&protocol=v1
V/fr_drv_ng: [2020-05-14 16:57:57.718] [4487] [classic_interface_0x95f03c80    ] [T] Set_IPAddress() ok
V/fr_drv_ng: [2020-05-14 16:57:58.334] [4487] [classic_interface_0x95f03c80    ] [T] Set_TCPPort(`12345`)
D/fr_drv_ng: [2020-05-14 16:57:58.335] [4487] [classic_interface_0x95f03c80    ] [D] updated ConnectionURI:tcp://127.0.0.1:12345?timeout=15000&protocol=v1
V/fr_drv_ng: [2020-05-14 16:57:58.335] [4487] [classic_interface_0x95f03c80    ] [T] Set_TCPPort() ok
V/fr_drv_ng: [2020-05-14 16:57:58.913] [4487] [classic_interface_0x95f03c80    ] [T] Set_Timeout(`30000`)
D/fr_drv_ng: [2020-05-14 16:57:58.914] [4487] [classic_interface_0x95f03c80    ] [D] updated ConnectionURI:tcp://127.0.0.1:12345?timeout=30000&protocol=v1
V/fr_drv_ng: [2020-05-14 16:57:58.914] [4487] [classic_interface_0x95f03c80    ] [T] Set_Timeout() ok
V/fr_drv_ng: [2020-05-14 16:57:59.590] [4487] [classic_interface_0x95f03c80    ] [T] Set_ProtocolType(`2`)
D/fr_drv_ng: [2020-05-14 16:57:59.590] [4487] [classic_interface_0x95f03c80    ] [D] updated ConnectionURI:tcp://127.0.0.1:12345?timeout=30000&protocol=v1
V/fr_drv_ng: [2020-05-14 16:57:59.590] [4487] [classic_interface_0x95f03c80    ] [T] Set_ProtocolType() ok
V/fr_drv_ng: [2020-05-14 16:58:00.920] [4487] [classic_interface_0x95f03c80    ] [T] Connect()
I/fr_drv_ng: [2020-05-14 16:58:00.920] [4487] [getIoFromString                 ] [I] io_url looks good: tcp://127.0.0.1:12345?timeout=30000&protocol=v1
I/fr_drv_ng: [2020-05-14 16:58:00.920] [4487] [getIoFromString                 ] [I] type: tcp
    [2020-05-14 16:58:00.921] [4487] [getIoFromString                 ] [I] path: 127.0.0.1
I/fr_drv_ng: [2020-05-14 16:58:00.922] [4487] [getProtocolFromString           ] [I] protocol v1
    [2020-05-14 16:58:00.922] [4487] [getTimeout                      ] [I] timeout: 30000
    [2020-05-14 16:58:00.922] [4487] [ProtocolV1_0x95e68000           ] [I] setTimeout(30000ms)
I/fr_drv_ng: [2020-05-14 16:58:00.923] [4487] [getCheckStateType               ] [I] enq_mode: auto
    [2020-05-14 16:58:00.923] [4487] [ProtocolV1_0x95e68000           ] [I] timeout: 30000
    [2020-05-14 16:58:00.923] [4487] [TcpSocketIO_0xae5ea510          ] [I] IO timeout = 30000ms
W/fr_drv_ng: [2020-05-14 16:58:00.923] [4487] [TcpSocketIO_0xae5ea510          ] [W] open() false
W/fr_drv_ng: [2020-05-14 16:58:00.924] [4487] [ProtocolV1_0x95e68000           ] [W] connect() false
D/fr_drv_ng: [2020-05-14 16:58:00.924] [4487] [classic_interface_0x95f03c80    ] [D] Connect() fail
E/fr_drv_ng: [2020-05-14 16:58:00.924] [4487] [classic_interface_0x95f03c80    ] [E] Inout error

При этом выкачал все самые последние либы - думал дело в этом.

Подскажите пожалуйста что еще может быть не так?

**Comment by swex** [comment]
1. лучше использовать protocol v2, чтобы использовать "второй" протокол, нужно передать в Set_ProtocolType(1)
```c++
    //!
    //! @brief Тип протокола.
    //!
    //! | Значение | Протокол         |
    //! |----------|--------------------------|
    //! |    0     | Cтандартный      |
    //! |    1     | Протокол ККТ 2.0 |
    //!
    //! @par Методы доступа:
    //!   #Get_ProtocolType, #Set_ProtocolType
    //!
    //! @par Используется методами:
    //!   #Connect
    //!
    DOXYGEN_PROPERTY(int ProtocolType)
```
2. Можно все настройки соединения передать строкой через Set_ConnectionURI
3. точно порт не занят? КЯ поддерживает только одно соединение и не принимает следующее пока жива пред. сессия

**Comment by ConsperSerj** [comment]
1) Пробовал протоколы версии V1 и V2 - результат один и тот же
2) Я знаю, спасибо. Так пишу по причине того чтобы все максимально наглядно было. Таков запрос от заказчика
3) Пробовал сделать даже следующее - ребутнуть девайс. Запустить ядро. После этого прописать чтобы отладка была не через шнурок. Запускаю свою прилу с этим котод и результат такой же

**Comment by ConsperSerj** [comment]
V/fr_drv_ng: [2020-05-14 17:10:28.387] [4910] [classic_interface_0x95f03c80    ] [T] Set_Password(`1`)
    [2020-05-14 17:10:28.387] [4910] [classic_interface_0x95f03c80    ] [T] Set_Password() ok
V/fr_drv_ng: [2020-05-14 17:10:28.932] [4910] [classic_interface_0x95f03c80    ] [T] Set_SysAdminPassword(`30`)
    [2020-05-14 17:10:28.932] [4910] [classic_interface_0x95f03c80    ] [T] Set_SysAdminPassword() ok
V/fr_drv_ng: [2020-05-14 17:10:29.362] [4910] [classic_interface_0x95f03c80    ] [T] Set_ConnectionType(`Tcp`)
D/fr_drv_ng: [2020-05-14 17:10:29.362] [4910] [classic_interface_0x95f03c80    ] [D] updated ConnectionURI:tcp://192.168.137.111:7778?timeout=15000&protocol=v1
V/fr_drv_ng: [2020-05-14 17:10:29.362] [4910] [classic_interface_0x95f03c80    ] [T] Set_ConnectionType() ok
V/fr_drv_ng: [2020-05-14 17:10:29.752] [4910] [classic_interface_0x95f03c80    ] [T] Set_UseIPAddress(`false`)
D/fr_drv_ng: [2020-05-14 17:10:29.752] [4910] [classic_interface_0x95f03c80    ] [D] updated ConnectionURI:tcp://192.168.137.111:7778?timeout=15000&protocol=v1
V/fr_drv_ng: [2020-05-14 17:10:29.752] [4910] [classic_interface_0x95f03c80    ] [T] Set_UseIPAddress() ok
V/fr_drv_ng: [2020-05-14 17:10:30.156] [4910] [classic_interface_0x95f03c80    ] [T] Set_IPAddress(`127.0.0.1`)
D/fr_drv_ng: [2020-05-14 17:10:30.157] [4910] [classic_interface_0x95f03c80    ] [D] updated ConnectionURI:tcp://192.168.137.111:7778?timeout=15000&protocol=v1
V/fr_drv_ng: [2020-05-14 17:10:30.157] [4910] [classic_interface_0x95f03c80    ] [T] Set_IPAddress() ok
V/fr_drv_ng: [2020-05-14 17:10:30.524] [4910] [classic_interface_0x95f03c80    ] [T] Set_TCPPort(`12345`)
D/fr_drv_ng: [2020-05-14 17:10:30.524] [4910] [classic_interface_0x95f03c80    ] [D] updated ConnectionURI:tcp://192.168.137.111:12345?timeout=15000&protocol=v1
V/fr_drv_ng: [2020-05-14 17:10:30.524] [4910] [classic_interface_0x95f03c80    ] [T] Set_TCPPort() ok
V/fr_drv_ng: [2020-05-14 17:10:30.917] [4910] [classic_interface_0x95f03c80    ] [T] Set_Timeout(`20000`)
D/fr_drv_ng: [2020-05-14 17:10:30.917] [4910] [classic_interface_0x95f03c80    ] [D] updated ConnectionURI:tcp://192.168.137.111:12345?timeout=20000&protocol=v1
V/fr_drv_ng: [2020-05-14 17:10:30.917] [4910] [classic_interface_0x95f03c80    ] [T] Set_Timeout() ok
V/fr_drv_ng: [2020-05-14 17:10:31.530] [4910] [classic_interface_0x95f03c80    ] [T] Set_ProtocolType(`1`)
D/fr_drv_ng: [2020-05-14 17:10:31.530] [4910] [classic_interface_0x95f03c80    ] [D] updated ConnectionURI:tcp://192.168.137.111:12345?timeout=20000&protocol=v2
V/fr_drv_ng: [2020-05-14 17:10:31.530] [4910] [classic_interface_0x95f03c80    ] [T] Set_ProtocolType() ok
V/fr_drv_ng: [2020-05-14 17:10:32.045] [4910] [classic_interface_0x95f03c80    ] [T] Connect()
I/fr_drv_ng: [2020-05-14 17:10:32.046] [4910] [getIoFromString                 ] [I] io_url looks good: tcp://192.168.137.111:12345?timeout=20000&protocol=v2
    [2020-05-14 17:10:32.046] [4910] [getIoFromString                 ] [I] type: tcp
    [2020-05-14 17:10:32.046] [4910] [getIoFromString                 ] [I] path: 192.168.137.111
I/fr_drv_ng: [2020-05-14 17:10:32.047] [4910] [getProtocolFromString           ] [I] protocol v2
I/fr_drv_ng: [2020-05-14 17:10:32.048] [4910] [getTimeout                      ] [I] timeout: 20000
    [2020-05-14 17:10:32.048] [4910] [ProtocolV2_0x95e7b000           ] [I] setTimeout(20000ms)
    [2020-05-14 17:10:32.048] [4910] [ProtocolV2_0x95e7b000           ] [I] timeout: 20000
    [2020-05-14 17:10:32.048] [4910] [TcpSocketIO_0xae5eaf90          ] [I] IO timeout = 20000ms
W/fr_drv_ng: [2020-05-14 17:10:32.050] [4910] [TcpSocketIO_0xae5eaf90          ] [W] open() false
    [2020-05-14 17:10:32.051] [4910] [ProtocolV2_0x95e7b000           ] [W] connect() false
D/fr_drv_ng: [2020-05-14 17:10:32.051] [4910] [classic_interface_0x95f03c80    ] [D] Connect() fail
E/fr_drv_ng: [2020-05-14 17:10:32.051] [4910] [classic_interface_0x95f03c80    ] [E] Inout error
V/fr_drv_ng: [2020-05-14 17:10:53.404] [4910] [classic_interface_0x95f03c80    ] [T] Get_Connected()
    [2020-05-14 17:10:53.405] [4910] [classic_interface_0x95f03c80    ] [T] Get_Connected() -> `false`
V/fr_drv_ng: [2020-05-14 17:10:54.191] [4910] [classic_interface_0x95f03c80    ] [T] Disconnect()
    [2020-05-14 17:10:54.191] [4910] [classic_interface_0x95f03c80    ] [T] Disconnect() ok
I/art: Starting a blocking GC Explicit

**Comment by ConsperSerj** [comment]
Вот подтверждение моих слов по поводу второго протокола

**Comment by swex** [comment]
а пермишены правильные в манифесте есть?
```xml
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```

**Comment by ConsperSerj** [comment]
Я так же пробовал все настройки передавать через URL. результат такой же

**Comment by ConsperSerj** [comment]
Кстати пермишены, про них совсем забыл. Сейчас чекну.

**Comment by ConsperSerj** [comment]
Пермишены тоже есть.

**Comment by ConsperSerj** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="ru.lifepay.periphery.drivers.shtrihfiscalcoreapp">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:usesCleartextTraffic="true"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>

**Comment by ConsperSerj** [comment]
Ребят спасибо. Я кажись понял в чем была моя ошибка

**Comment by swex** [comment]
ок, закрываем
