### ISSUE TITLE
Информация о лицензии

### ISSUE THREAD

**Issue by t0pd3v1c3** [shtrih-m/fr_drv_ng#110]
Каким образом можно получить текст информации о лицензии:

> Лицензия "20% НДС": без ограничения
Лицензия "ФФД 1.1": отсутствует
Лицензия "маркировка базовая": без ограничения
Подписка на обновление: действительна с 01.01.2019 по 31.12.2019

Команда ReadFeatureLicenses возвращает License, но в виде:
`FE000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000`

Как можно расшифрованную информацию получить?

**Comment by swex** [comment]
каждый байт в этой hex строке - это количество месяцев в течение которые лицензия действует. или бесконечная, если FF или FE
Сами лицензии пока такие:
0 - лицензия на НДС 20% и новые названия тегов
1 - лицензия на ФФД 1.1
2 - лицензия на работу с кодами маркировки

**Comment by t0pd3v1c3** [comment]
Почему тогда здесь такая разница?

> FE000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
> Лицензия "20% НДС": без ограничения
> Лицензия "ФФД 1.1": отсутствует
> Лицензия "маркировка базовая": без ограничения
> Подписка на обновление: действительна с 01.01.2019 по 31.12.2019 

> FF000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
> Лицензия "20% НДС": без ограничения
> Лицензия "ФФД 1.1": отсутствует
> Лицензия "маркировка базовая": отсутствует
> Подписка на обновление: отсутствует

**Comment by swex** [comment]
есть нюансы, связанные с версией прошивки. в первом случае на ККТ у вас старая прошивка.

**Comment by t0pd3v1c3** [comment]
> есть нюансы, связанные с версией прошивки. в первом случае на ККТ у вас старая прошивка.
Вот такая:
>  Версия ПО                 : C.1
 Сборка ПО                 : 19018
 Дата ПО                   : 13.02.2020

**Comment by harley-davidson-spb** [comment]
_----------------------------------------
 Версия ПО                 : C.1
 Сборка ПО                 : 29542
 Дата ПО                   : 22.12.2020
 ----------------------------------------_
Вызов метода **Get_License()** возвращает:
_FE000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000_

Согласно Вашим пояснениям, Лицензия "маркировка базовая" отсутствует.
Однако Тест драйвера ККТ 4.0.15.0.833 утверждает обратное:
_Лицензия "20% НДС": без ограничения
Лицензия "маркировка базовая": без ограничения
Подписка на обновление: действительна с 01.01.2019 по 31.12.2019_


Как же все таки корректно получить состояние этой лицензии?

**Comment by LankoRu** [comment]
Хотел бы присоединиться к дискуссу.
Есть вот такой ответ в тесте драйвера:

_FF00FF00000000000700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
Лицензия "20% НДС": без ограничения
Лицензия "маркировка базовая": без ограничения
Подписка на обновление: действительна c 01.01.2020 по 30.09.2020_

Основной вопрос, как получить из первой строки диапазон действия подписки на обновление?

**Comment by swex** [comment]
> Основной вопрос, как получить из первой строки диапазон действия подписки на обновление?

посчитать биты в байтах в промежутке между 9ым и 16ым байтом. Каждый бит это квартал, начиная с 1ого 2020 года. В Вашем примере 07  это 0b111 - 09.2020.

**Comment by LankoRu** [comment]
Т.е. общее правило такое:
- с 0 по 7 байты - это дата окончания какой-либо лицензии, это значение прибавляем к 01.01.2019, получаем месяц и год окончания
- с 8 по 15 байты - это всё одна лицензия на обновление, там считаем биты по-очереди, каждый бит +3 месяца
- остальные - резерв, туда не смотрим

Так получается? 
Могут ли быть пробелы в подписке? Т.е. может ли быть значение 0b110011 например?

**Comment by swex** [comment]
> Так получается?

Да, только с 21 года если есть подписка на обновления - то она включает все лицензии и можно не смотреть на остальные.
> Могут ли быть пробелы в подписке? Т.е. может ли быть значение 0b110011 например?

могут, но только между байтами, те в каждом байте считаются биты справа
