### ISSUE TITLE
Округление и скидка

### ISSUE THREAD

**Issue by SerebryakovAS** [shtrih-m/fr_drv_ng#111]
Доброго времени суток.
- При установке Set_RoundingSumm(99) и вызове метода FNCloseCheckEx выходит ошибка 
"64/ККТ Неверное округление итога чека", что надо указывать для того чтобы округлить  сумму в чеке?
- Возможна ли установка скидки на позицию в чеке?

**Comment by olefard** [comment]
> 64/ККТ Неверное округление итога чека

Приложите файл лога с такой ошибкой.

> Возможна ли установка скидки на позицию в чеке?

Нет. В драйвер надо передавать цену уже с учетом скидки.
Скидку можно напечатать обычным текстом.
