### ISSUE TITLE
Тег 1162 СИЗ

### ISSUE THREAD

**Issue by madskills700** [shtrih-m/fr_drv_ng#112]
Здравствуйте!

В процессе реализации маркировки средств индивидуальной защиты, согласно постановлению правительства РФ от 16 апреля 2020 г. № 521 “О внесении изменений в постановление Правительства Российской Федерации от 21 февраля 2019 г. N 174” (найти можно на том же консультант плюс). 

Руководствовался документацией "Честный Знак" 

https://честныйзнак.рф/upload/iblock/bce/formirovanie-tega-1162-na-KKT.pdf

Особое внимание обращал на примечание 4.

Для работы у маркируемой позиции драйверу передавал следующие команды:
```java
driver.Set_MarkingType(0x450D);
driver.Set_GTIN("2400002886707");
driver.Set_SerialNumber("");
```

В итоге получал в ОФД такое наполнение:

![изображение](https://user-images.githubusercontent.com/10121340/84769296-4563f280-afde-11ea-9276-ff9767428783.png)

В целом наполнение корректное, но после верной полезной нагрузки идут лишние пробелы (если быть точным, то 13). Я пробовал передать GTIN пустой, а в serial писал EAN13 маски, но тогда было совсем не то, что должно быть, исходя из документации ЧЗ. Null в serial в java обертке записать нельзя, если его не задать пустой строкой, то туда может попасть что угодно.

Драйвер версии 1.5.0.987. Версия ПО на ККТ мне на данный момент неизвестна. Лог-файл прикладываю. 

[fr_drv.log](https://github.com/shtrih-m/fr_drv_ng/files/4786307/fr_drv.log)

![изображение](https://user-images.githubusercontent.com/10121340/84768922-b656da80-afdd-11ea-9b91-f44fd890bf16.png)
Вот так выглядит пример с тем же EAN-13 на ККТ АТОЛ (что соответствует документации ЧЗ)

Подскажите пожалуйста, как быть в данной ситуации? Является ли это багом или дело в командах или вообще версии прошивки ККТ? Спасибо!

**Comment by swex** [comment]
Это баг у нас. Исправлено в 1.5.0-9-gabfb925. Можно забрать из релизов

**Comment by madskills700** [comment]
Загрузил новую версию, все заработало как должно.
