### ISSUE TITLE
Проблемы со строковыми типами. 

### ISSUE THREAD

**Issue by NayaNary** [shtrih-m/fr_drv_ng#113]
Здравствуйте. 
Я пытаюсь взаимодействовать с кассой штрих-м. Создала консольное приложение в visual studio. Подключила к проекту classic_fr_drv_ng.lib. Добавила к проекту classic_interface.h. Пишу на с++. 
У меня вышло подключится к кассе и некоторые функции типа открытия, закрытия смены или выплаты, внесения работают хорошо. Но когда приходится обращаться к строковым данным, например запросить заводской номер касс, передать наименование товара в чек, запросить текст ошибки, программа "ругается". На запрос заводского номера или текста ошибки вот такое исключение вылазит:
![ошибка](https://user-images.githubusercontent.com/66299599/84990446-d0afc600-b14d-11ea-9f02-bacee81e8b1f.png)
А при попытке записать наименование номенклатуры в чеке возвращается: string too long. Данный текст ошибки "пойман" с помощью блока try-catch. 
Функция для получения заводского номера: 
```
Result GetFactoryNumber()
{
	Result FactoryNumber;
	ci.Set_SysAdminPassword(30);
	try
	{
		int r = ci.GetECRStatus();
  FactoryNumber.ResultCode = ci.ReadSerialNumber();
  if (FactoryNumber.ResultCode == 0 || r == 0) 
   {   	  
	   FactoryNumber.ErrorResult.ErrorText = ci.Get_SerialNumber();
   }

	}
	catch (const std::exception& Error)
	{
		FactoryNumber.ErrorResult.ErrorCode = -801;
		FactoryNumber.ErrorResult.ErrorText = Error.what();
	}
	return FactoryNumber;
}
```
Регистрирую товар так:
```
int RegistrationDataReceipt(int Password, int CheckType, float Quantity, float Price, int Tax, int TypeSing, int ItemSing, unsigned char NameGood[], int SizeName)
{	
	int ResultReg = -905;
	ci.Set_CheckType(CheckType);
	ci.Set_Password(Password);
    const string Good = ConvertByteToString(NameGood,SizeName);
    const char* Good_1 = "Молоко";
	ci.Set_Price(Price);
	ci.Set_Quantity(Quantity);

    ci.Set_PaymentTypeSign(TypeSing);
	ci.Set_PaymentItemSign(ItemSing);	
	ci.Set_Tax1(Tax);
	ci.Set_Tax2(0);
	ci.Set_Tax3(0);
	ci.Set_Tax4(0);
	try
	{					
		ci.Set_StringForPrinting(u8"Молоко");
	}
	catch (const std::exception& error)
	{
		cout << error.what() << endl;
		ResultReg = ci.FNOperation();
		if (ResultReg != 0) 
		{
		ci.Set_SysAdminPassword(30);
		cout<<ci.SysAdminCancelCheck()<<endl;
		}

	}
	if (ResultReg == -905)
	{
		ResultReg = ci.FNOperation();
	}
	return ResultReg;
}

```
Подскажите, пожалуйста, что я делаю не так? Почему "не работают" строки?

**Comment by swex** [comment]
проблема в том что библиотека релизная, а сборка у вас дебажная, рецепт [здесь](https://github.com/shtrih-m/fr_drv_ng/issues/64).

**Comment by NayaNary** [comment]
Спасибо за помощь
