### ISSUE TITLE
Ошибка inout error

### ISSUE THREAD

**Issue by id-thx1138** [shtrih-m/fr_drv_ng#115]
При работе с штрих нано-ф, на arm устройстве под Linux, при запросе getECRMode висит в тайм-ауте (30 секунд) и потом выдаёт ошибку -1 inout error
Последующая попытка запроса getECRMode успешна.
Такая ситуация довольно часто происходит. 
Подскажите, как организована работа с портом внутри библиотеки? Используете select или poll?

На линуксе на PC такое не воспроизводится.
Вообще лучше всего использовать poll для работы с портом, я часто сталкивался со странностями в работе select на arm системах.

**Comment by swex** [comment]
1. хорошо бы хоть знать какой транспорт используется
2. где возможно (TCP, COM) используется boost asio. Там по умолчанию epoll, но можно во время сборки выбрать другой бэкенд

> Вообще лучше всего использовать poll для работы с портом, я часто сталкивался со странностями в работе select на arm системах.

3. это вообще как? все эти вызовы - это интерфейс пользователя, изменилось ли состояние дескрипторов это механизмы ядра. Те или ядро знает что что-то произошло и сообщит об этом наверх или и ядро о событиях не знает.
4. Предлагаю сделать минимальный пример с getECRMode в цикле и собрать с него strace.
5. Если речь о TCP - так же можно еще собрать трафик с помощью tcpdump

**Comment by id-thx1138** [comment]
serial:///dev/ttyACM0?timeout=30000&baudrate=115200

**Comment by id-thx1138** [comment]
Вы уверены насчёт boost?
fr_drv_ng/linux_x86_64[master*]$ ldd ./libclassic_fr_drv_ng.so.1.4 
  linux-vdso.so.1 (0x00007ffdeeff3000)
  libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fef2821c000)
  libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fef28099000)
  libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fef2807f000)
  libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fef2805e000)
  libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fef27e9d000)
  /lib64/ld-linux-x86-64.so.2 (0x00007fef2897c000)

**Comment by swex** [comment]
> serial:///dev/ttyACM0?timeout=30000&baudrate=115200

в таком случае я бы грешил на usb host контроллер/драйвер вашей железки или на сам НАНО, но никак не на асинхронные вызовы

**Comment by swex** [comment]
> Вы уверены насчёт boost?
> fr_drv_ng/linux_x86_64[master*]$ ldd ./libclassic_fr_drv_ng.so.1.4
> linux-vdso.so.1 (0x00007ffdeeff3000)
> libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fef2821c000)
> libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fef28099000)
> libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fef2807f000)
> libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fef2805e000)
> libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fef27e9d000)
> /lib64/ld-linux-x86-64.so.2 (0x00007fef2897c000)

более чем, это header only библиотека.

**Comment by id-thx1138** [comment]
Что с контроллером это конечно не исключено, но странно что проявляется исключительно на запросе ECR…
Вот кусочек лога
https://pastebin.com/yseZAwKT

**Comment by id-thx1138** [comment]
Видно что обмен данными на обмене с ошибкой и с успехом отличаются…

**Comment by swex** [comment]
нужно:
1. версия драйвера(пишется при старте лога)
2. версия прошивки НАНО
стоит попробовать:
1. актуализировать драйвер и прошивку НАНО
2. попробуйте переключиться на протоколv2(`serial:///dev/ttyACM0?timeout=30000&baudrate=115200&protocol=v2`) на сколько я помню у НАНО были известные проблемы с протоколом 1.

**Comment by id-thx1138** [comment]
Смотрите, я провёл замеры, и стабильно если 4 секунды не писать ничего в штрих нано Ф то первый запрос будет с inout error а следующий ок
Есть такое подозрение что штрих переходит в какой-то режим сна… есть ли что-то такое и как отключить?

**Comment by olefard** [comment]
Обновите, пожалуйста, драйвер, сделайте несколько запросов состояния, в том числе и через 4 секунды, и приложите файл лога целиком.
Про засыпание уточним у разработчика ККТ.

**Comment by id-thx1138** [comment]
Лог программы, как видно стабильно после каждых 4 сек простоя штрих не отвечает
https://pastebin.com/TtPLUTBP

листинг драйвера
https://pastebin.com/kEGaaTjx

**Comment by id-thx1138** [comment]
Сборка с последней библиотекой выдаёт ошибку
/usr/bin/ld: ./libs/fr_drv_ng/linux_x86_64/libclassic_fr_drv_ng.so.1.4: undefined reference to `pow@GLIBC_2.29'

При этом у меня апрельская версия - там все ок, простая замена либы не срабатывает, я пока не разбирался что за новая проблема с pow@GLIBC

**Comment by olefard** [comment]
А если переключиться на протокол v2?
Вызвать Set_ConnectionURI("serial:///dev/ttyACM0?timeout=30000&baudrate=115200&**protocol=v2**")

**Comment by id-thx1138** [comment]
Спасибо! Кажется protocol v2 помог на первый взгляд! До минуты бездействия и все ок.

**Comment by olefard** [comment]
Еще прошивка НАНО очень старая: "fw_date: 2018-12-10T00:00:00".

**Comment by swex** [comment]
> Сборка с последней библиотекой выдаёт ошибку
> /usr/bin/ld: ./libs/fr_drv_ng/linux_x86_64/libclassic_fr_drv_ng.so.1.4: undefined reference to `pow@GLIBC_2.29'
> 
по всей видимости у вас старый дистрибутив и соотв. glibc ...
что выдает?
```
/usr/lib/libc-*.so
```

**Comment by id-thx1138** [comment]
GNU C Library (Debian GLIBC 2.28-10) stable release version 2.28.
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 8.3.0.
libc ABIs: UNIQUE IFUNC ABSOLUTE
For bug reporting instructions, please see:
<http://www.debian.org/Bugs/>.

$ lsb_release -a
No LSB modules are available.
Distributor ID:  Debian
Description:  Debian GNU/Linux 10 (buster)
Release:  10
Codename:  buster

**Comment by id-thx1138** [comment]
На Debian я в принципе мог бы и обновить, а вот на линуксе под arm это уже проблематично (( нельзя ли сделать сборку со старым glibc?

**Comment by swex** [comment]
> На Debian я в принципе мог бы и обновить, а вот на линуксе под arm это уже проблематично (( нельзя ли сделать сборку со старым glibc?

можно и со старым glibc, но я бы попробовал для начала явно передать -lm в флаги линкера, должно помочь

**Comment by id-thx1138** [comment]
-lm флаг пробовал… не помогло

**Comment by swex** [comment]
да, в мае мы обновили сборочное окружение и glibc обновилась до 2.29. След. релиз будет собран с glibc 2.28 снова.
PS: а какое окружение на ваших АРМах?

**Comment by swex** [comment]
в [текущей сборке](https://github.com/shtrih-m/fr_drv_ng/releases/tag/1.5.0-10-g7f7f651) снова используется glibc 2.27
