### ISSUE TITLE
Чтение полного серийного номера ККТ

### ISSUE THREAD

**Issue by LankoRu** [shtrih-m/fr_drv_ng#118]
Не удаётся получить полный серийный номер ККТ.

> [2020-10-12 20:34:57.304] [259958] [classic_interface_0x2363970     ] [T] GetLongSerialNumberAndLongRNM()
> [2020-10-12 20:34:57.304] [259958] [classic_interface_0x2363970     ] [D] GetLongSerialNumberAndLongRNM() fail
> [2020-10-12 20:34:57.304] [259958] [classic_interface_0x2363970     ] [E] Не поддерживается в данной версии драйвера
> [2020-10-12 20:34:57.304] [259958] [classic_interface_0x2363970     ] [T] Get_ResultCodeDescription()
> [2020-10-12 20:34:57.304] [259958] [classic_interface_0x2363970     ] [T] Get_ResultCodeDescription() -> `Не поддерживается в данной версии драйвера`

Драйвер 1.4.6.329 (хотя архив 1.5.0), linux x64.

Я так понимаю, другого способа (кроме `ExchangeBytes()` разве что) для чтения полного серийника нет?

**Comment by swex** [comment]
Чтобы получить серийный номер нужно считать первое поле из таблицы ФН.
Как получить номер таблицы ФН можно посмотреть [здесь](https://github.com/shtrih-m/fr_drv_ng/issues/7)

**Comment by swex** [comment]
> Драйвер 1.4.6.329 (хотя архив 1.5.0), linux x64.

В драйвере несколько модулей и у всех них есть своя версия. Подробнее можно посмотреть в логе при инициализации библиотеки.

**Comment by LankoRu** [comment]
Работает, спасибо
