### ISSUE TITLE
dylib отдельно от фреймворка

### ISSUE THREAD

**Issue by LankoRu** [shtrih-m/fr_drv_ng#119]
Можно ли как-то получить dylib драйвера? Хочется подключить к Go, а линковать ради этого фреймворк не очень кроссплатформенно. Вопрос про macOS.

**Comment by swex** [comment]
А что не так с теми *.dylib что уже есть в архиве под мак?

**Comment by LankoRu** [comment]
Они от Qt зависят

**Comment by swex** [comment]
по всей видимости можно взять библиотеку из `classic_fr_drv_ng.framework/Versions/C/classic_fr_drv_ng` добавить расширение dylib и использовать без framework

**Comment by LankoRu** [comment]
Пробовал, сходу как-то не вышло... Попробую ещё разок

**Comment by LankoRu** [comment]
Не, не хочет, судя по всему из-за rpath

```
dyld: Library not loaded: @rpath/classic_fr_drv_ng.framework/Versions/C/classic_fr_drv_ng
  Referenced from: <тут путь до символа>
  Reason: image not found
```

```
% otool -L libclassic_fr_drv_ng.dylib                                                   
libclassic_fr_drv_ng.dylib:
        @rpath/classic_fr_drv_ng.framework/Versions/C/classic_fr_drv_ng (compatibility version 1.4.0, current version 1.4.0)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
```

В принципе проблема должна порешаться с C-API и загрузкой как плагина

**Comment by swex** [comment]
не уверен что C API спасёт в работе dlopen тот же линкер участвует и есть вероятность что напишет то же самое.
Посмотрите [здесь](https://stackoverflow.com/questions/7562793/how-do-i-create-a-working-framework-with-dylib-files-in-xcode-4/7563064), может что поможет

**Comment by LankoRu** [comment]
Ну, с АТОЛом так работает.

Я пробовал играться с этими параметрами, как-то не заходит. Вобщем, подожду.

**Comment by swex** [comment]
да, вот [этот](https://github.com/shtrih-m/fr_drv_ng_examples/blob/master/classic_interface/c_main.cpp) пример с dlopen действительно работает.

**Comment by LankoRu** [comment]
Подтверждаю, всё работает
