### ISSUE TITLE
Работа пример FNSendTLV

### ISSUE THREAD

**Issue by susloparov77** [shtrih-m/fr_drv_ng#12]
Нет ли у вас примера как писать теги с помощью FNSendTLV? А именно как правильно сформировать std::vector< uint8_t > TLVData перед передачей?

**Comment by swex** [comment]
Это нужно изучить [ФФД](http://www.consultant.ru/document/cons_doc_LAW_214339/c7bcefffc3cbf3b1189c0f92e21f7bd930aa5b96/) в большинстве случаев ККТ и драйвер помогают избежать ручного формирования TLV. 
Лучше скажите какую задачу решаете и мы подскажем как. Так же хорошо бы ознакомиться с общим руководством на КЯ(Кассово Ядро) и ККТ в целом.
https://www.shtrih-m.ru/catalog/onlayn-kassy/shtrikh-smartpos-f/ 
Скачать -> Документация

**Comment by Mzales** [comment]
В описании свойства  [TLVData](../wiki/Properties#group___properties_1ga6af40dabb609ba89f9a173f0c09ff563) есть пример правильного заполнения перед вызовом [FNSendTLV](../wiki/Methods#group___base_methods_1gaf50ce7dab01716c3e031b4f97e2f3371)

**Comment by susloparov77** [comment]
спасибо по этому все закрываем.
