### ISSUE TITLE
Как получить номер фискального документа внутри смены?

### ISSUE THREAD

**Issue by ola-skorp** [shtrih-m/fr_drv_ng#124]
Мне нужно получить номер фискального документа внутри смены, а не сквозной. Смотрела в сторону регистров, но нашла там получение только сквозного номера, либо получение номеров по типам операций (приход, расход, возврат прихода, возврат расхода), а это не совсем то, что мне нужно, ведь помимо них есть другие операции, которые меняют этот номер

**Comment by swex** [comment]
Правильно понимаю что нужен номер последнего документа ФН?
Посмотрите метод `FNGetStatus`

**Comment by ola-skorp** [comment]
```
checkResult(FNGetStatus())
val docNum = Get_DocumentNumber()
```
docNum = 1297
А у меня три чека напечатано в смене. Я так понимаю, что Get_DocumentNumber() возвращает сквозной
Не нашла в FNGetStatus() не сквозной

**Comment by swex** [comment]
у вас же есть номер документа открытия смены. Он сквозной. И вот этот номер документа из `FNGetStatus`. Разность и будет нужным числом.

**Comment by surfernsk** [comment]
> ```
> checkResult(FNGetStatus())
> val docNum = Get_DocumentNumber()
> ```
> 
> docNum = 1297
> А у меня три чека напечатано в смене. Я так понимаю, что Get_DocumentNumber() возвращает сквозной
> Не нашла в FNGetStatus() не сквозной

Это номер фискального документа. Документа в ФН.
Можно прочитать ФД в виде текста.

> КАССОВЫЙ ЧЕК
1041,ФН:99990789324
1037,РН ККТ:0000895624029053
1018,ИНН:5603180288
1040,ФД:6
1012,ДАТА, ВРЕМЯ:29.10.2020 11:37:00
1077,ФП:3005039222 (3104B31D4276)
1038,СМЕНА:1
1042,НОМЕР ЧЕКА ЗА СМЕНУ:4
1054,ПРИЗН. РАСЧЕТА:1 (Приход)
1020,ИТОГ:243.25
1059,ПРЕДМ. РАСЧЕТА:
 1030,НАИМЕН. ПРЕДМ. РАСЧЕТА:Камбала Х/К, кг
 1079,ЦЕНА ЗА ЕД. ПРЕДМ. РАСЧ.:689.09
 1023,КОЛ-ВО ПРЕДМ. РАСЧЕТА:0.353000
 1043,СТОИМ. ПРЕДМ. РАСЧЕТА:243.25
 1214,ПРИЗН. СПОСОБА РАСЧ.:4
 1212,ПРИЗН. ПРЕДМЕТА РАСЧ.:1
1021,КАССИР:Администратор
1031,НАЛИЧНЫМИ:243.25
1081,БЕЗНАЛИЧНЫМИ:0.00
1215,ПРЕДВАРИТЕЛЬНАЯ ОПЛАТА (АВАНС):0.00
1216,ПОСЛЕДУЮЩАЯ ОПЛАТА (КРЕДИТ):0.00
1217,ИНАЯ ФОРМА ОПЛАТЫ:0.00
1060,САЙТ ФНС:www.nalog.ru
1187,МЕСТО РАСЧЕТОВ:Магазин
1209,ВЕРСИЯ ФФД:2 (1.05)
1105,СУММА БЕЗ НДС:243.25
1048,НАИМЕН. ПОЛЬЗ.:ООО "ООО"
1009,АДР.РАСЧЕТОВ:Адрес
1055,СНО:8 (ЕНВД)

**Comment by ola-skorp** [comment]
Я знаю, что это номер фискального документа. Но мне нужен не он. Мне нужен номер документа внутри смены. У меня в смене 3 документа. На последнем документе написано ЧЕК 3. Вот этот номер мне нужно получить программно

**Comment by ola-skorp** [comment]
> у вас же есть номер документа открытия смены. Он сквозной. И вот этот номер документа из `FNGetStatus`. Разность и будет нужным числом.

Откуда у меня номер документа открытия смены?

**Comment by surfernsk** [comment]
> Я знаю, что это номер фискального документа. Но мне нужен не он. Мне нужен номер документа внутри смены. У меня в смене 3 документа. На последнем документе написано ЧЕК 3. Вот этот номер мне нужно получить программно

Еще раз.  ТЕГ 1042 в документе. Посмотрите внимательнее на https://github.com/shtrih-m/fr_drv_ng/issues/124#issuecomment-725975522

**Comment by swex** [comment]
> > у вас же есть номер документа открытия смены. Он сквозной. И вот этот номер документа из `FNGetStatus`. Разность и будет нужным числом.
> 
> Откуда у меня номер документа открытия смены?

В #123 мы же научились с вами пользоваться методом `FNFindDocument`, берем из документа `DocumentNumber`.

**Comment by ola-skorp** [comment]
Нет, не научились. Здесь указан Get_ReceiptNumber, который всегда 0. https://github.com/shtrih-m/fr_drv_ng/issues/109#issuecomment-634552855

**Comment by ola-skorp** [comment]
> > Я знаю, что это номер фискального документа. Но мне нужен не он. Мне нужен номер документа внутри смены. У меня в смене 3 документа. На последнем документе написано ЧЕК 3. Вот этот номер мне нужно получить программно
> 
> Еще раз. ТЕГ 1042 в документе. Посмотрите внимательнее на [#124 (comment)](https://github.com/shtrih-m/fr_drv_ng/issues/124#issuecomment-725975522)

Как прочитать этот тег?

**Comment by surfernsk** [comment]
> Можно прочитать ФД в **виде текста.** ТЕГ 1042

FNGetDocumentAsString()

**Comment by swex** [comment]
@surfernsk нене, этого не нужно.
@ola-skorp см. метод `FNGetCurrentSessionParams`

**Comment by ola-skorp** [comment]
Вызывала Get_ReceiptNumber после FNGetCurrentSessionParams. Он всегда 0

**Comment by olefard** [comment]
> Вызывала Get_ReceiptNumber после FNGetCurrentSessionParams. Он всегда 0

Можете в новой смене пробить пару чеков, выполнить FNGetCurrentSessionParams и выложить лог?

**Comment by swex** [comment]
> Вызывала Get_ReceiptNumber после FNGetCurrentSessionParams. Он всегда 0


1. не должно быть такого. давайте лог.  
2. как я и писал, вы всегда можете посчитать номер самостоятельно, получив номер смены документа открытия смены вот так:
  2.1. получаем текущий `DocumenNumber` через `FNGetStatus`
  2.2. получаем `DocumentType` через `FNFindDocument`
  2.3. если `DocumentType` == 3 это искомый `DocumentNumber`
  2.4. Чеков за смену = `DocumentNumber` из п.2.1 -  `DocumentType` из п.2.3

**Comment by ola-skorp** [comment]
> 2. как я и писал, вы всегда можете посчитать номер самостоятельно, получив номер смены документа открытия смены вот так:
>    2.1. получаем текущий `DocumenNumber` через `FNGetStatus`
>    2.2. получаем `DocumentType` через `FNFindDocument`
>    2.3. если `DocumentType` == 3 это искомый `DocumentNumber`
>    2.4. Чеков за смену = `DocumentNumber` из п.2.1 -  `DocumentType` из п.2.3

Перебор - плохое решение

**Comment by ola-skorp** [comment]
> > Вызывала Get_ReceiptNumber после FNGetCurrentSessionParams. Он всегда 0
> 
> 1. не должно быть такого. давайте лог.

Вызвала отдельно, получила номер чека 3. Видимо, вызов ломали предыдущие вызовы

**Comment by ola-skorp** [comment]
Ответ на мой вопрос:
FNGetCurrentSessionParams()
val receiptNum = Get_ReceiptNumber()
receiptNum - это не сквозной номер документа

**Comment by swex** [comment]
Есть нюансы.  В `FNGetCurrentSessionParams`, `ReceiptNumber` отчеты о состоянии расчетов не учитываются.
