### ISSUE TITLE
Как получить количество чеков за смену из чека закрытия смены?

### ISSUE THREAD

**Issue by ola-skorp** [shtrih-m/fr_drv_ng#125]
Как получить количество чеков за смену из чека закрытия смены?
Пробовала такой код
```
Set_DocumentNumber(reportReceiptNum)
FNFindDocument()
val docCount = Get_DocumentCount()
```
docCount = 0
А у меня в чеке закрытия смены стоит 1

**Comment by swex** [comment]
Свойство `DocumentCount` появляется в `FNFindDocument` только если тип документа 21 (Отчет о состоянии расчетов)

**Comment by ola-skorp** [comment]
А из отчёта о закрытии смены никак не получить количество чеков за смену?

**Comment by surfernsk** [comment]
DocumentCount - кол-во документов не отправленных в ОФД

**Comment by swex** [comment]
> А из отчёта о закрытии смены никак не получить количество чеков за смену?

Нельзя. Только если брать разницу между `DocumentNumber` и `DocumentNumber` открытия смены. Или перед закрытием делать как в #124

**Comment by ola-skorp** [comment]
Спасибо

**Comment by surfernsk** [comment]
Читайте документ, там и чеков в смене и суммы общие и др.

> ОТЧЕТ О ЗАКРЫТИИ СМЕНЫ
1041,ФН:99990789324
1037,РН ККТ:0000895624029053
1018,ИНН:4303180286
1040,ФД:10
1012,ДАТА, ВРЕМЯ:03.11.2020 16:01:00
1077,ФП:4038995575 (2404F0BE2E77)
1038,СМЕНА:2
1118,ЧЕКОВ ЗА СМЕНУ:1
1111,ФД ЗА СМЕНУ:3
1097,НЕПЕРЕДАННЫХ ФД:9
1098,ФД НЕ ПЕРЕДАНЫ С:29.10.2020
1050,РЕСУРС ФН МЕНЕЕ 30 ДНЕЙ:0
1051,РЕСУРС ФН МЕНЕЕ 3 ДНЕЙ:0
1052,ПАМЯТЬ ФН ЗАПОЛНЕНА:0
1053,ОФД НЕ ОТВЕЧАЕТ:0
1021,КАССИР:Администратор
1209,ВЕРСИЯ ФФД:2 (1.05)

**Comment by swex** [comment]
@surfernsk "нельзя из отчета" я имел в виду, что нет таких полей в ответе на команду закрытия.
