### ISSUE TITLE
Проблемы при печати текста.

### ISSUE THREAD

**Issue by ConsperSerj** [shtrih-m/fr_drv_ng#126]
Добрый день. Есть следующая задача.

Есть длинная строка(чек в виде строки), от отформатирован, каждая строчка по 32 символа. Нужно распечатать данный текст на ленте. 

Я попробовал выполнить печать текста по строчно - то есть разбил большую строку на маленькие по 32 и печатал командой построчной печати. Но это очень долго. Печать чека с большим количеством позиций занимает 15-25 секунд, хотя при проведении такой транзакции система печатает такой чек за 5-7 секунд.

Вопрос: через какую команду можно выполнить быструю печать текста на чековой ленте? может как то можно ядру скормить просто одну большую строку и он распечатает все сам?

**Comment by surfernsk** [comment]
![1](https://user-images.githubusercontent.com/2264893/101357398-f3849100-38cb-11eb-80ed-5b6ed726b5a1.png)
![2](https://user-images.githubusercontent.com/2264893/101357404-f54e5480-38cb-11eb-9b3c-a211a33ffa3a.png)

Попробуйте установить свойство перенос строки. Увы не проверял, на универсальном драйвере.

```
    //! @brief Переносить строки при печати
    //!
    //! @note для моделей, поддерживаемых перенос
    //!
    //! @par Используется методами:
    //!   #PrintString, #PrintStringWithFont, #PrintWideString
    //!
    //! @par Методы доступа:
    //!   #Get_CarryStrings, #Set_CarryStrings
    //!
    DOXYGEN_PROPERTY(bool CarryStrings)
    //!
    //! @brief Возвращает значение свойства #CarryStrings
    //! @return CarryStrings
    //! @relates CarryStrings
    //!
    bool Get_CarryStrings() const;
    //!
    //! @brief Устанавливает значение свойства #CarryStrings
    //! @return CarryStrings
    //! @relates CarryStrings
    //!
    void Set_CarryStrings(bool value);

**Comment by ConsperSerj** [comment]
вся строка длинная разбита \n. То есть переносы есть. Но если просто передать длинную строку, то печатается первые 32 символа и все. Дальше печать не проиходит

**Comment by surfernsk** [comment]
CarryStrings() == ?

**Comment by ConsperSerj** [comment]
true

**Comment by surfernsk** [comment]
Команда F7H какое значение возвращала?

**Comment by ConsperSerj** [comment]
Сейчас проверю настройки. Спасибо за подсказки

**Comment by swex** [comment]
Здравствуйте! Если у вас устройство на базе КЯ - то есть несколько способов:
1. Печать строк внутри не фискального документа
```c++
ci.BeginDocument();
ci.PrintString();
ci.EndDocument();
```
2. Отложенная печать
```c++
ci.Set_DelayedPrint(true);
ci.PrintString();
...
//и последнюю строку печатаем уже без задержки печати
ci.Set_DelayedPrint(false);
ci.PrintString();
```
3. Перенос строк как посоветовал @surfernsk тоже должен работать. Так же рекомендуется использовать протокол версии 2 для КЯ. Т.к. во втором протоколе есть возможность передавать длинные строки потому что тело команды может быть аж до ~64килобайт.

**Comment by ConsperSerj** [comment]
Спасибо буду пробовать
