### ISSUE TITLE
UpdateFirmware

### ISSUE THREAD

**Issue by harley-davidson-spb** [shtrih-m/fr_drv_ng#128]
В описании к драйверу есть метод для обновления прошивки
**UpdateFirmware**
_ОбновитьПрошивку
Метод начинает обновление прошивки устройства в асинхронном режиме. Следить за состоянием
обновления можно по значениям свойств **UpdateFirmwareStatus** (0 – успешно завершено, 1 – в
процессе, 2 – завершено с ошибкой). **UpdateFirmwareStatusMessage** хранит текстовое описание
текущего состояния обновления прошивки. После перепрошивки значения таблиц ККТ
автоматически восстанавливаются._

Однако в скачанном архиве fr_drv_ng_java_wrappers_1.5.0-15-gd7ee9cd.zip в файле classic_java_fr_drv_ng-1.4.6.334.jar
отсутствует реализация методов **UpdateFirmware** и **Set_UpdateFirmwareMethod**, равно как и **Get_UpdateFirmwareStatus** и **Get_UpdateFirmwareStatusMessage**

Когда этот функционал можно ожидать и будет ли он реализован в принципе?

**Comment by swex** [comment]
Проблема в том что мы распространяем этот драйвер в виде библиотеки и сразу для множества платформ, а для обновлений используются внешние утилиты (dfu, rx) и найти и еще и поставлять их под все платформы проблематично. 

Что предлагаю:
1. Посмотрите [пример скрипта](https://github.com/shtrih-m/fr_drv_ng_examples/blob/master/console_test/dfu_update.sh) обновления. 
2. Так же есть сервис [облачная касса](https://okassa.info/). Через него тоже можно автоматизировать обновление парка ККТ, мониторить состояние и др.
