### ISSUE TITLE
получение номера фискального документа

### ISSUE THREAD

**Issue by try2bajed1** [shtrih-m/fr_drv_ng#13]
Нашел в документации 152 – сквозной номер документа; Читаю из регистра. 
 Set_RegisterNumber(152)
 checkResult(Get_DocumentCount())
log("Get_ContentsOfOperationRegister ${Get_ContentsOfOperationRegister()}")
но в ответ получаю ноль, хотя на чеке значение 2317.

подскажите, как правильно получать эту информацию. Или она лежит в какой то из таблиц?
Так же интересует другие значения на чеке (фн фп зн ккт итд.)

**Comment by swex** [comment]
Все методы, начинающиеся с `Get_`/ `Set_` - это геттеры и сеттеры свойств объекта драйвера, соотв.  
Сами по себе они не меняются. Вам необходимо вызвать один из **методов** драйвер чтобы он внутри себя модифицировал свойство.
Т.е. у Вас ошибка во второй строке: `Get_DocumentCount()` - это просто текущее значение свойства `DocumentCount`. 
Чтобы получить операционный регистр нужно вызвать `GetOperationReg`

**Comment by try2bajed1** [comment]
да, при помощи этого метода я получил данные по этому индексу. Но сквозной номер , это немного не то, что мне нужно, мне нужен тот номер, который идет после букв ФД. Я просто читаю список регистров и я нигде не могу найти этот индекс. Или это значение надо брать из таблицы?

**Comment by swex** [comment]
это номер документа в ФН - получить можно через свойство `DocumentNumber`, из метода `FNGetStatus`

**Comment by try2bajed1** [comment]
Спасибо, получилось. Правильно ли я понимаю,  что данные о принтере мы берем из 3 мест: таблицы, регистры, и методы после FNGetStatus (ну или схожих с ним) ?

**Comment by swex** [comment]
вопрос не совсем корректный стоит почитать общее руководство. При использовании драйвера все "данные" берутся из свойств, а модифицируются "данные" методами.

**Comment by try2bajed1** [comment]
Спасибо, становится немного понятней )
