### ISSUE TITLE
Дата окончания ФН console_test

### ISSUE THREAD

**Issue by elchako** [shtrih-m/fr_drv_ng#133]
Здравствуйте! подскажите каким способом можно получить дату окончания ФН через консольный вариант драйвера?
Благодарю!

**Comment by swex** [comment]
Здравствуйте!
есть команда `fs-get-eol`
пример вывода:
```
Command FN EOL status
EOL date        11.05.2022
registrations count     1
registrations left      29
```
получить дату можно как-то так:
```bash
console_test_fr_drv_ng fs-get-eol|grep 'EOL date'|cut -f2
```

**Comment by elchako** [comment]
Спасибо за быстрый ответ!
Появился еще вопрос: где можно ознакомиться с полнм списком команд для консольного тест драйвера?

**Comment by swex** [comment]
1. запустить утилиту без аргументов
2. с кривыми аргументами

**Comment by elchako** [comment]
Оказалось использую старую версию, даже не могу сказать какую именно. И в ней нет команды fs-get-eol.
При попытке использовать новую получаю ошибку **FATAL: kernel too old**
Подопытный с таким ядром Linux box 4.14.62-tinycore
Какую можно использовать версию чтобы и команда работала и требования к ядру удовлетворить?

**Comment by swex** [comment]
попробуйте версию i486_ok

**Comment by elchako** [comment]
Еще раз спасибо! i486_ok решила проблему
