### ISSUE TITLE
Падение драйвера при считывании документа из ФН

### ISSUE THREAD

**Issue by LankoRu** [shtrih-m/fr_drv_ng#134]
При считывании чека с нулевым итогом из ФН (`FNGetDocumentAsString()`) происходит падение драйвера. Смотрел две последние версии драйвера, под win (x86) и mac - под win падают оба, под mac оба отрабатывают.

Лог - https://pastebin.com/5ByU1dWp, там сначала чек формируется, потом сразу считывается.

**Comment by swex** [comment]
да, есть такое, как оказалось, ФН может возвращать VLN тег с длиной 0.
Фикс будет чуть позже.

**Comment by swex** [comment]
исправлено в [1.5.0-18-g97415ba](https://github.com/shtrih-m/fr_drv_ng/releases/tag/1.5.0-18-g97415ba)
