### ISSUE TITLE
Добавление сборки для Raspberry Pi OS (armv7l)

### ISSUE THREAD

**Issue by v0d0m3r** [shtrih-m/fr_drv_ng#135]
Здравствуйте, @swex 
при попытке использовать fr_drv_ng_linux_armv7_le*.zip или fr_drv_ng_linux_armv7hf_le_*.zip на Raspberry Pi OS,
получил следующий вывод от команды:
`# ldd /opt/dist/linux_1.5.0.552/armv7hf_le/console_test_fr_drv_ng-1.5`
не является динамическим исполняемым файлом
И
`# ldd /opt/dist/linux_1.5.0.552/armv7_le/console_test_fr_drv_ng-1.5`
не является динамическим исполняемым файлом
Соотвественно вопрос, _есть ли возможность добавить данную архитектуру или нужно попробовать другую существующую сборку_?
Так же прилагаю вывод команд о сведениях о системе
//--------------------------------------------
`lscpu`
Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               4
Model name:          Cortex-A53
Stepping:            r0p4
CPU max MHz:         1200,0000
CPU min MHz:         600,0000
BogoMIPS:            38.40
//--------------------------------------------
`uname -a`
Linux user14 5.10.17-v7+ #1403 SMP Mon Feb 22 11:29:51 GMT 2021 armv7l GNU/Linux
//--------------------------------------------

**Comment by swex** [comment]
так, а что оно не запускается?

**Comment by swex** [comment]
получится ли запустить с библиотеками из состава сборки?
в директории сборки:
```bash
./libs/ld-linux*.so* --library-path ./libs/ ./console_test_fr_drv_ng
```

**Comment by v0d0m3r** [comment]
Да, спасибо.
Я сначала проверил `ldd `, и сделал неправильный вывод о том, что данная архитектура не поддерживается (для i686 - мне показывало зависимости). После Вашего ответа, программа действительно запустилась. Прошу прощения за потраченное время.

**Comment by v0d0m3r** [comment]
Так же, если будет полезно обнаружил:
//--------------------------------------------
`./console_test_fr_drv_ng -v`
Получил успешный ответ:
console_test version: 1.5.2.155 ....
//--------------------------------------------
Но при запуске 
`./console_test_fr_drv_ng beep`
./console_test_fr_drv_ng: relocation error: ./console_test_fr_drv_ng: symbol _ZNSt15__exception_ptr13exception_ptrC1Ev version CXXABI_1.3.11 not defined in file libstdc++.so.6 with link time reference
//--------------------------------------------
Помогает запустить, как вы указали
`./libs/ld-linux*.so* --library-path ./libs/ ./console_test_fr_drv_ng beep`
ККТ издала звук, но вышло следующее сообщение:
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (internal error): ignored.

**Comment by swex** [comment]
Что у вас за окружение? Версию ядра и архитектуру я видел, а тулчейн с которым собрана ОС? libc/ компилятор?
Если команды отрабатывают, я бы забил на сообщения эти линкера

**Comment by v0d0m3r** [comment]
> я бы забил на сообщения эти линкера
Согласен, пожалуйста добавьте в хелп проги или куда-ещё (если не добавлено), что запускать на rpi или на других армах `./libs/ld-linux*.so* --library-path ./libs/ ./console_test_fr_drv_ng`
Также предоставляю версию libc
`/lib/arm-linux-gnueabihf/libc.so.6`
GNU C Library (Debian GLIBC 2.28-10+rpi1) stable release version 2.28.
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 8.3.0.
libc ABIs: UNIQUE ABSOLUTE
For bug reporting instructions, please see:
<http://www.debian.org/Bugs/>.
