### ISSUE TITLE
Добавить возможность замены фискального накопителя с помощью console_test_fr_drv_ng

### ISSUE THREAD

**Issue by v0d0m3r** [shtrih-m/fr_drv_ng#136]
Здравствуйте,
интересует добавление функции закрытие архива в данную программу.
 
Также интересует, правильно ли я интепретировал команды и аргументы следующих функций?
Можно ли передавать режим работы 0?

#  1) Сгенерировать отчет о перерегистрации 
Аргументы: код системы налогообложения.режим работы.причина перерегистрации
(описание аргументов см. ниже)
### console_test_fr_drv_ng kkt-rereg-report 1.4.1 
#------------
  значение | система налогообложения                               |
|----------|-------------------------------------------------------|
|    1     | основная                                              |
|    2     | упрощенная система налогообложения доход              |
|    4     | упрощенная система налогообложения доход минус расход |
|    8     | единый налог на вмененный доход                       |
|    16    | единый сельскохозяйственный налог                     |
|    32    | патентная система налогообложения                     |

#------------
 значение | Режим работы             |
|---------|--------------------------|
|    0    | без режима               | (Это под вопросом)
|    1    | шифрование               |
|    2    | автономный режим         |
|    4    | автоматический режим     |
|    8    | применение в сфере услуг |
|    16   | режим БСО                |
|    32   | применение в Интернет    |

Код причины перерегистрации
Допустимые значения:
 - 1 – замена ФН;
 - 2 – замена ОФД;
 - 3 – изменение реквизитов;
 - 4 – изменение настроек ККТ.

#  2) Начать/инициализировать отчет о регистрации
Аргументы: тип отчета о регистрации (значения представлены ниже)
### console_test_fr_drv_ng kkt-reg-begin 0
| Значение |                  Тип отчета                                         |
|----------|---------------------------------------------------------------------|
|   0      | Отчет о регистрации КТТ                                             |
|   1      | Отчет об изменении параметров регистрации ККТ, в связи с заменой ФН |
|   2      | Отчет об изменении параметров регистрации ККТ без замены ФН         |

# 3) Сформировать отчет о регистрации (описание полей см. выше)
Аргументы: ИНН.РНМ ККТ.код системы налогообложения.режим работы
# console_test_fr_drv_ng kkt-reg-end XXXXXXXXXX.XXXXXXXXXXXXXXXX.1.0

**Comment by swex** [comment]
Да, кажется, всё так. Остальные параметры регистрации можно изменять через таблицу ФН.

**Comment by v0d0m3r** [comment]
Так же в выводе справки о работе данной программы возможно опечатка
read - "read table"
        args: table[.row[.field]]

write - "write table"
        args: table.field.row
        params: new value
Для функции read после номера таблицы идет ряд, затем поле. Для write идет сначала поле, а затем ряд.

**Comment by swex** [comment]
Да, разумеется, в `write` порядок такой же как и в `read`, с разницей только в том что в `write` все поля обязательные.
Спасибо за внимательность, поправим в след. релизе.

**Comment by v0d0m3r** [comment]
Спасибо!
