### ISSUE TITLE
Ошибка при печати чека

### ISSUE THREAD

**Issue by harcoPro** [shtrih-m/fr_drv_ng#137]
Проблема состоит в том, что при печати чека в момент вызова команды `FNCloseCheckEx()` в результат приходит Ошибка 9, и чек не печатается, но данные все которые были внесены до этого остаются в ФН и учитываются при сверке итогов. Могу я как-то очищать данные, которые уже попали в ФН и как корректно обработать эту ошибку? Спасибо

**Comment by swex** [comment]
Не пойму. Если на закрытие чека приходит ошибка - значит данные и не попадают в ФН. Нужен лог.
