### ISSUE TITLE
Вопрос по номеру ККТ

### ISSUE THREAD

**Issue by ConsperSerj** [shtrih-m/fr_drv_ng#138]
Добрый день. Возможно ли как то получить регистрационный номер ККТ при условии что ФН не вставлен в кассу?

**Comment by surfernsk** [comment]
Добрый день, обратиться в ФНС.

**Comment by ConsperSerj** [comment]
А какой командой я могу сделать это?

**Comment by ConsperSerj** [comment]
Но вроде бы это для регистрации нужен. А вот метод который мне поможет получить номер ККТ без ФН я что-то не могу найти

**Comment by surfernsk** [comment]
Возможно после извлечения ФН из ККТ данные останутся в таблице 18

**Comment by swex** [comment]
По таблице 18:
При регистрации поля 7-23 заполнить, это и будут параметры регистрации.
Поля 1-6 передаются в теле команды регистрации.
После чего все эти поля восстанавливаются при загрузке ККТ и инициализации ФНа.

**Comment by ConsperSerj** [comment]
Я просто смотрю что номер ккт есть в двух таблицах. В последней 18 и в
таблице с ФН. По этому хочу понять кто из них главнее и на какую таблицу
нужно опираться чтобы получить номер ккт. Я так понимаю что лучше на
таблицу 18?

чт, 27 мая 2021 г., 16:31 Alexey Mednyy ***@***.***>:

**Comment by swex** [comment]
Что за устройство? В устройствах различаются номера таблиц. Все что до этого обсуждали касалось таблицы ФН, которую можно получить из [команды F7](https://github.com/shtrih-m/fr_drv_ng_examples/blob/master/classic_interface/main.cpp#L1054).

**Comment by ConsperSerj** [comment]
Pax a90. У меня есть таблица состояние фн. И таблица самая последняя
параметры регистрации. И там и там есть номер ккт. Я завтра с утра могу
более детально скрины прислать если нужно.

чт, 27 мая 2021 г., 17:11 Alexey Mednyy ***@***.***>:

**Comment by swex** [comment]
Параметры регистрации это служебная таблица, можно на нее не смотреть, смотрите только таблицу ФН.

**Comment by ConsperSerj** [comment]
Но вот если я достаю фн из кассы, то в данной таблице номер ккт становится
пустым. А вот в таблице параметры регистрации он остаётся.

чт, 27 мая 2021 г., 17:54 Alexey Mednyy ***@***.***>:

**Comment by swex** [comment]
в таблице фн данные из ФН, в таблице регистрации данные, записанные при регистрации и они доступны на запись в любой момент, их можно переписать.

**Comment by ConsperSerj** [comment]
Значит на таблицу параметры регистрации кассы лучше не смотреть чтобы
получить номер ккт, а лучше смотреть на таблицу Фискальный накопитель?

Получается что без фн не получится получить номер ккт?

Или я не правильно понимаю?

чт, 27 мая 2021 г., 18:02 Alexey Mednyy ***@***.***>:

**Comment by ConsperSerj** [comment]
Если достать фн у меня в таблице фискальный накопитель все затирается.
Нооо. В таблице 17 номер ккт остаётся . Можно ли опираться на номер таблице
17 или лучше не стоит?

Это я для пояснения все прислал

чт, 27 мая 2021 г., 18:05 Siarhei Vaitovich ***@***.***>:

**Comment by ConsperSerj** [comment]
У меня задача стоит чтобы каким то образом получить номер фн при отсутствии
фн в кассе. Я изначально полез в таблицу фискальный накопитель. Но
обнаружил что когда фн нет в кассе то логично нету и номера ккт и данных в
этой таблице. Тогда получал что можно опираться на таблицу параметры
регистрации кассы. Решил у вас уточнить можно ли это делать?

чт, 27 мая 2021 г., 18:09 Siarhei Vaitovich ***@***.***>:

**Comment by ConsperSerj** [comment]
Смотри у меня есть вот такая таблица. 

https://drive.google.com/file/d/1rvEZTG7WeScoH-vqkEtq8L6263WHr-Ub/view?usp=sharing
https://drive.google.com/file/d/1kLRhqskLgFL0SSmn51j_CbEx8XiviXrO/view?usp=sharing

Номер 17. 

Я провел эксперемент. Я в этой таблице зачистил все данные. Потом на кассе сделал технологическое обнуление. После чего перезагрузил кассу. По итогу я получил что все таблицы пусты. Потом я провел регистрацию. Зашел в таблицу номер 17 и увидел что регистрационный номер ККТ заполнился правильно.

Отсюда вопрос. Данную таблицу и данное 3 поле, может меняться в ходе работы ядра? Или их могут менять только методы регистрации и перерегистрации?

**Comment by swex** [comment]
могут, ее может переписать любой клиент. Не нужно туда смотреть. Хотите запоминать соответствие ЗН ККТ: РНМ - ведите базу

**Comment by ConsperSerj** [comment]
Понял. Спасибо
