### ISSUE TITLE
Проверка КМ

### ISSUE THREAD

**Issue by LankoRu** [shtrih-m/fr_drv_ng#139]
Есть ряд вопросов/замечаний по процедуре проверке и регистрации выбытия КМ по ФФД 1.2.

1. Нашёл метод FNAcceptMa**kr**ingCode(), тут очепятка в названии
2. Не нашёл метода для очистки буфера КМ (который FF69h с параметром 2), в JPOS он есть - https://github.com/shtrih-m/javapos_shtrih/blob/master/Source/Core/src/com/shtrih/fiscalprinter/command/FSAcceptMC.java
3. Планируется реализовать такой порядок проверки КМ:
- провести проверку набора КМ через метод FNCheckItemBarcode() (итеративно), вызывая FNAcceptMakringCode() на каждом
- открыть чек, передать позиции с привязкой КМ через FNBindMarkingItem() (тут видимо в документации не хватает параметра Barcode или какого-то такого)
- оплатить и закрыть чек

По этой схеме есть вопросы:
- возможна ли она в принципе или проверку КМ можно запускать только внутри открытого чека?
- правильно ли я понимаю, что между проверкой КМ и чеком с этими КМ других ФД формироваться не должно?
- нужно ли передавать значение реквизита 2106 из результата FNCheckItemBarcode() в позицию, или ККТ/драйвер сами подставят это значение из какого-нибудь кеша?

4. Нужно ли как-то заниматься ручным вызовом обновления ключей ФН-М, или ККТ сделает всё сама?
5. Есть ли возможность настроить время ожидания ответа сервера ИСМ или прервать проверку?

**Comment by swex** [comment]
Если еще актуально:
1. Добавлен метод `FNAcceptMakringCode` (без опечатки), старый оставлен для совместимости...
2. Добавлен метод `FNMarkingClearBuffer`
3. см. [Порядок действий при работе с кодами маркировки (ФФД 1.2).docx](https://github.com/shtrih-m/fr_drv_ng/files/6705036/1.2.docx)
4. не нужно
5. нет

**Comment by v0d0m3r** [comment]
Здравствуйте,
после прочтения документа из п.3 предыдущего комента (порядок действий при 1.2), появился вопрос как работать с ЕГАИС 2.0 и ЕГАИС 3.0? (До этого вызывался метод передачи tlv-структуры, привязанной к операции 0xff4d и указывался тег 1162, и т.д.)

**Comment by surfernsk** [comment]
> Здравствуйте,
> после прочтения документа из п.3 предыдущего комента (порядок действий при 1.2), появился вопрос как работать с ЕГАИС 2.0 и ЕГАИС 3.0? (До этого вызывался метод передачи tlv-структуры, привязанной к операции 0xff4d и указывался тег 1162, и т.д.)

Все по прежнему должно работать. ЕГАИС не имеет отношение к маркировке продукции

**Comment by v0d0m3r** [comment]
Спасибо, т.е. для ЕГАИС товара использую тег 1162, а логику для маркированных товаров убираю из 1162 в логику из документа про 1.2(там тег 1163 сформирует ккт)?

**Comment by surfernsk** [comment]
> Спасибо, т.е. для ЕГАИС товара использую тег 1162, а логику для маркированных товаров убираю из 1162 в логику из документа про 1.2(там тег 1163 сформирует ккт)?

Поспешил ответить, там есть изменения

**Comment by v0d0m3r** [comment]
Да, тоже немного в смятении. Согласно приложению к приказу от  ФНС от ... есть таблица 117 структура реквизита код товара тег 1163, и там есть вложенные теги, помимо тегов для КТ GS1.0/GS1.M, так же 1308 и 1309 (для егаис товаров).

**Comment by v0d0m3r** [comment]
Понятно, как его сформировать? (Есть ли пример используя 0xff4d-метод, или как это можно сделать программой Тест драйвера)

**Comment by surfernsk** [comment]
> Понятно, как его сформировать? (Есть ли пример используя 0xff4d-метод, или как это можно сделать программой Тест драйвера)

Попробуйте метод FNSendItemBarcode(). передаете код маркировки целиком Set_BarCode(), ккт сама должна разобрать.

**Comment by v0d0m3r** [comment]
Хорошо, попробую, передам в метод 0xff67(у нас своя реализация драйвера), по результату отпишу. Так же, в тест драйвере(5.15.858 32 бит) выполнил на вкладке "Операции с ФН" открыть чек -> выбрал призн.предм.расчета подакцизный товар -> операция v2 -> перешёл на вкладку ККТ2 -> скопировал марку ЕГАИС 3.0 в поле данные штрих-кода -> нажал Передать и распознать КТ -> получил "код товара не распознан".

**Comment by olefard** [comment]
> скопировал марку ЕГАИС 3.0 в поле данные штрих-кода -> нажал Передать и распознать КТ -> получил "код товара не распознан".

Это ошибка в прошивке ФРа. Должна быть исправлена в прошивках после 8 июля.

**Comment by v0d0m3r** [comment]
В из длинного запроса: Сборка ПО 40716, дата по 19.07.2021.

**Comment by olefard** [comment]
Выложите, пожалуйста, марку и лог.

**Comment by v0d0m3r** [comment]
Не знаю что поменялось, но код распознался в тест драйвере...

**Comment by olefard** [comment]
Может в прошлый раз нажали не "передать и распознать КТ", а кнопку ниже "Поверить код маркировки"?

**Comment by v0d0m3r** [comment]
Скорее всего, 99% вы правы, (моя вина, шрифт мелкий на ноуте, мог не различить)

**Comment by v0d0m3r** [comment]
Сейчас, тогда для маркированного товара буду делать как в инструкции по 1.2. А для ЕГАИС-товара, только после операции v2 буду вызывать метод FNSendItemBarcode() вместо формирования тега 1162. Спасибо)

**Comment by v0d0m3r** [comment]
Здравствуйте, оставлю здесь, свои наблюдения по 1.2. Изменился Тег 1212(признак предмета расчета). Мы пришли к следующим значениям (для категорий, которыми мы торгуем):
1) для товара не егаис и не маркированного - 1
2) для пива, ЕГАИс 2.0 и 3.0 - 2
3) для сиг пачек и блоков - 31
4) для легкой, обуви - 33

**Comment by v0d0m3r** [comment]
Также, было не очевидно для меня, что тег 2108 (мера количества предмета расчета) должен задаваться для ВСЕХ видов товаров (как для маркированных, так и для без маркировки).
