### ISSUE TITLE
Описания кодов возврата из утилиты в случае ошибки

### ISSUE THREAD

**Issue by HFShak** [shtrih-m/fr_drv_ng#14]
Добрый день.
Подскажите, а где посмотреть коды возврата ошибок из утилиты и их описание? Кроме логов и чтения из консоли. Есть где-нибудь документ со списком всех ошибок?

**Comment by swex** [comment]
Найти можно в протоколе ФР. Например [здесь](https://github.com/shtrih-m/javapos_shtrih/blob/master/Doc/SHTRIH/%D0%9F%D1%80%D0%BE%D1%82%D0%BE%D0%BA%D0%BE%D0%BB%D0%9A%D0%9A%D0%A2_2.0(c24)11.05.17.pdf).
