### ISSUE TITLE
Неверное время

### ISSUE THREAD

**Issue by Yanovsky** [shtrih-m/fr_drv_ng#142]
Скачал **fr_drv_ng_windows_i386_1.5.0-23-gfc65de4.zip** и **fr_drv_ng_java_wrappers_1.5.0-23-gfc65de4.zip**
Распаковав **fr_drv_ng_java_wrappers_1.5.0-23-gfc65de4.zip**, имею **classic_java_fr_drv_ng-1.4.6.355.jar**

Имею странный результат:
После вызова команды _driver.GetECRStatus()_
в свойстве Time (получаемом вызовом метода _driver.Get_Time()_) время на 3 часа больше актуального. 

Те же операции на драйвере 1.4.6.334 время правильное

**Comment by swex** [comment]
Да, сломалось для java. В последнем релизе поправили.
