### ISSUE TITLE
Ошибка при отправке тега с датой

### ISSUE THREAD

**Issue by Kizkaz** [shtrih-m/fr_drv_ng#143]
Добрый день, начала появляться ошибка при формировании тега 1178. Используется последняя актуальная версия библиотеки + java-враппер.

Пример кода:

```java
checkResult(driver.FNBeginCorrectionReceipt());

// Основание для коррекции
driver.Set_CorrectionType(receipt.getCorrection().getType().getCode());

// Дата документа основания для коррекции
if (receipt.getCorrection().getDocumentDate() != null) {
    var date = new SimpleDateFormat("yyyy-MM-dd").parse(receipt.getCorrection().getDocumentDate());
    addDateTag(1178, date);
}
```

метод addDateTag: 
```java
/**
 * Добавить тег с датой
 * @param tag   тег
 * @param value дата
 */
private void addDateTag(int tag, Date value) {
    driver.Set_TagNumber(tag);
    driver.Set_TagType(6);
    driver.Set_TagValueDateTime(value);
    checkResult(driver.FNSendTag());
}
```

[fr_drv_ng.log](https://github.com/shtrih-m/fr_drv_ng/files/6847289/fr_drv_ng.log)
Ошибка на 368 строке

Подскажите, пожалуйста, это новая версия библиотеки или на нашей стороне ошибка? Заранее спасибо

**Comment by swex** [comment]
1. у вас версия явно не последняя. При обновлении библиотеки необходимо заменить jar и *.so файлы из сборки
```
[2021-07-20 12:52:05.102] [10272] [classic_fr_drv_ng               ] [I] classic_fr_drv_ng version: 1.4.6.347
[2021-07-20 12:52:05.102] [10272] [classic_fr_drv_ng               ] [I] build date: 2021-03-30T04:30:53
```
2. с java оберткой есть проблемы в части даты, свойство `TagValueDateTime` принимает дату в unixtime в секундах и ККТ ничего не знает о часовых поясах. Для чека коррекции необходимо брать время до суток чтобы было 0 часов 0 минут. А ваш код делает локальное время:
```
[2021-07-20 12:52:26.834] [2496] [classic_interface_0x1f004002010 ] [T] Set_TagValueDateTime(`1625605200`)
```
что равно `Tue Jul 06 2021 21:00:00 GMT`
Необходимо явно указать временную зону для `SimpleDateFormat`
```java
var sdf = new SimpleDateFormat("yyyy-MM-dd");
sdf.setTimeZone(TimeZone.getTimeZone("UTC"));
var date = sdf.parse(receipt.getCorrection().getDocumentDate());
```

**Comment by Kizkaz** [comment]
Да, спасибо, дело было в часовом поясе.
