### ISSUE TITLE
Lazarus

### ISSUE THREAD

**Issue by ApiDjango** [shtrih-m/fr_drv_ng#146]
Добрый день. Есть проект на Delphi, хочу перенести в Linux,  подскажите пожалуйста как можно импортировать либу в Lazarus

**Comment by swex** [comment]
Общий подход по линковке C/C++ библиотек с FreePascal можно найти `[здесь](https://forum.lazarus.freepascal.org/index.php?topic=44237.0)`

В случае с fr_drv_ng в архиве со сборками поставляется заголовочный `c_classic_interface.h` в котором можно найти все C-шные сигнатуры для импорта в свой Lazarus проект.

**Comment by ApiDjango** [comment]
Есть вот такой пример 
```
const
{$ifdef win32}
  gtklib = 'libgtk-win32-2.0-0.dll';
{$else}
  {$ifdef darwin}
    gtklib = 'gtk-x11-2.0';
    {$linklib gtk-x11-2.0}
  {$else}
    gtklib = 'libgtk-x11-2.0.so';
  {$endif}
{$endif}

procedure gtk_widget_set_events(widget:PGtkWidget; events:gint); cdecl; external gtklib;
```

Должно быть примерно так и либу правильно указал ? 
`const
  Drv = 'ld-linux-x86-64.so.2';   

procedure Connect (Password:string; nil; nil; nil; ComputerName:string; 0; 6; TCPPort:integer; IPAddress:string; nil); cdecl; external Drv ;
`

**Comment by swex** [comment]
>  Drv = 'ld-linux-x86-64.so.2';
это точно криво, т.к. библиотека называется `libclassic_fr_drv_ng`

**Comment by Kirill** [comment]
@swex А у Вас получилось скомпилировать полученный файл pas? У меня ругается на него. Последнее, что я не смог победить - не найдено определение c_classic_context_t.
