### ISSUE TITLE
Продажа маркированного товара на ФФД 1.2

### ISSUE THREAD

**Issue by harley-davidson-spb** [shtrih-m/fr_drv_ng#147]
ККТ Штрих-ON-LINE + МГМ (ФМ ФН-М)
Зарегистрирован на ФФД 1.2
Реализация на java с релизом 1.5.0-24-g182e6f0

- Проверяю КМ (код маркировки):
`driver.Set_BarCode(markCode);`
`driver.Set_ItemStatus(1);`
`driver.Set_CheckItemMode(0);`
`driver.FNCheckItemBarcode();`
- Подтверждаю продажу КМ:
`driver.FNAcceptMarkingCode();`
- При добавлении позиции:
`driver.FNOperation();`
`driver.Set_BarCode(barcode);`
`driver.FNSendItemBarcode();`

Вызовы этих методов выполняются без ошибок. 

Однако при закрытии чека, вызов 
`driver.FNCloseCheckEx();`
приводит к ошибке **"Marking items processing temporary blocked"**

[Запрос итогов фискализации](https://yadi.sk/i/Lc7Mg3EiN4VtXw)
[Запрос состояния](https://yadi.sk/i/YPzvmNyNDy-xxw)
[Лог вызовов fr_drv_ng.log](https://yadi.sk/d/jjxNT0cR8rnKOQ)

Переписка с вашей техподдержкой (support@shtrih-m.ru) разрешить проблему не помогла
Может быть здесь посоветуют что то полезное

**Comment by olefard** [comment]
Похоже что заполнился буфер уведомлений о продаже маркированных товаров.
Можно в тесте драйвера на вкладке ФН чеки/КТ2 сделать "Получить состояние передачи уведомлений".

Для передачи уведомлений надо в таблице ФР/параметры ОФД задать поля "Сервер КМ/порт КМ".

**Comment by harley-davidson-spb** [comment]
Не похоже:
[Параметры ОФД](https://yadi.sk/i/qfv_J72fGvG_Ow)
[Получить состояние передачи уведомлений](https://yadi.sk/i/q7E6HQy8Z5F_rA)

**Comment by olefard** [comment]
Попробуйте отправить все уведомления.

**Comment by harley-davidson-spb** [comment]
Не очень понимаю что для этого надо сделать
Так же мне не совсем понятно почему чеки в ОФД не уходят
хотя настроено вроде все правильно:
[Параметры офд](https://yadi.sk/i/zKHnp4ko7Y4JGQ)
[Сетевые интерфейсы](https://yadi.sk/i/nGq-7xpZoWw8Wg)
[Статус обмена с фн](https://yadi.sk/i/CnDb0dlsqe4D9Q)

**Comment by swex** [comment]
а что в таблице сетевой адрес, попробуйте включить режим DHCP

**Comment by v0d0m3r** [comment]
И ещё попробуйте прописать реальные ip адреса, вместо dns. У нас так работает, с ОФД Ярус.

**Comment by harley-davidson-spb** [comment]
Прописал IP вместо f1test.taxcom.ru
[Сетевой адрес](https://yadi.sk/i/qBm8FlqU97fARQ)
В какой таблице можно "включить режим DHCP" не нашел
Но теперь [вот здесь](https://yadi.sk/i/IRYDOwdaTZpmLw) значения параметров
"Транспортное соединение установлено", "Есть сообщение для передачи в ОФД" и "Ожидание ответного сообщения от ОФД", с периодичностью в 2-3 нажатия на кнопку "Получить статус инф. обмена", меняются на противоположные значения.
Однако "Количество сообщений для ОФД" не уменьшается

**Comment by olefard** [comment]
> В какой таблице можно "включить режим DHCP" не нашел

В таблице "сетевой адрес" в первом поле "static ip" прописать 0.
0 - DHCP
1 - статический ip

**Comment by harley-davidson-spb** [comment]
Прописал 0 в "static ip", перезагрузил принтер. 
Теперь не подключается вообще

Было настроено подключение через RNDIS.
При включении принтера RNDIS адаптер появляется в списке сетевых подключений, но из "Тест драйвера" принтер больше не коннектится

**Comment by olefard** [comment]
Для rndis`а зря прописали static ip=0. Теперь он получает ip-адрес из диапазона (192.168.137.1 .. 192.168.137.255).
Можно или программку написать для перебора или bat-файл для console_test_fr_drv_ng.
Через console_test_fr_drv_ng можно написать такой bat-файл:
```
for /L %%I in (2,1,254) DO (
console_test_fr_drv_ng status -a tcp://192.168.137.%%I:7778?timeout=100 -p 30
)
```
И посмотреть на каком ip-адресе будет получено состояние.

Или подключиться к принтеру по COM-портовому кабелю.

**Comment by swex** [comment]
1. ФР работает только с одним сетевым интерфейсом
2. Как устроена инициализация сети на ФР:
а) Если включен режим PPP - то ФР стартует службу PPP
б) Если WiFi адаптер присутствует и WiFi включен в таблицах - работаем с wifi, иначе если RNDIS включен - работаем с RNDIS, в остальных случаях ethernet

Попробуйте восстановить доступ к ФР с помощью советов от @olefard и сконфигурировать ТОЛЬКО WiFi (отключить RNDIS и всё остальное).
На время конфигурации удобно иметь соединение по COM порту.

**Comment by harley-davidson-spb** [comment]
> Для rndis`а зря прописали static ip=0. Теперь он получает ip-адрес из диапазона (192.168.137.1 .. 192.168.137.255).
> Можно или программку написать для перебора или bat-файл для console_test_fr_drv_ng.
> Через console_test_fr_drv_ng можно написать такой bat-файл:
> 
> ```
> for /L %%I in (2,1,254) DO (
> console_test_fr_drv_ng status -a tcp://192.168.137.%%I:7778?timeout=100 -p 30
> )
> ```
> 
> И посмотреть на каком ip-адресе будет получено состояние.
> 
> Или подключиться к принтеру по COM-портовому кабелю.

Увы, [не находит](https://yadi.sk/d/bs1p0chvAmq3vA)

**Comment by olefard** [comment]
А вы как свойства сетевого подключения Shtrih-ON_LINE на компьютере настраивали? Вручную или расшарили интернет с подключения "Ethernet"?

И попробуйте подключить принтер через COM-порт. СОМ-порт всегда работает.

**Comment by harley-davidson-spb** [comment]
- Расшарили интернет с подключения "Ethernet"
- Да уже понял, что только через COM. Но у меня на компе нет COM-портов... Буду искать уже в понедельник. 
- Спасибо

**Comment by olefard** [comment]
Все-таки если рндис работал, то и с static ip=0 должен работать. Попробуйте, пожалуйста, выполнить следующие действия:
- отключить расширивание интернета, включить
- выключить принтер, включить
- дождаться, когда принтер пискнет и на нем перестанет мигать зеленая лампочка
- запустить бат-файл

**Comment by harley-davidson-spb** [comment]
Сработало! 👍🏻

**Comment by olefard** [comment]
Тогда static ip можно вернуть в 1 и в той же таблице ip адрес прописать нужный.
И по идее сейчас должны чеки и уведомления о продаже марок отправиться.

**Comment by harley-davidson-spb** [comment]
По этому вопросу решено. 
Спасибо
