### ISSUE TITLE
FNGetFiscalizationResult() - Не верные данные о фискализации (ФФД 1.2)

### ISSUE THREAD

**Issue by surfernsk** [shtrih-m/fr_drv_ng#148]
Здравствуйте.
_Qt 5.12.8 и qclassic_interface.h
Версия драйвера:  "1.4.6.358"_

Запрос данных о последней фискализации возвращает не верные данные. Не учтен формат возвращаемых командой _**FF09h**_ данных, при использовании ФФД 1.2 (ФФД 1.1)
Не верные данные в свойствах: _RegistrationReasonCode, DocumentNumber, FiscalSign, FiscalSignAsString_.
А также в _Date_ и _Time_, время отличается на 1 минуту.

<img width="461" alt="Screenshot_20210822_025854" src="https://user-images.githubusercontent.com/2264893/130334037-4f556d1b-05b3-4932-89d6-c84d91bea213.png">

```
Версия драйвера:  "1.4.6.358"
Fiscalization Date:  "20-08-2021 15-52-00"
Fiscalization Date:  QDateTime(2021-08-20 15:52:00.000 +07 Qt::LocalTime)
User INN:  "5403180281"
RegistrationNumbe:  "0020210812064397"
Tax type:  55
WorkMode:  1
RegistrationReasonCode:  17
DocumentNumber:  942815031
FiscalSign:  892942646
FiscalSignAsString:  "892942646"
```

[fr_drv_ng.log](https://github.com/shtrih-m/fr_drv_ng/files/7026163/fr_drv_ng.log)
[shtrihTD.zip](https://github.com/shtrih-m/fr_drv_ng/files/7026174/shtrihTD.zip)

**Comment by swex** [comment]
спасибо, поправлено в актуальном релизе
