### ISSUE TITLE
Настройка взаимодействия с c#

### ISSUE THREAD

**Issue by MAY-ME-PP** [shtrih-m/fr_drv_ng#149]
Добрый день!
Стоит задача разработать модуль для взаимодействия с ккт штрих-фр-01ф на языке c# в операционной системы linux.
Никак не выходит настроить взаимодействие драйвера с c#. Есть ли какая-то инструкция, примеры или уже сгенерированная сборка под c#?
Спасибо.

**Comment by surfernsk** [comment]
Ответ на ваш вопрос здесь - #87 

Duplicate of # 87

**Comment by swex** [comment]
посмотрите [пример](https://github.com/shtrih-m/fr_drv_ng_examples/tree/master/classic_csharp)
