### ISSUE TITLE
получение значения ФП: в фискальном чеке

### ISSUE THREAD

**Issue by try2bajed1** [shtrih-m/fr_drv_ng#15]
я так понимаю генерируется рандомный номер, соответствующий этому чеку. Подскажите, как -то можно выдернуть это значение? посмотрел через FNGetStatus все возвращаемые методы, не нашел такого. Или такой возможности просто нет? Спасибо.

**Comment by olefard** [comment]
Если для закрытия чека пользуетесь методом `FNCloseCheckEx`, то после успешного вызова будут заполнены свойства:
 - DocumentNumber - номер ФД,
 - FiscalSign - фискальный признак(ФП).

**Comment by try2bajed1** [comment]
закрывю через CloseCheck(). Видимо поэтому у меня в DocumentNumber отдавается ноль.
Т.е через FnCloseCheckEx предпочтительней делать закрытие?

**Comment by try2bajed1** [comment]
FNOperation заменил недавно ввиду работы с дробными количествами. Про FNCloseCheckEx не знал. большое спасибо.

**Comment by olefard** [comment]
И можно вытащить из ФН документ, там все фискальные признаки будут. См. методы: `FNRequestFiscalDocumentTLV`, `FNReadFiscalDocumentTLV`, `FNGetDocumentAsString`.
