### ISSUE TITLE
Чек коррекции на ФФД 1.2

### ISSUE THREAD

**Issue by harley-davidson-spb** [shtrih-m/fr_drv_ng#150]
Прошу помочь разобраться с оформлением чека коррекции на ФФД 1.2
Какие методы и в какой последовательности вызывать?
Если пробовать выполнять это в "Тест Драйвера ККТ 5.16.0.868" то, очевидно, надо вызывать 
- "ФН Чеки" -> "Операции ФН" -> "Открыть чек коррекции" (**_FNBeginCorrectionReceipt_**)
- "ФН Чеки" -> "Атрибуты чека" -> "Атрибуты чека коррекции" -> "Передать данные коррекции" (**_FNSendUserAttribute_**)
-  "ФН Чеки" -> "Операции ФН" -> "Операция v2" (**_FNOperation_**)
-  "ФН Чеки" -> "Операции ФН" -> "Закрытие чека расширенное v2" (**_FNCloseCheckEx_**)
Странно то, что метод **_FNSendUserAttribute_** отсутствует как в **документации**, так и в **classic_java_fr_drv_ng-1.4.6.358.jar**

**Comment by surfernsk** [comment]
@harley-davidson-spb 
В [репозитории](https://github.com/shtrih-m/fr_drv_ng_examples) с примерами, присутствует реализация с примерами.

**Comment by harley-davidson-spb** [comment]
> @harley-davidson-spb
> В [репозитории](https://github.com/shtrih-m/fr_drv_ng_examples) с примерами, присутствует реализация проведения чека коррекции.

Вот [тут](https://github.com/shtrih-m/fr_drv_ng_examples/blob/master/classic_java/src/main/java/example.java) нет примера оформления чека коррекции. Поэтому и спрашиваю

**Comment by surfernsk** [comment]
> > @harley-davidson-spb
> > В [репозитории](https://github.com/shtrih-m/fr_drv_ng_examples) с примерами, присутствует реализация проведения чека коррекции.
> 
> Вот [тут](https://github.com/shtrih-m/fr_drv_ng_examples/blob/master/classic_java/src/main/java/example.java) нет примера оформления чека коррекции. Поэтому и спрашиваю

Напомню что драйвер написан на С++ (С), и полные примеры тоже приложены на С++ (С).
[Пример](https://github.com/shtrih-m/fr_drv_ng_examples/blob/master/classic_interface/main.cpp)
````
/*!
 * \brief fsCorrectionReceipt пример печати чека коррекции FNBuildCorrectionReceipt2
 * \param ci
 */
static void fsCorrectionReceipt(classic_interface* ci)
{
    PasswordHolder ph(ci, ci->Get_SysAdminPassword());

    //начало чека коррекции
    executeAndHandleError(std::bind(&classic_interface::FNBeginCorrectionReceipt, ci));

    //отправка тэгов

    //устанавливаем тег 1177 наименование основания для коррекции
    ci->Set_TagNumber(1177);
    ci->Set_TagType(7); //Тип "строка"
    ci->Set_TagValueStr("correction name");
    executeAndHandleError(std::bind(&classic_interface::FNSendTag, ci));

    //здесь устанавливаем тег 1178 дата документа основания для коррекции
    ci->Set_TagNumber(1178);
    ci->Set_TagType(6); //Тип "время"
    std::time_t unixtime;
    { // 1.01.2018 - 48 лет с 1.01.1970, в секундах
        std::tm date20180101 = {};
        date20180101.tm_year = 118;
        date20180101.tm_mday = 1;
        date20180101.tm_isdst = -1;
        unixtime = timegm(&date20180101);
    }
    ci->Set_TagValueDateTime(unixtime);
    executeAndHandleError(std::bind(&classic_interface::FNSendTag, ci));

    //устанавливаем тег 1179 номер документа основания для коррекции
    ci->Set_TagNumber(1179);
    ci->Set_TagType(7); //Тип "строка"
    ci->Set_TagValueStr("12345");
    executeAndHandleError(std::bind(&classic_interface::FNSendTag, ci));

    //печать чека коррекции
    ci->Set_Summ1(3000); //сумма коррекции
    ci->Set_Summ2(2000);
    ci->Set_Summ3(1000);
    ci->Set_Summ4(0);
    ci->Set_Summ5(0);
    ci->Set_Summ6(0);
    ci->Set_Summ7(0);
    ci->Set_Summ8(0);
    ci->Set_Summ9(0);
    ci->Set_Summ10(0);
    ci->Set_Summ11(0);
    ci->Set_Summ12(0);
    ci->Set_CorrectionType(0); //Тип коррекции "самостоятельно"
    ci->Set_CalculationSign(1); //признак расчета "коррекция прихода"
    ci->Set_TaxType(1); //схема налогообложения "основная"
    executeAndHandleError(std::bind(&classic_interface::FNBuildCorrectionReceipt2, ci));
}
````

**Comment by harley-davidson-spb** [comment]
Увы, но вызов метода FNBeginCorrectionReceipt() приводит к ошибке 55 ("Command is not supported")

> [2021-08-24 17:38:13.821] [8960] [classic_interface_0x2004fd18    ] [T] FNBeginCorrectionReceipt()
[2021-08-24 17:38:13.821] [8960] [SerialIO_0xb4f270               ] [D] -> 02 06 FF 35 1E 00 00 00 D2
[2021-08-24 17:38:13.836] [8960] [SerialIO_0xb4f270               ] [D] <- 06 02 03 FF 35 37 FE
[2021-08-24 17:38:13.836] [8960] [SerialIO_0xb4f270               ] [D] -> 06
[2021-08-24 17:38:13.836] [8960] [ProtocolV1_0x1c4feeb0           ] [D] command FF35 return code: 55 execution took 15ms
[2021-08-24 17:38:13.836] [8960] [ProtocolV1_0x1c4feeb0           ] [E] Command is not supported
[2021-08-24 17:38:13.836] [8960] [ProtocolV1_0x1c4feeb0           ] [D] commands total: 511, succeed: 509, failed: 2, avg. exec time: 21ms
[2021-08-24 17:38:13.836] [8960] [classic_interface_0x2004fd18    ] [D] FNBeginCorrectionReceipt() fail
[2021-08-24 17:38:13.836] [8960] [classic_interface_0x2004fd18    ] [E] Command is not supported
[2021-08-24 17:38:19.242] [8960] [classic_interface_0x2004fd18    ] [T] Get_ResultCode()
[2021-08-24 17:38:19.242] [8960] [classic_interface_0x2004fd18    ] [T] Get_ResultCode() -> `55`
[2021-08-24 17:38:19.886] [8960] [classic_interface_0x2004fd18    ] [T] Get_ResultCodeDescription()
[2021-08-24 17:38:19.886] [8960] [classic_interface_0x2004fd18    ] [T] Get_ResultCodeDescription() -> `Command is not supported`

**Comment by surfernsk** [comment]
> Увы, но вызов метода FNBeginCorrectionReceipt() приводит к ошибке 55 ("Command is not supported")
> 
> > [2021-08-24 17:38:13.821] [8960] [classic_interface_0x2004fd18    ] [T] FNBeginCorrectionReceipt()
> > [2021-08-24 17:38:13.821] [8960] [SerialIO_0xb4f270               ] [D] -> 02 06 FF 35 1E 00 00 00 D2
> > [2021-08-24 17:38:13.836] [8960] [SerialIO_0xb4f270               ] [D] <- 06 02 03 FF 35 37 FE
> > [2021-08-24 17:38:13.836] [8960] [SerialIO_0xb4f270               ] [D] -> 06
> > [2021-08-24 17:38:13.836] [8960] [ProtocolV1_0x1c4feeb0           ] [D] command FF35 return code: 55 execution took 15ms
> > [2021-08-24 17:38:13.836] [8960] [ProtocolV1_0x1c4feeb0           ] [E] Command is not supported
> > [2021-08-24 17:38:13.836] [8960] [ProtocolV1_0x1c4feeb0           ] [D] commands total: 511, succeed: 509, failed: 2, avg. exec time: 21ms
> > [2021-08-24 17:38:13.836] [8960] [classic_interface_0x2004fd18    ] [D] FNBeginCorrectionReceipt() fail
> > [2021-08-24 17:38:13.836] [8960] [classic_interface_0x2004fd18    ] [E] Command is not supported
> > [2021-08-24 17:38:19.242] [8960] [classic_interface_0x2004fd18    ] [T] Get_ResultCode()
> > [2021-08-24 17:38:19.242] [8960] [classic_interface_0x2004fd18    ] [T] Get_ResultCode() -> `55`
> > [2021-08-24 17:38:19.886] [8960] [classic_interface_0x2004fd18    ] [T] Get_ResultCodeDescription()
> > [2021-08-24 17:38:19.886] [8960] [classic_interface_0x2004fd18    ] [T] Get_ResultCodeDescription() -> `Command is not supported`

Это общее описание. При формирования ФД, метод начала применяется редко.
В драйвере Win, будет аналогично - это кнопка "Начать форм. чека коррекции"
Пропустите его.

**Comment by harley-davidson-spb** [comment]
Если не вызывать 
На чековой ленте печатается "ЧЕК НА ПРОДАЖУ N: ...."

**Comment by surfernsk** [comment]
> Если не вызывать
> На чековой ленте печатается "ЧЕК НА ПРОДАЖУ N: ...."
> 
> И вызов FNBuildCorrectionReceipt2()
> Так же приводит к ошибке 55 "Command is not supported"

Аналогичное поведение при формировании чека из ТестДрайвер ФР. Ошибку возвращает ККТ, необходимо обратиться в ТП производителя ККТ.

**Comment by harley-davidson-spb** [comment]
Мне хотелось бы получить примерно то же, что на [видео](https://yadi.sk/i/qdFy-dl9ouzYcw)

**Comment by surfernsk** [comment]
> Из ТестДрайвера ФР все прекрасно отрабатывает
> Мне хотелось бы получить примерно то же, что на [видео](https://yadi.sk/i/qdFy-dl9ouzYcw)

Методы не реализованы, увы. Пример использовал команды для ффд 1.05

FNOpenCheckCorrection() - открыть чек коррекции
далее передать теги для описания коррекции, если будет отсутствовать реализация в драйвере.

**Comment by harley-davidson-spb** [comment]
Вызов метода FNOpenCheckCorrection() так же приводит к ошибке:

> [2021-08-24 18:18:06.224] [9468] [classic_interface_0x1fd1d030    ] [T] FNOpenCheckCorrection()
[2021-08-24 18:18:06.224] [9468] [classic_interface_0x1fd1d030    ] [D] FNOpenCheckCorrection() fail
[2021-08-24 18:18:06.224] [9468] [classic_interface_0x1fd1d030    ] [E] Not supported
[2021-08-24 18:18:06.793] [9468] [classic_interface_0x1fd1d030    ] [T] Get_ResultCode()
[2021-08-24 18:18:06.793] [9468] [classic_interface_0x1fd1d030    ] [T] Get_ResultCode() -> `-12`
[2021-08-24 18:18:06.793] [9468] [classic_interface_0x1fd1d030    ] [T] Get_ResultCodeDescription()
[2021-08-24 18:18:06.793] [9468] [classic_interface_0x1fd1d030    ] [T] Get_ResultCodeDescription() -> `Not supported`

**Comment by surfernsk** [comment]
> Вызов метода FNOpenCheckCorrection() так же приводит к ошибке:
> 
> > [2021-08-24 18:18:06.224] [9468] [classic_interface_0x1fd1d030    ] [T] FNOpenCheckCorrection()
> > [2021-08-24 18:18:06.224] [9468] [classic_interface_0x1fd1d030    ] [D] FNOpenCheckCorrection() fail
> > [2021-08-24 18:18:06.224] [9468] [classic_interface_0x1fd1d030    ] [E] Not supported
> > [2021-08-24 18:18:06.793] [9468] [classic_interface_0x1fd1d030    ] [T] Get_ResultCode()
> > [2021-08-24 18:18:06.793] [9468] [classic_interface_0x1fd1d030    ] [T] Get_ResultCode() -> `-12`
> > [2021-08-24 18:18:06.793] [9468] [classic_interface_0x1fd1d030    ] [T] Get_ResultCodeDescription()
> > [2021-08-24 18:18:06.793] [9468] [classic_interface_0x1fd1d030    ] [T] Get_ResultCodeDescription() -> `Not supported`

Методы не реализованы для ффд 1.2 - FNOpenCheckCorrection() "в заголовочном отсутствует описание"

**Comment by olefard** [comment]
В тесте драйвера не правильная всплывающая подсказка для кнопки "Передать данные коррекции". Выводится всплывающая подсказка от кнопки сверху "Передать доп. реквизит пользователя".
При нажатии на кнопку "Передать данные коррекции" передаются теги 1173, 1177, 1178, 1179 методом FNSendTag.

**Comment by surfernsk** [comment]
можно отравить команду 8D 1E 00 00 00 80 - открыть чек (коррекции), как временное решение, а далее 
> При нажатии на кнопку "Передать данные коррекции" передаются теги 1173, 1177, 1178, 1179 методом FNSendTag.
и т.д.

````
    //!
    //! @brief Метод посылает последовательность байтов от хоста в ККТ и получает ответ.
    //!
    //! Посылает последовательность по текущему транспортному слою
    //!
    //! @note Метод может вызываться в любой момент времени
    //!
    //! @par Используемые свойства:
    //!  - #TransferBytes - Последовательность байтов, посылаемая от хоста в ККТ.
    //!
    //! @par Модифицируемые свойства:
    //!  - #TransferBytes - ответ ККТ
    //!
    //! @return Код ошибки
    //!
    int ExchangeBytes();
````


> При нажатии на кнопку "Передать данные коррекции" передаются теги 1173, 1177, 1178, 1179 методом FNSendTag.

**Comment by harley-davidson-spb** [comment]
А как через драйвер отправить команду?
Есть какой то метод прямой передачи массива байт?

**Comment by surfernsk** [comment]
> А как через драйвер отправить команду?
> Есть какой то метод прямой передачи массива байт?

Исправил сообщение с более правильным решением. Посмотрите на сайте.

**Comment by harley-davidson-spb** [comment]
Не понял, на каком сайте посмотреть

**Comment by olefard** [comment]
> Не понял, на каком сайте посмотреть

[На этом](https://github.com/shtrih-m/fr_drv_ng/issues/150#issuecomment-904767773)

@surfernsk имел ввиду, что он исправил свое сообщение, и исправленное сообщение можно посмотреть на github`е.

Вместо передачи массива байт можно вызывать метод OpenCheck.

**Comment by harley-davidson-spb** [comment]
Да, сработало.
Но тег 1178 (Дата совершения корректируемого расчета) никак не хочет передаваться 
ошибка 51 "Incorrect command parameters"

> [2021-08-24 20:02:10.026] [6964] [classic_interface_0x1e412330    ] [T] Set_TagNumber(`1178`)
[2021-08-24 20:02:10.026] [6964] [classic_interface_0x1e412330    ] [T] Set_TagNumber() ok
[2021-08-24 20:02:10.393] [6964] [classic_interface_0x1e412330    ] [T] Set_TagValueDateTime(`1628542800`)
[2021-08-24 20:02:10.393] [6964] [classic_interface_0x1e412330    ] [T] Set_TagValueDateTime() ok
[2021-08-24 20:02:10.690] [6964] [classic_interface_0x1e412330    ] [T] Set_TagType(`6`)
[2021-08-24 20:02:10.690] [6964] [classic_interface_0x1e412330    ] [T] Set_TagType() ok
[2021-08-24 20:02:11.307] [6964] [classic_interface_0x1e412330    ] [T] FNSendTag()
[2021-08-24 20:02:11.307] [6964] [SerialIO_0xed6320               ] [D] -> 02 0E FF 0C 1E 00 00 00 9A 04 04 00 50 97 11 61 CE
[2021-08-24 20:02:11.334] [6964] [SerialIO_0xed6320               ] [D] <- 06 02 03 FF 0C 33 C3
[2021-08-24 20:02:11.334] [6964] [SerialIO_0xed6320               ] [D] -> 06
[2021-08-24 20:02:11.334] [6964] [ProtocolV1_0xeb5f58             ] [D] command FF0C return code: 51 execution took 26ms
[2021-08-24 20:02:11.334] [6964] [ProtocolV1_0xeb5f58             ] [E] Incorrect command parameters

В остальном вроде работает

**Comment by olefard** [comment]
Попробуйте установить часовой пояс "UTC", как здесь: https://github.com/shtrih-m/fr_drv_ng/issues/143#issuecomment-883335635

**Comment by harley-davidson-spb** [comment]
> Попробуйте установить часовой пояс "UTC", как здесь: [#143 (comment)](https://github.com/shtrih-m/fr_drv_ng/issues/143#issuecomment-883335635)

Спасибо! Помогло
