### ISSUE TITLE
console_test_fr_drv_ng

### ISSUE THREAD

**Issue by realo** [shtrih-m/fr_drv_ng#151]
Можно ли немного расширить функционал, чтобы была возможность командой fs-get-document-classic так же печатать документ непосредственно на ФР?

**Comment by swex** [comment]
Хорошая мысль, но не совсем так, добавим просто функцию print, будет печатать всё что передали на stdin или аргументом типа того:
```bash
#напечататет весь документ
console_test_fr_drv_ng fs-get-document-classic 123| console_test_fr_drv_ng print
#напечатает строку hello world
console_test_fr_drv_ng print "hello world"
```

**Comment by realo** [comment]
Спасибо!

**Comment by realo** [comment]
Спасибо!

**Comment by swex** [comment]
Добавлено в актуальном релизе, правда синтаксис немного другой:
```
print - "print from stdin"
        args: [font_number[.flags]]
```
```bash
#напечатать "Привет!" пятым шрифтом
echo "Привет!"| console_test print 5 
```
