### ISSUE TITLE
ФФД 1.2

### ISSUE THREAD

**Issue by 2UTM** [shtrih-m/fr_drv_ng#156]
Здравствуйте, какое число соответствует ФФД 1.2 в таблице кассы?
В документации нашел только
0 — Формат ФД 1.0 Beta.
1 — Формат ФД 1.0 New.
2 — Формат ФД 1.05.

И есть ли отдельная функция для получения формата ФФД, или только через таблицы можно получить?

**Comment by swex** [comment]
4 - 1.2
Отдельной функции нет, только если получать соотв. тег из документа пере/регистрации. Поэтому самый простой способ - таблицы.
