### ISSUE TITLE
Получение Qr-code от зарегистрированного чека

### ISSUE THREAD

**Issue by ConsperSerj** [shtrih-m/fr_drv_ng#159]
Подскажите пожалуйста еще 1 вопрос.

После выполнения операции регистрации чека вызываю метод FNGetDocumentAsString для получения всех параметров. Тут все прекрасно работает.

Но есть такой параметр с тэгом 1196 - qrCode. Он сейчас не присутствует в данном ответе. Подскажите будете ли данный параметр в будущем? Если будет то в каком виде?
Речь идет о qrCode Который печатается на чековой ленте в самом конце

ВАШ ОТВЕТ: 
Потому что его действительно нет в TLV документа.
Его можно сформировать самостоятельно, используя TLV или если используется КЯ, взять из таблицы 11.
PS: Открывайте новые темы, возможно кому-то будет полезно

**Comment by ConsperSerj** [comment]
Я правильно понимаю что под словами "Его можно сформировать самостоятельно, используя TLV" - нужно понимать что получить TVL документ как строку и отправить его на печать как qr код, то получится как раз Qr как в конце текста?

**Comment by olefard** [comment]
Содержимое QR-кода: t=20211007T1027&s=923.46&fn=9280440300842837&i=86248&fp=173339396&n=1
где:
t=20211007T1027 - дата/время пробития чека, формат YYYYMMDD T HHMM
s=923.46 - сумма чека 
fn=9280440300842837 - номер ФН
i=86248 - номер ФД
fp=173339396 - ФП
n=1 - СНО

Если вы получили TLV документа, все эти данные у вас точно есть.
