### ISSUE TITLE
Печать копии чека

### ISSUE THREAD

**Issue by susloparov77** [shtrih-m/fr_drv_ng#16]
Здравствуйте подскажите плиз, как напечатать копию чека по его фискальному номеру?

**Comment by swex** [comment]
такого функционала в кассе нет

**Comment by susloparov77** [comment]
Ок, а есть печать фискального документа по номеру?? Без этого вроде сертификация ККТ не возможна же?

**Comment by swex** [comment]
В интерфейсе есть метод `FNPrintDocument`, но он еще не рализован, добавим.

В данный момент можно получить документ через `FNGetDocumentAsString` и самостоятельно распечатать его по строкам через `PrintString`

**Comment by susloparov77** [comment]
Так правильно:
        execute(std::bind(&classic_interface::WaitForPrinting,  &m_ci));
        m_ci.Set_DocumentNumber(__number.toInt());
        if(execute(std::bind(&classic_interface::FNGetDocumentAsString, &m_ci)))
        {
            execute(std::bind(&classic_interface::PrintString, &m_ci))
        }
???

**Comment by susloparov77** [comment]
Скажите после Set_DocumentType нужно вызывать  FNFindDocument?

**Comment by swex** [comment]
> Так правильно:
> execute(std::bind(&classic_interface::WaitForPrinting, &m_ci));
> m_ci.Set_DocumentNumber(__number.toInt());
> if(execute(std::bind(&classic_interface::FNGetDocumentAsString, &m_ci)))
> {
> execute(std::bind(&classic_interface::PrintString, &m_ci))
> }
> ???

Чек может быть очень длинным. В общем случае необходимо руками делить "строку на строки"  :)

**Comment by swex** [comment]
> Скажите после Set_DocumentType нужно вызывать FNFindDocument?

Судя по справке - да. Вы попробуйте, ФР не должен сгореть...

**Comment by Mzales** [comment]
> Так правильно:
> execute(std::bind(&classic_interface::WaitForPrinting, &m_ci));
> m_ci.Set_DocumentNumber(__number.toInt());
> if(execute(std::bind(&classic_interface::FNGetDocumentAsString, &m_ci)))
> {
> execute(std::bind(&classic_interface::PrintString, &m_ci))
> }
> ???

Вот так, например:
```c++
uint32_t adminPassword = 30;

ci.Set_DocumentNumber(3);
ci.Set_ShowTagNumber(false);
ci.Set_Password(adminPassword);
ci.FNGetDocumentAsString();

std::string str = ci.Get_StringForPrinting();
std::size_t already_print = 0;
std::string str2;
std::size_t eos;

while((eos = str.find('\n', already_print)) != std::string::npos)
{
   str2 = str.substr(already_print, eos - already_print);
   already_print = eos + 1;

   ci.Set_StringForPrinting(str2);
   ci.PrintString();
}

str2 = str.substr(already_print);
if (!str2.empty()){
    ci.Set_StringForPrinting(str2);
    ci.PrintString();
}
```
