### ISSUE TITLE
Нерабочая ссылка в readme

### ISSUE THREAD

**Issue by mFoxRU** [shtrih-m/fr_drv_ng#162]
Ссылка в конце README не работает, отдаёт `-- 404 -- `
> общая справка [здесь](https://exam.shtrih-m-partners.ru/assets/materials/DriverKKT_Guide_414_02_10_17.zip),

**Comment by elchako** [comment]
@mFoxRU  попробуй эту ссылку
https://exam.shtrih-m-partners.ru/assets/materials/Obshchee_rukovodstvo_po_nastroyke_KKTver12_041220.zip

**Comment by surfernsk** [comment]
> Ссылка в конце README не работает, отдаёт `-- 404 -- `
> 
> > общая справка [здесь](https://exam.shtrih-m-partners.ru/assets/materials/DriverKKT_Guide_414_02_10_17.zip),

[doc.shtrih-m.ru](http://doc.shtrih-m.ru/) - все актуальные данные
