### ISSUE TITLE
Проверка маркированного кода для ФФД 1.2

### ISSUE THREAD

**Issue by t0pd3v1c3** [shtrih-m/fr_drv_ng#165]
Здравствуйте.

Драйвер Штрих-М: 5.16.0.883
Касса: ФН-М с ключами и лицензией

Есть несколько проблем:
1. Не отправляются чеки в ОФД:
![image](https://user-images.githubusercontent.com/26054454/139224744-7febe6de-e39c-4079-85e2-6f6f5a850fed.png)
Связь вроде как есть:
![image](https://user-images.githubusercontent.com/26054454/139224840-a6ccd1a7-415c-4cab-9735-675f1dc15593.png)
![image](https://user-images.githubusercontent.com/26054454/139224935-5f48a927-df61-4c9e-b743-6796b6991236.png)

2. При открытии смены ошибка:
![image](https://user-images.githubusercontent.com/26054454/139225022-8117e927-83b3-4df2-afff-ef085bd7a16b.png)
Также ошибка печатается на чеке открытия смены.

3. Не проходит проверка кода маркировки:
![image](https://user-images.githubusercontent.com/26054454/139225191-e90913d6-fc8e-480b-91a9-f22e69299de6.png)

Сам код:
`010401154803070721FWX00GG65908U<0x1D>91EE06<0x1D>92ty6nIoq1w2xrmcVLmKc3+cnhZxS/kgAnq7Bf5FH0CRQ=`

Код с реального товара

**Comment by surfernsk** [comment]
@t0pd3v1c3 
[Обновление ключей проверки не выполнено](https://docs.google.com/document/d/1uQL6Pmi883xbmVik_j--1GF1SQq4Mt8BIB5pI-Br81M)

**Comment by t0pd3v1c3** [comment]
@surfernsk
Этот документ видел. Галочка есть, регистрация правильная. Связь с ОФД также настроена через Antinat. По таблице с логами связи с ОФД ошибок нет и все подключено, но чеки не отправляются в тестовый ОФД и ошибка про ключи отображается.

**Comment by surfernsk** [comment]
@t0pd3v1c3 Повторюсь, Ваш вопрос не касается "Кроссплатформенный Драйвер ФР на C++ (fr_drv_ng)".
Вопрос по работе тест-драйвера ККТ, а также ККТ производства Штрих-М необходимо направлять на почту [tp@shtrih-m.ru](tp@shtrih-m.ru) (согласно регламента техподдержки)

**Comment by swex** [comment]
@t0pd3v1c3 посмотрите на таблицу:
![image](https://user-images.githubusercontent.com/1026241/141465751-66c8a4a2-e6e1-472c-a9aa-6ec04de93f73.png)
`Last 26h answer code`: 32 - это значит что ФН не приял ответ от ОФД
в таком случае нужно смотреть на поле `Last ofd answer code` и интерпретировать его согласно этой таблице:
![image](https://user-images.githubusercontent.com/1026241/141465990-7e45191c-d28a-4736-9c1b-8e01390bed35.png)
Похоже что Ваш ОФД стал проверять корректность поля ИНН ОФД.
Перерегистрируйте ФН на свой ОФД и всё должно заработать.

**Comment by t0pd3v1c3** [comment]
@swex 
Спасибо за помощь, действительно в тестовой ККМ на ФН был зарегистрирован ИНН ОФД другой.

**Comment by dmig2006** [comment]
Добрый день. Пытаюсь сделать частичное списание товара:
int ElvisRegVer3::CheckMarkingCode(string Actsiz)
{
    const char* MarkingBarcode = (const char*)Actsiz.c_str();

    fprintf(log,"\n%s\tCHECK BARCODE. ACTSIZ %s", GetCurDateTime(), Actsiz.c_str());
    fflush(log);

    SetInstrHeaderV2(0x61); //пароль отправки инструкции

    int len = Actsiz.length();
#ifndef ALCO_VES //Проверка работы
	*((int*)(DataN+6))=1; // Новый статус товара (Реализация)
	*((int*)(DataN+7))=0; //
	*((int*)(DataN+8))=len; // Длина кода маркировки
	*((int*)(DataN+9))=0; // 0-полная проверка, 1-онлайн-проверка, 2-локальная
    strncpy((char*)(DataN+10),MarkingBarcode, len);  // Код маркировки
#else
    
#endif
    //strncpy((char*)(DataN+10),MarkingBarcode, 3);
	int ret = ProcessError(JustDoIt(10+len,50));

	return ret;
}

В таком виде работает отправка на поверку кода датаматрикса, например, сметаны, но без частичного списания.

По инструкции следующее: 
Код команды FF61h. Длина сообщения: 10+X+Y байт.
Пароль оператора (4 байта)
Входные данные (4+X+Y байт)

Состав входных данных:
Смещение Длина Параметр Значение
0 1 байт Планируемый статус Тег 2003
1 1 байт Режим обработки Тег 2102 (сейчас всегда «0»)
2 1 байт Длина кода маркировки (КМ) в байтах (X)  Полная длина КМ 
3 1 байт Длина списка TLV в байтах Полная длина списка TLV (сюда добавляем 4)
4 X байт КМ  Сам КМ, как он был прочитан сканером
4+X Y байт Список TLV  Если планируется частичное выбытие маркированного товара (согласно с тегом 2003), то 
                                        необходимо сформировать буфер из тегов 2108 (мера) и 1023 (количество) и передать его здесь
в это поле добавляем EB 31 2С 35 (л 1 . 5)
Вопрос в том как в представленном коде добавить длину TLV и значение EB 31 2С 35?

**Comment by olefard** [comment]
Тег 2108(тип байт), значение "л" = 41 = 29h
Тег 1023(тип FVLN), значение 1.5 можно закодировать как 03 DC 05 00 00 00 00 00 или 01 0F 00 00 00 00 00 00 
Теги формируются так: <номер тега, 2 байта><длина, 2 байта><значение>

номер тега 2108: 3C 08
длина: 01 00
значение: 29

номер тега 1023: FF 03
длина: 08 00 
значение: 03 DC 05 00 00 00 00 00

Собираем все вместе: 3C 08 01 00 29 FF 03 08 00 03 DC 05 00 00 00 00 00

EB 31 2С 35 - неправильно. Теги кодируются согласно 54-ФЗ.
https://www.consultant.ru/cons/cgi/online.cgi?req=doc&base=LAW&n=448874#1iys68UMpNr5Y2Qf

**Comment by dmig2006** [comment]
Спасибо за ответ. Пока разбираюсь дальше. А где можно найти эти кодировки тегов? в консультанте не нашел или по какому правило она происходит
Например берем тег 2108 : 3С 08.
Если сделать перевод из 10-ой в 16 получаем 83С
если посмотреть обратный 3С 08 там вообще большое число.

Например считана была маркировка: 01046006531059902152CUnq93Gk30
штрих получил последовательность: 
02 29 FF 61 1E 00 00 00 01 00 1F 00 30 31 30 34 36 30 30 36 35 33 31 30 35 39 39 30 32 31 35 32 43 55 6E 71 1D 39 33 47 6B 33 30 85

ответил FF 61 00 00 01 05 00 9D  (CRC is Ok (9D = 9D))  

якобы ошибок нет все хорошо.     
FF 61 - это отправляем инструкцию, по документации Протокол ККТ 1.17 это отправляется проверка маркированного товара
1E это пароль
01 - это планируемый статус Тег 2003
00 - режим обработки тег 2102
1F - Длина кода маркировки 31
30 31 30 34 36 30 30 36 35 33 31 30 35 39 39 30 32 31 35 32 43 55 6E 71 1D 39 33 47 6B 33 30 это код маркировки
85 - какая то проверка, как понимаю о правильности посылки
не понятно что означают 00 00 00 которые идут между 1Е и 01
не могу также понять что означает 00, располагающийся между 1F и 30
и как тут зашифрованы теги 2003, 2102, если они вообще передаются.
Пожалуйста, подскажите знающие люди.
Если смотреть новую документацию программиста 5.17, там вообще нету описания этих посылок, а примеры написаны с# где просто вызывается и заполняется все как надо, например тега 2108
      Driver.TLVDataHex = "";
      Driver.TagNumber = 2108;
      Driver.TagType = 0; // тип ttByte
      Driver.TagValueInt = 0;
      Driver.GetTagAsTLV();
А драйвера под линукс чтобы так работало я не нашел

**Comment by olefard** [comment]
C консультанта

> Таблица 2
> Тип данных | Тег | UInt16 | 2

До этого

> UInt16 - целое число без знака в диапазоне чисел от 0 до 65535,
представленное в электронной форме в виде 16-ти бит (2 байта)
с порядком следования байтов от младшего к старшему
(unsigned integer 16 bits, little endian).

То есть 2108 = 83Ch, в байтах будет 3С 08

---

Из протокола ККТ 1.17

> Пароль оператора (4 байта)
> ...
> 2 | 1 байт | Длина кода маркировки (КМ) в байтах (X) | Полная длина КМ
3 | 1 байт | Длина списка TLV в байтах | Полная длина списка TLV

То есть `00 00 00 которые идут между 1Е и 01` входят в 4 байта пароля 1E 00 00 00
а `00, располагающийся между 1F и 30` это полная длина списка TLV

---

Вот [пример отправки тегов 2108 и 1023](https://github.com/shtrih-m/fr_drv_ng_examples/blob/a66a720e335cb1fea9443e2925b900d5a253f4f5/classic_interface/main.cpp#L766).

**Comment by dmig2006** [comment]
Спасибо, буду дальше разбираться

**Comment by swex** [comment]
> А драйвера под линукс чтобы так работало я не нашел

Вы пишите это сообщение как раз в репозитории такого драйвера...
