### ISSUE TITLE
Выполнение команды FNSendUserAttribute в Тест Драйвера ФР 4.15 вызывает ошибку

### ISSUE THREAD

**Issue by NickVStepin** [shtrih-m/fr_drv_ng#168]
Пытаюсь проверить заполнение в чеке продажи пользовательского атрибута.
Пошел простым путем через Тест драйвера ФР 4.15.
Открыл чек через команду Операции ФН/Открыть чек.
Выполняю команду Атрибуты чека/Передать доп.реквизит пользователя
Результат: (0) ККТ: Некорректные параметры в команде <0x00330024: тег не может быть отправлен в текущий документ ФН>
Передано: 8F 03 00 B4 00 6B 2C 00 
Принято: 8F | 69 | 00 | B4 | 00 6B 00 CA CA D2 3A 20 CD E5 EA EE F0 F0 E5 EA F2 ED FB E5 20 EF E0 F0 E0 EC E5 F2 F0 FB 20 E2 20 EA EE EC E0 ED E4 E5 20 3C 30 78 30 30 33 33 30 30 32 34 3A 20 F2 E5 E3 20 ED E5 20 EC EE E6 E5 F2 20 E1 FB F2 FC 20 EE F2 EF F0 E0 E2 EB E5 ED 20 E2 20 F2 E5 EA F3 F9 E8 E9 20 E4 EE EA F3 EC E5 ED F2 20 D4 CD 3E 6F | B2

Что означает эта ошибка 0x00330024?

**Comment by swex** [comment]
Здравствуйте!
У вас ККТ на основе Кассового Ядра, значит он поддерживает "подробное текстовое описание ошибки", вы его сами написали в своем сообщении:

> Результат: (0) ККТ: Некорректные параметры в команде <0x00330024: тег не может быть отправлен в текущий документ ФН>

**Comment by NickVStepin** [comment]
Мой вопрос больше был о причине ошибки, а не расшифровке ее кода. Она возникла почему, кассовое ядро не поддерживает? Или я как-то не так команду подаю (хотя вариантов там не много)

**Comment by NickVStepin** [comment]
Выяснил, что КЯ не поддерживало данную команду. После обновления КЯ проблема ушла
