### ISSUE TITLE
FiscalSign в FiscalSignAsString

### ISSUE THREAD

**Issue by t0pd3v1c3** [shtrih-m/fr_drv_ng#170]
Здравствуйте.
Подскажите каким образом происходит конвертация `FiscalSign` в `FiscalSignAsString`, потому что они отличаются и `FiscalSign` отрицательное целое значение.

**Comment by swex** [comment]
нужен лог

**Comment by t0pd3v1c3** [comment]
Уже нашел. Свойство `FiscalSign` необходимо интерпретировать как беззнаковое 4-х байтное число (приводить
к беззнаковому типу).
