### ISSUE TITLE
Получение данных по тегу 1194. Итоговые суммы расчетов, указанных в кассовых чеках (БСО) и кассовых чеках коррекции (БСО коррекции).

### ISSUE THREAD

**Issue by ConsperSerj** [shtrih-m/fr_drv_ng#172]
Добрый день.
Подскажите пожалуйста. При закрытии смены есть ли возможность как то получиться данные по тегу 1194 - Итоговые суммы расчетов, указанных в кассовых чеках (БСО) и кассовых чеках коррекции (БСО коррекции).
?

**Comment by t0pd3v1c3** [comment]
Можно через метод `GetTagAsTLV()`, либо считать нужные регистры через `GetCashReg()` и `GetOperationReg()`, если я правильно понял
