### ISSUE TITLE
Команда не поддерживается в данной реализации или при данных настройках <0x00370002: ФФД 1.2>

### ISSUE THREAD

**Issue by ola-skorp** [shtrih-m/fr_drv_ng#173]
Пытаюсь проверять маркировку, получаю эту ошибку. 
Версия ядра кассового ядра 1.10.40306
https://gist.github.com/ola-skorp/1a543ce26291dadaaa277dc44a0b4abe

Проверка версии ффд возвращает 3. Я так понимаю, для 1.2 должно быть 4?
Сбросила мгм, зарегистрировала с 1.2 на фискал мастере 2.4.3 в автоматическом режиме. Значение ффд всё ещё 3

**Comment by swex** [comment]
версия 3 - это вообще ФФД 1.1 ФискалМастер вообще  не может зарегистрировать в ФФД 1.1 что-то странное творится.

1. нужен лог регистрации. 
2. нужен лог как вы получаете версию ФФД

см скриншот: выбор версии ФФД при регистрации:
![image](https://user-images.githubusercontent.com/1026241/147731310-be72bb7d-1fce-4a2c-b1e4-f57aa4b05cba.png)
