### ISSUE TITLE
Касса не передает документы ФДД 1.2 через физический ком порт

### ISSUE THREAD

**Issue by 2UTM** [shtrih-m/fr_drv_ng#174]
Приветствую, скорее всего пишу не по теме, но так как все форумы у штриха закрыты и писать там могут только партнеры, по поиску на форуме ничего подобного нет, в техподдержку писал, никакого ответа нет, поэтому пишу здесь, возможно вы в курсе и проясните ситуацию, или подскажете, к кому мне обратиться.

ОС Win7
Есть касса в магазине, РИТЕЙЛ-01Ф, подключена по физическому ком порту, чеки передавались через средства драйвера по ком порту, все работало.
Потом на кассе закончился фн, и мы перерегистрировали кассу, как РИТЕЙЛ-01ФМ и с ФФД 1.2, соответственно была обновлена прошивка на кассе (Дата ПО: 26.08.2021) и поставлен новый драйвер 5.16.0.886, и тут чеки перестали уходить, настройки все перепроверил.
В другом магазине такие же настройки, единственная разница что там ФФД 1.05, старая прошивка (Дата ПО: 24.10.2018) и старый драйвер 4.14.0.803, все работает.
На новой кассе, где чеки не уходили, попробовал откатить прошивку на 24.10.2018 и поставил старый драйвер 4.14.0.803 и все заработало, чеки стали уходить. Возможно чеки отправились не верно но суть не в этом.

Отсюда вопрос, это недоработка в драйвере или прошивке? или функцию передачи чеков через ком порт в новой версии убрали? Подскажите куда обратиться с этим вопросом?

**Comment by swex** [comment]
Да, в прошивке под ФФД 1.2 передача средствами невозможна. Необходимо переходить на RNDIS/Ethernet/Wifi/PPPoS

**Comment by 2UTM** [comment]
Ясно, спасибо

**Comment by 2UTM** [comment]
Тогда еще вопрос, если чеки уже сохранились в фн как ффд 1.2, то на старой прошивке он их просто передаст в офд?
то есть если чеки пробивались в новой прошивке с ффд 1.2, то в старой прошивке эти чеки не меняются и передаются как ффд 1.2?

**Comment by swex** [comment]
1. Нужно передавать документы по ФФД 1.2 на прошивке с ФФД 1.2.
2. по ФФД перед пере/регистрацией необходимо убедиться что все документы переданы
3. ККТ с прошивкой ФФД 1.05 должна заругаться и отказаться работать с ФНом, зарегистрированным под 1.2

**Comment by 2UTM** [comment]
Ясно, спасибо
