### ISSUE TITLE
Перерегистрации ККТ на ФФД 1.2 через консольный драйвер. Ошибка некорректные параметры в команде для данной реализации ККТ

### ISSUE THREAD

**Issue by elchako** [shtrih-m/fr_drv_ng#175]
Добрый день! при подаче команды перерегистрации ККТ (Ритейл-01Ф) через консольный драйвер получаю ошибку
Пробую последним драйвером, результат тотже
console_test version: 1.5.2.168
cppbase version: 1.5.0.1062
boost version: 1_77
```
$EXE kkt-rereg-report 1.1.22
```
#1-Налогообложение ОСН, 1-реж.работы Шифрование, 22-причина изменение ФФД
Не важно какую причину ставлю 1.1.22, пробовал 1.1.4, 1.1.3
![image](https://user-images.githubusercontent.com/82187221/149628538-81a2c24d-5059-447e-90ca-8ca68eb131fe.png)

![image](https://user-images.githubusercontent.com/82187221/149628505-0f48ab5a-d060-4f9b-a302-a13f6b0625e7.png)
![image](https://user-images.githubusercontent.com/82187221/149628679-3f1b3eba-f650-471d-a6f8-711f0760c463.png)
![image](https://user-images.githubusercontent.com/82187221/149629685-54994b8c-6c63-433d-8bf6-a4af3c22f4bb.png)

Также при подаче команды **kkt-reg-begin 4** получаю ошибку. Попробовал указать 2 для теста, с 2 ошибки нет.
```
$EXE kkt-reg-begin 4
Неизвестная команда, неверный формат посылки или неизвестные параметры
```

**Comment by elchako** [comment]
Вижу подобную проблему тут https://github.com/shtrih-m/fr_drv_ng/issues/160, но какой именно код применить не понятно
Судя по руководству, должен быть 22 (kkt-rereg-report 1.1.22)
![image](https://user-images.githubusercontent.com/82187221/149801153-bba0e41e-c0a4-43a0-b6b8-c14fa078a31e.png)

**Comment by surfernsk** [comment]
@elchako 
![Screenshot_20220118_002205](https://user-images.githubusercontent.com/2264893/149813841-beaa8f0b-123d-441b-9027-1da7ac82a8a8.png)

 Кажется путаете тип отчета о регистрации, с значением реквизита "коды причин изменения
сведений о ККТ" (тег 1205, битовая маска) таб 18 поле 22

**Comment by elchako** [comment]
@surfernsk @swex 
Попробовал указать код причины изменений сведений о ККТ 0, 4294967295, 2147483648
Результат тотже

Вообще правильная ли последовательность действий?
1) записываю в таблицу 17.1.17 4 ( Rus формат ФД для ФФД 1.2 = 4)
записываю в таблицу 18.1.21 11 (Расширенные признаки работы ккт = 11 (маркировка))
2) kkt-reg-begin 2 (инициализировать отчет о регистрации KKT с параметром 2 (не знаю правильно ли выбрать 2, но 4 не дает выбрать. Перерег без замены ФН) )
3) Сгенерировать отчет о перерегистрации kkt-rereg-report 1.1.??? (пробовал разные паремтры, ответ один и тотже. )
```
$EXE write 17.1.17 4  # формат ФД для ФФД 1.2
$EXE write 18.1.21 11   # 11 Торговля маркированными товарами      

$EXE kkt-reg-begin 2   # или 4 тип отчета «Смена настроек ККТ» ? но 4 не дает выбрать
$EXE kkt-rereg-report 1.1.???
```

**Comment by elchako** [comment]
@surfernsk 
Да ФН был зареган ранее еще на ФФД 1.2
Далее обновил прошивку Ритейл 01Ф до версии 1708, имя ККТ изменилось на Ритейл 01ФМ (это нормально)
И вот вижу проблему, хотя через графический тест драйвер все ОК

**Comment by surfernsk** [comment]
> @surfernsk Да ФН был зареган ранее еще на ФФД 1.05 Далее обновил прошивку Ритейл 01Ф до версии 1708, залил ключи, имя ККТ изменилось на Ритейл 01ФМ (это нормально) И вот вижу проблему, хотя через графический тест драйвер все ОК

Вроде же надо кассу Ритейл-01Ф снять с учета, и поставить на учет кассу Ритейл-01ФМ (не забыв комплект модернизации). Как-то так.

**Comment by surfernsk** [comment]
#160

**Comment by elchako** [comment]
@surfernsk Снимать с учета не нужно (Сам ФР и его номер не меняется). Через графический тест драйвер перерегал без проблем, но с учетом того что перед перерегом обязательно снять отчет о состоянии расчетов.
Через консоль повторяю теже действия,  fs-calculation-report (снимаю отчет). Но проблема таже самая, как и в случае с https://github.com/shtrih-m/fr_drv_ng/issues/160
В решении https://github.com/shtrih-m/fr_drv_ng/issues/160 сообщается что была кривая причина перерегистрации
@swex если известно какую причину ставить подскажи пожалуйста

![image](https://user-images.githubusercontent.com/82187221/150328704-c212be89-e20d-4b54-b9b5-b0c43e5963cf.png)

**Comment by swex** [comment]
@elchako 
1. я не пойму что вы делаете? Это первый документ в новом ФНе или нет? 
2. Нужны содержимое таблицы 18, статус ФН, лог. 
3. Такая ошибка может возникать при перерегистрации если:
  3.1 В Т17П17 стоит формат ФД не равный 4
  3.2 В Т18П22 стоит значение с флагом 21(изменение версии ФФД ) в 1, а у вас и так уже версия ФФД такая же, как та, на которую вы пытаетесь перейти

**Comment by surfernsk** [comment]
еще вот здесь наверное:
````
write 18.1.21 11
````
11 - Это 00001011:

 + Продажа подакцизного товара
 + Проведение азартных игр
 - Проведение лотереи
 + Признак установки принтера в автомате
 - Торговля маркированными товарами
 - Ломбардная деятельность
 - Страховая деятельность

Точно не "Маркированный товар

**Comment by elchako** [comment]
> @elchako
> 
> 1. я не пойму что вы делаете? Это первый документ в новом ФНе или нет?
> 2. Нужны содержимое таблицы 18, статус ФН, лог.
> 3. Такая ошибка может возникать при перерегистрации если:
>    3.1 В Т17П17 стоит формат ФД не равный 4
>    3.2 В Т18П22 стоит значение с флагом 21(изменение версии ФФД ) в 1, а у вас и так уже версия ФФД такая же, как та, на которую вы пытаетесь перейти

1) ФР ранее была заменена на 1.1М, в ФН имеется 3 документа. Мне нужно перерегестрировать на ФФД 1.2 и поставить признак маркировки
2) Таблица 18 
```
060886*******13
********5354      
**********34005004        
9960440********        1       1       
ООО "Магазин"     
Системный администратор 
198332, 78, г.Санкт-Петербург   
ООО "Компания "Тензор"  
kkt.sbis.ru     7605016030      www.nalog.ru    Магазин № 0001  sbis@sbis.ru    64 
```
Статус ФН
```
Command FN status
Current document        0
Document data   0
FN date and time        20.01.2022 14:37
FN number       996044030********
Last fiscal document number     5
Life state stage        3
 01. FN adjustment completed    true
 02. Fiscal mode opened true
 03. Fiscal mode closed false
 04. Fiscal data transfer to OFD is finished    false
Session state   0
Warning flags   0

 01. Urgent replacement required(3 days left)   false
 02. Exhaustion of the resource COP(30 days left)       false
 03. Memory overflow (Archive is 90% full)      false
 04. OFD response timeout       false
```
Лог [fr_drv_ng.log](https://github.com/shtrih-m/fr_drv_ng/files/7905912/fr_drv_ng.log)

3.1 Перед перерегистрацией выполняется $EXE write 17.1.17 4
3.2 18,1,22,4,0,0,4294967295,'Код причины изм. сведений о ККТ (ФФД>=1.','2147483648'

**Comment by elchako** [comment]
Полный список действий 
```
$EXE kkt-reg-begin 2  #тип отчета «Смена настроек ККТ» должен быть 4
но 4 не принимает, ошибка Неизвестная команда, неверный формат посылки или неизвестные параметры 
$EXE write 18.1.13 www.nalog.gov.ru
$EXE write 17.1.17 4   # формат ФД для ФФД 1.2
$EXE write 18.1.21 16   # 16 Торговля маркированными товарами      
$EXE save-tables  > $tables_new

$EXE fs-calculation-report

$EXE kkt-rereg-report 1.1.2097216
#1-Налогообложение ОСН, 1-реж.работы Шифрование, 2097216-причина изменение ФФД+смена модификации ккт
```

**Comment by surfernsk** [comment]
> Полный список действий
> 
> ```
> $EXE kkt-reg-begin 2  #тип отчета «Смена настроек ККТ» должен быть 4
> но 4 не принимает, ошибка Неизвестная команда, неверный формат посылки или неизвестные параметры 
> $EXE write 18.1.13 www.nalog.gov.ru
> $EXE write 17.1.17 4   # формат ФД для ФФД 1.2
> $EXE write 18.1.21 16   # 16 Торговля маркированными товарами      
> 
> $EXE fs-calculation-report
> 
> $EXE kkt-rereg-report 1.1.2097216
> #1-Налогообложение ОСН, 1-реж.работы Шифрование, 2097216-причина изменение ФФД+смена модификации ккт
> ```
@elchako 
````
!!  write 18.1.21 ???? - причина изменение ФФД + не забываем что изменилась версия ккт (была 001, стала 003) 
!!  kkt-rereg-report 1.1.4 - изменение настроек ккт
````

**Comment by swex** [comment]
@surfernsk, как обычно, опередил, спасибо!
 kkt-rereg-report 1.1.4 - в таком случае должен быть 4 - изменение настроек
а коды причины надо уже в Т18П22, это тоже битовое поле, сформировать их можно через тест драйвера:
![image](https://user-images.githubusercontent.com/1026241/150367513-e07bc8b7-0264-463d-a7f1-e76a901d3277.png)

**Comment by surfernsk** [comment]
@swex в ТП написать по инструкции о настройке ккт, с ошибкой в описании значений т18.п.21?

**Comment by swex** [comment]
@surfernsk спасибо, я передам, и наконец поправлю ссылки на актуальную документацию

**Comment by elchako** [comment]
@surfernsk @swex 
Добавил write 18.1.22 2097216 но проблема таже, в логах тоже самое

write 18.1.13 www.nalog.gov.ru
write 17.1.17 4   # формат ФД для ФФД 1.2
write 18.1.21 16   # 16 Торговля маркированными товарами  
write 18.1.22 2097216  #изменение версии модели ккт+ффд1.2 
fs-calculation-report 
kkt-reg-begin 2  # 2 - отчет без замены ФН
kkt-rereg-report 1.1.4  #перерегистрация  причина: изменение настроек ккт
![image](https://user-images.githubusercontent.com/82187221/150378410-2beff8be-b596-4089-ac27-af29a37c6f2c.png)

**Comment by swex** [comment]
не знаю...
1. Предполагаю что в кассе уже ФФД 1.2 и поэтому ей не нравится бит21 в кодах причины.
2. Предлагаю попробовать перерегистрировать через графический тест драйвера и через консольный и сравнить/дать сравнить логи.

**Comment by elchako** [comment]
> не знаю...
> 
> 1. Предполагаю что в кассе уже ФФД 1.2 и поэтому ей не нравится бит21 в кодах причины.
> 2. Предлагаю попробовать перерегистрировать через графический тест драйвера и через консольный и сравнить/дать сравнить логи.

Попроборвал перерег через графический тест-драйвер 5.16, таже самая ошибка.

Но через фискал мастер проходит без проблем
Если логи должны лежать тут C:\Users\10\AppData\Roaming\SHTRIH-M\DrvFR\Logs, их нет ((
![2022-01-21_11-58](https://user-images.githubusercontent.com/82187221/150499073-dd2aca6f-1a56-4e87-a593-ba28ad5e1929.png)

**Comment by elchako** [comment]
@swex @surfernsk  все таки решилась проблема, большое вам спасибо за помощь !! 
Дело было в том что $EXE fs-calculation-report надо снимать до записи в таблицы
```
$EXE fs-calculation-report
#укажем DNS
$EXE write 16.1.15 8
$EXE write 16.1.16 8
$EXE write 16.1.17 8
$EXE write 16.1.18 8

#пропишем настройки офд и исм
$EXE write 19.1.1 kkt.sbis.ru
$EXE write 19.1.2 7777
$EXE write 19.1.3 5000
$EXE write 19.1.5 91.213.144.29
$EXE write 19.1.6 7777
$EXE write 19.1.7 33
$EXE write 19.1.9 prod01.okp-fn.ru
$EXE write 19.1.10 26101
$EXE write 19.1.11 30 
$EXE write 18.1.13 www.nalog.gov.ru

$EXE write 17.1.17 4  # формат ФД для ФФД 1.2
$EXE write 18.1.21 16  # 16 Торговля маркированными товарами 
$EXE write 18.1.22 2097216  # причина изменение ФФД  изменение версии модели ккт+ффд1.2 

sleep 3

$EXE kkt-reg-begin 2  #1 тип отчета без замены ФН

$EXE kkt-rereg-report 1.1.4
```
