### ISSUE TITLE
Что значит ошибка 211 и почему в примере проверки маркировки она игнорируется?

### ISSUE THREAD

**Issue by ola-skorp** [shtrih-m/fr_drv_ng#178]
В примере в строке по этой ссылке написано про игнорирование ошибки. Почему игнорируем? Значит ли эта ошибка, что маркировка неправильная?
https://github.com/shtrih-m/fr_drv_ng_examples/blob/master/classic_interface/main.cpp#L823
` } else if (ret == 211) { //для КМ игнорируем ошибку разбора разбора(211)`

**Comment by surfernsk** [comment]
maybe
![Screenshot_20220126_194541](https://user-images.githubusercontent.com/2264893/151165382-e9482cd0-01ad-420e-854d-4b43f76ae867.png)

**Comment by ola-skorp** [comment]
Код валидный, добавляется один раз. Но вопрос состоит в том, почему в примере кода игнорируется эта ошибка

**Comment by surfernsk** [comment]
1 - это пример.
2 - 
```
    auto acceptOrDeclineMarkingItem = [](Item* item, Item::MarkingCode* mc, classic_interface* ci) {
        // решение о принятии и отклонении товара исходя из результатов проверки КМ индивидуально
        // и должно приниматься в зависимости от типа законодательства, мнения контрагентов итд.
        // для примера мы не откажемся от одной позиции и
        auto explainLocalCheck = [](auto value) {
            std::string result;
            result += "\n    ";
            if (value & 1) {
                result += u8"код маркировки проверен фискальным накопителем с использованием ключа "
                          u8"проверки КП";
            } else {
                result += u8"код маркировки не может быть проверен фискальным накопителем с "
                          u8"использованием ключа проверки КП";
            }
            result += "\n    ";
            if (value & 1 << 1) {
                result += u8"результат проверки КП КМ фискальным накопителем с использованием "
                          u8"ключа проверки КП положительный";
            } else {
                result += u8"результат проверки КП КМ фискальным накопителем с использованием "
                          u8"ключа проверки КП отрицательный (в случае, если значение нулевого "
                          u8"бита равно «1») или код маркировки не может быть проверен фискальным "
                          u8"накопителем с использованием ключа проверки КП (в случае, если "
                          u8"значение нулевого бита равно «0»)";
            }
            result += "\n";
            return result;
        };
```

**Comment by ola-skorp** [comment]
Этот метод не вызывается для маркировок с ошибкой 211

**Comment by ola-skorp** [comment]
Принтер выдаёт ошибку 211 на все маркировки, которые я пробовала. Даже на маркировку из примера кода. Вот лог ошибки проверки одной из маркировок https://gist.github.com/ola-skorp/3d2fb28c8171c5f3c497f773d4f81cb4 . Приложение Честный Знак без проблем считывает эту маркировку

**Comment by asem-m** [comment]
можно примеры маркировок (не из примера)?

попробуйте эту (сепаратор `<0x1D>` возможно нужно переоформить):
`010123456789012321Ng/kkYnMKctFYb<0x1D>91808B<0x1D>922LgwirizH3VrlKLE/SuFbeYpXqe8SoIKkGc4uJ+RgnoZElVnaGtgzOoqwqcv0qHd/23GiUQBNGUz1+eyKNEpnw==`

**Comment by ola-skorp** [comment]
(0) Код ошибки 32h (50) от ФН: Запрещена работа с маркированным товарами

**Comment by asem-m** [comment]
необходимо перерегистрировать МГМ-М в режиме ТМТ: Т13П21=16

**Comment by surfernsk** [comment]
> Принтер выдаёт ошибку 211 на все маркировки, которые я пробовала. Даже на маркировку из примера кода. Вот лог ошибки проверки одной из маркировок https://gist.github.com/ola-skorp/3d2fb28c8171c5f3c497f773d4f81cb4 . Приложение Честный Знак без проблем считывает эту маркировку

Ваш код маркировки сформирован с ошибкой. По стандарту GS1 не должно быть впереди разделителя 0x1D ( в начале другой символ и его отбрасывает сканер - чаше всего). Приложение ЧЗ игнорирует факт того что многие формируют неправильные datamatix (по формату). 
```
Set_BarCode(`010290000101456421gOZdDD:ZVshH291803992plS+39qNt6wnj+i6q4O68L1E/WVb4fPaXEupbkbCqWt0z6AFUwvO4cwHsy7bk0TygjtoddQXUkG0bmB2hSLd6w==`)
```
Также Вам в описании ошибки написано как отключить жесткий контроль 
```
[E] Код ошибки D3h (211) от ККТ: КМ не может быть декодирован, ошибка формата GS1 <0x00D3000B: код товара (КТ) не распознан, чтобы игнорировать ошибку установите настройку Т1П57=1 "ПРИНИМАТЬ ВСЕ КОДЫ ТОВАРА">. 
```

**Comment by ola-skorp** [comment]
> необходимо перерегистрировать МГМ-М в режиме ТМТ: Т13П21=16

Спасибо, помогло, теперь через тест драйвера ошибок нет. Но через приложение ошибка осталась

**Comment by ola-skorp** [comment]
Вот стек ошибки https://gist.github.com/ola-skorp/7ac057f028e8ba83e601dabb718cbc56

**Comment by asem-m** [comment]
драйвер, по логу, передал в ККТ разделитель 0x1D в ASCII формате: `3C 30 78 31 44 3E`, т.е. `"0x1D"` - это неверно.
скорректируйте данные маркировки перед отправкой в функцию драйвера так, чтобы разделитель 0x1D был в HEX формате: `1D`

**Comment by ola-skorp** [comment]
Спасибо, ошибка пропала, появилась новая https://gist.github.com/ola-skorp/cba58c67285691f678a3e6ab245b3941

**Comment by asem-m** [comment]
сервис КЯ в памяти есть?

**Comment by ola-skorp** [comment]
Да. Ошибка происходит только с проверкой маркировок. Для остальных команд такой ошибки нет

**Comment by asem-m** [comment]
уточните таймаут на онлайн проверку маркировки: Т14П8=?

какой таймаут вы задаете драйверу на подключение к КЯ?

необходимо, чтобы время выполнения команд было меньше, чем таймаут установления связи с КЯ

**Comment by ola-skorp** [comment]
Т14П8=10

**Comment by ola-skorp** [comment]
таймаут через драйвер я не задаю

**Comment by asem-m** [comment]
через 10 с (совпадает с Т14П8) драйвер получает отклик от КЯ, но почему-то возникает ошибка передачи ответа на команду в драйвер, но что там происходит подсказать не могу

logcat можете прислать, где КЯ сообщает, когда команда FF61h началась и закончилась

**Comment by ola-skorp** [comment]
https://gist.github.com/ola-skorp/89bbbce5232596adb38de11790f9c2b6

**Comment by asem-m** [comment]
в вашем logcat нет строчек от cashcore, уточните значения в Т10П13 и Т10П14?

**Comment by ola-skorp** [comment]
Т10П13 = 127
Т10П14 = 38

**Comment by asem-m** [comment]
`adb logcat "cashcore:D" "*:S"` с таким фильтром logcat присылайте

**Comment by ola-skorp** [comment]
https://gist.github.com/ola-skorp/6e0fe42d10cb667015361e2ef63daa36

**Comment by asem-m** [comment]
теперь видны сообщения от КЯ

**Comment by asem-m** [comment]
> Да. Служба запущена. Ошибка происходит только с проверкой маркировок. Для остальных команд такой ошибки нет. Чек без маркировок отлично печатается.

сообщение "Клиентское приложение отключено!" от КЯ говорит о том, что драйвер отключился от КЯ, скорее вам необходимо увеличить (>10 с) таймаут подключения драйвера к КЯ

**Comment by ola-skorp** [comment]
Get_ConnectionTimeout() = 15000
Или это не тот таймаут?

**Comment by ola-skorp** [comment]
Set_Timeout(15000) помогло, спасибо
