### ISSUE TITLE
Откат с ФФД 1.2 на ФФД 1.05

### ISSUE THREAD

**Issue by elchako** [shtrih-m/fr_drv_ng#179]
Доброго дня! Есть необходимость откатить(перерегистрировать с ФФД 1.2 на 1.05).
Вернул на старую прошивку, но перерегистрация не работает. Пробовал фискал мастер версии 1 и 5
Это вообще возможно?
![image](https://user-images.githubusercontent.com/82187221/151784326-5a1c665e-3e04-459f-9a82-d4e45c5afdf4.png)

**Comment by swex** [comment]
прошивка под ффд 1.2 работает только с ффд 1.2. На ней можно выполнить перерегистрацию с 1.05 на 1.2, но не обратно.
