### ISSUE TITLE
Номер чека

### ISSUE THREAD

**Issue by susloparov77** [shtrih-m/fr_drv_ng#18]
Подскажите как получить:
1) Локальный номер чека в смене?? Через ReceiptNumber
2) И текущий номер чека в ФН, они отличаются у вас?

**Comment by swex** [comment]
1. см `FNGetCurrentSessionParams`
2. В ФН есть счетчик "документов" а не "чеков", и его можно получить через `FNGetStatus`+ свойство `FNCurrentDocument`
