### ISSUE TITLE
ФФД 1.2 Маркировка отсутствует в tlv

### ISSUE THREAD

**Issue by ola-skorp** [shtrih-m/fr_drv_ng#180]
Передаю маркировку через 
```
Set_BarCode()
FNSendItemBarcode()
```
Как видно в логе, отправка проходит успешно. Но в tlv маркировки нет
https://gist.github.com/ola-skorp/e7db367586d8849485b0c6167df8dd54

**Comment by asem-m** [comment]
внизу `changelog.txt` из zip-архива КЯ дано описание пробивания маркированного товара в чек

надо рассмотреть Вариант 1: открыть чек, проверить код маркировки, принять КМ, передать и распознать КМ, добавить позицию v2, закрыть чек v2

**Comment by ola-skorp** [comment]
Спасибо, работает. Значит ваш пример на C++ с неверным порядком операций

**Comment by asem-m** [comment]
есть особенность - порядок команд нужно изменить: сначала передать и распознать, потом провести позицию в чек
