### ISSUE TITLE
No implementation found for void ru.shtrih_m.fr_drv_ng.classic_interface.classic_fr_drv_ngJNI.classic_interface_Set_ItemStatus(long, ru.shtrih_m.fr_drv_ng.classic_interface.classic_interface, int)

### ISSUE THREAD

**Issue by ola-skorp** [shtrih-m/fr_drv_ng#181]
На большом смартпосе вызов Set_ItemStatus() приводит к исключению. Вот логи:
https://gist.github.com/ola-skorp/24ad35644f19c3e1ffa05e682d0964ee
Кассовое ядро 1.10.40306
На смартпосе мини с той же версией кассового ядра ошибка не наблюдается

**Comment by ola-skorp** [comment]
Проверила на кассовом ядре 1.10.40682, ошибка осталась та же

**Comment by asem-m** [comment]
Укажите строчку в логе

**Comment by ola-skorp** [comment]
188

**Comment by asem-m** [comment]
`2022-02-21 12:53:39.560 10687-10785/ru.insales.ekam E/art: No implementation found for void ru.shtrih_m.fr_drv_ng.classic_interface.classic_fr_drv_ngJNI.classic_interface_Set_ItemStatus(long, ru.shtrih_m.fr_drv_ng.classic_interface.classic_interface, int) (tried Java_ru_shtrih_1m_fr_1drv_1ng_classic_1interface_classic_1fr_1drv_1ngJNI_classic_1interface_1Set_1ItemStatus and Java_ru_shtrih_1m_fr_1drv_1ng_classic_1interface_classic_1fr_1drv_1ngJNI_classic_1interface_1Set_1ItemStatus__JLru_shtrih_1m_fr_1drv_1ng_classic_1interface_classic_1interface_2I)`

не могу прокомментировать

**Comment by swex** [comment]
Здесь дело не в версии кассового ядра, а в версии библиотеки libclassic_interface.so.
Почему у вас там библиотека от  `build date: 2020-08-24T01:25:39`, обновите библиотеку и всё будет ок.
Судя по всему у вас сборка сразу под несколько архитектур и для arm64 вы обновили библиотеку, а для armv7 нет.

**Comment by ola-skorp** [comment]
Спасибо, работает
