### ISSUE TITLE
fr_drv_ng_java_wrappers_1.5.0-41-g1b0b878 на Ubuntu 20.04 x64

### ISSUE THREAD

**Issue by Yanovsky** [shtrih-m/fr_drv_ng#183]
При работе на Linux x64 (Ubuntu 20.04) через драйвер с к ККТ ШТРИХ-ON-LINE, подключенным по USB возникает «Ошибка ввода вывода» при вызове разных методов (GetECRStatus(), GetShortECRStatus(), GetCashReg() и др.). Причем, если смотреть [fr_drv_ng.log](https://disk.yandex.ru/d/Z5vZ_jIdH-lG0g) видно, что после подключения вызовы этих же самых методов проходили без ошибок. Но в какой то момент начинают валиться ошибки. Пробовал «играть» с таймаутом, результата не дало.
При подключении принтера через RNDIS работает без нареканий.
На Windows тоже проблем не замечено

**Comment by swex** [comment]
```
[2022-03-14 11:31:18.382] [3142] [SerialIO_0x7f1f7cc724d0         ] [E] read problem: End of file
[2022-03-14 11:31:18.382] [3142] [SerialIO_0x7f1f7cc724d0         ] [I] close()
```
Судя по всему устройство отвалилось на уровне драйвера в ОС.
Посмотрите dmesg. Там наверняка будет отвал устройства.

**Comment by swex** [comment]
В логе драйвера вы соединяетесь с ttyUSB0, а в логе ядра видно ttyACM2...
Плюс я не пойму, почему у вас за ttyACM2 борются 2 девайса:
```
[    8.161632] cdc_acm 1-4:1.0: ttyACM2: USB ACM device
#какой-то девайс был изначально
[ 4047.819681] usb 1-4: new full-speed USB device number 8 using xhci_hcd
[ 4047.969930] usb 1-4: New USB device found, idVendor=0483, idProduct=5740, bcdDevice= 2.00
[ 4047.969954] usb 1-4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 4047.969966] usb 1-4: Product: STM32 Virtual ComPort  in FS Mode
[ 4047.969975] usb 1-4: Manufacturer: STMicroelectronics
[ 4047.969983] usb 1-4: SerialNumber: 00000000050C
[ 4047.973242] cdc_acm 1-4:1.0: ttyACM2: USB ACM device
#потом какое-то устройство на STM32
```
```
[ 6838.335460] usb 1-4: USB disconnect, device number 9
[ 6842.950054] usb 1-4: new full-speed USB device number 10 using xhci_hcd
[ 6843.104138] usb 1-4: New USB device found, idVendor=1fc9, idProduct=0083, bcdDevice= 1.00
[ 6843.104156] usb 1-4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 6843.104164] usb 1-4: Product: VCOM Port
[ 6843.104170] usb 1-4: Manufacturer: NXP
[ 6843.104175] usb 1-4: SerialNumber: SHM001
[ 6843.109027] cdc_acm 1-4:1.0: ttyACM2: USB ACM device
#а вот это уже наш девайс
```
Рекомендации стандартные: проверить блок питания, порт, кабель.

**Comment by Yanovsky** [comment]
Потому что сначала был один RRN? потом я его отключил и подключил Штрих. Он определился на ttyACM2 и на него создался symlink на ttyUSB1 (не ttyUSB0)
io_url looks good: serial://**ttyUSB1**?timeout=30000&protocol=v1&baudrate=115200

Симлик создаю потому что если в метод Set_ComNumber передать значение 1, то судя по тому же логу драйвер подключается к принтеру на ttyUSB1

**Comment by Yanovsky** [comment]
Так же попробовал 
driver.Set_ConnectionURI("serial://ttyACM2?timeout=30000&protocol=v1&baudrate=115200");

результат тот же

**Comment by Yanovsky** [comment]
Симлинк создается автоматически так как в папке /lib/udev/rules.d лежит наш файл rules 
Так сделано потому что принтер подключаемый по USB встает на очередной ttyACMx
К сожалению не очень понял что должна дать команда _stty -F /dev/ttyUSB0 raw_

**Comment by swex** [comment]
`stty -F /dev/ttyUSB0 raw` сносит все параметры порта на уровне драйвера, в т.ч. выставляет минимальное кол-во байт для успешного read в 1 (min 1). Может помочь.

**Comment by Yanovsky** [comment]
- отключил принтер от USB
- подключил к USB - появился ttyACM2 и создался симлинк ttyUSB1
- выполнил stty -F /dev/ttyUSB1 raw и, на всякий случай, stty -F /dev/ttyACM2 raw
- увы, результат тот же

**Comment by swex** [comment]
Пока идей больше нет.
Еще заметил: сразу после ошибки начинаете общаться с методами драйвера из другого потока. Там у вас случайно никакой гонки нет? Сможете воспроизвести такое же поведение внутри одного потока?

**Comment by swex** [comment]
Попробуйте еще добавить в `ConnectionURI` `enq_mode`
```
 driver.Set_ConnectionURI("serial://ttyACM2?timeout=30000&protocol=v1&baudrate=115200&enq_mode=1");
```

**Comment by Yanovsky** [comment]
Попробовал enq_mode=1
В логе появилось соответствующее сообщение "enq_mode: enforced"
Но поведение лучше не стало.
На счет многопоточности, не думаю что там какая то гонка возможна. Так windows устройствах все работает без нареканий. Пересобрать все кассовое приложение без многопоточности, конечно, не представляется возможным.

**Comment by swex** [comment]
Покажите, пожалуйста, обновленный лог.
Не нужно пересобирать приложение без многопоточности, просто попробуйте воспроизвести минимальный тест где у вас возникает такая же проблема, но в одном потоке исполнения.

**Comment by Yanovsky** [comment]
[вот лог с enq_mode](https://disk.yandex.ru/d/ARqNAnWUWPAigg)
Щас попробую накататать отдельную тестовую аппликуху

**Comment by Yanovsky** [comment]
Разобрался в чем было дело.
Но явление правда странное.
Суть в следующем:
1. Драйвер начинает работу с принтером, открывает указанный порт и обменивается данными
2. Но так же запускается модуль работы со сканером штрих-кодов, который пытается (согласно неверным настройкам) открыть тот же порт.
3. И вот оно чудо, система разрешает ему его открыть. Никаких ошибок, типа "Порт(файл) занят другим приложением"!
4. Порт открылся и модуль сканера вычитывает оттуда то, что ждет драйвер. 
В итоге драйвер получает "ошибку ввода-вывода"

Но как так получается, что система позволяет открыть занятый другим процессом порт, я пока так и не понял.

Но все равно спасибо огромное за потраченное время и своевременную поддержку

**Comment by swex** [comment]
рад что локализовали проблему.
Да, в POSIX не лочится файл по умолчанию. Можно сколько угодно раз открыть и производить операции из нескольких процессов. Но поведение будет загадочным :)
