### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by ApiDjango** [shtrih-m/fr_drv_ng#184]
Партирую оплату на Linux, после установки Либы делаю 
`
#!/usr/bin/env python3
import sys
from fr_drv_ng import classic_interface

def checkResult(err):
    if err:
        print(ci.ResultCodeDescription, file=sys.stderr)
        sys.exit(ci.ResultCode)

ci = classic_interface()
ci.ConnectionURI="tcp://172.16.0.222:7778?timeout=10000&protocol=v1&enq_mode=1"
checkResult(ci.Connect())
if ci.ECRMode is classic_interface.PM_TechnologicalResetAllowed:
    checkResult(ci.ResetSettings())
`
Traceback (most recent call last):
  File "./Start.py", line 3, in <module>
    from fr_drv_ng import classic_interface
  File "/root/.local/lib/python3.8/site-packages/fr_drv_ng.py", line 15, in <module>
    from _fr_drv_ng import *
ImportError: /root/.local/lib/python3.8/site-packages/_fr_drv_ng.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN17classic_interface13Set_ComNumberEi

**Comment by swex** [comment]
1. не может найти `libclassic_fr_drv_ng.so`.
сделайте ldd /root/.local/lib/python3.8/site-packages/_fr_drv_ng.cpython-38-x86_64-linux-gnu.so и убедитесь что `libclassic_fr_drv_ng.so` лежит там где его ищет python обертка
сгенерированная библиотека явно не может найти 
2. исполняемый вы устанавливаете пакет в пользователя root, а нужно в того пользователя от которого будет исполняться потом программа. Правильная строка такая:
```bash
python3 setup.py  install --py3  -O2 --user
```
3. у вас точно актуальная версия скрипта setup.py? в актуальной версии к обертке должен автоматом добавляться относительный путь к `libclassic_fr_drv_ng.so`

**Comment by ApiDjango** [comment]
Я взял из релиза

**Comment by ApiDjango** [comment]
File "/home/vvv/Grad_Pay/x86_64/fr_drv_ng.py", line 15, in <module>
    from _fr_drv_ng import *
ImportError: /home/vvv/.local/lib/python3.8/site-packages/_fr_drv_ng.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN17classic_interface13Set_ComNumberEi

**Comment by swex** [comment]
покажите вывод 
```bash
ldd /home/vvv/.local/lib/python3.8/site-packages/_fr_drv_ng.cpython-38-x86_64-linux-gnu.so
```

**Comment by ApiDjango** [comment]
linux-vdso.so.1 (0x00007ffc76a98000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007efc0743e000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007efc07423000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007efc07400000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007efc0720e000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007efc070bf000)
        /lib64/ld-linux-x86-64.so.2 (0x00007efc0779b000)

**Comment by swex** [comment]
это странно.
должно быть примерно вот так:
```
linux-vdso.so.1 (0x00007ffeaa394000)
libclassic_fr_drv_ng.so.1.4 => /home/user/Downloads/fr_drv_ng/fr_drv_ng/classic_fr_drv_ng/libclassic_fr_drv_ng.so.1.4 (0x00007f80f147e000)
libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f80f121c000)
libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f80f1201000)
libc.so.6 => /lib64/libc.so.6 (0x00007f80f0ff7000)
libm.so.6 => /lib64/libm.so.6 (0x00007f80f0f1b000)
/lib64/ld-linux-x86-64.so.2 (0x00007f80f21cf000)
```

**Comment by ApiDjango** [comment]
Сейчас пересобрал либу.
В папке получается:
_fr_drv_ng.cpython-38-x86_64-linux-gnu.so
fr_drv_ng.py
libclassic_fr_drv_ng.so
libclassic_fr_drv_ng.so.1.4
И папка libs
Но все равно ошибка, пробую на виртуалке
ImportError: /media/sf_Grad_Module/_fr_drv_ng.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN17classic_interface13Set_ComNumberEi

**Comment by swex** [comment]
действительно, наблюдаю у себя точно такое же поведение в случае с python 3.8. В 3.9, 3.10, 3.11 всё ок.
для 3.8 можно воспользоваться хаком запускать вот так:
```bash
 LD_PRELOAD="libclassic_fr_drv_ng.so" python3.8 ...
```

**Comment by ApiDjango** [comment]
А если собирать под 3.9 у меня по крайней мере 
`
fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I. -I/usr/include/python3.9 -c classic_interface_wrap.cpp -o build/temp.linux-x86_64-3.9/classic_interface_wrap.o
classic_interface_wrap.cpp:179:11: fatal error: Python.h: No such file or directory
  179 | # include <Python.h>

`

**Comment by ApiDjango** [comment]
Нашел причину
`sudo apt-get install python3.9-dev`

**Comment by ApiDjango** [comment]
Но теперь другая ошибка 
`/usr/bin/ld:./libclassic_fr_drv_ng.so: file format not recognized; treating as linker script`

**Comment by ApiDjango** [comment]
Почему-то если собирать под 3.9
```

building '_fr_drv_ng' extension
/usr/bin/ld:./libclassic_fr_drv_ng.so: file format not recognized; treating as linker script
/usr/bin/ld:./libclassic_fr_drv_ng.so:0: syntax error
collect2: error: ld returned 1 exit status

```

**Comment by ApiDjango** [comment]
В python 3.10 
```
/usr/bin/ld:./libclassic_fr_drv_ng.so: file format not recognized; treating as linker script
/usr/bin/ld:./libclassic_fr_drv_ng.so:0: syntax error
collect2: error: ld returned 1 exit status
error: command '/usr/bin/x86_64-linux-gnu-g++' failed with exit code 1

```

**Comment by ApiDjango** [comment]
После
```
sudo cp libclassic_fr_drv_ng.so /usr/bin/ld
sudo cp libclassic_fr_drv_ng.so.1.4 /usr/bin/ld
```
```
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.11/classic_interface_wrap.o -L. -Wl,--enable-new-dtags,-R/media/sf_Grad_Module -lclassic_fr_drv_ng -o build/lib.linux-x86_64-3.11/_fr_drv_ng.cpython-311-x86_64-linux-gnu.so
collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped
compilation terminated.
error: command '/usr/bin/x86_64-linux-gnu-g++' failed with exit code 1

```

**Comment by ApiDjango** [comment]
Походу руки у меня кривые. ладно тогда

**Comment by swex** [comment]
> sudo cp libclassic_fr_drv_ng.so /usr/bin/ld
> sudo cp libclassic_fr_drv_ng.so.1.4 /usr/bin/ld

это вы заменили системный линкер на библиотеку драйвера....

Скажите что у вас там за окружение? Какой дистрибутив ?

**Comment by ApiDjango** [comment]
Пробовал на Linux Mint 20.3 64bit
И на Linux Lite 5.8 64bit
У обоих python 3.8, вручную ставил 9-10 и такая же ошибка.

**Comment by ApiDjango** [comment]
А если делать так  LD_PRELOAD="libclassic_fr_drv_ng.so"  python3.10 setup.py  install --py3  -O2 --user

```
ERROR: ld.so: object 'libclassic_fr_drv_ng.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.10/classic_interface_wrap.o -L. -Wl,--enable-new-dtags,-R/media/sf_Grad_Module -lclassic_fr_drv_ng -o build/lib.linux-x86_64-3.10/_fr_drv_ng.cpython-310-x86_64-linux-gnu.so
ERROR: ld.so: object 'libclassic_fr_drv_ng.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libclassic_fr_drv_ng.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libclassic_fr_drv_ng.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
/usr/bin/ld:./libclassic_fr_drv_ng.so: file format not recognized; treating as linker script
/usr/bin/ld:./libclassic_fr_drv_ng.so:0: syntax error
collect2: error: ld returned 1 exit status
```

**Comment by ApiDjango** [comment]
ldd /bin/ls
ERROR: ld.so: object '/media/sf_Grad_Module/libclassic_fr_drv_ng.so' from LD_PRELOAD cannot be preloaded (file too short): ignored.
ERROR: ld.so: object '/media/sf_Grad_Module/libclassic_fr_drv_ng.so' from LD_PRELOAD cannot be preloaded (file too short): ignored.
	linux-vdso.so.1 (0x00007fff24d3d000)

**Comment by ApiDjango** [comment]
export LD_PRELOAD=/media/sf_Grad_Module/libclassic_fr_drv_ng.so.1.4
/media/sf_Grad_Module/libclassic_fr_drv_ng.so.1.4 (0x00007f9bfbbd8000)

**Comment by ApiDjango** [comment]
/usr/bin/ld:./libclassic_fr_drv_ng.so: file format not recognized; treating as linker script

**Comment by surfernsk** [comment]
> /usr/bin/ld:./libclassic_fr_drv_ng.so: file format not recognized; treating as linker script /usr/bin/ld:./libclassic_fr_drv_ng.so:0: syntax error collect2: error: ld returned 1 exit status

Попробуйте другой линкер использовать.
```
sudo alternatives --config ld

**Comment by swex** [comment]
я не поленился и прошел путь на виртуалке с mint 20.3.

```bash
apt install python3.9-dev
apt install build-essential
apt install swig
apt install python3-pip
wget https://github.com/shtrih-m/fr_drv_ng/releases/download/1.5.0-41-g1b0b878/fr_drv_ng_linux_x86_64_1.5.0-41-g1b0b878.zip
unzip fr_drv_ng_linux_x86_64_1.5.0-41-g1b0b878.zip
cd dist/linux_1.5.0.575/x86_64/
python3.9 setup.py  install --py3  -O2 --user
```
далее запускаем python3.9
```bash
python3.9
```
```python3
from fr_drv_ng import classic_interface #ошибок нет
```
для python3.8
```bash
apt install python3-dev
python3 setup.py  install --py3  -O2 --user
```
далее запускаем python3.8
```bash
LD_PRELOAD=./libclassic_fr_drv_ng.so python3
```
```python3
from fr_drv_ng import classic_interface #ошибок нет
```
Важно: директория с библиотекой должна остаться там же где и была при установке обертки. Те куда вы разархивируете zip с либой - там и оставьте.

**Comment by ApiDjango** [comment]
Спасибо тебе, хороший человек!!!! Собралось!!!

**Comment by ApiDjango** [comment]
Вопрос такой, пренес на виртуалку но там сейчас идет ошибка 
```
 LD_PRELOAD=./libclassic_fr_drv_ng.so.1.4 python3.9 Start.py
Ошибка ввода вывода

```

**Comment by ApiDjango** [comment]
А вопрос на будшее, отправку тегов во так 
```
fptr.setParam(1178, date);
fptr.setParam(1179, '№1234');
```
Трудно сделать ?

**Comment by ApiDjango** [comment]
Просто спрашивают цикл по данным из базы чтоб заполнять теги

**Comment by swex** [comment]
> А вопрос на будшее, отправку тегов во так
> 
> ```
> fptr.setParam(1178, date);
> fptr.setParam(1179, '№1234');
> ```
> 
> Трудно сделать ?

Это не задача обертки над C библиотекой.
Для других вопросов создавайте отдельные темы. Это закрываю.
