### ISSUE TITLE
Код ошибки 33h (51) от ККТ: Некорректные параметры в команде или ошибка при работе с КМ <0x00330074: не допускается повтор тега внутри тега 1163 "Код товара" в операции (в теге 1059 "Предмет расчета") {тег 1305}>

### ISSUE THREAD

**Issue by ola-skorp** [shtrih-m/fr_drv_ng#185]
При попытке добавить больше одной маркировки для лайна происходит ошибка 
https://gist.github.com/ola-skorp/b3f8773c7269a6d15c23a9392260204c#file-gistfile1-txt-L470

**Comment by olefard** [comment]
Да, сейчас можно привязать к позиции только один код маркировки.
Делайте несколько вызовов FNOperation.

**Comment by ola-skorp** [comment]
Ошибка теперь Код ошибки 34h (52) от ФН: Работа с маркированными товарами временно заблокирована

**Comment by ola-skorp** [comment]
В каком смысле переполнился? У меня один лайн с двумя маркировками

**Comment by olefard** [comment]
Это в этом чеке. А в сколько было чеков до этого.
Что возвращается в тесте драйвера на команду "ФН чеки/КТ2/Запрос статуса по работе с КМ"?

**Comment by ola-skorp** [comment]
Состояние проверки КМ               : 1, нет КМ на проверке
Сост. по форм. уведомления          : 0, уведомление о реализации не формируется
Флаги разрешения команд работы с КМ : 37
Кол-во сохр. результатов проверки КМ: 2
Кол-во КМ, вкл. в уведомление о реализации: 0
Заполнение области хранения уведомлений   : 0, менее чем 50%
Количество уведомлений в очереди: 10

**Comment by olefard** [comment]
> Количество уведомлений в очереди: 10

Какие-то неотправленные уведомления в очереди есть. Возможно уже давно не отправлялись. В ФФД 1.2 кроме отправки чеков в ОФД еще отправляются уведомления о продаже маркировок.

В тесте драйвере ниже есть кнопка "Получить сост. передачи увед.". Она должна показать дату неотправленного уведомления. 

Проверьте адрес сервера КМ в таблицах ФРа/Параметры ОФД.

**Comment by ola-skorp** [comment]
Изменила параметры, теперь опять 51, но с другим текстом
https://gist.github.com/ola-skorp/8f1c916c1f1d97533171bc803c9a64fd#file-gistfile1-txt-L316

**Comment by asem-m** [comment]
А вы не пытаетесь самостоятельно сформировать тег 2114 и передать его в кассу?

**Comment by asem-m** [comment]
номер сборки КЯ уточните

**Comment by olefard** [comment]
> А вы не пытаетесь самостоятельно сформировать тег 2114 и передать его в кассу?

Нет, выполняется команда FF61.

> номер сборки КЯ уточните

по логу сборка 40306

**Comment by ola-skorp** [comment]
> А вы не пытаетесь самостоятельно сформировать тег 2114 и передать его в кассу?

Нет
