### ISSUE TITLE
FNOperation не проходит при продажи на python под Linux

### ISSUE THREAD

**Issue by ApiDjango** [shtrih-m/fr_drv_ng#186]
Добрый день, снова я ) 
Перенес код под Linux, на python чек открывается, но продажа не проходит 
```

        ci.Tax1=3
	print(str(float(RPRICE))+' : '+str(QUANTITY)+' : '+str(SaleSumma))
	ci.Price=int(RPRICE)
	ci.Quantity=float(QUANTITY)
	ci.CheckType=1
	ci.Summ2=float(SaleSumma)
	ci.PaymentTypeSign= 4 #int(SaleType)
	ci.PaymentItemSign=4
	ci.MeasureUnit=0
	ci.Password=1
	ci.StringForPrinting=SaleText[0:35];
	checkResult(ci.FNOperation(),ci,'37')
```

TypeError: in method 'classic_interface_Price_set', argument 2 of type 'int64_t'

**Comment by ApiDjango** [comment]
```
 ci.Summ2=float(SaleSumma)
TypeError: in method 'classic_interface_Summ2_set', argument 2 of type 'int64_t'
```

**Comment by ApiDjango** [comment]
Почему-то просит int, хотя должен быть double или float как я понимаю

**Comment by olefard** [comment]
Нет, так и должно быть int. Передаете сумму/цену в копейках.

**Comment by ApiDjango** [comment]
То есть нужно * 100 ?

**Comment by olefard** [comment]
Ага

**Comment by ApiDjango** [comment]
Не могу понять что именно не нравиться, чек открывается

**Comment by ApiDjango** [comment]
```
ci.Tax1=3
	#print(str(RPRICE)+'|'+str(int(RPRICE*100)))
	ci.Price=int(RPRICE*100)
	ci.Quantity=int(QUANTITY)
	ci.CheckType=1
	ci.Summ2=int(SaleSumma*100)
	ci.PaymentTypeSign=4 #int(SaleType)
	ci.PaymentItemSign=4
	ci.MeasureUnit=0
	ci.Password=1
	ci.StringForPrinting=SaleText[0:35];
	checkResult(ci.FNOperation(),ci,'37')
```

Invalid command ((

**Comment by ApiDjango** [comment]
Кстати если ставить ci.CheckType=0 то
`Invalid property CheckType`
а если перед открытием чека то все норм

**Comment by olefard** [comment]
Для OpenCheck и FNOperation надо указывать разные значения CheckType. Попробуйте указать перед OpenCheck Checktype = 0, а перед FNOperation CheckType=1.

Можете еще код ошибки указывать? И хорошо бы лог драйвера.

**Comment by ApiDjango** [comment]
> Для OpenCheck и FNOperation надо указывать разные значения CheckType. Попробуйте указать перед OpenCheck Checktype = 0, а перед FNOperation CheckType=1.
> 
> Можете еще код ошибки указывать? И хорошо бы лог драйвера.

Помогло.

**Comment by ApiDjango** [comment]
Добрый день. 
```
if (AddAttr >'') and (AddAttr.count("@")>0):
		ci.CustomerEmail = AddAttr
		checkResult(ci.FNSendCustomerEmail(),ci,'73')
		
```
Inout error:73 
Выскакивает через раз.
