### ISSUE TITLE
Line exeed maximum print width

### ISSUE THREAD

**Issue by Yanovsky** [shtrih-m/fr_drv_ng#187]
ККТ Штрих-ON_LINE (C.3 от 17.01.2022)
В таблице 17 в поле 18 (Rus компактный заголовок) записываю значение 7
При закрытии чека (метод FNCloseCheckEx()) получаю ошибку 145 "Line exeed maximum print width"
Если в том же поле и в той же таблице значение от 0 до 5 то ошибки нет.

В чем может быть проблема?

P.S. Строк больше 32 символов в принтер не передается. Однако попробовал (чисто ради эксперимента) передавать строки обрезанные до 20 символов. Результат тот же: "Line exeed maximum print width"

[fr_drv_ng.log](https://disk.yandex.ru/d/fsSLCOy6iIZ9pA)

Спасибо

**Comment by surfernsk** [comment]
Добрый день @Yanovsky.
1. Вопрос не относиться к драйверу!
2. Согласно руководству по настройке ККТ, Вам доступны значения поля от 0 до 6. (Скрин ниже)

![image](https://user-images.githubusercontent.com/2264893/161315953-833348be-e40a-41d1-8437-2c61e572dbd2.png)

**Comment by Yanovsky** [comment]
Спасибо. Так клиенту и ответим.
