### ISSUE TITLE
Отключение печати отчётов об операциях со сменой 

### ISSUE THREAD

**Issue by NovikovRA** [shtrih-m/fr_drv_ng#188]
Добрый день, возможно ли отключить печать отчётов об открытии\закрытии смены? 
Пробовал Set_SkipPrint, но как я понял, данный метод не актуален,  также пробовал следующим образом: 

```
 driver.Set_DeviceFunctionNumber(DFE_SkipAllPrinting.swigValue());
 driver.Set_ValueOfFunctionInteger(1);
 driver.OpenSession();
```

Отчёт всё равно печатается

**Comment by asem-m** [comment]
укажите устройство (кассу) с которым вы работаете

**Comment by NovikovRA** [comment]
[asem-m](https://github.com/asem-m) 
Pax A930

**Comment by asem-m** [comment]
ФФД 1.2 или 1.05?

отключить печать отчетов можно, если касса зарегистрирована для торговли в Интернет

**Comment by NovikovRA** [comment]
[asem-m](https://github.com/asem-m)
ФФД 1.2
Каким методом можно отключить печать?

**Comment by asem-m** [comment]
касса зарегистрирована для торговли в Интернет?

полностью отключить печать?

**Comment by NovikovRA** [comment]
[asem-m](https://github.com/asem-m)
Как оказалось, не зарегистрирована для торговли в Интернет.
Отключить печать только для операций пробития чеков и включения\выключения смены

**Comment by swex** [comment]
есть еще метод `SetDeviceFunction`, с параметром `DeviceFunctionNumber` равным `DFE_SkipAllPrinting`, для КЯ работает путём переключения на NULL принтер.
см. Таблица 3 Поле 18

**Comment by asem-m** [comment]
Для отключения печати чека нужно записать в Т1П48=1 и передать телефон или почту покупателя в чек.

Для отключения принтера, в случае если касса зарегистрирована для Интернет торговли, в Т3П18=2 (null принтер).
