### ISSUE TITLE
1с перехватывает кассу

### ISSUE THREAD

**Issue by 2UTM** [shtrih-m/fr_drv_ng#189]
Приветствую, опишу ситуацию.
Есть небольшая программка, которая собирает данные с кассы (не отправленные чеки, сроки фн и так далее) и отправляет на сервер, сделана с использованием релиза fr_drv_ng_windows_i386_1.5.0-37. На старом драйвере (4.14, 4.15) все работает, касса доступна вне зависимости открыта 1с или нет, даже по ком порту.
Но сейчас идет переход на ФФД 1.2, соответственно обновляем прошивки и драйвера, и тут появилась проблема, что 1с может перехватить кассу на глухаря, и даже сам драйвер до нее не достукивается, версия драйвера 5.16 32бит, версия прошивки С3 от 26.08.2021. Если выйти из 1с, то все становиться доступно.
Но еще интересно то, что такое не всегда, иногда касса доступна при открытой 1с, иногда нет.
Подскажите в чем проблема, как сделать, чтобы драйвер, и соответственно моя программа, всегда получали доступ до кассы, как было на старых драйверах и прошивках?

**Comment by swex** [comment]
1. Интересно конечно что 1С делает с ККТ что-то в фоне, на мой взгляд это странно и "по идее" должна быть возможность такое поведение отключить
2. В этой ситуации мы со своей стороны ничем помочь не сможем, такое поведение пример гонки за ресурс. Используются 2 разных драйвера и две разные программы, они ничего не знают и не должны знать друг о друге. Вам необходимо самостоятельно разрулить конфликт между 1С и вашей утилитой
