### ISSUE TITLE
Как задать имя системного администратора?

### ISSUE THREAD

**Issue by ola-skorp** [shtrih-m/fr_drv_ng#19]
Как задать имя системного администратора? Насколько я поняла, нужно делать это через таблицу. Я пробовала
Set_TableNumber(2)
Set_RowNumber(30)
Set_FieldNumber(2)
Set_ValueOfFieldString("Имя")
Но я получаю ошибку 89 при вызове этого до connect.
Если добавить checkResult(WriteTable()) и вызвать всё это после connect, то я получаю ошибку 74.

**Comment by swex** [comment]
В любом случае нужно после Connect взаимодействовать с ККТ. Что такое ошибка 89 до connect не пойму. Вообще ошибка 89 - это "Документ открыт другим оператором", а 74 больше похожа на правду: "Открыт чек – операция невозможна".

Большинство таблиц можно писать только в состоянии закрытой смены ECRMode - 4

**Comment by ola-skorp** [comment]
А можно ли поменять имя кассира в чеке без записи в таблицу?

**Comment by ola-skorp** [comment]
Теперь ошибка 89 выдаётся постоянно при попытке печатать что-либо. Даже через фискал мастер. Как вывести принтер из этого состояния?

**Comment by swex** [comment]
> А можно ли поменять имя кассира в чеке без записи в таблицу?

нет нельзя.

> Теперь ошибка 89 выдаётся постоянно при попытке печатать что-либо. Даже через фискал мастер. Как вывести принтер из этого состояния?

Давайте лог, или скажите что в ECRMode. Мы здесь не знаем в каком состоянии у вас ККТ.
Так же посмотрите  [пример](https://github.com/shtrih-m/fr_drv_ng_examples/blob/master/classic_interface/main.cpp#L126), как можно действовать в зависимости от состояния (Снятие отчета если 24 часа истекли, отменять документ если открыт, итд...)

**Comment by ola-skorp** [comment]
Мне помог ответ отсюда https://github.com/shtrih-m/fr_drv_ng_examples/issues/5
