### ISSUE TITLE
Использование MinGW с Windows

### ISSUE THREAD

**Issue by alexander-zolkin** [shtrih-m/fr_drv_ng#191]
Здравствуйте!
Скажите, есть ли возможность собрать программу, используя не MSVC а MinGW? OS — Windows. IDE — Qt Creator.

**Comment by swex** [comment]
добавим соотв сборку

**Comment by alexander-zolkin** [comment]
Это было бы отлично, спасибо! Добавите с новой версией?

**Comment by swex** [comment]
Что-то не всё так просто оказалось с mingw, я не понимаю какой проект актуальный mingw или mingw64. У вас какой mingw используется и если не секрет, по какой причине mingw, а не стандартный виндовый vc runtmie?

**Comment by alexander-zolkin** [comment]
Наш проект на Qt чувствует себя отлично на MinGW, но на MSVC в режиме отладки работает очень странно и невозможно отлаживать некоторые части программы. Мы используем ту версию, что [ставит Qt с версией 5.15](https://wiki.qt.io/MinGW), то есть, 8.1. По идее Это MinGW-w64.

**Comment by alexander-zolkin** [comment]
@swex, скажите, есть шанс что библиотеки под MinGW появятся в будущих релизах?

**Comment by swex** [comment]
с актуального релиза добавлены сборки mingw, просьба проверить, как у вас работает

**Comment by alexander-zolkin** [comment]
Вижу, спасибо! На этой неделе проверю, скорее всего.

**Comment by alexander-zolkin** [comment]
При сборке на Windows под MinGW теперь всё отлично работает, спасибо!

Всплыла другая проблема: при сборке архива на iPadOS выдаёт следующую ошибку: 

`ld: bitcode bundle could not be generated because '/Users/build/Posiflora/posiflora-pos/pos/ios/Frameworks/classic_fr_drv_ng.framework/classic_fr_drv_ng' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/build/Posiflora/posiflora-pos/pos/ios/Frameworks/classic_fr_drv_ng.framework/classic_fr_drv_ng' for architecture arm64`

То есть раньше библиотека была собрана с биткодом, а теперь нет? Как теперь следует собирать?

**Comment by alexander-zolkin** [comment]
@swex, у Вас есть мысли по поводу вышеописанной проблемы?

**Comment by alexander-zolkin** [comment]
После ковыряний в настройках сборки, получаю теперь такое сообщение :D

![image](https://user-images.githubusercontent.com/7412935/179919217-67436116-29a6-4648-84ea-ac7cf2f419c5.png)

**Comment by swex** [comment]
ну вроде как второе сообщение уже про то что нужно поднять минимальную версию ОС, возможно поможет?

**Comment by alexander-zolkin** [comment]
Вы имеете в виду ключ `MinimumOSVersion`? Наше приложение собирается под, минимум, iPadOS 12.0. Поставил так же в обе библиотеки (cppbase_fr_drv_ng и classic_fr_drv_ng). А так же установил параметры, как в [этом ответе](https://stackoverflow.com/a/53021962/8587673). Последняя ошибка пропала, но верхняя остаётся.

![image](https://user-images.githubusercontent.com/7412935/180001619-dbad1a2c-0f8a-4a6d-a5cc-1957eb86a46a.png)

**Comment by swex** [comment]
в актуальном релизе добавлен ключ сборки `XCODE_ATTRIBUTE_ENABLE_BITCODE` `ON`, хотя не уверен что он поможет, т.к. оно вроде как включено по умолчанию

**Comment by alexander-zolkin** [comment]
Проверил, действительно, bitcode'а всё так же нет.

```
Bitcode bundle could not be generated because '/Users/adzol/Projects/posiflora-pos/pos/ios/Frameworks/classic_fr_drv_ng.framework/classic_fr_drv_ng' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/adzol/Projects/posiflora-pos/pos/ios/Frameworks/classic_fr_drv_ng.framework/classic_fr_drv_ng' for architecture arm64
```

Ключи для сборки, что я указал [ранее](https://github.com/shtrih-m/fr_drv_ng/issues/191#issuecomment-1187469340) у вас поставить нет возможности?

**Comment by alexander-zolkin** [comment]
Очень не хотелось бы выпускать приложение под Windows с новой библиотекой, а под iPadOS со старой. Такая фрагментация усложнит разработку. Есть ли ещё какие-то варианты с это библиотекой?

**Comment by swex** [comment]
а вон сегодня у кого-то завелось https://github.com/shtrih-m/fr_drv_ng/issues/214

**Comment by alexander-zolkin** [comment]
Интересно, значит завтра покопаю. Спасибо!

**Comment by alexander-zolkin** [comment]
Разве в #214 библиотеку используют не на MacOS?
