### ISSUE TITLE
Использование библиотеки в Debug режиме (Qt Creator)

### ISSUE THREAD

**Issue by alexander-zolkin** [shtrih-m/fr_drv_ng#192]
Здравствуйте!
Для разработки приложения я использую Qt Creator. Если я пытаюсь запустить приложение в режиме отладки (Debug) падает на функции `Set_IPAddress()`. В Release всё отрабатывает отлично. Есть ли сборка библиотека для режима отладки? OS — Windows.

**Comment by surfernsk** [comment]
https://github.com/shtrih-m/fr_drv_ng/issues/64#issuecomment-499864388

**Comment by alexander-zolkin** [comment]
Вижу, что тут ответ относится к VS или если для сборки используется CMake. Мы для сборки используем qmake, и если в файле проекта я пишу `QMAKE_CXXFLAGS_DEBUG += /MDd`, ничего, к сожалению, не меняется, программа так же падает на использовании функций библиотеки.

**Comment by swex** [comment]
так наоборот нужно собирать с /MD, а не /MDd

**Comment by alexander-zolkin** [comment]
Да, верно, спасибо что поправили. Теперь, правда, у меня загрузка библиотек через `[QLibrary](https://doc.qt.io/qt-5/qlibrary.html)`  не работает :-(

**Comment by swex** [comment]
ну у всех C++ библиотек должен быть один рантайм, тогда всё будет ок.

**Comment by alexander-zolkin** [comment]
Да, значит не судьба, потому что мы вряд ли другие библиотеки от сбера найдём :D 

Спасибо за пояснение!
