### ISSUE TITLE
ИНН возвращается без первого 0

### ISSUE THREAD

**Issue by SChepinog** [shtrih-m/fr_drv_ng#193]
Добрый день!
Ритейл 02Ф, прошивка 0.0.41963 build C.3 от 26.08.2021, версия драйвера для java 1.4.6.379
ККТ зарегистрировала на ИНН 030905569106, а при запросе Get_INN получаем 30905569106, то есть без первой цифры 0.
Подскажите, пожалуйста, в чем может быть проблема.

**Comment by swex** [comment]
Здравствуйте! 
Свойство `INN` заполняется множеством методов, в том числе, например, `GetECRStatus` в этот метод ИНН приходит как 48-битное число, отсюда и результат пропадает лидирующий 0. 

Правильным способом получения ИНН будет чтение поля 2 из таблицы "Фискальный накопитель", номер которой может отличаться в зависимости от модели, получить его можно вот так:
```c++
    // получаем номер таблицы "Фискальный Накопитель"
    ci->Set_ModelParamNumber(classic_interface::DPE_FsTableNumber);
    executeAndHandleError(std::bind(&classic_interface::ReadModelParamValue, ci));
    auto fsTableNumber = ci->Get_ModelParamValue();
``` 
Другой вариант это получить ИНН из метода `FNGetFiscalizationResult`.

PS: Можно попробовать поправить ИНН, добавлять префикс из нулей до 10 или 12 символов, но там всё не так просто.(получаем 9значное число и сколько нулей добавлять 1 или 3?)

**Comment by SChepinog** [comment]
Спасибо, вроде, получилось
