### ISSUE TITLE
Теряется связь с ККТ

### ISSUE THREAD

**Issue by YaNokk** [shtrih-m/fr_drv_ng#195]
Здравствуйте. При попытке вызвать команду по типу печати или получения статуса получаю "command 17 return code: -1 execution took 10001ms Inout error", если команда была вызвана спустя > 4с после вызова предыдущей команды. Если вызвать команду после ошибки, то она пройдет и все повторится. Пробовал увеличивать Timeout до 20с, но без результата. Connect отрабатывает правильно, а Get_Connected всегда возвращает true.

 Версия драйвера:

 Версия        : 5
 Подверсия     : 16
 Релиз         : 0
 Сборка        : 877
 Полная версия : 5.16.0.877
[fr_drv_ng.log](https://github.com/shtrih-m/fr_drv_ng/files/8878615/fr_drv_ng.log)

**Comment by swex** [comment]
Видно, что просто не приходит ответ на команду. Нижний уровень передачи у вас COM порт. Там возможны потери.  Что касается свойства `Connected` то оно действительно остается `True` т.к. порт остается открытым.
Причины такого поведения по логу назвать не могу.
Попробуйте добавить в `ConnectionURI` `ack_timeout` время до получения байта `ACK` - подтверждение получения посылки.
Это позволит ускорить отвал в случае проблем чтобы не ждать полный таймаут.
Так же можно попробовать добавить параметр `enq_mode` 1 - посылать ENQ перед каждой командой
вот так: `serial://PORT?timeout=30000&baudrate=115200&ack_timeout=1000&enq_mode=1`
