### ISSUE TITLE
REST API server

### ISSUE THREAD

**Issue by w2x** [shtrih-m/fr_drv_ng#196]
Подскажите есть ли документация по REST API server? Спасибо.

**Comment by mejgun** [comment]
А где он находится?

**Comment by swex** [comment]
подскажите, о чем речь?

**Comment by w2x** [comment]
Речь запуске console_test_fr_drv_ng-1.5 с параметром run-http-api-server

**Comment by swex** [comment]
ой, да это просто обертка чтобы можно было команды консольного теста вызывать через http, единственная разница в том что не будет разрыва сессии с ККТ между вызовами.
пример запуска:
```bash
console_test_fr_drv_ng run-http-api-server 0.0.0.0:8888
```
пример вызова
```bash
curl http://127.0.0.1:8888/console_command --data '{"command": "write","args": "2.1.2","params":"Первый кассир"}'

```
команды все те же что и просто через вызов утилиты
возможные ключи json: 
command - команда
params - параметры
args - аргументы

**Comment by w2x** [comment]
Было бы замечательно, если  можно было чеки пробивать через run-http-api-server. Теоретически можно использовать  команду hex-cmd, но в этом случае все сильно усложняется )

**Comment by w2x** [comment]
>команды все те же что и просто через вызов утилиты
>возможные ключи json:
>command - команда
>params - параметры
>args - аргументы

Как использовать с командой print, которая при запуске из командной строки берет данные для печати из stdin?

пробую так:

curl http://127.0.0.1:8888/console_command --data '{"command": "print","args": "1","params":"строка для печати"}'

получаю на ленте  текст в двойных кавычках, переданный в args , напечатанный шрифтом из args

![shtrih_print](https://user-images.githubusercontent.com/3272612/175210331-20262d16-de88-47a0-b62f-189683852f1c.jpg)

**Comment by swex** [comment]
print никак не заработает через http-api-server. Для такой печати нужна другая команда, которая бы брала строку из аргументов.  На данный момент единственное назначение http-api-server это выполнение нескольких команд в рамках одной сессии. Чтобы можно было занять ККТ и быть уверенным в "атомарности" своих действий (например при заполнении таблицы регистрации)
