### ISSUE TITLE
Сборка для go и linux

### ISSUE THREAD

**Issue by mejgun** [shtrih-m/fr_drv_ng#198]
Здравствуйте. Объясните, пожалуйста, как использовать библиотеку в связке с go.
Есть какая-то подробная инструкция? [Такая](https://github.com/shtrih-m/fr_drv_ng_examples/blob/master/classic_go/README.md) есть, но я не понимаю(

Если пытаться использовать `c_classic_interface.h`, то компиляция падает с ошибкой что нужно указать `-std=gnu++11`, но это не помогает, потому что, как я понял, он собирает c компилятором, а не c++.

Если через swig, то получаю бесконечные сообщения вроде 
<pre>
/usr/lib/gcc/x86_64-pc-linux-gnu/11.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: $WORK/b001/_x003.o: in function `_wrap_new_classic_interface__SWIG_0_classic_fr_drv_ng_22d3d00e2a0b08d1':
./classic_interface_wrap.cxx:2578: undefined reference to `classic_interface::classic_interface()'
/usr/lib/gcc/x86_64-pc-linux-gnu/11.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: $WORK/b001/_x003.o: in function `_wrap_new_classic_interface__SWIG_1_classic_fr_drv_ng_22d3d00e2a0b08d1':
./classic_interface_wrap.cxx:2594: undefined reference to `classic_interface::classic_interface(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/lib/gcc/x86_64-pc-linux-gnu/11.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: $WORK/b001/_x003.o: in function `_wrap_delete_classic_interface_classic_fr_drv_ng_22d3d00e2a0b08d1':
./classic_interface_wrap.cxx:2605: undefined reference to `classic_interface::~classic_interface()'
/usr/lib/gcc/x86_64-pc-linux-gnu/11.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: $WORK/b001/_x003.o: in function `_wrap_classic_interface_AddLD_classic_fr_drv_ng_22d3d00e2a0b08d1':
./classic_interface_wrap.cxx:2617: undefined reference to `classic_interface::AddLD()'
/usr/lib/gcc/x86_64-pc-linux-gnu/11.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: $WORK/b001/_x003.o: in function `_wrap_classic_interface_Beep_classic_fr_drv_ng_22d3d00e2a0b08d1':
./classic_interface_wrap.cxx:2630: undefined reference to `classic_interface::Beep()'

</pre>

**Comment by swex** [comment]
можете описать по шагам что делаете? где-то не передается линковка с libclassic_fr_drv_ng.so.

**Comment by mejgun** [comment]
всё верно, проблема оказалась в отсутствии линковки. я думал надо только к libclassic_fr_drv_ng_go.so линковаться

написал свои шаги можете обновить инструкцию?

1. генерирую swig обертку `swig -c++ -go -cgo -use-shlib -intgosize 64  -o classic_interface_wrap.cxx classic_interface.i`
2. собираю либу-обертку `g++ -shared classic_interface_wrap.cxx -I. -o libclassic_fr_drv_ng_go.so`
3. после `#undef intgo` добавляю LDFLAGS чтоб получилось 
```go
#undef intgo
#cgo LDFLAGS: -L. -lclassic_fr_drv_ng -lclassic_fr_drv_ng_go
*/
import "C"
```
4. делаю `go mod init classic_fr_drv_ng && go mod tidy`
5. на этом этапе уже можно проверить сборку либы через go build
6. создаю соседнюю папку `app`
7. делаю в ней `go mod init app`
8. добавляю в конец go.mod `replace classic_fr_drv_ng => ../x86_64`
9. создаю main.go, в него пишу:
```go
package main

import (
	"classic_fr_drv_ng"
	"fmt"
)

func checkError(err int) error {
	if err != 0 {
		return fmt.Errorf("bad return code: %d", err)
	}
	return nil
}

func main() {
	ci := classic_fr_drv_ng.NewClassic_interface()
	ci.Set_ConnectionURI("tcp://192.168.137.111:7778?timeout=30048&plain_transfer=auto")
	fmt.Println(checkError(ci.Connect()), checkError(ci.GetECRStatus()))
	fmt.Println("mode: ", ci.Get_ECRMode(), ci.Get_ECRModeDescription())
}
```
10. делаю `go mod tidy`
11. `go mod build`

**Comment by mejgun** [comment]
а если собирать c_classic_interface, то получается вот так:

main.go:
```go
package main

// #cgo LDFLAGS: -lclassic_fr_drv_ng
// #cgo CFLAGS: -I/usr/lib/gcc/x86_64-pc-linux-gnu/11.3.0/include/g++-v11/ -I /usr/lib/gcc/x86_64-pc-linux-gnu/11.3.0/include/g++-v11/x86_64-pc-linux-gnu
// #include <c_classic_interface.h>
import "C"

func main() {}
```
получаю 
<pre>
/usr/lib/gcc/x86_64-pc-linux-gnu/11.3.0/include/g++-v11/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
</pre>

**Comment by mejgun** [comment]
а нельзя вот [этот rest api server](https://github.com/shtrih-m/fr_drv_ng/issues/196#issuecomment-1162753858) расширить на все команды (пробивать чеки)? можно было бы использовать драйвер на любом языке

**Comment by swex** [comment]
@mejgun спасибо, актуализируем доку. Там сейчас какой-то мусор, половина скопипасчено с readme про csharp, хотя это я когда-то делал видимо был в бреду.


> а нельзя вот [этот rest api server](https://github.com/shtrih-m/fr_drv_ng/issues/196#issuecomment-1162753858) расширить на все команды (пробивать чеки)? можно было бы использовать драйвер на любом языке

давно витает такая мысль, никак не дойдут руки, да и никто не просил...
Думаю сможем на след. неделе прикрутить что-то по websocket с сообщениями вроде json-rpc.

**Comment by mejgun** [comment]
> Думаю сможем на след. неделе прикрутить что-то по websocket с сообщениями вроде json-rpc.

ого) было бы круто

**Comment by theart84** [comment]
> всё верно, проблема оказалась в отсутствии линковки. я думал надо только к libclassic_fr_drv_ng_go.so линковаться
> 
> написал свои шаги можете обновить инструкцию?
> 
> 1. генерирую swig обертку `swig -c++ -go -cgo -use-shlib -intgosize 64  -o classic_interface_wrap.cxx classic_interface.i`
> 2. собираю либу-обертку `g++ -shared classic_interface_wrap.cxx -I. -o libclassic_fr_drv_ng_go.so`
> 3. после `#undef intgo` добавляю LDFLAGS чтоб получилось
> 
> ```go
> #undef intgo
> #cgo LDFLAGS: -L. -lclassic_fr_drv_ng -lclassic_fr_drv_ng_go
> */
> import "C"
> ```
> 
> 4. делаю `go mod init classic_fr_drv_ng && go mod tidy`
> 5. на этом этапе уже можно проверить сборку либы через go build
> 6. создаю соседнюю папку `app`
> 7. делаю в ней `go mod init app`
> 8. добавляю в конец go.mod `replace classic_fr_drv_ng => ../x86_64`
> 9. создаю main.go, в него пишу:
> 
> ```go
> package main
> 
> import (
> 	"classic_fr_drv_ng"
> 	"fmt"
> )
> 
> func checkError(err int) error {
> 	if err != 0 {
> 		return fmt.Errorf("bad return code: %d", err)
> 	}
> 	return nil
> }
> 
> func main() {
> 	ci := classic_fr_drv_ng.NewClassic_interface()
> 	ci.Set_ConnectionURI("tcp://192.168.137.111:7778?timeout=30048&plain_transfer=auto")
> 	fmt.Println(checkError(ci.Connect()), checkError(ci.GetECRStatus()))
> 	fmt.Println("mode: ", ci.Get_ECRMode(), ci.Get_ECRModeDescription())
> }
> ```
> 
> 10. делаю `go mod tidy`
> 11. `go mod build`

Большое спасибо за подробный мануал по сборке.
