### ISSUE TITLE
в чем отличие javapos от https://github.com/shtrih-m/javapos_shtrih

### ISSUE THREAD

**Issue by whiskas** [shtrih-m/fr_drv_ng#2]
добрый день, а в чем отличие javapos в это репозитории от того, что находится тут:
 https://github.com/shtrih-m/javapos_shtrih ?

какой вариант лучше использовать в работе?

Спасибо!

**Comment by swex** [comment]
Здравствуйте.

Это кроссплатформенный проект на c++ с биндингами для java и python, сгенерированными через SWIG. Интерфейс classic_fr_drv_ng повторяет интерфейс "классического" Драйвер ФР под Windows. JavaPOS - это про Java и UnifiedPOS.

Что использовать зависит от используемых в проекте технологий, предпочтений разработчиков и.т.д.

**Comment by whiskas** [comment]
Спасибо!
подскажите, в каких либо проектах это решение уже используется? 
вопросы по работе драйвера - можно задавать здесь на гитхабе в issue?

**Comment by swex** [comment]
До недавнего времени этот проект распространялся среди партнёров через внутренние сервисы штрих-м. Поэтому на GitHub пока нет активности. Драйвер используется в том числе в крупных компаниях.

Да, конечно, задавайте здесь.
