### ISSUE TITLE
получение данных о фискальном чеке для возвратов

### ISSUE THREAD

**Issue by try2bajed1** [shtrih-m/fr_drv_ng#20]
для извлечения фискальных данных для продажи я использую операции FNOperation и 
FNCloseCheckEx для закрытия чека. У меня операция возврата регистрируется через ReturnSale и получаю ошибку -55 .
соответственно те значения для считывания значений для продажи в возврате не работают. 

[T] Connect() ok
[T] GetECRStatus()
[D] -> 8F 07 00 04 00 11 1E 00 00 00 E9 7F
[D] <- 8F
[D] <- 34 00 04 00 11 00 1E 43 32 40 83 0E 0B 12 01 E3 08 90 00 28 00 80 4E 41 00 00 01 01 10 10 0B 12 0E 2E 30 00 A1 03 00 00 12 00 00 00 00 00 D2 58 01 CD 01 00 00 00 F2 42
[D] command 11 return code: 0 execution took 11ms
[D] commands total: 4, succeed: 4, failed: 0, avg. exec time: 10ms
[T] GetECRStatus() ok
[T] Get_ECRMode()
[T] Get_ECRMode() -> `8`
[T] CancelCheck()
[D] -> 8F 07 00 05 00 88 1E 00 00 00 7E 49
[D] <- 8F
[D] <- 05 00 05 00 88 00 1E 3A CA
[D] command 88 return code: 0 execution took 104ms
[D] commands total: 5, succeed: 5, failed: 0, avg. exec time: 29ms
[T] CancelCheck() ok
[T] WaitForPrinting()
[D] -> 8F 03 00 06 00 FC ED 63
[D] <- 8F
[D] <- 1A 00 06 00 FC 00 00 00 02 00 2D 00 D8 D2 D0 C8 D5 2D D1 CC C0 D0 D2 CF CE D1 2D D4 5B 60
[D] command FC return code: 0 execution took 0ms
[D] commands total: 6, succeed: 6, failed: 0, avg. exec time: 24ms
[D] -> 8F 04 00 07 00 F7 01 EB C3
[D] <- 8F
[D] <- 29 00 07 00 F7 00 08 00 C0 F7 3F 08 02 00 00 00 01 0C 0A 00 00 00 00 00 00 1E 00 00 00 00 06 AF 05 28 00 00 00 0D 0E 10 0A 1D 11 C8 78
[D] command F7 return code: 0 execution took 8ms
[D] commands total: 7, succeed: 7, failed: 0, avg. exec time: 22ms
[D] -> 8F 07 00 08 00 11 1E 00 00 00 82 2D
[D] <- 8F
[D] <- 34 00 08 00 11 00 1E 43 32 40 83 0E 0B 12 01 E3 08 90 00 02 00 80 4E 41 00 00 01 01 10 10 0B 12 0E 2E 30 00 A1 03 00 00 12 00 00 00 00 00 D2 58 01 CD 01 00 00 00 3D B5
[D] command 11 return code: 0 execution took 5ms
[D] commands total: 8, succeed: 8, failed: 0, avg. exec time: 20ms
[D] -> 8F 08 00 09 00 26 1E 00 00 00 01 41 91
[D] <- 8F
[D] <- 09 00 09 00 26 00 80 01 0C 19 06 EF 5B
[D] command 26 return code: 0 execution took 0ms
[D] commands total: 9, succeed: 9, failed: 0, avg. exec time: 17ms
[D] -> 8F 08 00 0A 00 26 1E 00 00 00 02 57 69
[D] <- 8F
[D] <- 09 00 0A 00 26 00 80 01 18 2D 06 59 20
[D] command 26 return code: 0 execution took 0ms
[D] commands total: 10, succeed: 10, failed: 0, avg. exec time: 16ms
[D] -> 8F 08 00 0B 00 26 1E 00 00 00 03 A5 3E
[D] <- 8F
[D] <- 09 00 0B 00 26 00 80 01 0C 13 06 43 72
[D] command 26 return code: 0 execution took 0ms
[D] commands total: 11, succeed: 11, failed: 0, avg. exec time: 14ms
[D] -> 8F 08 00 0C 00 26 1E 00 00 00 04 5A 89
[D] <- 8F
[D] <- 09 00 0C 00 26 00 80 01 18 19 06 80 B3
[D] command 26 return code: 0 execution took 2ms
[D] commands total: 12, succeed: 12, failed: 0, avg. exec time: 13ms
[D] -> 8F 08 00 0D 00 26 1E 00 00 00 05 A8 DE
[D] <- 8F
[D] <- 09 00 0D 00 26 00 7C 01 0A 13 06 16 2E
[D] command 26 return code: 0 execution took 1ms
[D] commands total: 13, succeed: 13, failed: 0, avg. exec time: 12ms
[D] -> 8F 08 00 0E 00 26 1E 00 00 00 06 BE 26
[D] <- 8F
[D] <- 09 00 0E 00 26 00 80 01 08 13 06 4F D9
[D] command 26 return code: 0 execution took 1ms
[D] commands total: 14, succeed: 14, failed: 0, avg. exec time: 11ms
[D] device properties cached
[D] name: ШТРИХ-СМАРТПОС-Ф
[D] fonts: 6
[D] isUM: false
[D] -> 8F 07 00 0F 00 10 1E 00 00 00 97 9E
[D] <- 8F
[D] <- 13 00 0F 00 10 00 1E 90 00 02 00 00 00 00 00 00 00 FF FF FF 00 F7 CC
[D] command 10 return code: 0 execution took 3ms
[D] commands total: 15, succeed: 15, failed: 0, avg. exec time: 11ms
[T] WaitForPrinting() ok
[T] Set_CheckType(`2`)
[T] Set_CheckType() ok
[T] OpenCheck()
[D] -> 8F 08 00 10 00 2D 1E 00 00 00 01 5E 36
[D] <- 8F
[D] <- 2F 00 10 00 2D 00 CD C0 D1 D2 D0 CE C9 CA C8 20 CA CA D2 20 28 CA C0 D1 D1 CE C2 CE C3 CE 20 DF C4 D0 C0 29 00 00 00 00 00 00 00 00 00 00 01 00 3C 5C 17
[D] command 2D return code: 0 execution took 5ms
[D] commands total: 16, succeed: 16, failed: 0, avg. exec time: 10ms
[D] -> 8F 09 00 11 00 2E 1E 00 00 00 01 30 2E D5
[D] <- 8F
[D] <- 30 00 11 00 2E 00 CA C0 D1 D1 CE C2 DB C5 20 D7 C5 CA C8 20 28 C1 D1 CE 29 20 C2 20 DD CB C5 CA D2 D0 CE CD CD CE C9 20 D4 CE D0 CC C5 00 00 01 00 01 2B 77
[D] command 2E return code: 0 execution took 2ms
[D] commands total: 17, succeed: 17, failed: 0, avg. exec time: 10ms
[D] -> 8F 0B 00 12 00 1F 1E 00 00 00 01 01 00 30 A5 06
[D] <- 8F
[D] <- 05 00 12 00 1F 00 00 E2 A7
[D] command 1F return code: 0 execution took 1ms
[D] commands total: 18, succeed: 18, failed: 0, avg. exec time: 9ms
[D] -> 8F 08 00 13 00 8D 1E 00 00 00 02 60 2F
[D] <- 8F
[D] <- 05 00 13 00 8D 00 1E 15 E8
[D] command 8D return code: 0 execution took 305ms
[D] commands total: 19, succeed: 19, failed: 0, avg. exec time: 25ms
[T] OpenCheck() ok
[T] Set_CheckType(`1`)
[T] Set_CheckType() ok
[T] Set_Password(`30`)
[T] Set_Password() ok
[T] Set_Quantity(`1`)
[T] Set_Quantity() ok
[T] Set_Price(`2807686`)
[T] Set_Price() ok
[T] Set_Summ1Enabled(`false`)
[T] Set_Summ1Enabled() ok
[T] Set_Tax1(`0`)
[T] Set_Tax1() ok
[T] Set_Department(`1`)
[T] Set_Department() ok
[T] Set_PaymentTypeSign(`4`)
[T] Set_PaymentTypeSign() ok
[T] Set_PaymentItemSign(`1`)
[T] Set_PaymentItemSign() ok
[T] Set_StringForPrinting(`Кружевное платье мини с высоким воротом Three Floor (Размер: S)`)
[T] Set_StringForPrinting() ok
[T] ReturnSale()
[D] -> 8F 55 00 14 00 82 1E 00 00 00 E8 03 00 00 00 86 D7 2A 00 00 01 00 00 00 00 CA F0 F3 E6 E5 E2 ED EE E5 20 EF EB E0 F2 FC E5 20 EC E8 ED E8 20 F1 20 E2 FB F1 EE EA E8 EC 20 E2 EE F0 EE F2 EE EC 20 54 68 72 65 65 20 46 6C 6F 6F 72 20 28 D0 E0 E7 EC E5 F0 3A 20 53 29 6B C6
[D] <- 8F
[D] <- 04 00 14 00 82 37 A9 E2
[D] command 82 return code: 55 execution took 12ms
[E] Command is not supported
[D] commands total: 20, succeed: 19, failed: 1, avg. exec time: 24ms
[D] -> 8F 04 00 15 00 6B 37 37 3E
[D] <- 8F
[D] <- 50 00 15 00 6B 00 CA CA D2 3A 20 CA EE EC E0 ED E4 E0 20 ED E5 20 EF EE E4 E4 E5 F0 E6 E8 E2 E0 E5 F2 F1 FF 20 E2 20 E4 E0 ED ED EE E9 20 F0 E5 E0 EB E8 E7 E0 F6 E8 E8 20 E8 EB E8 20 EF F0 E8 20 E4 E0 ED ED FB F5 20 ED E0 F1 F2 F0 EE E9 EA E0 F5 D4 B3
[D] command 6B return code: 0 execution took 1ms
[D] commands total: 21, succeed: 20, failed: 1, avg. exec time: 23ms
[D] ReturnSale() fail
[E] ККТ: Команда не поддерживается в данной реализации или при данных настройках
[T] Get_ResultCodeDescription()
[T] Get_ResultCodeDescription() -> `ККТ: Команда не поддерживается в данной реализации или при данных настройках`
[T] Disconnect()
[I] disconnect()
[I] close()
[T] Disconnect() ok

а если я делаю через ReturnSaleEx то получаю ошибку -12 не реализовано. Подскажите как правильно надо выставить условия операции возврата, чтобы извлекаать фиск. данные

**Comment by swex** [comment]
Нужно использовать `FNOperation` и для возврата. `RetunSale` в КЯ объявлен устаревшим и, кажется, вообще не работает в актуальной версии.

**Comment by try2bajed1** [comment]
в принципе я игрался и с ним, но еще раз попробую

**Comment by try2bajed1** [comment]
WaitForPrinting() ok
 Set_CheckType(`2`)
 Set_CheckType() ok
 OpenCheck()
 -> 8F 08 00 10 00 2D 1E 00 00 00 01 5E 36
 <- 8F
 <- 2F 00 10 00 2D 00 CD C0 D1 D2 D0 CE C9 CA C8 20 CA CA D2 20 28 CA C0 D1 D1 CE C2 CE C3 CE 20 DF C4 D0
 command 2D return code: 0 execution took 1ms
 commands total: 16, succeed: 16, failed: 0, avg. exec time: 9ms
 -> 8F 09 00 11 00 2E 1E 00 00 00 01 30 2E D5
 <- 8F
 <- 30 00 11 00 2E 00 CA C0 D1 D1 CE C2 DB C5 20 D7 C5 CA C8 20 28 C1 D1 CE 29 20 C2 20 DD CB C5 CA D2 D0
 command 2E return code: 0 execution took 1ms
 commands total: 17, succeed: 17, failed: 0, avg. exec time: 8ms
 -> 8F 0B 00 12 00 1F 1E 00 00 00 01 01 00 30 A5 06
 <- 8F
 <- 05 00 12 00 1F 00 00 E2 A7
 command 1F return code: 0 execution took 0ms
 commands total: 18, succeed: 18, failed: 0, avg. exec time: 8ms
 -> 8F 08 00 13 00 8D 1E 00 00 00 02 60 2F
 <- 8F
 <- 05 00 13 00 8D 00 1E 15 E8
 command 8D return code: 0 execution took 317ms
 commands total: 19, succeed: 19, failed: 0, avg. exec time: 24ms
 OpenCheck() ok
 Set_CheckType(`1`)
 Set_CheckType() ok
 Set_Password(`30`)
 Set_Password() ok
 Set_Quantity(`1`)
 Set_Quantity() ok
 Set_Price(`2807600`)
 Set_Price() ok
 Set_Summ1Enabled(`false`)
 Set_Summ1Enabled() ok
 Set_Tax1(`0`)
 Set_Tax1() ok
 Set_Department(`1`)
 Set_Department() ok
 Set_PaymentTypeSign(`4`)
 Set_PaymentTypeSign() ok
 Set_PaymentItemSign(`1`)
 Set_PaymentItemSign() ok
 Set_StringForPrinting(`Кружевное платье мини с высоким воротом Three Floor (Размер: S)`)
 Set_StringForPrinting() ok
 FNOperation()
 -> 8F 61 00 14 00 FF 46 1E 00 00 00 01 40 42 0F 00 00 00 30 D7 2A 00 00 FF FF FF FF FF FF FF FF FF FF 00
 <- 8F
 <- 05 00 14 00 FF 46 5E 07 D6
 command FF46 return code: 94 execution took 14ms
 Invalid command
 commands total: 20, succeed: 19, failed: 1, avg. exec time: 23ms
 -> 8F 04 00 15 00 6B 5E B8 C3
 <- 8F
 <- 1A 00 15 00 6B 00 CA CA D2 3A 20 CD E5 E2 E5 F0 ED E0 FF 20 EE EF E5 F0 E0 F6 E8 FF 0F AC
 command 6B return code: 0 execution took 1ms
 commands total: 21, succeed: 20, failed: 1, avg. exec time: 22ms
 FNOperation() fail
 ККТ: Неверная операция
 Get_ResultCodeDescription()
 Get_ResultCodeDescription() -> `ККТ: Неверная операция`
 Disconnect()
 disconnect()
 close()
 Disconnect() ok
ошибка 94

**Comment by swex** [comment]
перед `FNOperation` `checkType` должен быть 2

**Comment by try2bajed1** [comment]
но я выставляю двойку
OpenCheck() ok
Set_CheckType(`2`)
Set_CheckType() ok
Set_Password(`30`)
Set_Password() ok
Set_Quantity(`1`)
Set_Quantity() ok
Set_Price(`2807643`)
Set_Price() ok
Set_Summ1Enabled(`false`)
Set_Summ1Enabled() ok
Set_Tax1(`0`)
Set_Tax1() ok
Set_Department(`1`)
Set_Department() ok
Set_PaymentTypeSign(`4`)
Set_PaymentTypeSign() ok
Set_PaymentItemSign(`1`)
Set_PaymentItemSign() ok
Set_StringForPrinting(`Кружевное платье мини с высоким воротом Three Floor (Размер: S)`)
Set_StringForPrinting() ok
FNOperation()
-> 8F 61 00 13 00 FF 46 1E 00 00 00 02 40 42 0F 00 00 00 5B D7 2A 00 00 FF FF FF FF FF FF FF FF FF FF 00
<- 8F
<- 05 00 13 00 FF 46 5E D3 B1
command FF46 return code: 94 execution took 14ms
Invalid command
commands total: 19, succeed: 18, failed: 1, avg. exec time: 22ms
-> 8F 04 00 14 00 6B 5E 0C B5
<- 8F
<- 1A 00 14 00 6B 00 CA CA D2 3A 20 CD E5 E2 E5 F0 ED E0 FF 20 EE EF E5 F0 E0 F6 E8 FF 6E 00
command 6B return code: 0 execution took 1ms
commands total: 20, succeed: 19, failed: 1, avg. exec time: 21ms
FNOperation() fail
ККТ: Неверная операция

**Comment by swex** [comment]
В примеры [добавлен возврат с FNOperation](https://github.com/shtrih-m/fr_drv_ng_examples/blob/master/classic_interface/main.cpp#L261).

**Comment by try2bajed1** [comment]
спасибо, пример помог.
