### ISSUE TITLE
Теряется связь при открытии чека

### ISSUE THREAD

**Issue by YaNokk** [shtrih-m/fr_drv_ng#200]
Здравствуйте, по какой-то причине не проходит OpenCheck, начинается обмен с ОФД, после чего отваливается соединение с -1 ошибкой, если открыть чек из закрытой смены, то открывается только смена, но не чек. Подключение по v2 протоколу с увеличенной задержкой. Пробовал через тест драйвер и обертку, но результат везде один. Открытия, закрытия смен в свою очередь нормально проходят и отправляются в офд.

Версия драйвера:

Версия : 5
Подверсия : 16
Релиз : 0
Сборка : 877
Полная версия : 5.16.0.877

[Логи драйвера.log](https://github.com/shtrih-m/fr_drv_ng/files/8976039/default.log)
[Логи обертки.log](https://github.com/shtrih-m/fr_drv_ng/files/8976047/default.log)

**Comment by olefard** [comment]
Попробуйте обновить прошивку штрих-нано.

**Comment by YaNokk** [comment]
Спасибо!
