### ISSUE TITLE
Http API

### ISSUE THREAD

**Issue by mishunn** [shtrih-m/fr_drv_ng#204]
Добрый день.

Вы упомянули об идее создать JSON API для всех команд в https://github.com/shtrih-m/fr_drv_ng/issues/198.

У нас есть задача заинтегрировать штрих с Python на Ubuntu. Было бы очень классно иметь для её решения http/websocket API.

Подскажите, когда можно ожидать релиза?
Где можно посмотреть список команд с параметрами?

**Comment by swex** [comment]
Добрый, бета готова, сейчас решаем проблемы со сборками под различные платформы, у нас их много... думаю еще день и выложим.  Все функции и свойства и справку по ним можно посмотреть в `classic_interface.h` внутри сборок.

**Comment by swex** [comment]
пример "как будет"
```python3
#!/bin/python3
import asyncio
from jsonrpc_websocket import Server
import base64

#create instance with http POST like: curl -vvv -X POST http://localhost:8888/classic/{devicename}
#in example below used classic_test device name...

async def routine():
    server = Server('ws://localhost:8888/classic/classic_test')

    try:
        await server.ws_connect()

        await server.Set_ConnectionURI("tcp://localhost:7778")
        typez = await server.Get_ConnectionType()
        print(typez)
        ret = await server.Connect()
        code = await server.Get_ResultCode()

        code_description = await server.Get_ResultCodeDescription()
        some_binary_data = base64.b64encode(b'kinda binary')
        await server.Set_BlockData(some_binary_data)
        print(code, code_description)

    finally:
        await server.close()

asyncio.get_event_loop().run_until_complete(routine())

```

**Comment by swex** [comment]
[fr_drv_ng_linux_i486_ok_1.5.0-56-gb71c7d6.zip](https://github.com/shtrih-m/fr_drv_ng/files/9054952/fr_drv_ng_linux_i486_ok_1.5.0-56-gb71c7d6.zip)
[fr_drv_ng_linux_x86_64_1.5.0-56-gb71c7d6.zip](https://github.com/shtrih-m/fr_drv_ng/files/9054964/fr_drv_ng_linux_x86_64_1.5.0-56-gb71c7d6.zip)
[fr_drv_ng_windows_i386_1.5.0-56-gb71c7d6.zip](https://github.com/shtrih-m/fr_drv_ng/files/9054982/fr_drv_ng_windows_i386_1.5.0-56-gb71c7d6.zip)
[fr_drv_ng_windows_x86_64_1.5.0-56-gb71c7d6.zip](https://github.com/shtrih-m/fr_drv_ng/files/9054994/fr_drv_ng_windows_x86_64_1.5.0-56-gb71c7d6.zip)
[fr_drv_ng_darwin_x86_64_1.5.0-56-gb71c7d6.zip](https://github.com/shtrih-m/fr_drv_ng/files/9055003/fr_drv_ng_darwin_x86_64_1.5.0-56-gb71c7d6.zip)
[fr_drv_ng_linux_i686_1.5.0-56-gb71c7d6.zip](https://github.com/shtrih-m/fr_drv_ng/files/9055025/fr_drv_ng_linux_i686_1.5.0-56-gb71c7d6.zip)
[fr_drv_ng_linux_i486_1.5.0-56-gb71c7d6.zip](https://github.com/shtrih-m/fr_drv_ng/files/9055027/fr_drv_ng_linux_i486_1.5.0-56-gb71c7d6.zip)

Пока не релиз, функционально ничего не поменялось, только поддержка json-rpc.
Сам экземпляр classic драйвера живет вне websocket сессии, работа предполагается такая:
```bash
# для отладки чтобы лог в консоль
export FR_DRV_DEBUG_CONSOLE=1
# запускаем json-rpc сервер, console_test теперь зависит от библиотеки classic_fr_drv_ng, нужно положить ее рядом.
console_test_fr_drv_ng run-ws-json-rpc-server 0.0.0.0:8888
export CLASSIC_INSTANCE_NAME="kkt_device_1"
curl -vvv -X POST "http://localhost:8888/classic/$CLASSIC_INSTANCE_NAME"
# должен быть ответ 201 Created если всё ок
# здесь можно соединяться по ws://localhost:8888/classic/$CLASSIC_INSTANCE_NAME
# мы тестировали через python и websocat

# можно удалить инстанс или убить "службу console_test"
curl -vvv -X DELETE "http://localhost:8888/classic/$CLASSIC_INSTANCE_NAME"
```

**Comment by mejgun** [comment]
@swex спасибо. работает)

вчера не получалось. потом понял что в стандартной библиотеке go json-rpc версии 1.0. написал запросы руками, всё заработало.

сервер никаких сообщений самостоятельно не посылает? только ответы на запросы?

**Comment by swex** [comment]
@mejgun нет не посылает, в jsonrpc такого механизма не предусмотрено

**Comment by mejgun** [comment]
@swex это хорошо) спасибо

**Comment by mejgun** [comment]
методы [GetECRStatus](https://github.com/shtrih-m/fr_drv_ng/wiki/Methods#group___base_methods_1ga31aa02120c0f37c11cb49a130f8cbccc), GetShortECRStatus, GetDeviceMetrics возвращают ошибку 
"Method not found", что-то не так делаю? вызываю без параметров, перед этим вызываю Set_Password

**Comment by swex** [comment]
сразу не скажу, покажите отсылаемый json.

**Comment by mejgun** [comment]
```json
{"jsonrpc":"2.0","method":"GetDeviceMetrics","params":null,"id":0}              
{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":0}   

{"jsonrpc":"2.0","method":"Get_CapGetShortECRStatus","params":null,"id":0}      
{"jsonrpc":"2.0","result":true,"id":0}                                          

{"jsonrpc":"2.0","method":"GetECRStatus","params":null,"id":0}                  
{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":0}   

{"jsonrpc":"2.0","method":"GetShortECRStatus","params":null,"id":0}             
{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":0}   
```

**Comment by swex** [comment]
Да, была такая проблема, в след. сборке уже поправлено
[fr_drv_ng_linux_i686_1.5.0-57-g71eca03.zip](https://github.com/shtrih-m/fr_drv_ng/files/9065944/fr_drv_ng_linux_i686_1.5.0-57-g71eca03.zip)
[fr_drv_ng_linux_x86_64_1.5.0-57-g71eca03.zip](https://github.com/shtrih-m/fr_drv_ng/files/9065945/fr_drv_ng_linux_x86_64_1.5.0-57-g71eca03.zip)
[fr_drv_ng_windows_i386_1.5.0-57-g71eca03.zip](https://github.com/shtrih-m/fr_drv_ng/files/9065946/fr_drv_ng_windows_i386_1.5.0-57-g71eca03.zip)
[fr_drv_ng_windows_x86_64_1.5.0-57-g71eca03.zip](https://github.com/shtrih-m/fr_drv_ng/files/9065947/fr_drv_ng_windows_x86_64_1.5.0-57-g71eca03.zip)
[fr_drv_ng_darwin_x86_64_1.5.0-57-g71eca03.zip](https://github.com/shtrih-m/fr_drv_ng/files/9065948/fr_drv_ng_darwin_x86_64_1.5.0-57-g71eca03.zip)

**Comment by mejgun** [comment]
ого) спасибо

**Comment by mishunn** [comment]
Добрый день, установили версию 1.5.0

Из консоли касса печатает и текстовую строку и отчет.
Единственно, на команду:

> console_test_fr_drv_ng-1.5 fs-calculation-report -a 'serial://ttyS0?timeout=100&baudrate=115200' -p 30

выдается ошибка: "Ошибка ввода вывода".

После запуска rpc-server, соединение проходит, но печать текста и печать отчета не работает.

{"jsonrpc": "2.0", "method": "PrintString", "params": {"StringForPrinting": "hello"}, "id": "3bdf1f55-64d6-4729-a164-71927b3bfbf5"}
{"jsonrpc":"2.0","result":0,"id":"3bdf1f55-64d6-4729-a164-71927b3bfbf5"}
и печатается пустая строка

{"jsonrpc": "2.0", "method": "PrintReportWithoutCleaning", "params": {}, "id": "80891ef8-e2a4-4fc3-9429-277c7f948f81"}
{"jsonrpc":"2.0","result":79,"id":"80891ef8-e2a4-4fc3-9429-277c7f948f81"}

{"jsonrpc": "2.0", "method": "FNBuildCalculationStateReport", "params": {"Password": 30}, "id": "5d30c6f4-ab75-4355-9b6d-901d8f5b2667"}
{"jsonrpc":"2.0","result":79,"id":"5d30c6f4-ab75-4355-9b6d-901d8f5b2667"}

**Comment by swex** [comment]
выложил релиз 1.6.0, в нем втч добавлена поддержка вызовов с именованными параметрами. см. [readme](https://github.com/shtrih-m/fr_drv_ng_examples/tree/master/classic_jsonrpc)
```json
{"jsonrpc": "2.0", "method": "PrintString", "params": {"StringForPrinting": "hello"}, "id": "3bdf1f55-64d6-4729-a164-71927b3bfbf5"}
```
PS: json-rpc все еще "бета" как всегда возможны проблемы

**Comment by mishunn** [comment]
Большое спасибо, количество кода уменьшилось в разы. 

Сейчас при попытке закрытия чека, сервис падает.

```
{"jsonrpc": "2.0", "method": "OpenCheck", "params": {"CheckType": 0, "Password": 30}, "id": "6008ce55-d519-4b47-b039-34dc9666eb28"}
{"jsonrpc":"2.0","result":{"OperatorNumber":30,"ResultCode":0,"ResultCodeDescription":"Ошибок нет"},"id":"6008ce55-d519-4b47-b039-34dc9666eb28"}

{"jsonrpc": "2.0", "method": "FNOperation", "params": {"Price": 100, "Quantity": 1.0, "StringForPrinting": "\u041a\u043e\u043c\u043f\u043b\u0435\u043a\u0441\u043d\u044b\u0439 \u043e\u0431\u0435\u0434", "Summ1Enabled": 1, "Summ1": 100, "TaxValueEnabled": 1, "Tax1": 1, "TaxValue": 20, "Password": 30, "CheckType": 1}, "id": "87bb3db9-d95e-4dd7-9f33-c130b0dea554"}
{"jsonrpc":"2.0","result":{"ResultCode":0,"ResultCodeDescription":"Ошибок нет"},"id":"87bb3db9-d95e-4dd7-9f33-c130b0dea554"}

 {"jsonrpc": "2.0", "method": "FNCloseCheckEx", "params": {"Summ1": 100, "TaxType": 1, "TaxValue1": 20, "Password": 30, "RoundingSumm": 0}, "id": "f66ae3d8-d742-401d-a737-8609d9d03951"}
```

Ответе нет, сервис падает, в логах "Ошибка сегментирования (стек памяти сброшен на диск)"

```
[2022-07-25 16:18:06.759] [6246] [ws_rpc_session_0x1b5efb0        ] [T] on_read got <- text message: {"jsonrpc": "2.0", "method": "FNCloseCheckEx", "params": {"Summ1": 100, "TaxType": 1, "TaxValue1": 20, "Password": 30, "RoundingSumm": 0}, "id": "f66ae3d8-d742-401d-a737-8609d9d03951"}
[2022-07-25 16:18:06.759] [6249] [ws_rpc_session_0x1b5efb0        ] [T] about to call single rpc
[2022-07-25 16:18:06.759] [6249] [ci_kkt_device_1                 ] [T] Set_Summ1(`100`)
[2022-07-25 16:18:06.759] [6249] [ci_kkt_device_1                 ] [T] Set_Summ1() ok
[2022-07-25 16:18:06.759] [6249] [ci_kkt_device_1                 ] [T] Set_TaxType(`1`)
[2022-07-25 16:18:06.760] [6249] [ci_kkt_device_1                 ] [T] Set_TaxType() ok
Ошибка сегментирования (стек памяти сброшен на диск)
```

**Comment by mishunn** [comment]
И еще беда - 1.6 не билдится. 

```
running build
running build_ext
building '_fr_drv_ng' extension
swigging classic_interface.i to classic_interface_wrap.cpp
swig -python -module fr_drv_ng -c++ -modern -modernargs -builtin -o classic_interface_wrap.cpp classic_interface.i
creating build/temp.linux-x86_64-3.6
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I. -I/usr/include/python3.6m -c classic_interface_wrap.cpp -o build/temp.linux-x86_64-3.6/classic_interface_wrap.o
classic_interface_wrap.cpp: In function ‘PyObject* _wrap_classic_interface_FontHashHex_set(PyObject*, PyObject*)’:
classic_interface_wrap.cpp:8269:63: error: ‘class classic_interface’ has no member named ‘Set_FontHashHex’; did you mean ‘Get_FontHashHex’?
 #define classic_interface_FontHashHex_set(self_, val_) self_->Set_FontHashHex(val_)
                                                               ^
classic_interface_wrap.cpp:52837:3: note: in expansion of macro ‘classic_interface_FontHashHex_set’
   classic_interface_FontHashHex_set(arg1,(std::string const &)*arg2);
   ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

```

**Comment by swex** [comment]
> Большое спасибо, количество кода уменьшилось в разы.
> 
> Сейчас при попытке закрытия чека, сервис падает.
> 
> ```
> {"jsonrpc": "2.0", "method": "OpenCheck", "params": {"CheckType": 0, "Password": 30}, "id": "6008ce55-d519-4b47-b039-34dc9666eb28"}
> {"jsonrpc":"2.0","result":{"OperatorNumber":30,"ResultCode":0,"ResultCodeDescription":"Ошибок нет"},"id":"6008ce55-d519-4b47-b039-34dc9666eb28"}
> 
> {"jsonrpc": "2.0", "method": "FNOperation", "params": {"Price": 100, "Quantity": 1.0, "StringForPrinting": "\u041a\u043e\u043c\u043f\u043b\u0435\u043a\u0441\u043d\u044b\u0439 \u043e\u0431\u0435\u0434", "Summ1Enabled": 1, "Summ1": 100, "TaxValueEnabled": 1, "Tax1": 1, "TaxValue": 20, "Password": 30, "CheckType": 1}, "id": "87bb3db9-d95e-4dd7-9f33-c130b0dea554"}
> {"jsonrpc":"2.0","result":{"ResultCode":0,"ResultCodeDescription":"Ошибок нет"},"id":"87bb3db9-d95e-4dd7-9f33-c130b0dea554"}
> 
>  {"jsonrpc": "2.0", "method": "FNCloseCheckEx", "params": {"Summ1": 100, "TaxType": 1, "TaxValue1": 20, "Password": 30, "RoundingSumm": 0}, "id": "f66ae3d8-d742-401d-a737-8609d9d03951"}
> ```
> 
> Ответе нет, сервис падает, в логах "Ошибка сегментирования (стек памяти сброшен на диск)"
> 
> ```
> [2022-07-25 16:18:06.759] [6246] [ws_rpc_session_0x1b5efb0        ] [T] on_read got <- text message: {"jsonrpc": "2.0", "method": "FNCloseCheckEx", "params": {"Summ1": 100, "TaxType": 1, "TaxValue1": 20, "Password": 30, "RoundingSumm": 0}, "id": "f66ae3d8-d742-401d-a737-8609d9d03951"}
> [2022-07-25 16:18:06.759] [6249] [ws_rpc_session_0x1b5efb0        ] [T] about to call single rpc
> [2022-07-25 16:18:06.759] [6249] [ci_kkt_device_1                 ] [T] Set_Summ1(`100`)
> [2022-07-25 16:18:06.759] [6249] [ci_kkt_device_1                 ] [T] Set_Summ1() ok
> [2022-07-25 16:18:06.759] [6249] [ci_kkt_device_1                 ] [T] Set_TaxType(`1`)
> [2022-07-25 16:18:06.760] [6249] [ci_kkt_device_1                 ] [T] Set_TaxType() ok
> Ошибка сегментирования (стек памяти сброшен на диск)
> ```

да, это поправлено

**Comment by swex** [comment]
> И еще беда - 1.6 не билдится.
> 
> ```
> running build
> running build_ext
> building '_fr_drv_ng' extension
> swigging classic_interface.i to classic_interface_wrap.cpp
> swig -python -module fr_drv_ng -c++ -modern -modernargs -builtin -o classic_interface_wrap.cpp classic_interface.i
> creating build/temp.linux-x86_64-3.6
> x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I. -I/usr/include/python3.6m -c classic_interface_wrap.cpp -o build/temp.linux-x86_64-3.6/classic_interface_wrap.o
> classic_interface_wrap.cpp: In function ‘PyObject* _wrap_classic_interface_FontHashHex_set(PyObject*, PyObject*)’:
> classic_interface_wrap.cpp:8269:63: error: ‘class classic_interface’ has no member named ‘Set_FontHashHex’; did you mean ‘Get_FontHashHex’?
>  #define classic_interface_FontHashHex_set(self_, val_) self_->Set_FontHashHex(val_)
>                                                                ^
> classic_interface_wrap.cpp:52837:3: note: in expansion of macro ‘classic_interface_FontHashHex_set’
>    classic_interface_FontHashHex_set(arg1,(std::string const &)*arg2);
>    ^
> error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
> ```

это тоже поправлено,будет в релизе

**Comment by swex** [comment]
можно забрать [1.6.0-1-gd46012a](https://github.com/shtrih-m/fr_drv_ng/releases/tag/1.6.0-1-gd46012a) эту тему закрываю, лучше создавать новую тему под каждый вопрос/баг
