### ISSUE TITLE
печать x-отчета ФФД1.2

### ISSUE THREAD

**Issue by ConsperSerj** [shtrih-m/fr_drv_ng#205]
Добрый день. На ффд 1.2 пытаюсь выполнить команду

PrintReportWithoutCleaning

Получаю ошибку 
Код ошибки 37h (55) от ККТ: Команда не поддерживается в данной реализации или при данных настройках {команда ФН 46h}

Подскажите пожалуйста как выполнить печать отчета без гашения?

**Comment by swex** [comment]
В законодательстве уже давно нет такого документа. Соотв. не все реализации поддерживают его. Самое близкое что есть - это формирование "отчета о состоянии расчетов"  см. `FNBuildCalculationStateReport`

**Comment by ConsperSerj** [comment]
@swex Подскажите пожалуйста а возможно ли какой то командой определить версиию ФФД для того чтобы для разных версий вызывать нужную функцию для ответа?

**Comment by swex** [comment]
> @swex Подскажите пожалуйста а возможно ли какой то командой определить версиию ФФД для того чтобы для разных версий вызывать нужную функцию для ответа?

https://github.com/shtrih-m/fr_drv_ng_examples/blob/master/classic_interface/main.cpp#L61=
