### ISSUE TITLE
Тэг 2108

### ISSUE THREAD

**Issue by ConsperSerj** [shtrih-m/fr_drv_ng#207]
Добрый день. На ФФД 1.2 провожу регистрацию чека. передаю меру исчесления тег 2108 например "кг.". На чеке он распечатался, но вот в выходных параметрах он отсутствует у позиций. Я про вывод который получается через 
Get_DocumentType
Get_StringForPrinting

Подскажите пожалуйста как его получить?

**Comment by swex** [comment]
Добрый день. Не пойму что пытаетесь получить, но для визуальной валидации можно, например, получить TLV документа в виде строки методом `FNGetDocumentAsString`

**Comment by ConsperSerj** [comment]
@swex  Ну вот когда получаю TLV документ, то в нем отсутствует тег 2108 для позиций

**Comment by ConsperSerj** [comment]
`КАССОВЫЙ ЧЕК
    1209,ВЕРСИЯ ФФД:1.2
    1041,НОМЕР ФН:9999078902012392
    1037,РЕГ. НОМЕР ККТ:1234567890041654    
    1018,ИНН ПОЛЬЗ.:7729724371  
    1040,НОМЕР ФД:17
    1012,ДАТА, ВРЕМЯ:21.07.2022 14:15:00
    1077,ФП ДОКУМЕНТА:2934697219
    1038,НОМЕР СМЕНЫ:3
    1042,НОМЕР ЧЕКА ЗА СМЕНУ:3
    1054,ПРИЗН. РАСЧЕТА:Приход
    1020,СУММА РАСЧЕТА В ЧЕКЕ(БСО):30.00 rub.
    1021,КАССИР:test user
    1059,ПРЕДМ. РАСЧЕТА
     1222,ПРИЗН. АГ. ПО ПРЕДМ. РАСЧ:1
     1223,ДАННЫЕ АГЕНТА
      1026,НАИМЕН. ОПЕР. ПЕРЕВОДА:transferOperatorName
      1005,АДР. ОПЕР. ПЕРЕВОДА:transferOperatorAddress
      1044,ОПЕРАЦИЯ ПЛАТ. АГЕНТА:payingAgent
      1016,ИНН ОПЕРАТОРА ПЕРЕВОДА:7704211201  
      1073,ТЕЛ. ПЛАТ. АГЕНТА:+79645678090
      1074,ТЕЛ ОПЕР. ПО ПРИЕМУ ПЛАТЕЖЕЙ:+79645678091
      1075,ТЕЛ. ОПЕР. ПЕРЕВОДА:+79645678089
     1224,ДАННЫЕ ПОСТАВЩИКА
      1225,НАИМЕН. ПОСТАВЩИКА:supplierName
      1171,ТЕЛ. ПОСТАВЩИКА:+79645999999
     1226,ИНН ПОСТАВЩИКА:7704211201  
     1230,КОД СТРАНЫ ПРОИСХ.:RUS
     1231,НОМЕР ТАМОЖ. ДЕКЛ.:12
     1198,РАЗМ. НДС ЗА ЕД. ПРЕДМ. РАСЧ.:0.00 rub.
     1030,НАИМЕН. ПРЕДМ. РАСЧЕТА:Корзиночки
     1191,ДОП. РЕКВ. ПРЕДМ. РАСЧЕТА:additionalAttribute
     1079,ЦЕНА ЗА ЕД. ПРЕДМ. РАСЧ.:15.00 rub.
     1023,КОЛ-ВО ПРЕДМ. РАСЧЕТА:2
     1043,СТОИМ. ПРЕДМ. РАСЧЕТА:30.00 rub.
     1199,СТАВКА НДС:5
     1200,СУММА НДС ЗА ПРЕДМ. РАСЧ.:0.00 rub.
     1214,ПРИЗН. СПОСОБА РАСЧ.:4
     1212,ПРИЗН. ПРЕДМЕТА РАСЧ.:1
    1055,ПРИМЕН. СИСТ. НАЛОГООБЛОЖЕНИЯ:ОСН
    1203,ИНН КАССИРА:250813181110
    1008,ТЕЛ. ИЛИ EMAIL ПОКУПАТЕЛЯ:ТЕЛ. ПОКУПАТЕЛЯ: +79645678067
    1104,СУММА РАСЧ. ПО ЧЕКУ 0%:30.00 rub.
    1031,СУММА ПО ЧЕКУ НАЛ (БСО):0.00 rub.
    1081,СУММА ПО ЧЕКУ ЭЛЕКТРОННЫМИ(БСО):30.00 rub.
    1215,СУММА ПО ЧЕКУ БСО ПРЕДОПЛ.:0.00 rub.
    1216,СУММА ПО ЧЕКУ БСО ПОСТОПЛ.:0.00 rub.
    1217,СУММА ПО ЧЕКУ БСО ВСТРЕЧН. ПРЕДОСТ.:0.00 rub.
    1117,ЭЛ.АДР.ОТПРАВИТЕЛЯ:test@taxcom.ru
    1192,ДОП. РЕКВ. ЧЕКА БСО:additionalReceip
    1009,АДР.РАСЧЕТОВ:Гомель
    1187,МЕСТО РАСЧЕТОВ:Гомель
    1084,ДОП. РЕКВИЗИТ ПОЛЬЗОВ.
     1085,НАИМЕН. ДОП. РЕКВИЗИТ. ПОЛЬЗОВ.:AttributeName
     1086,ЗНАЧ. ДОП. РЕКВИЗИТ. ПОЛЬЗОВ.:AttributeValue
    1256,СВЕД. О ПОКУПАТ.
     1227,ПОЛУЧАТЕЛЬ: 
     1243,ДР ПОКУПАТЕЛЯ:21.07.2022
     1245,КОД ВИДА ДОК. УДОСТ. ЛИЧН.:21                              
     1246,ДАННЫЕ ДОК. УДОСТ. ЛИЧН.:IdentityDocumentData
    1261,ОТРАСЛ. РЕКВ. ЧЕКА
     1262,ИД. ФОИВ:59
     1263,ДАТА ДОК. ОСН.:21.07.2022
     1264,НОМЕР ДОК. ОСН.:1
     1265,ЗНАЧ. ОТР. РЕКВ.:bbb`

**Comment by ConsperSerj** [comment]
Вот ответ о документе. Но там нет 2108 тега

**Comment by asem-m** [comment]
Вы используете ФР или КЯ?

**Comment by swex** [comment]
как передаете тег? через `MeasureUnit`? Покажите лог регистрации

**Comment by ConsperSerj** [comment]
Пытался передавать через   Set_MeasureUnit(it.code)
Так же через sendTagOperation(2108, it.code)
Результат один и тот же.

По логе я вижу что параметр принялся и при закрытии чека на этот тег не отругивает
@swex

**Comment by swex** [comment]
покажите лог чтобы мы тоже посмотрели... и какой у вас девайс?

**Comment by ConsperSerj** [comment]
Девайс Пакс 930. Логу завтра с утра скину. Для двух команд

**Comment by asem-m** [comment]
Обновите КЯ на 1.14 сборку.

**Comment by ConsperSerj** [comment]
> Обновите КЯ на 1.14 сборку.

Хорошо

**Comment by ConsperSerj** [comment]
Доброе  утро. Обновление КЯ до версии 1.14 помогло. Спасибо за помощь
