### ISSUE TITLE
Ошибка -8 и ошибка 51 при попытке напечатать из проекта-примера для драйвера на андроид

### ISSUE THREAD

**Issue by try2bajed1** [shtrih-m/fr_drv_ng#208]
Устройство pax a930. Зарегистрировал новый фн. Выставил флаги для работы с маркированной продукциией + работа с подакцизами. При попытке распечатать тестовый чек первый раз получаю 
 https://gist.github.com/try2bajed1/a88e8147d869a047712389b236308870 ошибка -8
 
 если кликнуть по кнопке снова(которая вызывает печать тест. чека) уже друга ошиибка
 https://gist.github.com/try2bajed1/39b0eff5f71434fd8efdb6a1fcc20727 ошибка 51
 
 Подскажите, проблема в коде или как-то некорректо настроен девайс?

**Comment by surfernsk** [comment]
ФФД 1.2?? - [код примера из документации](https://github.com/shtrih-m/fr_drv_ng_examples/blob/6584bba935b8abeac560597eda1400343cc59b5e/classic_interface/main.cpp#L491)

**Comment by asem-m** [comment]
ФФД 1.05 или ФФД 1.2?

**Comment by asem-m** [comment]
если ФФД 1.2, то тег 1162 нельзя передавать в чек

**Comment by swex** [comment]
[Здесь](https://exam.shtrih-m-partners.ru/base/) "Общее для всех моделей ККТ" -> "Дополнительно" и там можно найти много полезной информации в т.ч. [Порядок действий при работе с кодами маркировки (ФФД 1.2) (ZIP, 902.14 kB)](https://exam.shtrih-m-partners.ru/assets/materials/Instructions_working_KM.zip)

**Comment by asem-m** [comment]
Раздел "Рекомендации по использованию КЯ в режиме ФФД 1.2" в `changelog.txt`
