### ISSUE TITLE
поля Адрес Организации,Наименование Организации,Место расчетов после Фискализации\Перерегистрации

### ISSUE THREAD

**Issue by Commander4ek** [shtrih-m/fr_drv_ng#209]
Доброго времени суток, возможно не достаточно внимательно искал в Wiki, но не смог найти поля, указанные в теме, буду рад помощи, заранее спасибо

**Comment by surfernsk** [comment]
Добрый. Рекомендую ознакомиться с [Руководство по настройке ККТ 25.05.2022](http://doc.shtrih-m.ru/Files/manual.pdf)
Особенно с Таблицей 18.

**Comment by Commander4ek** [comment]
Добрый день, большое спасибо за ответ, ознакомился с документацией, понял основную суть, но на текущий момент в classic_interface.h по документации в Wiki я обнаружил лишь методы отправки данных в ОФД по тегам, мне нужна обратная операция, запроса регистрационных данных по тегам согласно таблице 18, что то вроде 
driver.GetRegistrationParameter("номер последней регистрации в ОФД", "номер тега, например ,1062") 
и чтобы мне в ответ осуществлялась модификация значение тега, его свойства и чтобы я его мог забирать через getter() для своей реализации

**Comment by surfernsk** [comment]
@Commander4ek  Добрый вечер. читайте данные из таблицы [ReadTable](https://github.com/shtrih-m/fr_drv_ng/wiki/Methods#group___base_methods_1ga892e4751efdb0742f50ffa2482f60729)

**Comment by Commander4ek** [comment]
я правильно понимаю что свойства

[TableNumber](https://github.com/shtrih-m/fr_drv_ng/wiki/Properties#group___properties_1gad68b86360e0bb5c873486657593dc0d2) - номер таблицы,

[RowNumber](https://github.com/shtrih-m/fr_drv_ng/wiki/Properties#group___properties_1gac048d4ec406d94f795937f6c98cef123) - номер ряда,

[FieldNumber](https://github.com/shtrih-m/fr_drv_ng/wiki/Properties#group___properties_1ga4cb689bda2268d0f61303793ed83d373) - номер поля.

берутся из [Руководство по настройке ККТ 25.05.2022](http://doc.shtrih-m.ru/Files/manual.pdf)?????

**Comment by surfernsk** [comment]
Совершенно верно, не забудьте убедится в каком состоянии находиться ФН - Фаза жизни ([FNGetStatus](https://github.com/shtrih-m/fr_drv_ng/wiki/Methods#group___base_methods_1ga418dd0cce3e90b2749015b64a0375bb9)())
Может ФН еще не зарегистрирован.
![Screenshot_20220812_214417](https://user-images.githubusercontent.com/2264893/184379937-8b5342cc-6be9-4225-a61c-bdb414f3f641.png)

**Comment by Commander4ek** [comment]
огромное спасибо, а нет еще в драйвере какого то синтаксического сахара, что то вроде enum???
чтобы не писать что-то вроде
driver.set_TableNumber(18)
driver.set_TableRow(1)
driver.set_TableColumn(1)
driver.readTable()

**Comment by swex** [comment]
есть несколько реализаций ККТ в них, в том числе отличаются таблицы. Необходимо смотреть документацию с описанием полей под свою модель ККТ. Поэтому такого сахара нет.

**Comment by Commander4ek** [comment]
также хотелось бы уточнить а как получить Максимальную поддерживаемую версию ФФД в ККТ, а также Макс версию ФФД в ФН, посмотрел по истории вопросов вроде как не не было такого еще???

**Comment by asem-m** [comment]
для КЯ можно узнать из таблицы:
Т10П38 "*ФН 3AH: ТЕК.ФФД: 0=НЕФИСК.,1=1.05,4=1.2" - текущий
Т10П43 "*ФН 3AH: МАКС. КОД ВЕРСИИ ФФД: 4=1.2" - максимальный

**Comment by asem-m** [comment]
для ККТ для КЯ:
Т10П29 "1209: ФФД, 0: 1.0 (N/A), 2: 1.05, 4: 1.2" по максимально возможному значению поля

**Comment by Commander4ek** [comment]
понял, спасибо

**Comment by Commander4ek** [comment]
добрый вечер, возник еще вопрос, чтобы не создавать большое количество тем, пишу сюда,  есть ли возможность у драйвера распечатать технический отчет, на некоторых кассах это называется отчет автотестирования?
