### ISSUE TITLE
20% ндс

### ISSUE THREAD

**Issue by try2bajed1** [shtrih-m/fr_drv_ng#21]
Есть ли на сегодняшний момент возможность выставлять для продукта 20% ндс. Если можно, то какое значение передавать в Set_Tax1() ?

**Comment by swex** [comment]
Все налоги можно посмотреть в таблице 6: "Налоговые ставки". На некоторых моделях можно поменять. В Set_Tax1 передавать соответствующий индекс из этой таблицы.

**Comment by try2bajed1** [comment]
А не подскажете, где брать актуальную документацию (пдф ворд итп) ?
у меня есть пдф "драйвер фр версии 4.8" 
![_034](https://user-images.githubusercontent.com/878652/48896329-6db65a00-ee58-11e8-87d9-59ee88f4c4fa.png)
там про 20% ндс ничего нет. Может быть есть доки поновее?

**Comment by swex** [comment]
кажется [вот](https://github.com/shtrih-m/fr_drv_ng/files/2607713/_4.14.pdf) актуальная версия pdf. Справку по реализованным методам нужно смотреть в classic_interface.h
