### ISSUE TITLE
-9 ошибка при вызове метода FNOperation()

### ISSUE THREAD

**Issue by Commander4ek** [shtrih-m/fr_drv_ng#211]
при вызове метода печати чека в конечном итоге вылетает 94 ошибка Закрытие чека без позиций

ЛОГИ:

D [INPAS_PAX]: <InpasPax::printPurchase> start
D [INPAS_PAX]: <InpasPax::readIsDocOpened> start
D [INPAS_PAX]: <InpasPax::readIsDocOpened> ECR STATUS 8
D [INPAS_PAX]: <InpasPax::cancelDoc> start
D [INPAS_PAX]: <InpasPax::checkResult> checkResult error code:  0
D [INPAS_PAX]: <InpasPax::cancelDoc> success
D [INPAS_PAX]: <InpasPax::printPurchase>  PURCHASE_TYPE_INPAS_SELL
D [INPAS_PAX]: <InpasPax::checkResult> checkResult error code:  0
D [INPAS_PAX]: <InpasPax::printPurchase> OpenCheck() CHECK OPENED
D [INPAS_PAX]: <InpasPax::printPurchase> Set_TaxType():  1
D [INPAS_PAX]: <InpasPax::printPurchase> Is countable:  yes ///штучный товар
D [INPAS_PAX]: <InpasPax::printPurchase> Set_Quantity :  1
D [INPAS_PAX]: <InpasPax::printPurchase> Set_CheckType :  0
D [INPAS_PAX]: <InpasPax::printPurchase> Set_Price :  10000
D [INPAS_PAX]: <InpasPax::printPurchase> Set_Tax1  0
D [INPAS_PAX]: <InpasPax::printPurchase> Set_MeasureUnit :  0
D [INPAS_PAX]: <InpasPax::printPurchase> Set_Department :  1
D [INPAS_PAX]: <InpasPax::printPurchase> Set_Summ1Enabled(false)
D [INPAS_PAX]: <InpasPax::printPurchase> Set_PaymentTypeSign(4)
D [INPAS_PAX]: <InpasPax::printPurchase> Set_PaymentItemSign(1)
D [INPAS_PAX]: <InpasPax::printPurchase> Set_StringForPrinting:  Test
D [INPAS_PAX]: <InpasPax::printPurchase> Set_DivisionalQuantity(false)
D [INPAS_PAX]: <InpasPax::checkResult> checkResult error code:  -9 ///тут вызов FNOperation()
D [INPAS_PAX]: <InpasPax::printPurchase> PAYMENT_CASH:  100
E [INPAS_PAX]: <InpasPax::printPurchase> TOTALE PRICE  =  100 TOTALE CASH  =  100 TOTALE CHANGE  =  0
D [INPAS_PAX]: <InpasPax::checkResult> checkResult error code:  94
D [INPAS_PAX]: <InpasPax::setLastErrMsg> start
D [INPAS_PAX]: <InpasPax::setLastErrMsg> lastErrMsg:  "Код ошибки 5Eh (94) от ККТ: Неверная операция <0x005E0033: закрытие чека без позиций>"

Можете подсказать что делаю не так?

**Comment by surfernsk** [comment]
@Commander4ek "Код ошибки 5Eh (94) от ККТ: Неверная операция <0x005E0033: закрытие чека без позиций>"
Вроде все в описании ошибки написано.

**Comment by Commander4ek** [comment]
я возможно не до конца понимаю как эту позицию добавить, я так понял, что это делает FNOperation(), предварительно заполнив все свойства, который использует данный метод или я ошибаюсь?

**Comment by swex** [comment]
да, всё так. покажите полный лог от открытия чека до закрытия, можно лог драйвера или лог КЯ.

**Comment by surfernsk** [comment]
@Commander4ek все верно, проверьте что именно передаете в параметрах,

**Comment by Commander4ek** [comment]
разобрался, спасибо, проблема была в том что передаются разные значения в Set_CheckType в OpenCheck и ФН методы
