### ISSUE TITLE
Ошибка при печати баркода на PAX A930

### ISSUE THREAD

**Issue by NovikovRA** [shtrih-m/fr_drv_ng#212]
Добрый день, необходимо распечатать баркод с типом CODE128, при попытке исполнения печати баркода падает ошибка:
Ошибка -9: Ошибок нет

Если печатать баркод с типом EAN-13 - ошибок нет, ошибка падает на устройстве PAX A930, пробовал все три типа CODE128 (значения: 0,1,2) 

### Фрагмент кода
                    driver!!.Set_BarCode("8077354219282")
                    driver!!.Set_LineNumber(75)
                    when(line.type) {
                        BarcodeType.QR -> driver!!.Set_BarcodeType(3)
                        BarcodeType.CODE128 -> driver!!.Set_BarcodeType(0)
                        BarcodeType.EAN13,
                        BarcodeType.EAN8 -> driver!!.Set_BarcodeType(5)
                    }
                    driver!!.Set_BarWidth(3)
                    driver!!.Set_BarcodeAlignment(classic_interface.TBarcodeAlignment.baCenter)
                    driver!!.Set_SwapBytesMode(0)
                    driver!!.Set_LineSwapBytes(false)
                    checkResult(driver!!.PrintBarcodeLine())

**Comment by swex** [comment]
Здесь нужен лог КЯ, а лучше КЯ и драйвера.
