### ISSUE TITLE
логика пробития в чеке при замятии\окончании бумаги в принтере

### ISSUE THREAD

**Issue by Commander4ek** [shtrih-m/fr_drv_ng#213]
хотелось бы уточнить немного логику работы драйвера,

кейс следующий:
мы пытаемся пробить чек прихода
заполняем все поля
 вызывается метод FNCloseCheckEx()
далее я вызываю метод WaitForPrinting() и в зависимости от его кода возврата считаю корректно отработала печать или нет

вопрос в следующем если в процессе печати чека у меня кончается бумага, то согласно документации метод WaitForPrinting() "ККТ ждет команду продолжения печати.Подает команду продолжения печати и возвращается в цикл", соответственно, если я поменяю рулон бумаги и вызову метод печати этого же чека, то у меня распечатается их сразу два одинаковых,

можно ли как то при окончании бумаги отменить печать чека?

пытался вызвать метод SysAdminCancelCheck() если WaitForPrinting() возвращает "нет бумаги" но получаю ошибку -8

заранее спасибо за ответы.

**Comment by olefard** [comment]
Двух одинаковых не будет. Один будет распечатан не до конца, а второй целиком.

> можно ли как то при окончании бумаги отменить печать чека?
Нет. После успешного выполнения FNCloseCheckEx чек закрыт и его никак не отменить.
