### ISSUE TITLE
Получение счетчиков по текущей смене

### ISSUE THREAD

**Issue by Commander4ek** [shtrih-m/fr_drv_ng#215]
Добрый день, необходимо за текущую смену получить сумму продаж по типам платежа и их количество(
наличными,
электронными,
аванс, 
кредит, 
встречное представление)

Также получить количество чеков по разным типам (  
количество чеков продажи,
количество чеков возврата,
количество аннулированных чеков,
количество отложенных чеков,
количество чеков внесения,
количество чеков изъятия)

и получить сумму по следующим типам(
суммы по аннулированным чекам,
суммы по отложенным чекам,
суммы по чекам внесения,
суммы по чекам изъятия)
 
 есть мысли сделать это при помощи кассовых регистров либо при помощи получения данных из отчета без гашения, но очень бы хотелось чтобы меня направили на правильный путь, как это можно сделать проще, заранее спасибо

**Comment by swex** [comment]
Путь с регистрами правильный. Смотрите общее руководство, берите нужные регистры и всё. Почитайте справку по методам: `GetCashReg` и `GetOperationReg`

**Comment by Commander4ek** [comment]
спасибо, помогло, еще возникла проблема
пытаюсь получить текущую версию ФФД, использую код из тестового примера

вот кусок кода который это делает: https://pastebin.com/KqfFvfAT

вот логи, которые выходят
D [INPAS_PAX]: <Shtrih::getCurFfdKktVer> start
D [INPAS_PAX]: <Shtrih::executeAndHandleError> start
D [INPAS_PAX]: <Shtrih::checkResult> checkResult error code:  0
D [INPAS_PAX]: <Shtrih::getCurFfdKktVer> DPE_FFDVersionTableNumber =  0
D [INPAS_PAX]: <Shtrih::executeAndHandleError> start
D [INPAS_PAX]: <Shtrih::checkResult> checkResult error code:  0
D [INPAS_PAX]: <Shtrih::getCurFfdKktVer> DPE_FFDVersionFieldNumber =  0
D [INPAS_PAX]: <Shtrih::executeAndHandleError> start
D [INPAS_PAX]: <Shtrih::checkResult> checkResult error code:  93
D [INPAS_PAX]: <Shtrih::setLastErrMsg> start
D [INPAS_PAX]: <Shtrih::setLastErrMsg> lastErrMsg:  ""
E [INPAS_PAX]: <Shtrih::getCurFfdKktVer> failed!

на принтере PAX A930 данный код отрабатывает отлично
на принтере Штрих-ФР-02Ф вот такая ошибка, заранее спасибо за ответы

**Comment by Commander4ek** [comment]
Согласно документации 

Код ошибки 5Dh  - 93 ККТ Таблица не определена
Вопрос в том почему на мои запросы возвращаются 0

**Comment by surfernsk** [comment]
А какую таблицу читаете на Штрих-ФР-02Ф?

**Comment by Commander4ek** [comment]
Ну технически, если я правильно понимаю работу данного кода, то валидный номер таблицы мне должно дать это свойство, сам номер руками я не ввожу

**Comment by Commander4ek** [comment]
под прошивкой вы имеете в виду версию непосредственно ПО ККТ?
или версию драйвера, которая с ним взаимодействует

**Comment by swex** [comment]
ПО ККТ.

**Comment by Commander4ek** [comment]
с этим разобрался, большое спасибо
возникла еще одна проблема с Чеком коррекции, опять таки делал по примеру, программа не хочет отправлять тег 1177(наименование основания для коррекции)
Выдается следующая ошибка:

D [INPAS_PAX]: <Shtrih::setLastErrMsg> lastErrMsg:  "Код ошибки 33h (51) от ККТ: Некорректные параметры в команде <0x00330023: тег не может быть отправлен в текущий документ ФН {тег 1177}>"

**Comment by Commander4ek** [comment]
сам код который это делает:

m_shtrihDriverInterface->Set_Password(30);
    bool rc  = executeAndHandleError(std::bind(&classic_interface::FNBeginCorrectionReceipt, m_shtrihDriverInterface));
    if(!rc)
    {
        cancelDoc();
        return false;
    }
    //отправка тэгов

       //устанавливаем тег 1177 наименование основания для коррекции
       m_shtrihDriverInterface->Set_TagNumber(1177);
       m_shtrihDriverInterface->Set_TagType(7); //Тип "строка"
       m_shtrihDriverInterface->Set_TagValueStr((EncodeConvertor::CP866toUTF8(correctionData.corReasonName)));
       rc = executeAndHandleError(std::bind(&classic_interface::FNSendTag, m_shtrihDriverInterface));
       if(!rc)
       {
           cancelDoc();
           return false;
       }

**Comment by asem-m** [comment]
> с этим разобрался, большое спасибо возникла еще одна проблема с Чеком коррекции, опять таки делал по примеру, программа не хочет отправлять тег 1177(наименование основания для коррекции) Выдается следующая ошибка:
> 
> D [INPAS_PAX]: Shtrih::setLastErrMsg lastErrMsg: "Код ошибки 33h (51) от ККТ: Некорректные параметры в команде <0x00330023: тег не может быть отправлен в текущий документ ФН {тег 1177}>"

тега 1177 не существует

**Comment by Commander4ek** [comment]
тогда я признаюсь в заблуждении, видимо в примере опечатка 
https://github.com/shtrih-m/fr_drv_ng_examples/blob/master/classic_interface/main.cpp - 1001 строчка

**Comment by asem-m** [comment]
> Добрый день, необходимо за текущую смену получить сумму продаж по типам платежа и их количество( наличными, электронными, аванс, кредит, встречное представление)
> 
> Также получить количество чеков по разным типам ( количество чеков продажи, количество чеков возврата, количество аннулированных чеков, количество отложенных чеков, количество чеков внесения, количество чеков изъятия)
> 
> и получить сумму по следующим типам( суммы по аннулированным чекам, суммы по отложенным чекам, суммы по чекам внесения, суммы по чекам изъятия)
> 
> есть мысли сделать это при помощи кассовых регистров либо при помощи получения данных из отчета без гашения, но очень бы хотелось чтобы меня направили на правильный путь, как это можно сделать проще, заранее спасибо

В режиме ФФД 1.2 для КЯ (PAX) следует читать и использовать расширенные регистры 4291...4353. Например:

 4293.Итоги смены ФН: Кол-во операций с признаком расчета «приход» : 2
 4294.Итоги смены ФН: Итоговая сумма расчета, указанного в чеке (БСО) (приход) : 200,00
 4295.Итоги смены ФН: Итоговая сумма по чекам (БСО) наличными (приход) : 0,00
 4296.Итоги смены ФН: Итоговая сумма по чекам (БСО) электронными (приход) : 80,00
 4297.Итоги смены ФН: Итоговая сумма по чеку (БСО) предоплатой (зачетом аванса) (приход) : 60,00
 4298.Итоги смены ФН: Итоговая сумма по чеку (БСО) постоплатой (в кредит) (приход) : 40,00
 4299.Итоги смены ФН: Итоговая сумма по чеку (БСО) встречным предоставлением (приход) : 20,00

 4293.Итоги смены ФН: Кол-во операций с признаком расчета «приход» : 2
 4306.Итоги смены ФН: Кол-во операций с признаком расчета «возврат прихода» : 0
 4319.Итоги смены ФН: Кол-во операций с признаком расчета «расход» : 0
 4332.Итоги смены ФН: Кол-во операций признака расчета возврат расхода : 0


Нефискальную статистику внесений/выплат, отмен чеков следует вести самостоятельно в Кассовом ПО

**Comment by surfernsk** [comment]
> тогда я признаюсь в заблуждении, видимо в примере опечатка https://github.com/shtrih-m/fr_drv_ng_examples/blob/master/classic_interface/main.cpp - 1001 строчка

«Описание коррекции» (тег 1177) исключен из состава тега 1174 с 01.03.2020

**Comment by Commander4ek** [comment]
тоесть я правильно понимаю что я просто убираю этот фрагмент кода с упоминанием тега 1177, а остальное остается неизменным?

**Comment by asem-m** [comment]
в тесте драйвера ФР (03. ФН чеки (ФФД 1.05-1.2) -> Атрибуты чека/Чек коррекции (ФФД 1.05)) можно поиграться с тегами, чтобы понять как формируется документ в соответствии с ФФД

**Comment by surfernsk** [comment]
> тоесть я правильно понимаю что я просто убираю этот фрагмент кода с упоминанием тега 1177, а остальное остается неизменным?
> 
> или "наименование основания для коррекции" передается каким то иным способом теперь?

https://its.1c.ru/db/kkt/content/78/hdoc
