### ISSUE TITLE
Чек коррекции с позициями ФФД 1.2

### ISSUE THREAD

**Issue by NovikovRA** [shtrih-m/fr_drv_ng#216]
Добрый день, подскажите, пожалуйста, имеется ли поддержка чеков коррекции с добавлением позиций в чек?

**Comment by surfernsk** [comment]
В этом и есть суть чека коррекции при применении ФФД 1.2.Коррекция доп. признак чека.29.08.2022, 16:20, "NovikovRA" ***@***.***>:
Добрый день, подскажите, пожалуйста, имеется ли поддержка чеков коррекции с добавлением позиций в чек?

**Comment by NovikovRA** [comment]
@surfernsk Не совсем корректно сформулировал вопрос, спасибо! Вопрос в том имеется ли поддержка чеков коррекции для ффд 1.2. 
Подходящих методов для данной операции не нашёл

**Comment by surfernsk** [comment]
@NovikovRA 
Методов добавления товарной позиции в чек, и записи тегов вам не достаточно?

**Comment by surfernsk** [comment]
Детальнее- 

1. Открыть чек коррекции
2. добавить позиции
3. Передать тег [1173](http://www.consultant.ru/document/cons_doc_LAW_362322/064e550fd71912fc057974955f776faca9134274/#dst108984) (ТИП КОРРЕКЦИИ) и составной тег [1174](http://www.consultant.ru/document/cons_doc_LAW_362322/e737c782d8feffffb0b923d2986a7fc5aa2e0dd8/) (ОСН. ДЛЯ КОРР.)
Порядок пунктов 2 и 3, вроде не важен

**Comment by NovikovRA** [comment]
> FNOpenCheckCorrection
Подскажите, пожалуйста, источник на который вы ссылаетесь, в скачанной документации по ссылке [https://exam.shtrih-m-partners.ru/assets/materials/DriverKKT_Guide_415_16_11_20_.zip](url) 
сказано, что данный метод - `int FNOpenCheckCorrection();` должен использоваться только для ФФД 1.1
![image](https://user-images.githubusercontent.com/60142222/187199877-53ab1d67-616d-49f6-817a-c59a563f471c.png)

**Comment by surfernsk** [comment]
1. Данный репозиторий - "Кроссплатформенный Драйвер ФР на C++", следовательно обсуждается только работа с этим драйвером. Скрин от документации для драйвера 4.15 под WIN.
2. Использование документации от 2020 года, вы серьезно!? Тогда не было ФФД 1.2 ([Вот ссылка на актуальную документацию](http://doc.shtrih-m.ru/Files/Programmer.pdf)). В принципе api драйвера win и Кроссплатформенного во многом схожи.
3. Документация/описание методов драйвера из этого репозитория, приводится в заголовочном файле classic_interface.h. О чем указанно в репозитории.

В дополнение сслка на полезный ресурс от [штрих-м ](http://doc.shtrih-m.ru/)
