### ISSUE TITLE
сбросить открытый документ

### ISSUE THREAD

**Issue by Commander4ek** [shtrih-m/fr_drv_ng#217]
Добрый вечер, вопрос следующего характера
у меня есть метод который через 
ci->Set_SysAdminPassword()
ci->FNGetStatus()
ci->Get_FNCurrentDocument()
смотрит если ли что то открытое в ФН, мне нужно при наличии документа(Get_FNCurrentDocument вернул не 0) потом вызывать метод, который закрывает все, если этот документ чек, то его можно закрыть через classic_interface::SysAdminCancelCheck, а что делать с остальными???

**Comment by surfernsk** [comment]
О каких других документах идет речь, кроме чека?

**Comment by Commander4ek** [comment]
Например я сейчас пытаюсь сделать регистрацию ФН
у меня после прошлой попытки произошла ошибка, и он( документ регистрации) не закрылся
возвращается 
Код ошибки 5Eh (94) от ККТ: Неверная операция <0x005E000E: в ФН открыт текущий документ 12h \"Отчет об изменении параметров регистрации в связи с заменой ФН\", что не соответствует команде ККТ FF06h>"

логи FNGetStatus()
D [SHTRIH]: <Shtrih::registerFs> FNLifeState 1
D [SHTRIH]: <Shtrih::registerFs> FNCurrentDocument  18
D [SHTRIH]: <Shtrih::registerFs> FNDocumentData  0
D [SHTRIH]: <Shtrih::registerFs> FNSessionState  0
D [SHTRIH]: <Shtrih::registerFs> FNWarningFlags 0

**Comment by Commander4ek** [comment]
это проблему в теме исправило
но код из примера все равно не работает

 //Начать формировать отчет о регистрации ККТ
    ci->Set_ReportTypeInt(1); //Отчет о регистрации КТТ
    executeAndHandleError(std::bind(&classic_interface::FNBeginRegistrationReport, ci));

    //посылаем необходимые теги
    ci->Set_TagNumber(1117); //тэг "адрес электронной почты отправителя чека"
    ci->Set_TagType(7); //Тип "строка"
    ci->Set_TagValueStr("example@example.org");
    executeAndHandleError(std::bind(&classic_interface::FNSendTag, ci));

    //Сформировать отчет о регистрации ККТ
    ci->Set_INN("000000000000");
    ci->Set_KKTRegistrationNumber("0000000837030527");
    ci->Set_TaxType(32); //система налогообложения - ПСН
    ci->Set_WorkMode(1); //режим работы - шифрование
    executeAndHandleError(std::bind(&classic_interface::FNBuildRegistrationReport, ci));
    
    вот пример кода
    FNBeginRegistrationReport возращает ошибок нет все хорошо, но при FNBuildRegistrationReport
    все равно 94 ошибка
    
Код ошибки 5Eh (94) от ККТ: Неверная операция <0x005E000E: в ФН открыт текущий документ 12h "Отчет об изменении параметров регистрации в связи с заменой ФН", что не соответствует команде ККТ FF06h>"

что могу делать не так??

**Comment by surfernsk** [comment]
Надо быть внимательнее!?
Вам драйвер возвращает точное описание ошибки, что Вы открыли отчет о перерегистрации с заменой ФН.

```
    //! | Значение |                  Тип отчета                                         |
    //! |----------|---------------------------------------------------------------------|
    //! |   0      | Отчет о регистрации КТТ                                             |
    //! |   1      | Отчет об изменении параметров регистрации ККТ, в связи с заменой ФН |
    //! |   2      | Отчет об изменении параметров регистрации ККТ без замены ФН         |
```

**Comment by surfernsk** [comment]
@swex в примерах ошибка, [исправте](https://github.com/shtrih-m/fr_drv_ng_examples/pull/35) пожалуйста.
```

**Comment by Commander4ek** [comment]
заработало, спасибо
