### ISSUE TITLE
Попытка записать теги ФФД 1.2

### ISSUE THREAD

**Issue by Commander4ek** [shtrih-m/fr_drv_ng#218]
Добрый день, в документации фигурируют  Расширенные признаки работы ККТ (ФФД 1.2), которые заполняются по маске

    0 0 0 0 0 0 1 Продажа подакцизного товара
    0 0 0 0 0 1 0 Проведение азартных игр
    0 0 0 0 1 0 0 Проведение лотереи
    0 0 0 1 0 0 0 Признак установки принтера в автомате
    0 0 1 0 0 0 0 Торговля маркированными товарами
    0 1 0 0 0 0 0 Ломбардная деятельность
    1 0 0 0 0 0 0 Страховая деятельность
    
 Вопрос следующего характера, я правильно понимаю что находясь в ФФД 1.05 у меня никак не получится записать эти признаки в таблицу Фискального накопителя Пункт 21(Расширенные признаки ККТ), просто например Продажа подакцизного товара фигурируют в ФФД 1.05

   int additionalWorkMode = 1;
   ci->Set_ModelParamNumber(classic_interface::DPE_FsTableNumber);
   executeAndHandleError(std::bind(&classic_interface::ReadModelParamValue, ci));
   auto fsTableNumber = ci->Get_ModelParamValue();
   ci->Set_TableNumber(fsTableNumber);
   ci->Set_RowNumber(1);
   ci->Set_FieldNumber(21);
   ci->Set_ValueOfFieldInteger(additionalWorkMode);
   executeAndHandleError(std::bind(&classic_interface::WriteTable, ci));
   
   Данный код отрабатывает без ошибок(Код возврата 0) но в таблицу ничего не записывается

**Comment by surfernsk** [comment]
Добрый время суток.
Почему вы пытаетесь записывать их в таблицу?

Наверное так, по аналогии и с [примером](https://github.com/shtrih-m/fr_drv_ng_examples/blob/master/classic_interface/main.cpp):
```
    //!
    //! @brief Расширенные признаки работы ККТ
    //!
    //! Битовое поле
    //!
    //! | Номер бита | Расширенные признаки работы ККТ         |
    //! |------------|-----------------------------------------|
    //! |      0     | Продажа подакцизного товара             |
    //! |      1     | Признак проведения азартных игр         |
    //! |      2     | Признак проведения лотереи              |
    //! |      3     | Признак установки принтера в автомате   |
    //! |      4     | Признак торговли маркиров.товарами(1.2) |
    //! |      5     | Признак ломбардной деятельности(1.2)    |
    //! |      6     | Признак страховой деятельности(1.1)     |
    //!
    //! @par Методы доступа:
    //!   #Get_WorkModeEx, #Set_WorkModeEx
```

**Comment by Commander4ek** [comment]
если верить вашей документации представленной на сайте (Руководство программиста), а также Wiki, то метод FNBuildReregistrationReport принимает следующие свойства
[Password](https://github.com/shtrih-m/fr_drv_ng/wiki/Properties#group___properties_1ga9f54fb61915a823ad4c60a3a5698baa1) - пароль системного администратора,

[INN](https://github.com/shtrih-m/fr_drv_ng/wiki/Properties#group___properties_1ga6b484429951e9fc28bd16b9cd87776ab) - ИНН,

[KKTRegistrationNumber](https://github.com/shtrih-m/fr_drv_ng/wiki/Properties#group___properties_1ga222bf2fe1ebe04dd720ef0d67671d285) - регистрационный номер ККТ,

[TaxType](https://github.com/shtrih-m/fr_drv_ng/wiki/Properties#group___properties_1ga9d77bd41c785a8738cb015c4824b342f) - код системы налогообложения,

[WorkMode](https://github.com/shtrih-m/fr_drv_ng/wiki/Properties#group___properties_1ga74ca576dec504e454333aacb1bd40f1f) - режим работы,

[RegistrationReasonCode](https://github.com/shtrih-m/fr_drv_ng/wiki/Properties#group___properties_1ga01f90fa001f9c26aaa176822b79e13a1) - код причины перерегистрации.

свойство WorkModeEx тут не используется, хотелось бы понимать в чем может причина того что метод executeAndHandleError(std::bind(&classic_interface::WriteTable, ci));  возвращает 0, но в таблицу ничего не записывается, может быть такое что данное поле только для чтения? Таблица ФН ряд  1 поле 21

**Comment by surfernsk** [comment]
@Commander4ek 
> свойство WorkModeEx тут не используется
>
Проверить удалось или нет?
В моем понимании (основываясь на 54ФЗ) - WorkMode и WorkModeEx, относятся к режиму работы ккт. Поэтому и дал вам совет попробовать.


PS. Это не моя документация и/или wiki

**Comment by Commander4ek** [comment]
проверить попытался, изменений не было, WorkMode и WorkModeEx разные вещи, поэтому сам не до конца понимаю как передать, 
WorkMode - шифрование, автономный режим и т д, с этим проблем нет, все работает
WorkModeEx - как раз то что вы перечислили, с этим проблема

**Comment by surfernsk** [comment]
А если добавить тег 1207 = 1 в открытий отчет о регистрации?

**Comment by olefard** [comment]
@Commander4ek, выложите, пожалуйста, лог драйвера. 
Делаете все правильно. Поле 21 должно записываться, ККТ перерегистрироваться.
В ФФД 1.2 добавились только последние три пункта(маркировка, ломбарды и страховка). Предыдущие были и в 1.05.

**Comment by surfernsk** [comment]
Проверил на ритейл-01Ф, запись в поле таблице происходит
```
    //Расширенный режим работы ККТ 
    ci->Set_TableNumber(fsTableNumber);
    ci->Set_RowNumber(1);
    ci->Set_FieldNumber(21);
    ci->Set_ValueOfFieldInteger(1);
    executeAndHandleError(std::bind(&classic_interface::WriteTable, ci));
```
чем смотрите содержимое полей таблицы и какой ККТ и прошивка?

PS
thx @olefard

**Comment by Commander4ek** [comment]
добрый день, к сожалению не могу пока предоставить логи КЯ, в связи с тем что моя IDE(QT CREATOR) их не выводит почему то

@surfernsk 
Устройство PAX A930(POSCENTER-BANK-01Ф)
Версия прошивки С.2
Дата сборки прошивки 10.07.2022
Сборка прошивки 41600
Смотрю таблицы и через FiscalMaster и через свой софт через ReadTable()

**Comment by olefard** [comment]
@Commander4ek, для КЯ расширенные признаки работы ККТ передаются через тег 1207.
Поле 21 на КЯ только для чтения(если запросить структуру поля `GetFieldStruct`, в начале названия поля будет * - признак, что поле только для чтения).

Тогда алгоритм регистрация для КЯ будет такой:
- `FNBeginRegistrationReport`
- `FNSendTag` 1207
- `FNBuildRegistrationReport`

**Comment by swex** [comment]
> добрый день, к сожалению не могу пока предоставить логи КЯ, в связи с тем что моя IDE(QT CREATOR) их не выводит почему то
> 

потому что qt creator фильтрует сообщения по идентификатору(package) приложения. Попробуйте посмотреть общий лог через `adb logcat` или профильтровать этот самый лог по package `ru.shtrihm.droidcashcore` одним из [способов](https://stackoverflow.com/questions/6854127/filter-logcat-to-get-only-the-messages-from-my-application-in-android)

**Comment by asem-m** [comment]
Для торговли подакцизными товарами:
- в ФФД 1.05 нужно передать тег 1207 в [пере]регистрацию;
- в ФФД 1.2 нужно предварительно записать +1 в Т13П21 (эквивалент бита 6 в теге 1290).

**Comment by asem-m** [comment]
В ФФД 1.2 "Признаки условий применения ККТ" задаются установкой соответствующих битов в 32-битном теге 1290, который формируется ФНом на основании битов, записанные в Т13П21 (расширенные признаки работы ККТ). Значение Т13П21 должно быть записано перед [пере]регистрацией.

**Comment by asem-m** [comment]
В ФФД 1.05 после Начала отчета о [пере]регистрации при необходимости передать теги 1207, 1193, 1126 со значением 1 в открытый фискальный документ и сформировать документ.

**Comment by asem-m** [comment]
Логи КЯ снимать можно так: `adb logcat "cashcore:D" "*:S"`

**Comment by Commander4ek** [comment]
тоесть я правильно понял что таблица Т13П21 для ффд 1.05 доступна только для чтения, а в ффд 1.2 в нее можно писать?

**Comment by asem-m** [comment]
> тоесть я правильно понял что таблица Т13П21 для ффд 1.05 доступна только для чтения, а в ффд 1.2 в нее можно писать?
да

**Comment by Commander4ek** [comment]
спасибо
