### ISSUE TITLE
Отключение логирования

### ISSUE THREAD

**Issue by YaNokk** [shtrih-m/fr_drv_ng#219]
Здравствуйте, подскажите, как отключить логирование? Пробовал через ci->Set_LogOn(false),  putenv("FR_DRV_LOG_FLAGS=0") перед подключением, но логи продолжают создаваться.

**Comment by swex** [comment]
выставите 
```bash
FR_DRV_LOG_PATH=/dev/null
```
до запуска ПО.

**Comment by swex** [comment]
или `FR_DRV_LOG_PATH=NUL`
