### ISSUE TITLE
При использовании кассового ядра с ниже приведенным кодом на СМАРТПОС . возникает как ошибка 115 так и -1

### ISSUE THREAD

**Issue by swex** [shtrih-m/fr_drv_ng#22]
причем разные промежутки времени. 
`        ci.Set_WaitForPrintingDelay(10); //задержка ожидания окончания печати
        int mode = ci.Get_ECRMode();
        if (mode == 4) {
            openSession(); //если смена закрыта то открываем
        }
        long checkres = 0;

        ci.Set_Password(casherPass);
        checkResult(ci.OpenCheck()); //открываем чек
        for (DataSale l : sale){
            ci.Set_Department(l.getDepartment());
            ci.Set_Quantity(l.getDepartment());
            ci.Set_StringForPrinting(l.getPrintString());
            ci.Set_Price(l.getPrice());
            //ci.Set_Tax1(l.getTax());
            ci.Set_Tax1(0);
            ci.Set_Tax2(0);
            ci.Set_Tax3(0);
            ci.Set_Tax4(0);
            //ci.Set_EmailAddress("test@test.com");
            checkResult(ci.Sale());
            checkres +=l.getPrice();
        }

        ci.CheckSubTotal();
        long result =  ci.Get_CheckResult();
        long  summ = ci.Get_Summ1();

        if (checkres >= clientSumm) {
            ci.Set_Summ1(checkres);
        } else{
            ci.Set_Summ1(clientSumm);
        }

        checkResult(ci.CloseCheck());
        checkResult(ci.WaitForPrinting()); // возможно в ческ не стоит оборачивать`

_Originally posted by @CavInc in https://github.com/shtrih-m/fr_drv_ng/issues/21#issuecomment-440726789_

**Comment by swex** [comment]
@CavInc давайте лог. В каком месте ошибка-то?

**Comment by CavInc** [comment]
судя по выводу в консоль Студии в любом дающем. команду. 
Как и в OpenCheck так и в остальных. В том числе и после закрытия чека в WaitForPrinting .
но кажется я разобралься в чем причина. надо проверить
