### ISSUE TITLE
статус памяти уведомлений

### ISSUE THREAD

**Issue by Commander4ek** [shtrih-m/fr_drv_ng#222]
Подскажите как выгрузить статус памяти уведомлений из ФН (ФФД 1.2)?

**Comment by asem-m** [comment]
Команда ККТ FF70h "Запрос статуса по работе с кодами маркировки".

Можно проверить в тесте драйвера ФР, например:
```
Состояние проверки КМ               : 1, нет КМ на проверке
Сост. по форм. уведомления          : 0, уведомление о реализации не формируется
Флаги разрешения команд работы с КМ : 5
Кол-во сохр. результатов проверки КМ: 0
Кол-во КМ, вкл. в уведомление о реализации: 0
Заполнение области хранения уведомлений   : 0, менее чем 50%
Количество уведомлений в очереди: 0
```

**Comment by swex** [comment]
см. метод `FNGetKMServerExchangeStatus`.

**Comment by Commander4ek** [comment]
отлично, это то что нужно, еще также хотелось бы уточнить насчет отправки ключей ОКП при открытии смены, как это реализовано в Штрихе, есть ли возможность поймать ошибку если они не были отправлены и как то их обновить?

**Comment by asem-m** [comment]
Если не обновились ключи, то при следующем открытии смены попытка будет повторена.

Информация об ошибках печатается на чеке открытия смены и дублируется в Т11П21-Т11П29.

**Comment by Commander4ek** [comment]
спасибо, вопрос решил, тему закрываю
