### ISSUE TITLE
тег 1197

### ISSUE THREAD

**Issue by Commander4ek** [shtrih-m/fr_drv_ng#223]
не подскажете как в ффд 1.05 прокинуть тег 1197 (измерения товаров) штуки граммы и т д

что то такое надо делать?
ci->Set_TagNumber(1197);
ci->Set_TagType(classic_interface::TagTypeEnumeration::TT_String); //Тип "строка"
ci->Set_TagValueStr(cur_pos.measure);
executeAndHandleError(std::bind(&classic_interface::FNSendTagOperation, ci));

или быть может есть какой то аналог свойства MeasureUnit(который для ФФД 1.2)

**Comment by asem-m** [comment]
Передать тег 1197 в чек:
- Открыть чек (8Dh);
- Передать произвольную TLV структуру привязанную к операции (FF4Dh);
- Операция V2 (FF46h);
- Закрытие чека расширенное вариант №2 (FF45h).

**Comment by Commander4ek** [comment]
попытался сделать как вы сказали
Тег вроде отправляется без ошибок, но ничего визуально не отоброжается

у меня на устройстве PAX A930 чек прихода, например выглядит
* Кассовый чек *
CARGO_NAME   = 999.99_Г

мне бы хотелось чтобы вместо странных букв _Г для штучного товара и  _В для весового товара
печаталось нормальное (шт. гр. кг. и т д)

**Comment by surfernsk** [comment]
> по тегу понял, спасибо, в добавок еще вопрос:
> 
> у меня на устройстве PAX A930 чек прихода, например выглядит
> 
> * Кассовый чек *
>   CARGO_NAME   = 999.99_Г для штучного товара
> 
> CARGO_NAME CARGO_PRICE * CARGO_Quantity = 999.99_В для весового товара Хотелось бы понимать что это за _Г и _В по логике на этом месте должна стоять символ валюты
> 
> ФФД 1.05 если что

Буква это обозначение НДС у данной позиции
