### ISSUE TITLE
тег 1205

### ISSUE THREAD

**Issue by Commander4ek** [shtrih-m/fr_drv_ng#224]
Доброго времени суток, есть необходимость при перерегистрации ФН отправлять тег 1205 \"Коды причин изменения сведений о ККТ\"
Однако возникла сложность с тем  чтобы записать значение в таблицу Т13П22
сложность заключается в переполнении типа int
максимально возможное значение Т13П22 - 2151677951(10000000001111111111111111111111 в двоичном представлении)

Для примера мне при регистрации приходят данные в виде битов: 10000000000101000000000000000000
в виде десятичном - 2148794368
я пытаюсь сделать:
 m_shtrihDriverInterface->Set_TableNumber(13);
m_shtrihDriverInterface->Set_RowNumber(1);
m_shtrihDriverInterface->Set_FieldNumber(22);
m_shtrihDriverInterface->Set_ValueOfFieldInteger(2148794368);
executeAndHandleError(std::bind(&classic_interface::WriteTable, m_shtrihDriverInterface));
в результате что логично у меня происходит переполнение int (макс значение int - 2 147 483 647) и я получаю код ошибки -9(вне диапазона)

также я пытался сделать вот так

 m_shtrihDriverInterface->Set_TagNumber(1205);
 m_shtrihDriverInterface->Set_TagType(classic_interface::TagTypeEnumeration::TT_BitMask); //Тип "Битовая Маска"
 m_shtrihDriverInterface->Set_TagValueBin(registrationData.regParamsChangeCode.to_string());
 m_shtrihDriverInterface->Set_TagValueLength(registrationData.regParamsChangeCode.size());
executeAndHandleError(std::bind(&classic_interface::FNSendTag, m_shtrihDriverInterface));

также получаю код ошибки -9(вне диапазона)
regParamsChangeCode - это std::bitset в виде массива бит с размерностью 32, которая приходит мне из вне

Подскажите что я делаю не так?

**Comment by asem-m** [comment]
Т13П22 - это `uint32_t`, а не `int`.

**Comment by Commander4ek** [comment]
согласен, но как мне через writeTable записать uint32_t если я правильно посмотрел там есть только std::string и int

**Comment by Commander4ek** [comment]
public int [WriteTable](https://github.com/shtrih-m/fr_drv_ng/wiki/Methods#group___base_methods_1ga83df009f846e41e399a47f4e2c843a97)()
Записать таблицу.

Команда записывает во внутреннюю таблицу ККМ с номером [TableNumber](https://github.com/shtrih-m/fr_drv_ng/wiki/Properties#group___properties_1gad68b86360e0bb5c873486657593dc0d2) в строку с номером RowNumber в поле с номером [FieldNumber](https://github.com/shtrih-m/fr_drv_ng/wiki/Properties#group___properties_1ga4cb689bda2268d0f61303793ed83d373) значение [ValueOfFieldString](https://github.com/shtrih-m/fr_drv_ng/wiki/Properties#group___properties_1ga1fdc714fb8b2e2b9bcbb46693df3f0b7)([ValueOfFieldInteger](https://github.com/shtrih-m/fr_drv_ng/wiki/Properties#group___properties_1ga05a9bf198ba74a0e9a073c6b1b98a950)).

Работает во всех режимах, кроме режимов 1 и 8. Не меняет режима ККМ.

Используемые свойства:

[Password](https://github.com/shtrih-m/fr_drv_ng/wiki/Properties#group___properties_1ga9f54fb61915a823ad4c60a3a5698baa1) - пароль системного администратора,

[TableNumber](https://github.com/shtrih-m/fr_drv_ng/wiki/Properties#group___properties_1gad68b86360e0bb5c873486657593dc0d2) - номер таблицы,

[RowNumber](https://github.com/shtrih-m/fr_drv_ng/wiki/Properties#group___properties_1gac048d4ec406d94f795937f6c98cef123) - номер ряда,

[FieldNumber](https://github.com/shtrih-m/fr_drv_ng/wiki/Properties#group___properties_1ga4cb689bda2268d0f61303793ed83d373) - номер поля.

[ValueOfFieldString](https://github.com/shtrih-m/fr_drv_ng/wiki/Properties#group___properties_1ga1fdc714fb8b2e2b9bcbb46693df3f0b7) - значение строкового поля,

[ValueOfFieldInteger](https://github.com/shtrih-m/fr_drv_ng/wiki/Properties#group___properties_1ga05a9bf198ba74a0e9a073c6b1b98a950) - значение числового поля.

Returns
Код ошибки

**Comment by Commander4ek** [comment]
я так и пытался
значение Т13П22 от 0 до 2151677951
отрицательные туда не идут

**Comment by Commander4ek** [comment]
@surfernsk 
теперь КЯ ведет себя странно
если я сначала пытаюсь вызвать 
executeAndHandleError(std::bind(&classic_interface::FNBeginRegistrationReport, m_shtrihDriverInterface));
то он пишет

D [SHTRIH]: <Shtrih::setLastErrMsg> lastErrMsg:  "Код ошибки 33h (51) от ККТ: Некорректные параметры в команде <0x00330087: при изменении версии ФФД не указана причина: не установлен бит 21 \"Изменение версии ФФД\" в теге 1205 \"Коды причин изменения сведений о ККТ\" в Т13П22>"

соответственно не открывает документ и при попытке отправить тег вашим способом 
я получаю D [SHTRIH]: <Shtrih::setLastErrMsg> lastErrMsg:  "Код ошибки 5Eh (94) от ККТ: Неверная операция <0x005E0012: в ФН не открыт документ, тег не может быть передан>"

так что по логике драйвер хочет чтобы я вначале записал через WriteTable перед FNBeginRegistrationReport
ну тогда мой вопрос все еще актуален, как в Т13П22 передать uint32_t

**Comment by surfernsk** [comment]
@Commander4ek 
```
m_shtrihDriverInterface->Set_TableNumber(13);
m_shtrihDriverInterface->Set_RowNumber(1);
m_shtrihDriverInterface->Set_FieldNumber(22);
m_shtrihDriverInterface->Set_ValueOfFieldString(2148794368);
```
Вроде так.

**Comment by Commander4ek** [comment]
executeAndHandleError возвращает 0(нет ошибок) но в таблицу ничего не пишется
FNBeginRegistrationReport по прежнему 51 ошибка с текстом как в моем комментарии выше

**Comment by surfernsk** [comment]
@Commander4ek 
![Screenshot_20220907_234848](https://user-images.githubusercontent.com/2264893/188934896-aa9eb65d-23d8-4a23-a48a-92322dde447e.png)

2097152 - изменение версии ФФД

**Comment by Commander4ek** [comment]
2097152 это 19 бит все так, и если я его запишу то должно работать ну только там помимо него еще есть биты, которые надо передать
мне приходит вот это значение 10000000000101000000000000000000

**Comment by surfernsk** [comment]
@Commander4ek  
> 2097152 это 19 бит все так,

2097152 -это бит 21 = 1

> которые надо передать мне приходит вот это значение 10000000000101000000000000000000

здесь:
 бит 31 = 1
 бит 21 = 0
 бит 20 = 1
 бит 18 = 1
```
1  000000000  0   1  0 1  00000000000000000 0
31                    21 20   18                                   0  | номер бита
итого 32 бита
```

**Comment by asem-m** [comment]
ФР/КЯ принимает 1, 2, 4 байтовые двоичные данные, необходимо найти в драйвере метод передачи 8, 16, 32 битных двоичных чисел (соответственно) без учета типа signed или unsigned

формально (по диапазону) тип - unsigned (значения неотрицательные)

**Comment by surfernsk** [comment]
> ФР/КЯ принимает 1, 2, 4 байтовые двоичные данные, необходимо найти в драйвере метод передачи 8, 16, 32 битных двоичных чисел (соответственно) без учета типа signed или unsigned
> 
> формально (по диапазону) тип - unsigned (значения неотрицательные)

Удивитесь когда посмотрите как ТестДрайвера записывает поле 22 в Таблице 18. Там запись в поле типа BIN - методом 
```
Set_ValueOfFieldString('');
WriteTable();
````

```
  [00000248] [DEBUG] TDrvFR Set_TableNumber: 18
  [00000248] [DEBUG] TDrvFR Set_FieldNumber
  [00000248] [DEBUG] TDrvFR Set_FieldNumber: 22
  [00000248] [DEBUG] TDrvFR Set_ValueOfFieldString
  [00000248] [DEBUG] TDrvFR Set_ValueOfFieldString: 2151677951
  [00000248] [DEBUG] TDrvFR WriteTable
```

**Comment by Commander4ek** [comment]
@surfernsk так еще раз как мне их записать в таблицу?

**Comment by surfernsk** [comment]
> @surfernsk так еще раз как мне их записать в таблицу?

Попробуйте по логике драйвера по win:
1.  Формируем число (по маске)
2.  Set_ValueOfFieldString - где число представлено в виде строки те 2565454 > "2565454"
3.  WriteTable
Только укажите правильные причины перерегистрации - при изменении версии ФФД не указана причина: не установлен бит 21 "Изменение версии ФФД"

**Comment by swex** [comment]
вообще не должно быть проблем с записью старшего бита 32битного числа в таблицу, единственное что не уверен что все обертки правильно себя поведут при приведении.

**Comment by swex** [comment]
записать в числовое поле через `ValueOfFieldString` в classic_interface нельзя. Нужно будет выдумывать доп. слой совместимости для такого

**Comment by Commander4ek** [comment]
@swex использую classic_interface.h на c++/c
и проблема с приведении есть
у меня приведение работает именно так

0b10000000000101000000000000000000 = 2148794368 (uint32_t) = -2146172928 (int)
как правильно отметил @asem-m 

хотелось бы что то с этим придумать, потому то что предложил @surfernsk в коде ошибки возвращает 0, но ничего в таблицу не пишет

**Comment by swex** [comment]
Поправлено приведение в [1.6.0-4-g422716f](https://github.com/shtrih-m/fr_drv_ng/releases/tag/1.6.0-4-g422716f)

**Comment by Commander4ek** [comment]
заработало, спасибо
