### ISSUE TITLE
Теги 2105 и 2109

### ISSUE THREAD

**Issue by Commander4ek** [shtrih-m/fr_drv_ng#225]
Доброго времени суток, делаю проверку маркированного товара в ФН и ОИСМ по ФФД 1.2 при помощи метода FNCheckItemBarcode2, для реализации моей задачи мне необходимо после проверки получить результаты след тегов:

тег 2105 
0 | Запрос имеет корректный формат, в том числе корректный формат кода маркировки
1 | Запрос имеет некорректный формат
2 | Указанный в запросе код маркировки имеет некорректный формат (не распознан)

и тег 2109 

Значение реквизита | Ответ ОИСМ о статусе товара
1 | Планируемый статус товара корректен
2 | Планируемый статус товара некорректен
3 | Оборот товара приостановлен

в документации таких тегов найти не смог, возможно мне следует использовать иной метод проверки ОИСМ, но этот уж слишком удобен, буду рад помощи

**Comment by asem-m** [comment]
Документацию по работе с КМ смотрите в разделе "2. Работа с чеком прихода/расхода/возвратов." в changelog.txt КЯ.

Необходимо работать по варианту 1 из документа "Порядок действий при регистрации ККТ и получении кассовых чеков с кодом маркировки в соответствии с ФФД 1.2".

После открытия чека выполните очередную проверку КМ (для товара в позиции чека), чтобы получить статус КМ. В тесте драйвера ФР получите такого рода ответ:
```
Статус локальной проверки    : 3
  "код маркировки проверен фискальным накопителем с использованием ключа проверки КП"
  "результат проверки КП КМ фискальным накопителем с использованием ключа проверки КП положительный"
Результат локальной проверки : 0, КМ проверен в ФН
Распознанный тип КМ          : 2, КМ со значением кода проверки длиной 88 символов, подлежащим проверке в ФН
Код ответа ФН на команду онлайн-проверки: 0, Ошибок нет
Результат проверки КМ        : 15
  "код маркировки проверен"
  "результат проверки КП КМ положительный"
  "проверка статуса ОИСМ выполнена"
  "от ОИСМ получены сведения, что планируемый статус товара корректен"
  "результат проверки КП КМ и статуса товара сформирован ККТ, работающей в режиме передачи данных"
Реквизиты ответа сервера     : 42 08 04 00 92 5A 20 63 39 08 01 00 00 D5 07 01 00 0F 3D 08 01 00 01 34 08 01 00 02
```

В реквизитах сервера получите искомые теги:
```
42 08 // тег 2114
04 00
92 5A 20 63

39 08 // тег 2105
01 00
00

D5 07 // тег 2005
01 00
0F

3D 08 // тег 2109
01 00
01

34 08 // тег 2100
01 00
02
```

**Comment by Commander4ek** [comment]
@asem-m 
Добрый вечер, делаю как вы сказали значения приходят похожие но почему то в логах  TLVDataHex(std::string) пустая, почему такое может быть?

вот что мне приходит в логах:

E [SHTRIH]: <Shtrih::checkCodeMarkInFs> CheckItemLocalResult:  3
E [SHTRIH]: <Shtrih::checkCodeMarkInFs> CheckItemLocalError:   0
E [SHTRIH]: <Shtrih::checkCodeMarkInFs> MarkingType2:  2
E [SHTRIH]: <Shtrih::checkCodeMarkInFs> KMServerErrorCode:  0
E [SHTRIH]: <Shtrih::checkCodeMarkInFs> KMServerCheckingStatus:  15
E [SHTRIH]: <Shtrih::checkCodeMarkInFs> TLVDataHex:

**Comment by swex** [comment]
покажите лог с обменом

**Comment by Commander4ek** [comment]
сделал через vector<uint8_t> TLVData, там все в порядке приходит, закрываю, спасибо
