### ISSUE TITLE
вопрос по проверки актуальности сборки

### ISSUE THREAD

**Issue by Commander4ek** [shtrih-m/fr_drv_ng#226]
Добрый день, хотел реализовать такой функционал как проверка актуальности сборки при подключении принтера и при наличии более новой сборки информирование пользователя об этом и отключаться.

Вопрос в следующем как получить актуальную версию последней прошивки( план минимум это просто получить int актуальной сборки и сравнить с ECRBuild после GetECRStatus, план максимум при не соответствии версии максимально помочь пользователю обновить сборку)

что тут можно сделать?

**Comment by Commander4ek** [comment]
Попробую уточнить для чего мне это необходимо

У меня сейчас находятся 2 устройства PAXA930

Первый
Версия прошивки С.2
Дата сборка прошивки 10.07.2022
Сборка прошивки 41600

Второй
Версия прошивки С.2
Дата сборка прошивки 25.02.2022
Сборка прошивки 40790

и проблема заключается в том, что код не работает на втором устройстве, пока самое фатальное различие заключается в том что на данном устройстве в таблице 10 после поля 38 везде (стоит Зарезервировано и значение 0), а в моем коде осуществляется чтение Т10П43 максимальное допустимая версия ФФД для ФН(которое на первом устройстве корректно работает), соответственно код не отрабатывает, хотелось бы быть уверенным что все значения в таблицах будут гарантированно прочитаны, ведь мне, как разработчику неизвестно с какой версии и с какого устройства будет запущен софт.

**Comment by asem-m** [comment]
Номер сборки КЯ можно считать в двоичном виде командой ККТ 11h из параметра `Сборка ПО ККТ (2 байта)` или в виде ASCII строки из Т3П25 `*ВЕРСИЯ СБОРКИ КЯ`.

Поля в таблицы могут добавляться с ростом номера сборки КЯ.

**Comment by Commander4ek** [comment]
тогда такой вопрос, если я сейчас возьму свою сборку(41600) как корректную, есть ли вероятность что версии, которые выйдут позже будут не совместимы( что то поменяется в таблицах местами и т д) с текущей?

**Comment by swex** [comment]
внутри девайса есть же магазин приложений. можно обновлять КЯ через него

**Comment by asem-m** [comment]
> тогда такой вопрос, если я сейчас возьму свою сборку(41600) как корректную, есть ли вероятность что версии, которые выйдут позже будут не совместимы( что то поменяется в таблицах местами и т д) с текущей?

обычно функционал в таблицах не меняется, а дополняется

понижать версию сборки без переустановки КЯ нельзя

**Comment by asem-m** [comment]
необходимо, чтобы последним ФД был отчет о расчетах

**Comment by asem-m** [comment]
начиная со сборки 1.14.41711 требование к печати отчета о расчетах относится к перерегистрации при изменении версии ФФД

**Comment by Commander4ek** [comment]
теперь ситуация поменялась после отчета о тек сост расчетов появляется

D [SHTRIH]: <Shtrih::setLastErrMsg> lastErrMsg:  "Код ошибки 33h (51) от ККТ: Некорректные параметры в команде или ошибка при работе с КМ <0x0033005D: количество непереданных ФД (тег 1097) должно быть равно 0; выполните команду ФН 20h \"Получить статус информационного обмена\">"

Но на самом чеке, который вышел написано непереданых ФД - 0, не очень понятно что происходит

**Comment by asem-m** [comment]
необходимо, чтобы были отправлены в ОФД все неотправленные ФД
