### ISSUE TITLE
Проблема с ИНН при регистрации\перерегистрации 

### ISSUE THREAD

**Issue by Commander4ek** [shtrih-m/fr_drv_ng#229]
Добрый день, проблема следующего характера, при регистрации выскакивает ошибка Код ошибки 33h (51) от ККТ: Некорректные параметры в команде <0x00330007: не совпадает контрольное число в 10-значном ИНН

ФФД 1.05
Передаю 10 значные ИНН компании через (Set_INN) и ИНН ОФД через запись в таблицу Фискального Накопителя пункт 12
Оба ИНН на валидность контрольного числа проверял(они валидные), ошибка возникает при вызове метода FnBulidRegistationReport()

возможно как то нужно дополнить 10 значный ИНН пробелами нулями или еще как то до 12 знаков, буду рад ответу

**Comment by asem-m** [comment]
если ИНН имеет длину меньше 12 цифр, то он дополняется справа пробелами

**Comment by Commander4ek** [comment]
это относится вообще ко всем ИНН?
и Инн компании и ОФД и инн кассира?

**Comment by asem-m** [comment]
все ИНН должны быть 12 знаков

**Comment by asem-m** [comment]
в Т13П12 можно передавать ASCII строку из 10 цифр

**Comment by Commander4ek** [comment]
сделал как вы сказали, но проблема все еще актуальна, проверяю размер строки с ИНН - 12 после  добавлении пробелов, ниже кусок куда реализации

const size_t requiredInnSize = 12;
m_shtrihDriverInterface->Set_INN(registrationData.INN + std::string(requiredInnSize - registrationData.INN.length(),' '));

**Comment by asem-m** [comment]
драйвер ФР под Windows передает 10-значный ИНН в Т13П12 так:
`1E 1E000000 0D 0100 0C 373731343733313436340000`

но можно передать без нулей:
`1E 1E000000 0D 0100 0C 37373134373331343634`

можно передать с пробелами справа:
`1E 1E000000 0D 0100 0C 373731343733313436342020`

**Comment by Commander4ek** [comment]
я так понял, что проблема не с Т13П12, а ИНН пользователя, т.е Т13П2, оно же свойство INN, которое требует метод FnBulidRegistationReport, пытался и по документации слева дописывать 0, пытался справа дополнять пробелами, результат пока одинаковый, насчет Т13П12, туда все нормально пишется если верить FiscalMaster

**Comment by Commander4ek** [comment]
я не знаю важно это или нет устройство PAXA930

**Comment by asem-m** [comment]
передавать 10-значный ИНН в команду ККТ регистрации с пробелами справа:
`FF06 1E000000 363434393031333731312020 3030303030303030313030313932343620202020 01 08`

**Comment by Commander4ek** [comment]
не выходит, мне нужно понимать как в коде это должно выглядеть должно,
допустим мне пришел запрос на регистрацию
в структуре данных хранится ИНН 7736207543(Яндекс) в виде строки размеров 10 символов
Соответсвенно, что было сделано, я пытался и 007736207543 и 773620754300 7736207543'2 пробела' и пробелы вперед строки добавлял, ошибка стабильна

**Comment by Commander4ek** [comment]
ФР под Windows не находит PAX A930

**Comment by asem-m** [comment]
Подключение: TCP сокет
Протокол обмена: Протокол ККТ 2.0
Адрес: IP address of PAX
Порт TCP: 12345
Таймаут: 1000

**Comment by Commander4ek** [comment]
так, подключился, зашел в команды скопировал то, что вы указали на выходе получил 
(0) Код ошибки 33h (51) от ККТ: Некорректные параметры в команде <0x0033000B: не совпадает контрольное число в РН ККТ>
видимо что то не то делаю

**Comment by Commander4ek** [comment]
В конечном итоге сделал перерегистрацию через драйвер ФР, вот что получилось

Передано 8F 2B 00 11 00 FF 34 1E 00 00 00 37 38 30 32 38 37 30 38 32 30 20 20 30 30 30 30 30 30 30 30 30 31 30 35 32 39 35 32 20 20 20 20 01 38 03 3F F4 

принято  8F | 0D | 00 | 11 | 00 FF 34 00 0A 00 00 00 E6 79 50 28 F9 | 69

**Comment by asem-m** [comment]
правильно, ИНН и РН ККТ переданы с пробелами справа
