### ISSUE TITLE
новые команды для версии 33431

### ISSUE THREAD

**Issue by try2bajed1** [shtrih-m/fr_drv_ng#23]
получили письмо от вашего менеджера:
в версии 33431 отключена часть старых, но важных команд продаж, так как они не позволяют передавать нужные тэги согласно ФФД 1.05

подскажите пожалуйста, о каких командах идет речь? 
это FNOperation для фискальной операции и FNCloseCheckEx для закрытия чека? 
Если у меня все корректно печатается и отправляется в офд на версии 33600, стоит ли мне проигнорировать это письмо?

**Comment by abramcumner** [comment]
FNOperation и FNCloseCheckEx - это как раз правильные и актуальные команды. Их и надо использовать. Старые - это `Sale`, `CloseCheck`.

**Comment by olefard** [comment]
FNOperation и FNCloseCheckEx - это как раз правильные и актуальные команды. Их и надо использовать. Старые - это Sale, CloseCheck.

**Comment by try2bajed1** [comment]
ой, да, не совсем корректно я написал. Я как раз имел ввиду эти новые команды, у нас используются именно они. Спасибо.
