### ISSUE TITLE
Статус Информационного обмена = 0

### ISSUE THREAD

**Issue by Commander4ek** [shtrih-m/fr_drv_ng#230]
очень странное поведение при не автономном режиме, каждый раз при вызове метода FNGetInfoExchangeStatus на выходе получаю 0, при регистрации принимаю следующие данные

Название ОФД                                         |   записываю в Т13П10    |       Test TaxCom
ИНН ОФД                                                 |   записываю в Т13П12    |        7704211201
URL налогового органа                           |   записываю в Т13П13    |        www.nalog.gov.ru
ofdHost                                                     |   записываю в Т14П1      |         f1test.taxcom.ru
ofdPort                                                      |   записываю в Т14П2      |         7778
Отправитель почты(1117)                       |   записываю в Т13П15    |         kassa@test.ru

регистрация отрабатывает корректно, и последующая работа кассы корректна(открытие закрытие смены чеки возвраты и т д)
проблема заключается в том, что как только я пытаюсь сделать перерегистрацию КЯ говорит об ошибке, что число непереданных ФД должны быть равны 0, и предлагает сделать Запрос Статуса Информационного обмена, который как написано в теме возвращает 0.

Что самое непонятное, что в Отчете о Текущем состоянии расчетов, который печатается перед перерегистрацией, число непереданных ФД = 0,  дата первого непереданного документа 01.01.1970(тоже 0) и в наш тестовый ОФД документы реально прилетают, помогите разобраться что происходит?

**Comment by asem-m** [comment]
какая сборка КЯ у вас установлена?

установите КЯ 1.14.41711 или выше

**Comment by Commander4ek** [comment]
1.14.41600

**Comment by Commander4ek** [comment]
для устройства PaxA930 нет возможности обновить КЯ, магазин приложений говорит актуальная версия

**Comment by asem-m** [comment]
02.ФН Сервис -> ОФД -> Получить статус инф.обмена:
Количество сообщений для ОФД должно быть 0

**Comment by asem-m** [comment]
PAX терминал для разработчиков должен позволять adb install, залейте вручную КЯ

**Comment by Commander4ek** [comment]
если я правильно понял, то стаус информационного обмена - битовая маска, когда я говорил, что возвращается 0, имеется в виду 0b00000000

**Comment by Commander4ek** [comment]
в таблице 15 практически везде стоят 0, кроме П7 П12 и П13

**Comment by Commander4ek** [comment]
@asem-m в интернете не могу найти ссылки на скачивания, либо инструкции о том как это можно сделать, можете есть какие-то ссылка\информация??

**Comment by asem-m** [comment]
в Т15П3 транслирутся тег 1097, который можно получить командой ККТ FF39h в параметре "Количество сообщений для ОФД (2 байта)". Если снят отчет о расчетах и тег 1097 нулевой, то можно перерегистрировать с ФФД 1.05 в 1.2

после снятия отчета о расчетах для уверенности подать команду ККТ FF39h

если номер ФФД не поднимается, то требование на отчет о расчетах и 1097=0 снят в 1.14.41711

**Comment by asem-m** [comment]
> @asem-m в интернете не могу найти ссылки на скачивания, либо инструкции о том как это можно сделать, можете есть какие-то ссылка\информация??

куда вам отправить КЯ?

**Comment by Commander4ek** [comment]
если можно на почту - будет прекрасно  germanbelyansky@gmail.com

**Comment by Commander4ek** [comment]
или какие иные варианты нужны?

**Comment by asem-m** [comment]
сделайте запрос по адресу <d.chernova@inpas.ru>

**Comment by Commander4ek** [comment]
готово

**Comment by Commander4ek** [comment]
@asem-m Драйвер, вчера получил, проблема при перерегистрации между одной ффд пропала, но когда я попытался переключится из ффд 1.05 на ффд 1.2 получил ровно такую же ошибку, хотелось бы понимать что делать

Т15П3 = 0, на отчете о текущем состоянии расчетов кол-во непереданных фд = 0, но стабильно ловится ошибка

"Код ошибки 33h (51) от ККТ: Некорректные параметры в команде <0x0033005D: количество непереданных ФД (тег 1097) должно быть равно 0; выполните команду ФН 20h \"Получить статус информационного обмена\">"

Метод FNGetInfoExchangeStatus в свойстве InfoExchangeStatus = 0

**Comment by asem-m** [comment]
> после снятия отчета о расчетах для уверенности подать команду ККТ FF39h

и убедиться, что количество сообщений для ОФД равно 0

**Comment by Commander4ek** [comment]
заработало, большое спасибо
