### ISSUE TITLE
Получение версии ФФД

### ISSUE THREAD

**Issue by subtotalhs** [shtrih-m/fr_drv_ng#231]
Через таблицу 10, ряд 1, столбец 29 я могу получить лишь два значения версии ФФД - 0 и 2, что означает 1.0 и 1.05 соответственно. Формат ФФД 1.0 устарел и не используется. Как я могу выяснить, зарегистрирована ли касса на ФФД 1.1 или 1.2?

**Comment by swex** [comment]
таблица/поле с версией ФФД может отличаться у разных реализаций. Необходимо воспользоваться свойствами [пример](https://github.com/shtrih-m/fr_drv_ng_examples/blob/master/classic_interface/main.cpp#L61).

**Comment by subtotalhs** [comment]
А есть ли подобные свойства в версии драйвера для Android?

**Comment by swex** [comment]
конечно есть, эта Java код из этого репозитория только обертка над C++ кодом.
вот [пример](https://github.com/shtrih-m/fr_drv_ng_examples/blob/master/classic_fr_drv_ng_android_example/app/src/main/java/ru/shtrih_m/classic_fr_drv_ng_example/ExampleStuff.java#L42) использования тех же функций но в java.
