### ISSUE TITLE
Проблема при чтении фискального документа из ФН (FNGetDocumentAsString)

### ISSUE THREAD

**Issue by ALexandrKoh** [shtrih-m/fr_drv_ng#237]
На некоторых фискальных регистраторах имеем такую проблему:
При выполнении операции FNGetDocumentAsString в "тесте драйвера" строка формируется не полностью, выводится только 1-7 тегов и время операции фиксируется в пределах 400 - 700 мс. При этом результат операции - (0) Ошибок нет.
т.е. нажимая несколько раз на кнопку "Прочитать фиск. документ", получаем разное количество тегов - может выдать только одну строчку а может несколько, но никогда не получает все данные. 
пробовали разные драйвера - не помогло. 
В чем может быть причина? Может какие-то таймауты нужно подкрутить?

**Comment by swex** [comment]
о каком "тесте драйвера" речь? давайте логи.

**Comment by ALexandrKoh** [comment]
![ТестДрайвера](https://user-images.githubusercontent.com/116652159/197797097-72f7c645-566c-42d3-8237-a04c18ce88c2.jpg)
Лог постараюсь завтра записать

**Comment by surfernsk** [comment]
@ALexandrKoh  Обновите прошивку, на актуальную версию для вашего ФР.
В прошивке 20 года, или около того были такие проблемы.

**Comment by ALexandrKoh** [comment]
@surfernsk Спасибо за рекомендацию, действительно прошивка была сильно старая (от 18 года) обновили на новую, и заработало хорошо.
На некоторых кассах с такой же старой прошивкой работает, поэтому возможно тут какое-то сочетание прошивки + ФН играет роль. В любом случае новая прошивка помогла, будем прошивать проблемные ФР.
Спасибо!
