### ISSUE TITLE
GetEKLZSessionReportInDatesRange Не поддерживается в данной версии драйвера

### ISSUE THREAD

**Issue by hexbear** [shtrih-m/fr_drv_ng#241]
Здравствуйте. Стоит задача формировать отчёты командой GetEKLZSessionReportInDatesRange в среде linux ubuntu.
Опыта в программировании немного, однако удалось запустить [json-rpc-server](https://github.com/shtrih-m/fr_drv_ng_examples/tree/master/classic_jsonrpc)

Но нужная функция GetEKLZSessionReportInDatesRange к сожалению, [нереализована](https://github.com/shtrih-m/fr_drv_ng/wiki/Unimplemented-Methods#group___unimplemented_1gae175d2b8730541eace3f1709435a8eba). В утилите Тест драйвера ФР 4.15 под windows такая функция есть. Возможно ли попросить вас добавить GetEKLZSessionReportInDatesRange в будущие релизы?

![2022-12-04 - 14 27 17](https://user-images.githubusercontent.com/11722858/205487902-4cb0bc57-97ef-45bd-b005-ab492be5ef99.png)
![image](https://user-images.githubusercontent.com/11722858/205488135-aee47016-7bc7-4938-8b91-d6b590ab5d9c.png)

**Comment by swex** [comment]
Все методы в названии которых есть ЭКЛЗ (EKLZ) не реализованы. Т.к. являются устаревшими. В ФФД используется ФН. Думаю вам нужен метод `FNBeginCalculationStateReport` или `FNCloseSession`

**Comment by hexbear** [comment]
К сожалению, сейчас мы пользуемся только такими аппаратами, штрих-м-птк со старой прошивкой, на время переходного периода.
Возможно, вы подскажите, как тогда лучше сделать? М.б.  через hex-cmd?

**Comment by swex** [comment]
Какого переходного периода? Вы из прошлого?

**Comment by hexbear** [comment]
ну почти
![photo_2022-12-05_09-28-26](https://user-images.githubusercontent.com/11722858/205564354-80e7ccb0-4136-434c-b19e-11005fc0b8eb.jpg)

**Comment by swex** [comment]
Всё понял. Прочитал сейчас что у вас переходный период до 2027.

Этот драйвер не предназначен для работы со старыми кассами. Он разрабатывался в момент перехода на кассы работающие по правилам ФЗ 54. 

Коротко суть:
1. ранее кассовые аппараты назывались "Фискальный Регистратор" (ФР) и в них был установлен модуль "электронная кассовая лента защищенная" (ЭКЛЗ) на котором безопасно записывалась и хранилась информация о кассовых операциях. Когда было необходимо, налоговые органы проверяли содержимое этой ЭКЛЗ и сравнивали с тем что есть в отчетных документах.
2. В 2016 году вступил в силу "Федеральный закон" (ФЗ) 54, в котором изменился подход к работе с кассовой техникой. ФР стали называться "Контрольно кассовая техника" (ККТ), модуль ЭКЗЛ был заменен на новый модуль "Фискальный накопитель" (ФН). Переходный период был до 1 июля 2017 года.
3. Основные различия ЭКЛЗ и ФН:
3.1 ЭКЛЗ хранила мало информации: даты, суммы и типы операций. ФН хранит и полное содержимое документов.
3.2 с ЭКЛЗ можно было считывать данные локально, ККТ с ФН обязаны сами передавать по сети данные в налоговые органы.
3.3 Передача документов в налоговые органы осуществляется не напрямую, а через промежуточные звенья "Операторов фискальных данных" (ОФД).
3.4 Документы передаются по сети в зашифрованном виде. На стороне ККТ шифрованием занимается ФН. На стороне ОФД документ расшифровывается, проверяется его корректность и на ККТ отправляется подтверждение документа. После этого документ уже может быть удален из ФН. Все это происходит в фоне, независимо и прозрачно от кассового ПО.
3.5 Если связи нет более 30 дней ФН перестает формировать новые документы до тех пор, пока не отправит старые. За исключением специального "автономного режима" работы ККТ.


Что можно сделать:
1. Для новых интеграций вы уже можете переходить на ФЗ 54. Вот разъяснение от налоговой:
```
В течение 5 лет организации и ИП в новых регионах могут как применять ККТ по тем правилам, которые 
были до вхождения в состав РФ, так и начать добровольно применять ККТ по правилам закона № 54-ФЗ.
```
2. Если хотите оставаться пока на ЭКЛЗ:
2.1 Можно использовать драйвер под windows (работает под wine) или javapos драйвером.
2.2 В первом посте вы пишете
```
Возможно ли попросить вас добавить GetEKLZSessionReportInDatesRange в будущие релизы?
```
Разумеется, мы могли бы, но если уж добавлять сюда поддержку ЭКЛЗ то нужно поддерживать весь связанный с ЭКЛЗ функционал.  Это уже достаточно серьезная работа, а с учетом наличия рабочих альтернатив, бесполезная.
3. Можно реализовать необходимые команды самостоятельно, и пользоваться драйвером как транспортом.  `hex-cmd` это из консольного теста, для `classic_interface` соответствующая команда это `TransferBytes`.

ИТОГО:
Если возможно - переходите на *новые* ККТ с ФН и интегрируйте свое кассовое ПО сразу с ними. В таком случае вам не придется интегрироваться 2 раза.

В общем пишите что решили, обязательно поможем!

**Comment by hexbear** [comment]
Спасибо за развёрнутый ответ! Думаю, пока воспользуемся третьим вариантом
