### ISSUE TITLE
Краш APK при создании объекта UsbCdcAcmHelper (сборка под Android 12)

### ISSUE THREAD

**Issue by Mantas-dev** [shtrih-m/fr_drv_ng#242]
Здравствуйте, столкнулся со следующей проблемой. Если собирать APK для Android 12, то при попытке создания объекта UsbCdcAcmHelper приложение вылетает, а в логах выводится следующее сообщение:

```
java.lang.RuntimeException: Unable to start activity
ComponentInfo{ru.shtrih_m.classic_fr_drv_ng_android_example/ru.shtrih_m.classic_fr_drv_ng_android_example.MainActivity}: java.lang.IllegalArgumentException: ru.shtrih_m.classic_fr_drv_ng_android_example: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent. 
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
```

Проверял также на тестовом приложении из репозитория https://github.com/shtrih-m/fr_drv_ng_examples с последней версией библиотек и проблема повторяется. На андроиде ниже 12 проблем не возникает. Play market требует теперь заливать приложения, собранные именно под 12 андроид. Есть ли способ обойти эту проблему или нужно ждать фикса?

**Comment by swex** [comment]
целевая версия те? target platform version теперь под 12!? Ну поправим, добавим флаг...

**Comment by Mantas-dev** [comment]
> целевая версия те? target platform version теперь под 12!? Ну поправим, добавим флаг...

Совсем забыл про целевую версию. Да, теперь требуется целевая версия не ниже 31

**Comment by swex** [comment]
я правильно понимаю что вы используете тип подключение по usb?

**Comment by Mantas-dev** [comment]
> я правильно понимаю что вы используете тип подключение по usb?

Да

**Comment by swex** [comment]
[android_util_fr_drv_ng-release.aar.zip](https://github.com/shtrih-m/fr_drv_ng/files/10195660/android_util_fr_drv_ng-release.aar.zip) просьба проверить работу на ваших устройствах с этой сборкой

**Comment by Mantas-dev** [comment]
Проверили полностью сборку, подключение по USB работает, вылетов не наблюдается. Спасибо за помощь)
