### ISSUE TITLE
C#: При использовании сгенерированной через SWIG оболочки не обнаружаются точки входа в библиотеку

### ISSUE THREAD

**Issue by SyirNick** [shtrih-m/fr_drv_ng#255]
По вашему гайдлайну сгенерировал оболочку для C#, но при попытке обращения к библиотеке получаю ошибку:

EntryPointNotFoundException: Unable to find an entry point named 'SWIGRegisterExceptionCallbacks_classic_fr_drv_ng' in DLL 'classic_fr_drv_ng_csharp'.

Вроде бы ничего такого, зачем мне exception handler от SWIG. Но если выпилить этот кусок кода, начинаю получать странную ошибку:

EntryPointNotFoundException: 'Unable to find an entry point named '?' in DLL 'classic_fr_drv_ng_csharp'.'

Судя по вызову PInvoke, он пытается создать экземпляр класса classic_interface, обращаясь к entry point "CSharp_rufshtrih_mffr_drv_ngfclassic_interface_new_BytesVector__SWIG_0___" из сгенеренной SWIGом оболочки. Судя по Lib файлу, никаких точек входа, начинающихся хотя бы с CSharp, в dll нет, если же вручную сменить entry point на "classic_interface", ошибка остаётся.

Вопрос в том, как заставить работать библиотеку под C# - нужна какая-то другая библиотека или есть иной способ генерации оболочки?

Библиотеку планируем использовать в .NET Core 7, win x86_x64

**Comment by olefard** [comment]
А вообще у вас есть classic_fr_drv_ng_csharp.dll? В ней должна быть куча методов, начинающихся с CSharp.

Рядом с exe должно быть 2 dll:
- classic_fr_drv_ng.dll (сам драйвер)
- classic_fr_drv_ng_csharp.dll(с++ часть обертки, сгенерированной SWIG)

на шаге 2 инструкции https://github.com/shtrih-m/fr_drv_ng_examples/tree/master/classic_csharp
дано содержимое CMakeLists.txt для сборки обертки SWIG
ее надо собрать cmake`ом и получить  classic_fr_drv_ng_csharp.dll

**Comment by SyirNick** [comment]
Спустя все тернии и звёзды, удалось собрать всё как надо. Наткнулся на две больших затычки (вдруг кто-нибудь с ними тоже столкнётся):

1) Проверяйте битность собранной библиотеки, скачанной библиотеки и ваших проектов. Студия может внезапно посчитать AnyCPU за х86, например, или выдать чего ещё экзотичнее. Из-за несоответствия битности будет выброшен BadImageFormatException: Была сделана попытка загрузить программу, имеющую неверный формат. (0x8007000B).

2) SWIG 15 лет имеет на борту баг, который исправлять не собираются, из-за которого будет вылетать System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt. Тут дело в том, что std::string != System.String, но разработчики SWIG в дефолтных настройках генератора для C# считают иначе. А вот информация по адресу переменной char * вполне приравнивается к System.String, поэтому в файле [swig directory]\Lib\csharp\std_string.i нужно сделать [вот так](https://github.com/swig/swig/issues/998#issuecomment-307607551).
