### ISSUE TITLE
Модифицируемое свойство StringForPrintingTLVData

### ISSUE THREAD

**Issue by kolombina** [shtrih-m/fr_drv_ng#256]
У метода FNGetDocumentAsString() есть модифицируемое свойство StringForPrintingTLVData, но нет геттера (Get_StringForPrintingTLVData)
Как получить значение этого свойства?
Что значит # перед названием этого свойства в документации?

**Comment by swex** [comment]
1. Такого свойства нет, правильное имя свойства `StringForPrinting`, где вы нашли `StringForPrintingTLVData`?  Лучше смотреть актуальный classic_interface.h который в каждом релизе в архиве.
2. classic_interface.h в можно использовать в doxygen и # там, для того чтобы ссылаться

**Comment by kolombina** [comment]
Смотрела методы в Вашем репозитории (https://github.com/shtrih-m/fr_drv_ng/wiki/Methods_Information#group___information_1gab312593abe7ee165aa1dc31fb3687954)
Но в classic_interface.h его нет, так что вопрос отпадает, так понимаю
Спасибо за быстрый ответ
