### ISSUE TITLE
Запуск run-http-api-server

### ISSUE THREAD

**Issue by SergeyZemlyanoy** [shtrih-m/fr_drv_ng#261]
Добрый день.
Скачал последний релиз. Версия под линукс x86. 
Приложение console_test при запуске в режиме вебсокет-сервера работает, все как в описании.
При запуске в режиме HTTP REST API сервера (run-http-api-server), на запросы в разных вариациях отвечает 404-ошибкой. Описания работы в этом режиме не нашел. Нет данных о endpoint-ах и методах, с которыми работает сервер. Сможете помочь?

**Comment by swex** [comment]
конечно! этот режим работы нужен для того чтобы выполнить несколько команд теста внутри одного подключения к ККТ.

```bash
curl http://127.0.0.1:8888/console_command --data '{"command": "write","args": "2.1.2","params":"Первый кассир"}'
```

**Comment by SergeyZemlyanoy** [comment]
Ок, заработало. Спасибо.
Я правильно понял, что этот режим (run-http-api-server) для полноценной работы не подходит?

**Comment by swex** [comment]
Да, вообще эта программа изначально предполагалась только для автоматизаций в скриптовых окружениях. 
Далее добавился режим этот режим (run-http-api-server) для того чтобы последовательность команд можно было вызвать внутри одной сессии. Это удобно потому что другой процесс, например кассового ПО, не может подключиться к TCP сокету пока он занят, а если каждую команду выполнять в отдельным вызовом console_test то может быть гонка за подключение..
Позже появился режим json-rpc для работы с классическим интерфейсом.
