### ISSUE TITLE
Как использовать hex-cmd?

### ISSUE THREAD

**Issue by v0d0m3r** [shtrih-m/fr_drv_ng#263]
Мы пытались выполнить команду Гудок в виде hex-строки. 
console_test_fr_drv_ng hex-cmd "02 05 13 01 00 00 00 17"
На что получили следующий ответ:
"Неверное значение в поле длины"
Как правильно пользоваться данной командой?

Из описания:
 hex-cmd - "send some data thru transport layer"
 args: hex encoded string: eq: "AB CD EF"
Кажется мы выполнили в соответствии с описанием.

**Comment by swex** [comment]
Без служебных байт протокола. Только тело команды. Протоколов у нас как синимум 2. Эта команда работает уже поверх на след. уровне.

**Comment by v0d0m3r** [comment]
Спасибо!
