### ISSUE TITLE
Выполнение сборки 

### ISSUE THREAD

**Issue by XmasL** [shtrih-m/fr_drv_ng#266]
Выполняя setup.py под Windows получаю след ошибку как быть?  

warning: I don't know what to do with 'runtime_library_dirs': ['E:\\ShtrixM']
error: don't know how to set runtime library search path for MSVC

**Comment by swex** [comment]
не знаю какая у вас версия setuptools, ну просто удалите соотв. строку из setup.py

**Comment by XmasL** [comment]
В этом случае пишется такая ошибка 
![Безымянный222](https://github.com/shtrih-m/fr_drv_ng/assets/49500511/264724b0-a803-4aa3-824f-661deaa8b7e6)

**Comment by swex** [comment]
[здесь](https://stackoverflow.com/questions/63112246/how-to-specify-the-dynamic-library-location-when-writing-a-setup-file-for-python) инфа как это пофиксить

**Comment by XmasL** [comment]
Спасибо. Еще вопрос результат сборки должен быть в формате dll? После исправления в папке build\lib.win-amd64-cpython-311  появилось два файла _fr_drv_ng.cp311-win_amd64.pyd и fr_drv_ng.py

**Comment by swex** [comment]
ну да, pyd это результат и есть. Оно на самом деле просто dll, почему-то в python решили такое расширение давать под windows... по идее после setup.py install нужные библиотеки уже должны оказаться в необходимых путях. После успешной установки через install можно пользоваться библиотекой.
```python3
from fr_drv_ng import classic_interface
```

**Comment by swex** [comment]
Вы пытаетесь прикрутить python обертку к .net? Это пожалуй зря.

я бы посоветовал вам прикрутить драйвер поверх [json-rpc](https://github.com/shtrih-m/fr_drv_ng_examples/tree/master/classic_jsonrpc). 
И вот [.net библиотека](https://github.com/microsoft/vs-streamjsonrpc)

**Comment by swex** [comment]
ну так по этой ссылке и есть инструкция как собирать под C#, а вы почему-то про python начали...
Вообще с генерацией оберток под C# были проблемы,  но люди решали см. [пост](https://github.com/shtrih-m/fr_drv_ng/issues/255)
