### ISSUE TITLE
Установка драйвера для 1с на Линукс

### ISSUE THREAD

**Issue by dalvinsky** [shtrih-m/fr_drv_ng#279]
Здравствуйте.

Понимаю, что вопрос, возможно, звучит наивно.

Но не могли бы вы объяснить по шагам, как устанавливать ваш драйвер в 1с на линуксе.

Что куда копировать или что запускать?

1с при попытке создания ккт с передачей данных говорит, что ей нужна установка внешней компоненты "ШТРИХ-М:ККТ с передачей данных в ОФД  (ФФД 1.2) 5.17", дальше, если нажать "Установить и продолжить", она, конечно, ничего не находит.

1с управление торговлей 11.5

**Comment by surfernsk** [comment]
![Screenshot_20240303_121408](https://github.com/shtrih-m/fr_drv_ng/assets/2264893/d78e6438-344e-4964-9f34-3b5088341027)

**Comment by dalvinsky** [comment]
Спасибо огромное! Получилось подключить.

Единственный вопрос - у вас для скачивания есть два разных файла:

one_s_fr_drv_ng_32_1.6.0-19-g75d85c5.zip
one_s_fr_drv_ng_40_1.6.0-19-g75d85c5.zip

а в чём у них разница?

**Comment by swex** [comment]
Здравствуйте, у 1С есть версии требований к драйверам. Архив с суффиксом 32 - Драйвер, совместимый с требованиями версии 3.2, суффикс 40 - соответственно 4.0.

**Comment by dalvinsky** [comment]
Спасибо! Всё понятно.
