### ISSUE TITLE
чек коррекции. Получить TaxType, чтобы передать в FNBeginCorrectionReceipt

### ISSUE THREAD

**Issue by try2bajed1** [shtrih-m/fr_drv_ng#28]
если не выставить корректное значение Set_TaxType  , то чек коррекции не распечатается. Т.е до печати чека мне нужно вытащить из таблицы это значение. КАк извлекать строки и числа я понял, а как быть, если возвращается массив байтов? 
метод  Get_TaxType() мне возвращает 0, хотя у меня упрощенная система налогообложения и по идее я должен получать 2.

**Comment by olefard** [comment]
>Т.е до печати чека мне нужно вытащить из таблицы это значение.

Это не массив байт, это битовое поле. Читается из таблицы, как обычное число.
Единственное, что ККТ может быть зарегистрирована на несколько систем налогообложения и передать значение напрямую не выйдет. Надо будет оставить только одну систему.

> метод Get_TaxType() мне возвращает 0, хотя у меня упрощенная система налогообложения и по идее я должен получать 2.

Это не метод, это геттер для свойства. Чтобы он вернул правильное значение, кто-то должен его в свойство записать: программист или какой-либо метод драйвера.

**Comment by try2bajed1** [comment]
Да, с извлечением как инт сработало.  А каким образом узнать, что их несколько и как это определить? Пообщался с нашей техподдержкой, они говорят что случаи, когда несколько сно , пусть нечасто, но бывают

**Comment by olefard** [comment]
Если в числе установлено несколько битов, значит несколько СНО. Какие биты установлены, на такие СНО зарегистрованы.
Типа 45 = 32 + 8 + 4 + 1 => ПСН + ЕНВД + УСНДМР + ОСН

**Comment by try2bajed1** [comment]
спасибо, остается только накидать алгоритм )
