### ISSUE TITLE
Не переносятся длинные строки

### ISSUE THREAD

**Issue by SnakePliskin777** [shtrih-m/fr_drv_ng#283]
Доброго!

Столкнулся с проблемой печати длинных строк и их переносом.
Нашел похожий случай [https://github.com/shtrih-m/fr_drv_ng/issues/126](https://github.com/shtrih-m/fr_drv_ng/issues/126), но что то не выходит каменный цветок. Подсобите пж советом. Если нужна доп. информация готов предоставить. Просто не хочется хардом бить строки, сами то девайсы на ванильном тест-драйвере строки переносят норм.

Заранее спасибо!

**Comment by olefard** [comment]
Нужен лог драйвера с печатью длинных строк.

**Comment by SnakePliskin777** [comment]
[fr_drv_ng.log](https://github.com/shtrih-m/fr_drv_ng/files/15065971/fr_drv_ng.log)
на печать выводит одну строку: **Столкнулся с проблемой печати длинных строк и их**

**Comment by olefard** [comment]
Вот так у меня переносит:
```
ci->Set_UseReceiptRibbon(true); //чековая лента
ci->Set_WrapStrings(true);
ci->Set_StringForPrinting("Столкнулся с проблемой печати длинных строк и их переносом");
ci->PrintString();
```

**Comment by SnakePliskin777** [comment]
спасибо. это работает. 
кстати запечатало еще вот так (посмотрел в логе ванильной версии тест-драйвера), но вариант выше работает лучше:
```
ci.UseReceiptRibbon = true;
ci.CarryStrings = false;
ci.DelayedPrint = false;
ci.UseSlipCheck = false;
ci.StringForPrinting ="Столкнулся с проблемой печати длинных строк и их переносом";
ci.PrintString();
```
