### ISSUE TITLE
Ошибка при закрытие чека

### ISSUE THREAD

**Issue by SnakePliskin777** [shtrih-m/fr_drv_ng#285]
Приветствую!
Столкнулся с ошибкой при закрытие чека в определенной ситуации, а именно после открытия открытии смены в по закрытие чека завершается ошибкой **Некорректные параметры в команде (51)** (файл fr_drv_ng_BAD.log), но если перезапустить по при открытой смене закрытие чека происходит норм (файл fr_drv_ng_OK.log). самое парадоксальное, что данные на вход одни и те же. подскажите, где мог накосячить? заранее спасибо.
[fr_drv_ng_BAD.log](https://github.com/shtrih-m/fr_drv_ng/files/15414723/fr_drv_ng_BAD.log)
[fr_drv_ng_OK.log](https://github.com/shtrih-m/fr_drv_ng/files/15414724/fr_drv_ng_OK.log)

**Comment by olefard** [comment]
Выложите, пожалуйста, полные логи: от старта до ошибки и от старта до закрытия чека.

**Comment by SnakePliskin777** [comment]
я бы с удовольствием, но теперь даже смена не открывается ) 
[fr_drv_ng.log](https://github.com/shtrih-m/fr_drv_ng/files/15416482/fr_drv_ng.log)

**Comment by olefard** [comment]
Дата прошивки: 2019-04-29
Лучше обновить на более актуальную.

**Comment by SnakePliskin777** [comment]
ок. скажу эксплуатации, пусть займется. вот здесь я игнорирую 94 ошибку и далее по задаче.
[fr_drv_ng.log](https://github.com/shtrih-m/fr_drv_ng/files/15416787/fr_drv_ng.log)

зы. есть какая то связь с записью любых данных в таблицу, перед открытием смены. если их убрать - все ок. 

ззы. в общем методом научного тыка выяснил, что если просто писать в таблицу, к примеру во 2 - ю, фио кассира, то последующая продажа будет неудачной. а если после записи в таблицу ее **прочитать**, то будет все ок. как то так )
