### ISSUE TITLE
Не нашли возможность вообще не передавать тег 1030 (Наименование товара)

### ISSUE THREAD

**Issue by kitamew** [shtrih-m/fr_drv_ng#288]
Приветствую. Вопрос касательно вот этой цитаты из ФФД "Реквизит "наименование предмета расчета" (тег 1030) включается в состав ФД, за исключением случая, когда реквизит "признак способа расчета" (тег 1214) имеет значение, равное "3".", то есть при авансах тега 1030 вообще не должно быть. У StringForPrinting есть примечание как не печатать название, но в ОФД передавать (***если строка начинается символами //, то она передаётся на сервер ОФД но не печатается на кассе.
). А есть возможность и не печатать и не передавать в ОФД?

**Comment by olefard** [comment]
Требуется прошивка ККТ новее, чем 04.12.2023

Тогда просто передаете пустой StringForPrinting, аванс и ККТ не формирует тег 1030.

**Comment by kitamew** [comment]
Спасибо! А напомните заодно, пожалуйста, для тестирования и разработки (с МГМ ФН) прошивку надо брать с ключами или без?

**Comment by olefard** [comment]
Насколько я знаю, прошивку надо брать ровно такую, какая у вас сейчас(с ключами или без). Другая просто не прошьется.

**Comment by kitamew** [comment]
Спрошу у общей технической поддержки тогда, спасибо.
