### ISSUE TITLE
Вопрос по отчетам: X-отчет и Отчет о расчетах

### ISSUE THREAD

**Issue by ConsperSerj** [shtrih-m/fr_drv_ng#289]
Добрый день. Имеется ффд 1.2

нужно поддержать X-отчет и Отчет о расчетах. В документации не могу разобраться какой метод относится к чему. 
Если я правильно понимаю то X-отчет это PrintReportWithoutCleaning(), тогда какой метод нужно вызывать для отчета о расчетах. Подскажите пожалуйста

@swex

**Comment by swex** [comment]
см. метод `FNBuildCalculationStateReport`

**Comment by ConsperSerj** [comment]
спасибо.
