### ISSUE TITLE
Параметры шрифта

### ISSUE THREAD

**Issue by susloparov77** [shtrih-m/fr_drv_ng#29]
Здравствуйте как мне правильно получить:

        m_ci.Set_FontType(1);
        int width = m_ci.Get_PrintWidth();
        int widthChar = m_ci.Get_CharWidth();

Нужно узнать сколько символов в строке при печати свободной строкой?

**Comment by olefard** [comment]
int charCount = width / widthChar;
Только между первой и второй строками надо вставить вызов метода GetFontMetrics.

**Comment by susloparov77** [comment]
Почему FontType не на что не влияет, размер всегда одинаковый?? Печатается чек только если FontType от 1 до 7 все другие номера от 0..255 не ставятся?? Это нормально?

**Comment by swex** [comment]
На что именно не влияет? Какой  метод используете? Что ждёте что получаете? Давайте лог.
Думается мне что  Вам нужен метод `PrintStringWithFont`...

**Comment by susloparov77** [comment]
FА можно пример простой с PrintStringWithFont???

**Comment by susloparov77** [comment]
А можно простой пример PrintStringWithFont?

**Comment by susloparov77** [comment]
Вместо PrintString использую PrintStringWithFont??

**Comment by swex** [comment]
Чем документация не пример? Есть метод, есть свойства, Вы попробуйте и заработает!

**Comment by swex** [comment]
> Вместо PrintString использую PrintStringWithFont??

Именно. Когда Вы использовали `FontType` и метод `PrintString` - это нормально что `FontType` ни на что не влиял. Т.к. он и не должен был.

**Comment by susloparov77** [comment]
Все спасибо
