### ISSUE TITLE
Неподдерживаемые методы

### ISSUE THREAD

**Issue by Karnah** [shtrih-m/fr_drv_ng#291]
Добрый день! Можете, пожалуйста, актуализировать [документацию](https://github.com/shtrih-m/fr_drv_ng/wiki/Unimplemented-Methods) по данным методам? Не поддержаны ли они до сих и планируется ли вообще поддержка?
1. DBPrintDocument
2. WideLoadLineData
3. PrintZReportInBuffer
4. PrintZReportFromBuffer

**Comment by swex** [comment]
Здравствуйте! 
1. DBPrintDocument в этом драйвере не ведется база данных документов и не планируется
2. WideLoadLineData сейчас не поддерживается, можно добавить, но метод устаревший, лучше использовать LoadGraphics512.
3. PrintZReportInBuffer поддерживается
4. PrintZReportFromBuffer поддерживается

**Comment by Karnah** [comment]
Отлично, спасибо большое!
