### ISSUE TITLE
Регистрация ффд

### ISSUE THREAD

**Issue by ConsperSerj** [shtrih-m/fr_drv_ng#292]
Добрый день. При попытке регистрации кодом получаю ошибку 

Пытаюсь выполнить код

 Set_ReportTypeInt(0)
 FNBeginRegistrationReport()
 
 Получаю ошибку: 
 
Код ошибки 33h (51) от ККТ: Некорректные параметры в команде <0x00330091: указан неверный код версии ФФД: КЯ поддерживает ФФД 1.05 (код 2) и ФФД 1.2 (код 4)>

Подскажите пожалуйста как передать данный код? Или в какую таблицу записывать данный код?

@swex @surfernsk

**Comment by finkonsk** [comment]
@ConsperSerj Ваш вопрос не относиться к драйверу.

Изучите "Общее руководство по настройке ККТ". [Для ККТ](https://doc.shtrih-m.ru/Files/manual.pdf), [Для ККТ на базе КЯ](https://doc.shtrih-m.ru/Files/cc.pdf)

Ответ на Ваш вопрос описан в разделе "Регистрация ККТ, оформление отчета о регистрации"

**Comment by ConsperSerj** [comment]
@finkonsk Из руководства по настройке ККТ, это как настраивать регистрацию руками.

У меня имеется PAX А930. Разрабатывается android приложение в котором есть кнопка зарегистрировать ККТ, то есть провести первичную регистрацию

Если изучить документацию https://doc.shtrih-m.ru/Files/Programmer.pdf, то там написано что для начала процесса регистрации нужно вызвать FNBeginRegistrationReport, но перед этим указать пароль админа и ReportTypeInt.

И вот имеем код:
Set_Password(SYS_ADMIN_PASSWORD)
Set_ReportTypeInt(0)
var codeResult = executeCommand { FNBeginRegistrationReport() }

После чего от КЯ в логу приходит ошибка код 51 и текст Код ошибки 33h (51) от ККТ: Некорректные параметры в команде <0x00330091: указан неверный код версии ФФД: КЯ поддерживает ФФД 1.05 (код 2) и ФФД 1.2 (код 4)>

Вопрос именно в том как мне кодом указать "код версии ФФД" чтобы метод FNBeginRegistrationReport отработал нормально?

В документациях которые скинули вы я что-то не вижу вообще каких то методов работы с КЯ посредсвам кода

**Comment by ConsperSerj** [comment]
Я кажись понял. вы о том что в таблицу 10 в поле 29 нужно кодом положить нужное значение. Так ли это?

**Comment by finkonsk** [comment]
> Я кажись понял. вы о том что в таблицу 10 в поле 29 нужно кодом положить нужное значение. Так ли это?

да.
в том числе о фискальном накопителе, и иные сведения (путем
программирования строк 7-15, 21 (для включения режима работы «Торговля
маркированными товарами установить значение - 16) в Таблице 13

**Comment by finkonsk** [comment]
> @finkonsk Из руководства по настройке ККТ, это как настраивать регистрацию руками.
> 
Данное руководство описывает как работать с ККТ, в том числе как регистрировать и т.д.

> Если изучить документацию https://doc.shtrih-m.ru/Files/Programmer.pdf, то там написано что для начала процесса регистрации нужно вызвать FNBeginRegistrationReport, но перед этим указать пароль админа и ReportTypeInt.
> 
Это руководство описывает методы доступные разработчику при использовании драйвера. Но не как работать с кассовой техникой!
