### ISSUE TITLE
Интеграция Штрих Smart Pos

### ISSUE THREAD

**Issue by susloparov77** [shtrih-m/fr_drv_ng#3]
Здравствуйте, вас беспокоят с проекта Альфа-касса, по договоренности с вами мы занимаемся подключением Штрих Smart Pos, не могли бы вы пояснить ряд вопросов?

1) Где можно получить описание пакета для релизов?
https://github.com/shtrih-m/fr_drv_ng/releases
2) Где можно получить ссылки на примеры?
3) Скажите есть ли у вас отладочный удаленный сервер для отладки ? Если есть IP и порт?
4) Для подключения под андройд из Qt мы должный использовать
- libqclassic_fr_drv_ng.so
- qclassic_interface.h это так, их достаточно?

**Comment by swex** [comment]
Здравствуйте,

1. Обновил [README.md](https://github.com/shtrih-m/fr_drv_ng/blob/master/README.md), большинство вопросов должно снять
2. Примеры [здесь](https://github.com/shtrih-m/fr_drv_ng_examples)
3. Такого нет, а что должен из себя представлять такой сервер?  Можно взять МГМ, вставить его в Smart Pos - это и будет отладочный сервер. КЯ(Кассовое Ядро) доступно по сети, можно отлаживаться по сети.
4. Да, достаточно, но qclassic_fr_drv-ng линкуется с classic_fr_drv_ng, а classic_fr_drv_ng с cppbase_fr_drv_ng. Поэтому нужно все 3 библиотеки. 
QClassic  - это обёртка над classic где свойства и методы обёрнуты в Qtшные Q_PROPERTY и слоты. Если не требуется данный функционал - можно остановиться на classic.

**Comment by susloparov77** [comment]
Спасибо

**Comment by susloparov77** [comment]
Здравствуте, есть OpenSession а как закрыть смену?

**Comment by swex** [comment]
Посмотрите [FAQ](https://github.com/shtrih-m/fr_drv_ng/wiki/%D0%A7%D0%B0%D1%81%D1%82%D0%BE-%D0%B7%D0%B0%D0%B4%D0%B0%D0%B2%D0%B0%D0%B5%D0%BC%D1%8B%D0%B5-%D0%B2%D0%BE%D0%BF%D1%80%D0%BE%D1%81%D1%8B-%D0%BF%D1%80%D0%BE-classic_fr_drv_ng) Смена закрывается вместе с Z-отчетом. Необходимо снять отчет с гашением.  
PS: Лучше заводить новую issue, наверняка кому-то пригодится.
