### ISSUE TITLE
Регистрация ФН

### ISSUE THREAD

**Issue by susloparov77** [shtrih-m/fr_drv_ng#32]
Здравствуйте, обновили релиз стало ломаться на записи поля 21, подскажите плиз как теперь это делать правильно?? Лог прилагаю.
[fr_drv.log](https://github.com/shtrih-m/fr_drv_ng/files/2662413/fr_drv.log)

**Comment by olefard** [comment]
Поле 21 стало только для чтения после обновления КЯ.
Теперь вместо записи в это поле надо передавать теги.

Вы в поле 21 пишете 0 , то есть вам не нужны никакие спец режимы? Тогда просто не передаете теги.

**Comment by susloparov77** [comment]
У мня было так:
//======================
        QString mode(  QString::number(__fiscalize->m_printer_auto) +   //1221 продажа подакцизного товара
                       QString::number(__fiscalize->m_lottery) +  //1126 признак проведения азартных игр
                       QString::number(__fiscalize->m_azart) + //1193 признак проведения лотереи
                       QString::number(__fiscalize->m_excise) ); //1207 признак установки принтера в автомате
        if(!writeFiscalInt(mode.toInt(nullptr, 2), fnTableNumber, 21)) return;
//======================

Теперь все эти поля мы просто пишем тегами так??? 
А по полю номер 16 тоже тегами или осталось как раньше??

**Comment by olefard** [comment]
Да, сейчас тегами.
И 16 тоже только для чтения, его тоже тегами.

**Comment by susloparov77** [comment]
А bool Теги пишем через Set_TagValueInt??? 0 - false Запишется туда???

**Comment by olefard** [comment]
Из ФФД:

Тег  | Наименование реквизита     | Тип  | Формат ЭФ | Формат ПФ | Фикс. | Длина | Примечание
-----|----------------------------|------|-----------|-----------|-------|-------|-----------
1126 |признак проведения лотереи  |Целое | byte      | -         | Да    | 1     | Принимает значения "1" или "0". При начении "0" реквизит не включается в состав ФД в ПФ.

То есть Set_TagType(0) и Set_TagValueInt(1 для true и 0 для false);

**Comment by susloparov77** [comment]
Подскажите плиз тег 1057 как пишем как int16 или int 32?
//===============================================
    __tag = 1057
    m_ci.Set_TagNumber(__tag);
    m_ci.Set_TagType(2); //Тип "байт"
    m_ci.Set_TagValueInt(__value);
    return execute(std::bind(&classic_interface::FNSendTag, &m_ci));
//===============================================
Какой тип в Set_TagType

**Comment by Mzales** [comment]
0
```c++
m_ci.Set_TagType(0); //Тип "byte"
```
