### ISSUE TITLE
Соответствие команд и методов

### ISSUE THREAD

**Issue by atolstykh** [shtrih-m/fr_drv_ng#35]
Можно ли как-то увидеть соответствия между номерами команд и методами сi?
Т.е. мне известна команда, например, 0xE0 (открытие смены). Мне нужно установить название метода (ci.OpenSession).
Или возможно существует метод, к которому можно обращаться по номеру команды?

**Comment by atolstykh** [comment]
Мы раньше использовали команды ККТ
    int GET_PRINTER_STATE = 0x11;
    int PRINT_BOLD_TEXT = 0x12;
    int PRINT_NORMAL_TEXT = 0x17;
    int PRINT_HEADER = 0x18;
    int REPORT_X = 0x40;
    int CUT_CHECK = 0x25;
    int REPORT_Z = 0x41;
    int PRINT_FOOTER = 0x53;
    int SELL = 0x80;
    int REVERT = 0x82;
    int CLOSE_CHECK = 0x85;
    int CANCEL_CHECK = 0x88;
    int OPEN_CHECK = 0x8D;
    int OPEN_MONEY_BOX=0x28;
    int SEND_BARCODE_LINE = 0xC0;
    int PRINT_BARCODE = 0xC1;
    int EXTENDED_PRINT_BARCODE = 0xC3;
    int EXTENDED_SEND_BARCODE_LINE = 0xC4;
    int OPEN_SHIFT = 0xE0;
    int GET_SERIAL_NUMBER = 0x11;
    int GET_MODEL = 0xFC;
    int GET_TABLE_FIELD = 0x1F;
    int INPUT = 0x50;
    int WITHDRAWAL = 0x51;
    int GET_RNM_NUMBER = 0x0F;
    int GET_MONEY_REGISTER = 0x1A;
Что является их аналогами в classic_interface? И возможности обращаться по этим командам сейчас нет?

**Comment by successeven** [comment]
Добрый день. 
Почему на чеке печатается 2 раза строка с Email отправителем при использовании метода FNSendSenderEmail?
