### ISSUE TITLE
GetDeviceMetrics

### ISSUE THREAD

**Issue by atolstykh** [shtrih-m/fr_drv_ng#36]
Из-за чего может не работать GetDeviceMetrics? Лог следующий:

V/fr_drv_ng: [2018-12-12 18:17:48.234] [3202] [classic_interface_0x89ba2000    ] [T] GetDeviceMetrics()
D/fr_drv_ng: [2018-12-12 18:17:48.234] [3202] [ProtocolV1_0x8e07e880           ] [D] command FC return code: -1 execution took 0ms
E/fr_drv_ng: [2018-12-12 18:17:48.234] [3202] [ProtocolV1_0x8e07e880           ] [E] Inout error
D/fr_drv_ng: [2018-12-12 18:17:48.234] [3202] [ProtocolV1_0x8e07e880           ] [D] commands total: 1, succeed: 0, failed: 1, avg. exec time: 0ms
D/fr_drv_ng: [2018-12-12 18:17:48.235] [3202] [classic_interface_0x89ba2000    ] [D] GetDeviceMetrics() fail
E/fr_drv_ng: [2018-12-12 18:17:48.235] [3202] [classic_interface_0x89ba2000    ] [E] Inout error
I/com.iretail.app.services.SynchronizationService: 18:18:09.118 [Timer-0] INFO  c.i.a.s.SynchronizationService - Launch synchronization actions

Хотя, например, метод внесения наличных работает.

**Comment by swex** [comment]
Судя по логу это первая же команда. Похоже Вы пропустили Connect...
