### ISSUE TITLE
BarCode

### ISSUE THREAD

**Issue by atolstykh** [shtrih-m/fr_drv_ng#37]
Можно где-то посмотреть минимальный набор команд печати одно-и двумерного штрих-кода? Возможные типы: QR_CODE, PDF417, CODE128.
Код
ci.Set_BarWidth(width);
ci.Set_LineNumber(height);
ci.Set_BarCode(text);
ci.Set_BarcodeType(3);
ci.Print2DBarcode();
возвращает 51ю ошибку

**Comment by swex** [comment]
Есть примеры печати ШК в [примерах](https://github.com/shtrih-m/fr_drv_ng_examples/blob/master/classic_interface/main.cpp)
