### ISSUE TITLE
 Email отправителя

### ISSUE THREAD

**Issue by successeven** [shtrih-m/fr_drv_ng#38]
Добрый день.
Почему на чеке печатается 2 раза строка с Email отправителем при использовании метода FNSendSenderEmail? ФР Штрих М - 01ф

**Comment by swex** [comment]
Здравствуйте.
Не должно быть такого.  Нужен лог? и что в таблице 17.12 "RUS ПЕЧАТЬ РЕКВИЗИТОВ ПОЛЬЗОВАТЕЛЯ"?

**Comment by successeven** [comment]
В таблице прописано значение "1". Правильно ли это? 
А то в мануале с сайта не нашел ничего об этом методе

**Comment by swex** [comment]
RUS ПЕЧАТЬ РЕКВИЗИТОВ ПОЛЬЗОВАТЕЛЯ это битовая маска, в зависимости от нее ФР решает будет ли он печатать различные теги. `FNSendSenderEmail` проверяет эту маску и если не выставлен бит - печатает методом печати строки из драйвера, иначе печатает сам ФР.
Почему у вас печатается 2 строки по-прежнему непонятно. Давайте лог.

**Comment by successeven** [comment]
так, про маску понял. подставил значение 63. если правильно понял это "печать все".
нашел этот пункт в "Общее руководство по настройке ККТ"
Ноб на странице 60 (где описание таблиц) указано что принимает значение от 0 до 63, а на странице 63, где расписана маска, описывается только 32 значения. где могу найти описание всех значений?

**Comment by Mzales** [comment]
Посмотрите в Таблице 17 "Региональные настройки" поле 18 "Rus компактный заголовок". Если значение этого поля 2-5, то e-mail отправителя и e-mail покупателя уже включаются в заголовок чека. И, если их печать дополнительно установлена через поле 12 "Rus печать реквизитов пользователя", то они задваиваются.

**Comment by successeven** [comment]
> Посмотрите в Таблице 17 "Региональные настройки" поле 18 "Rus компактный заголовок". Если значение этого поля 2-5, то e-mail отправителя и e-mail покупателя уже включаются в заголовок чека. И, если их печать дополнительно установлена через поле 12 "Rus печать реквизитов пользователя", то они задваиваются.

Добрый день. Спасибо за ответ! 
Нет, стоит значение 0. Как описал в предыдущем сообщении, при установки значения 63 в поле 12, то все ок. печатает 1 раз. но полное описание значений от 0 до 63 так и не нашел...

**Comment by Mzales** [comment]
Что касается битового поля 12:
оно указывает, что печатать, а что нет, в заголовке чека. Сам текст, который будет напечатан, берется из Таблицы 18 или из тегов.
Там, действительно, значения могут быть от 0-31. Физически ФР дает поставить значения до 63, но это не используется.
00001 = 1 - печатать только user
00010 = 2 - печатать только address
00100 = 4 - печатать только место расчета
01000 = 8 - печатать только адрес отправителя
10000 = 16-печатать только адрес покупателя
10101 = 21-печатать адрес покупателя, место расчета и user
11111 = 31 - печать все

**Comment by Mzales** [comment]
Еще Вы можете узнать "кто" напечатал Email.
Фр (могут отличаться) печатает примерно так: 

> Эл.адр.отправителя:                                      1@1.org

А драйвер примерно так:    

> ЭЛ.АДР.ОТПРАВИТЕЛЯ: 1@1.org

**Comment by successeven** [comment]
Я вас понял. Спасибо большое. 
Поставил значение 31, вроде все норм стало. изначально было 0.
