### ISSUE TITLE
Получение фискальных признаков

### ISSUE THREAD

**Issue by susloparov77** [shtrih-m/fr_drv_ng#39]
Здравствуйте, подскажите как получить фискальные признаки:
1. Максимальный платёж
2. Наименование ОФД
3. ИНН ОФД
4. Фискальный признак документа (getDocFiscalSign)

**Comment by swex** [comment]
Здравствуйте
1. Это что?
2. В таблице Фискальный накопитель поле 10.
```c++
ci->Set_ModelParamNumber(classic_interface::DPE_FsTableNumber);
checkResult(ci->ReadModelParamValue());
auto fsTableNumber = ci->Get_ModelParamValue();
```
3. В таблице Фискальный накопитель поле 12.
4. См. свойство `FiscalSign`. Там есть список методов которые его модифицируют.

**Comment by susloparov77** [comment]
А 2 и 3 А Set_RowNumber что ставить??

**Comment by swex** [comment]
1. Зависит от метода.  Для рекомендованных ФН методов FNOperation FNCloseCheckEx  это 0xFFFFFFFFFF  копеек

**Comment by swex** [comment]
> А 2 и 3 А Set_RowNumber что ставить??

1.

**Comment by Yurta-** [comment]
Добрый день.
А как получить адрес сайта ФНС (тег 1060)?
