### ISSUE TITLE
Вопросы по реализации ПО

### ISSUE THREAD

**Issue by susloparov77** [shtrih-m/fr_drv_ng#4]
Здравствуйте, подскажите, как получить и выполнить:
1) Как напечатать X-отчет
2) Как получить адрес магазина
3) ИНН Магазина
4) Название магазина
5) Номер текущей кассовой смены
6) Сумму в денежном ящике
7) Серийный номер ККТ
8) Текущее время с ККТ
9) Правильно я понял что печать Z-Отчета закрывает смену?

**Comment by swex** [comment]
1: PrintReportWithoutCleaning  
2, 3, 4: GetFiscalizationParameters
5: GetECRStatus, SessionNumber
6: Через денежные регистры GetCashReg и GetCashRegEx, список регистров в [общем руководстве на ККТ](https://www.shtrih-m.ru/docs/download.php?file=28008&iblock=21)
7: GetECRStatus, SerialNumber
8: GetECRStatus, Time

**Comment by susloparov77** [comment]
Здравствуйте, classic_interface ci; как лучше инициализировать одну глобальную переменную или создавать его локально для каждой операции в процедуре?

**Comment by susloparov77** [comment]
Подскажите где можно посмотреть ci.GetECRStatus() Коды ошибок?

**Comment by swex** [comment]
> Здравствуйте, classic_interface ci; как лучше инициализировать одну глобальную переменную или создавать его локально для каждой операции в процедуре?

Создавать по мере необходимости. Для каждого ФР с которым работаете придется создать по одному classic_interface.


> Подскажите где можно посмотреть ci.GetECRStatus() Коды ошибок?

В общем руководстве. Так же можно получить описание ошибок методом: ReadErrorDescription

**Comment by susloparov77** [comment]
Подскажите у нас устройство SHTRIH-SMARTPOS-F:
Как мне правильно проинициировать локальное подключение IP порт или по другому:
Я не знаю какой порт используется, IP 127.0.0.1 так?
classic_interface ci;
ci.Set_ConnectionType(classic_interface::TConnectionType::Tcp);
ci.Set_UseIPAddress(true);
ci.Set_IPAddress("192.168.0.1");
ci.Set_TCPPort(12345);
ci.Set_Timeout(4848);
ci.Set_ProtocolType(1);
int ret = ci.Connect();

**Comment by swex** [comment]
Порт по умолчанию, да 12345.
Если служба cashcore запущена - всё будет ок.
Вот [wiki](https://github.com/shtrih-m/fr_drv_ng/wiki/%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80.-%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%82%D1%8C-%D1%81%D0%B2%D1%8F%D0%B7%D1%8C.) на этот счет.

**Comment by susloparov77** [comment]
Подскажите:
ret = m_ci.Sale();
Ошибка продажи 78 - Смена превысила 24 часа ??
Ошибка снятия отчета с гашением 79 Неверный пароль - Это так? 
Какой пароль верный? Я даю m_ci.Set_SysAdminPassword(30);

**Comment by swex** [comment]
1. Метод Sale объявлен устаревшим, необходимо пользоваться FN методами. См [пример](https://github.com/shtrih-m/fr_drv_ng_examples/blob/master/classic_interface/main.cpp#L242)
2. Пароль по умолчанию 30, это так, но для снятия Z отчета необходимо вручную предварительно поменять свойство `Password` на пароль администратора. Свойство `SysAdminPassword` используется драйвером,  прозрачно для пользователя, например, для чтения структуры таблиц [пример](https://github.com/shtrih-m/fr_drv_ng_examples/blob/master/classic_interface/main.cpp#L126)

**Comment by CavInc** [comment]
А возможна ли отладка на СМАРТ терминале под Андройдом который ? 
а то при подключении к мини usb компьютер не видет терминал. Или я что то не верно делаю

**Comment by swex** [comment]
@CavInc  можно отлаживаться по сети: 
1.Снимаем в настройках есть подменю `USB Devices`, необходимо снять галочку `Enable USB Devices`
2. adb по usb заработает
3. adb tcpip 5555
4. Снова включаем `Enable USB Devices`
5. adb connect IP_устройства

**Comment by swex** [comment]
закрываю, необходимо заводить новые заявки под новые вопросы
