### ISSUE TITLE
Проблема с установкой признака агента

### ISSUE THREAD

**Issue by evkorm** [shtrih-m/fr_drv_ng#40]
Здравствуйте!  Имеется проблема.

При фискализации пытаемся установить признак агента (в нашем случае это "иной агент", бит 6, значение 64 получается). Тег 1057, заполняем следующим образом:

Сначала открываем чек командой printer.OpenCheck()

Затем пытаемся установить тег 1057 следующим образом:

Printer.TagNumber = 1057;

Printer.TagType = (int)TagType.BitMask; // 5 - битовая маска, согласно документации именно такой тип

Printer.TagValueInt = 64;

Printer.FNSendTagOperation();

В этом случае получаем ошибку "(-8) to large data". Копаем документацию дальше - вроде бы для битовых масок следует использовать не TagValueInt, а TagValueBin + TagValueLength.

Но TagValueBin это строка - как в неё засунуть 64 не очень понятно. Перепробовал всякие варианты, и в качестве первого символа как (char)64 с длиной 1, и просто 64 как строку - получаем ошибку (94) некорректная операция.

Буду очень благодарен любой помощи.

**Comment by evkorm** [comment]
Уточнение (вдруг это важно): фискальник не был зарегистрирован в налоговой с признаком агента.

**Comment by olefard** [comment]
Тег 1057 можно передать так:
```
Printer.TagNumber = 1057;
Printer.TagType = 1;// ttByte
Printer.TagValueInt = 64;
Printer.FNSendTag();
```

Printer.FNSendTagOperation(); передает тег для отдельной операции и в случае признака агента это будет не тег 1057, а тег 1222(признак агента по предмету расчета). Так что поменял на FNSendTag.

> Уточнение (вдруг это важно): фискальник не был зарегистрирован в налоговой с признаком агента.

По-хорошему надо сделать перерегистрацию ККТ с признаком агента. Но попробуйте пока закрыть чек. Посмотрим, какой результат вернет ФН.

**Comment by evkorm** [comment]
Большое спасибо за такой оперативный ответ. Будем пробовать.
