### ISSUE TITLE
проблема использования открытия чека и метода fnoperation

### ISSUE THREAD

**Issue by esklyarov** [shtrih-m/fr_drv_ng#41]
Ввиду скудного описания метода fnoperation в руководстве программиста, не удается понять почему при использовании метода OpenCheck, потом нельзя использовать fnoperation. Метод fnoperation так же открывает чек?
В связи с переходом на новый формат  ФФД 1.05, необходимо передавать для каждой позиции  "Признак способа расчета"(PaymentTypeSign) и "Признак предмета расчета"(PaymentItemSign). 
или необходимо использовать OpenCheck и затем передавать недостающие(PaymentTypeSign,PaymentItemSign) с помощью FNSendTagOperation?

**Comment by olefard** [comment]
FNOperation можно вызывать и после OpenCheck и без OpenCheck(тогда чек откроется при первом вызове FNOperation). Хорошо бы узнать, что возвращают OpenCheck и FNOperation или может быть даже лог драйвера.

**Comment by esklyarov** [comment]
спасибо. все получилось
