### ISSUE TITLE
Проблема со сборкой биндингов для Python

### ISSUE THREAD

**Issue by Gandzjur** [shtrih-m/fr_drv_ng#42]
Пытаюсь собрать Python модуль следующим образом:
`~/linux_1.4.4.520/armv7hf_le $ LD_LIBRARY_PATH="./:./libs" CPPFLAGS="-std=c++11 -fpermissive" python setup.py install --usb`
Все успешно собирается, но при попытке использовать получившийся пакет получаю ошибку:
`~/linux_1.4.4.520/armv7hf_le $ LD_LIBRARY_PATH="./:./libs" python -c "import fr_drv_ng"
ImportError: /home/pi/linux_1.4.4.520/armv7hf_le/venv/local/lib/python2.7/site-packages/fr_drv_ng-1.0-py2.7-linux-armv7l.egg/_fr_drv_ng.so: undefined symbol: _ZNK17classic_interface23Get_StatusRKDescriptionEv`

С чем это может быть связано? Может кто-то сталкивался с подобными проблемами?

### Окружение
Raspberry Pi B
Python 2.7.9
SWIG Version 3.0.12 Compiled with g++ [armv7l-unknown-linux-gnueabihf] Configured options: +pcre

**Comment by swex** [comment]
Как выяснилось в последнем релизе профиль swig сломан  `classic_interface.i`
Странно что swig обертка у вас вообще собирается.
[Вот](https://paste.fedoraproject.org/paste/43n9MA8IaF4RLautROvCvA) поправленная версия.

Далее как делаю я:
```bash
#обычно собираю и устанавливаю одной командой.
#устанавливаю в пользовательские модули вот так:
python3 setup.py install --usb --user --prefix=
#Запускаю из той же директории вот так:
LD_LIBRARY_PATH=`pwd` ipython3
```
бывает что pip что-то странное мутит с модулями (кажется он не заменят нативные библиотеки при повторной установке). Для надежности советую попробовать удалить модуль перед установкой нового, и также собирать модуль в чистой директории(без пред. сборок)
```bash
pip3 uninstall fr_drv_ng
```
Не знаю что за окружение на вашей Pi. Работают ли статические/динамические( console_test_fr_drv_ng_*) консольные утилиты из дистрибутива?

**Comment by groleore** [comment]
Еще раз попробовали собрать версию 1.4.4.524. Ошибка все та же. Консольная утилита также не запускается:
```
~/linux_1.4.4.524/armv7hf_le $ ./console_test.sh
FATAL: kernel too old
```
Что нужно уточнить по нашему окружению?Какое рекомендуемое окружение для сборки?

**Comment by swex** [comment]
@groleore какая та же? Какая ОС/дистрибутив, версии ядра и libc?

**Comment by groleore** [comment]
При попытке импортировать драйвер ошибка:
`ImportError: /home/pi/linux_1.4.4.520/armv7hf_le/venv/local/lib/python2.7/site-packages/fr_drv_ng-1.0-py2.7-linux-armv7l.egg/_fr_drv_ng.so: undefined symbol: _ZNK17classic_interface23Get_StatusRKDescriptionEv`
OC: Raspbian GNU/Linux 8 (jessie)
Kernel: 4.9.35-v7+
libc version: Debian GLIBC 2.19-18+deb8u10

**Comment by swex** [comment]
Я бы сказал что дело в stdlibc++, но не уверен. Есть возможность проверить на 9(Stretch)?

**Comment by groleore** [comment]
@swex  Проверили на Stretch, все собралось. Спасибо за помощь.
