### ISSUE TITLE
Область сменных итогов ФП переполнена

### ISSUE THREAD

**Issue by atolstykh** [shtrih-m/fr_drv_ng#44]
При закрытии смены возникает ошибка с кодом 20 (Область сменных итогов ФП переполнена).
Как ее исправлять?

**Comment by swex** [comment]
Где вы взяли это описание кода ошибки? Это устаревшее описание от ЭКЛЗ ФРов. Должно быть описание: Исчерпан ресурс хранения. Скорее всего у вас 30 дней передаются чеки в ОФД.

**Comment by atolstykh** [comment]
Взято из ПротоколККТ 11.05.17
Где можно увидеть обновленный вариант?
Как исправлять ошибку? Перерегистрировать МГМ?

**Comment by swex** [comment]
[ПротоколККТ 1.16.docx](https://github.com/shtrih-m/fr_drv_ng/files/2874755/1.16.docx)
Отправить данные в ОФД или перерегистрировать МГМ

**Comment by atolstykh** [comment]
Через ФискалМастер пытаюсь перерегистрировать ФН (МГМ). Ввожу ранее использовавшиеся параметры. Возвращается ошибка Некорректные параметры в команде. Можно как-то понять что именно введено неправильно?

**Comment by swex** [comment]
фискал мастер тот что под android или тот что под windows? какое устройство? нужно снять лог.

**Comment by atolstykh** [comment]
Андроидный, Штрих-М.
Как снять лог?

**Comment by swex** [comment]
logcat

**Comment by atolstykh** [comment]
Лог
[log.txt](https://github.com/shtrih-m/fr_drv_ng/files/2875045/log.txt)

**Comment by swex** [comment]
Ничего не прояснилось. В логе действительно "Некорректные параметры в команде". КЯ не всегда подробно сообщает причину ошибки. Нужно искать причину в передаваемых данных.

**Comment by atolstykh** [comment]
Что здесь может быть неправильно?
![_1](https://user-images.githubusercontent.com/2507271/52945688-633a2c80-3383-11e9-8a96-42f594b040c2.PNG)
![_2](https://user-images.githubusercontent.com/2507271/52945690-633a2c80-3383-11e9-91e9-b04151a684af.PNG)

**Comment by swex** [comment]
версия ФМ какая(на первом экране)? РНМ как получили?

**Comment by atolstykh** [comment]
Версия ФФД: 1.05
РНМ получен в Тест драйвера ККТ 4.14.0.731
11.ФН - РНМ - Сгенерировать РНМ

**Comment by swex** [comment]
В Фискал Мастер на первом экране отображается версия. Ее тоже скажите пожалуйста.
На всякий случай вот актуальная версия 2.1.9 https://yadi.sk/d/j__iAW8Labjbrg

**Comment by atolstykh** [comment]
Установил 2.1.9. Запустил, выбрал ручной режим, Перерегистрация без замены ФН, подгрузились сохраненные ранее данные - изменил имя кассира. Применить.
Ошибка 115 Команда не поддерживается

**Comment by swex** [comment]
1. снимите лог. Возможно у вас очень старая версия КЯ
2. попробуйте автоматический режим

**Comment by atolstykh** [comment]
1. Версия 32815
2. В автоматическом режиме просто пишет, что все уже зарегистрировано.
[log2.txt](https://github.com/shtrih-m/fr_drv_ng/files/2875516/log2.txt)

**Comment by swex** [comment]
Значит ФН уже зарегистрирован. Что в ответе на команды статуса ФН и КЯ?

**Comment by atolstykh** [comment]
Статус
Режим 2
Статус ФН
Состояние смены 1
Состояние фазы жизни 3

Из ФискалМастера можно смену закрыть?

**Comment by swex** [comment]
да, через отчеты -> снять отчет с гашением.

**Comment by atolstykh** [comment]
Ровно такая же ошибка 20 (ФН: Исчерпан ресурс хранения). 
Почему МГМ выдает такую ошибку и как ее исправить?

**Comment by swex** [comment]
Значит вы не сбросили МГМ.
У вас несколько вариантов:
1. Передать чеки в ОФД
2. Сбросить МГМ и перерегистрировать заново:
2.1 Подать команду `FNResetState` с кодом 22.
2.2 Фискализировать любым известным способом

**Comment by atolstykh** [comment]
Как реализовать п.1 и 2.2? Можно ли это сделать через ФискалМастер?

**Comment by swex** [comment]
1. Прописать корректные IP/порт ОФД в соотв. таблицу. Почитайте общее руководство на ваш ККТ.

**Comment by atolstykh** [comment]
1. Указанные параметры ОФД (скрин экрана ФискалМастера с ними я прикладывал) взяты из буклета "Быстрый старт", который был в коробке с ККТ
2. По 2.2 есть варианты?

**Comment by swex** [comment]
1. Не знаю что там в буклете, но факт в том что данные в ОФД не уходят. Или у вас нет интернета на устройстве или ОФД на данном порте/хосте отсутствует.
2. После сброса по коду 22, необходимо перезапустить КЯ. Далее можно воспользоваться Фискал Мастер.

**Comment by Rastiplan** [comment]
Режим работы: Применение в сфере услуг
Наименование пользователя: Горизонт
Кассир: Андрей
ИНН кассира: 312800742754
Адрес расчетов: Воронеж
Адрес сайта ФНС: www.nalog.ru
Место расчетов: 8 этаж
Адрес электронной почты отправителя
чека: andrey@relex.ru
Признак платежног
ПЛ.
СУБАГЕНТ
ИНН ОФД: 77286995
Наименование ОФД: 000 "ОФД"
Сервер ОФД: 188.127.243.105
