### ISSUE TITLE
FNSendCustomerEmail: Ошибка 79 "Неверный пароль"

### ISSUE THREAD

**Issue by rmarma** [shtrih-m/fr_drv_ng#45]
ci = new classic_interface();
ci.Set_Password(1);
ci.Set_CheckType(0);
ci.OpenCheck();
ci.Set_CustomerEmail("test@test.ru");
ci.FNSendCustomerEmail();

Вызов метода **FNSendCustomerEmail**() возвращает ошибку 79, если этот метод убрать, то чек печатается нормально.
Android 1.4.4-4-g484ac43.

Как правильно передавать почту покупателя?

**Comment by swex** [comment]
давайте лог

**Comment by rmarma** [comment]
Где его взять? Устройство "POSCenter A7L".

**Comment by swex** [comment]
смотрите справку к методу `Set_LogOn`
```
    //!
    //! @brief Логгирование в драйвере глобальное и включено всегда.
    //!
    //! Управление происходит через следующие переменные окружения <br>
    //! * FR_DRV_DEBUG_CONSOLE - если определено весь вывод лога будет на stderr <br>
    //! * FR_DRV_LOG_PATH - путь файла лога(по умолчанию fr_drv.log в рабочей директории)<br>
    //! * FR_DRV_LOG_FILE_COUNT - кол-во ротаций(по умолчанию 2)<br>
    //! * FR_DRV_LOG_PART_SIZE - размер части в байтах (по умолчанию 1024 * 1024 * 10)<br>
    //! * FR_DRV_LOG_FLAGS - флаги логгирования, битовая маска со следующими ключами(по умолчанию
    //! всё включено)
    //!
    //!     * 1 << 0 - логгировать обмен
    //!     * 1 << 1 - логгировать каждый read/write в IoLayer, иначе аккумулировать
    //!     * 1 << 2 - логгировать отладку протокола
    //!     * 1 << 3 - логгировать статистику протокола
    //!     * 1 << 4 - логгировать отладку функций-утилит
    //!     * 1 << 5 - логгировать отладку вызовов интерфейсов верхнего уровня (classic,upos, итд)
    //!
    //!
    //!
```

**Comment by rmarma** [comment]
Для Android'а эта справка актуальна? Как и где установить переменные окружения для управления логированием?
В обёртке под android не нашёл метод setLogCallback из справки.

**Comment by swex** [comment]
По умолчанию лог пишется в файл `fr_drv.log` в рабочей директории. Если файл невозможно открыть на запись - лог будет выводиться в logcat на android или stderr на остальных платформах. В примерах есть [пример установки переменных окружения под android](https://github.com/shtrih-m/fr_drv_ng_examples/blob/master/classic_fr_drv_ng_android_example/app/src/main/java/ru/shtrih_m/classic_fr_drv_ng_android_example/MainActivity.java#L69)

**Comment by rmarma** [comment]
Спасибо за информацию, вот лог:
[fr_drv_ng.log](https://github.com/shtrih-m/fr_drv_ng/files/2880573/fr_drv_ng.log)

**Comment by swex** [comment]
В данном сценарии необходимо перед вызовом `FNSendCustomerEmail` вручную поменять пароль( `Set_Password`) на пароль администратора.

**Comment by rmarma** [comment]
В этом случае выдаёт ошибку `89` `Чек открыт другим оператором`:
```
ci.Set_CustomerEmail("test@test.ru");
ci.Set_Password(30);
if (ci.FNSendCustomerEmail() != 0) {
 Log.e("Shtrih, ci.Get_ResultCode() + " " + ci.Get_ResultCodeDescription());
}
ci.Set_Password(DEF_PASSWORD);
```
[fr_drv_ng.log](https://github.com/shtrih-m/fr_drv_ng/files/2884363/fr_drv_ng.log)

**Comment by swex** [comment]
я вам наврал в первом ответе.
На самом деле пароль администратора для данной операции не требуется. Более того на тестовых устройствах ваш изначальный код отрабатывает корректно.

Те. возвращаемся к первому варианту. Вы все делали правильно, вероятней всего это какой баг внутри кассового ядра. Задал вопрос разработчикам КЯ, отпишусь как ответят.

**Comment by rmarma** [comment]
Хорошо, спасибо. Будем ждать.
Может заодно его можно как-то обновить? А то НДС 20% в нём тоже нет, таблицу редактировать не даёт, а отправка `ci.Set_Tax1(1)` печатает 18%.

**Comment by swex** [comment]
Обновить точно не помешает. Проблема в том что я не знаю как распространяется кассовое ядро на ваше устройство. Лучше обратиться к вендору.

**Comment by swex** [comment]
Да, это баг. Исправлено в сборках >= 33767 (12.12.18)
```
1. Исправлена проверка пароля в командах FF0C/FF4D передачи тегов. Разрешается передавать теги от кассиров.
```

**Comment by rmarma** [comment]
Спасибо. Обновление кассового ядра решило проблему с почтой, но возникла новая проблема с НДС, про неё в отдельной ветке.
