### ISSUE TITLE
Номер ФН

### ISSUE THREAD

**Issue by aovcharenko** [shtrih-m/fr_drv_ng#46]
Здравствуйте. Подскажите, пожалуйста, как получить "Номер ФН".

**Comment by olefard** [comment]
Вызвать метод ```FNGetStatus```, номер фн будет в свойстве ```SerialNumber```.

**Comment by aovcharenko** [comment]
Да, спасибо, так получилось.
Я вызывал `FNGetSerial`, если `Get_SerialNumber` возвращал пустую строку. А он возвращал мне "2013", решил, что это не то поле. Всегда лучше вызывать `FNGetStatus`/`FNGetSerial` перед `Get_SerialNumber`?

**Comment by olefard** [comment]
FNGetSerial тоже должен работать.

> Всегда лучше вызывать `FNGetStatus`/`FNGetSerial` перед `Get_SerialNumber`?

Не лучше. Только так и надо работать: перед вызовом метода надо заполнить все поля, которые метод использует. После вызова метода получить значения из свойств, которые он модифицирует.

Список свойств, который использует/модифицирует метод можно посмотреть в документации или в classic_interface.h

**Comment by aovcharenko** [comment]
Да, логику работы со свойствами я понял.
Номер ФН не меняется, не хотел лишний раз запрашивать, если он уже был прочитан.
После команды `GetECRStatus` в этом поле лежит "2013". Видимо, разные данные хранятся в одном поле.

**Comment by olefard** [comment]
> Видимо, разные данные хранятся в одном поле.

Так и есть. GetECRStatus записывает в это поле заводской номер ККТ.

Хранить лучше у себя в программе.

**Comment by aovcharenko** [comment]
Спасибо.
