### ISSUE TITLE
В ОФД уходит НДС 20%, но сумма от 18%

### ISSUE THREAD

**Issue by rmarma** [shtrih-m/fr_drv_ng#47]
![default](https://user-images.githubusercontent.com/12980966/53165166-12287380-35e3-11e9-8176-6b7553134e51.png)
В `ОФД` уходит `НДС 20%`, но сумма от `18%`. В чеке тоже `18%`. В таблице `"Налоговые ставки"` через интерфейс `"ФискалМастер"` данные не меняются (при закрытой и открытой смене).
[fr_drv_ng.log](https://github.com/shtrih-m/fr_drv_ng/files/2889046/fr_drv_ng.log)

**Comment by swex** [comment]
как выяснилось, такое возможно, если в таблице 1,1,54 АВТОМАТИЧЕСКИЙ ПЕРЕХОД НДС С 18% НА 20% стоит 0. Попробуйте в закрытой смене выставить в 1.

**Comment by rmarma** [comment]
Отлично, сработало. Спасибо.
