### ISSUE TITLE
НДС на чеке коррекции

### ISSUE THREAD

**Issue by aovcharenko** [shtrih-m/fr_drv_ng#48]
Здравствуйте. Печатаю чек коррекции через `FNBeginCorrectionReceipt`/`FNBuildCorrectionReceipt2`. На печатном чеке печатаются все НДС. Подскажите, пожалуйста, есть ли возможность не печатать НДС с нулевой суммой? Пробовал настройку "Печать налогов" в "Таблица 1 Тип и режим кассы" (ряд 1, поле 7), в чеках продажи эта настройка срабатывает, а чек коррекции не меняется.

**Comment by swex** [comment]
Здравствуйте. Драйвер этим выводом никак не управляет. Не знаю есть ли реализации на которых это возможно. Зависит от модели устройства. Лучше всего общие вопросы задавать сюда:
support@shtrih-m.ru

**Comment by aovcharenko** [comment]
спасибо
