### ISSUE TITLE
Настройка связи с ОФД

### ISSUE THREAD

**Issue by DMLeontyev** [shtrih-m/fr_drv_ng#49]
Используем смартпос-ф. 
Провели фискализацию с использованием приложения FiscalMaster, установленной на устройстве. При этом адрес ОФД был задан не тот, что нужен. Видимо, отчет о регистрации ушел на этот неверный адрес. Как послать его на нужный?

Получить параметры удалось с помощью
static String getOfdAddrTableInfo() {
        try {
            ci.Set_Password(30);
            ci.Set_TableNumber(14); // параметры оФД
            ci.Set_FieldNumber(1);
            ci.Set_RowNumber(1);
            checkResult(ci.ReadTable());
            String res = ci.Get_ValueOfFieldString();

            ci.Set_FieldNumber(2);
            ci.Set_RowNumber(1);
            checkResult(ci.ReadTable());
            res += " " + ci.Get_ValueOfFieldInteger();

            ci.Set_FieldNumber(3);
            ci.Set_RowNumber(1);
            checkResult(ci.ReadTable());
            res += " " + ci.Get_ValueOfFieldInteger();

            return res;

        } catch (Exception e) {
            return ci.Get_ResultCodeDescription();
        }
    }

Вероятно, аналогично их можно и изменить. 
Можно ли потом переслать отчет?

**Comment by swex** [comment]
а что в статусе информационного обмена `FNGetInfoExchangeStatus`? документ точно ушел?
Если он не ушел - ничего страшного. Можно просто поменять адрес ОФД в таблице 14 или выполнить перерегистрацию без замены ФН.
Если же документ ушел не могу сказать что делать. Это нужно выяснять у ОФД и налоговой.

**Comment by DMLeontyev** [comment]
после FNGetInfoExchangeStatus:
Status: 5
MessageCount: 1
DocumentNumber: 1
Date: Sat Jan 31 22:05:16 GMT+03:00 1970

Похоже документ не ушел? Просто поменять адрес?
Если и ушел, то в принципе ФН тестовый и это попытка подключиться именно к тестовому контуру ОФД.

**Comment by swex** [comment]
да, тогда ничего страшного. да, поменять адрес.

**Comment by DMLeontyev** [comment]
Адрес поменял. Но статус остается прежним. А как понять, были ли какие-то попытки связи и если нет, форсить их?

**Comment by swex** [comment]
проверить можно по логу КЯ. Новые параметры подхватываются при следующем сеансе связи.

**Comment by DMLeontyev** [comment]
А как можно посмотреть лог КЯ? Очищается ли он при рестарте КЯ?

**Comment by swex** [comment]
В logcat, отфильтровать по приложению `ru.shtrihm.droidcashcore`. Не могу сказать пишется ли он параллельно в файл.

**Comment by DMLeontyev** [comment]
Есть ли возможность узнать доступен ли ОФД в данный момент?

**Comment by DMLeontyev** [comment]
Спасибо.
