### ISSUE TITLE
Печать чека

### ISSUE THREAD

**Issue by susloparov77** [shtrih-m/fr_drv_ng#5]
При печати чека в примере есть такой код:
    auto isCashcore = m_ci.Get_ModelParamValue();
    qInfo() << QObject::tr("4f");
    if (isCashcore) {
        //посылать тег, привязанный к операции на cashcore(Кассовое Ядро) нужно ДО операции
        executeAndHandleError(std::bind(&classic_interface::FNSendItemCodeData, &m_ci));
    }
    При его выполнение под андрой штрих-м приходит ошибка:
    55 "ККТ - Команда не поддерживается в данной реализации", что это значит?
    Зачем нам в коде isCashcore? И что мы делаем функцией: FNSendItemCodeData?

**Comment by swex** [comment]
cashcore - он же КЯ (Кассово Ядро). Реализация протокола Штрих-М, которая втч используется в android кассах.
Реализации cashcore и других ККТ различаются, поэтому некоторые операции делаются в зависимости от используемого устройства.
В данном случае в коде есть комментарий, зачем эта проверка: 
```c++
    //посылать тег, привязанный к операции на cashcore(Кассовое Ядро) нужно ДО операции
```
По методу FNSendItemCodeData - вот же справка
```c++
    //!
    //! @brief Отправить КТН тег
    //!
    //! Отправляет тег 1162 (Код товарной номенклатуры), привязанный к операции. Метод должен
    //! вызываться только после метода #FNOperation.
    //!
    //! @note Работает только с онлайн-кассами.
    //!
    //! @par Используемые свойства:
    //!  - #Password - пароль пользователя.
    //!  - #MarkingType - Тип маркировки товара. (2 - Изделия из меха, 3 - лекарственные препараты,
    //!  5 - Табачные изделия)
    //!  - #SerialNumber - для Меха - КиЗ 20 символов; для лекарственных препаратов - Серийный номер
    //!  13 символов; для табачных изделий - код идентификации экземпляра, 24 симв.
    //!  - #GTIN - число, преобразуется в 6 байт Big endian
    //!
    //! @return Код ошибки
    //!
```
По ошибке:
Лучший способ выяснить описание проблемы на КЯ - это метод 
```c++
    //!
    //! @brief Получить описание последней ошибки
    //!
    //! @par Модифицируемые свойства:
    //!  - #ErrorDescription - текстовое описание ошибки
    //!
    //! @note Поддерживается не всеми моделями
    //!
    //! @return Код ошибки
    //!
    int ReadLastErrorDescription();
```

**Comment by susloparov77** [comment]
Почему в признаке предмета расчета отсутствует отсутствует - агентское вознаграждение?

**Comment by olefard** [comment]
агентское вознаграждение - 11.
Описание свойства PaymentItemSign будет исправлено.

**Comment by susloparov77** [comment]
Спасибо
