### ISSUE TITLE
Кодировка console_test_fr_drv_ng.exe write/read

### ISSUE THREAD

**Issue by HFShak** [shtrih-m/fr_drv_ng#52]
Добрый день.
При работе с консольной утилитой console_test_fr_drv_ng.exe read выдает данные в кодировке cp866. 
При попытке записать в таблицу русские символы console_test_fr_drv_ng.exe write 6.1.2 "НДС 20%" записывает пустую строку.

**Comment by swex** [comment]
Утилита выдаёт и принимает данные в utf8.
Рецепты из поисковиков типа: `chcp 65001` не работают.
Можно помучить себя и попытаться записать utf8 в переменную и передать её в качестве аргумента, но проще всего воспользоваться bash (из состава git for windows, например).

**Comment by swex** [comment]
Или, кстати, для записи таблиц можно воспользоваться командой `restore-tables`, которая читает строки со стандартного ввода в том же формате что выдаёт save-tables. 
как-то так:
```bash
#в файле table.txt у нас вот такое вот содержимое в utf8
6,1,2,64,1,0,0,'НАЗВАНИЕ НАЛОГА','НДС 20%'
#далее в командной строке
console_test_fr_drv_ng restore-tables < table.txt

```

**Comment by HFShak** [comment]
Спасибо. Можно закрывать.
Надо именно без save-table, поменять одну строку в таблице 6
Решил через перекодировку строки из windows-1251 в UTF-8
Если кому надо, код powershell:

```
$program = "$env:SystemDrive\console_test_fr_drv_ng.exe"

function ConvertTo-Encoding ([string]$From, [string]$To){
	Begin{
		$encFrom = [System.Text.Encoding]::GetEncoding($from)
		$encTo = [System.Text.Encoding]::GetEncoding($to)
	}
	Process{
		$bytes = $encTo.GetBytes($_)
		$bytes = [System.Text.Encoding]::Convert($encFrom, $encTo, $bytes)
		$encTo.GetString($bytes)
	}
}

Start-Process -FilePath $program -ArgumentList ('write 6.1.2 "' + $("НДС 20%" | ConvertTo-Encoding windows-1251 utf-8) + '"') -Wait -PassThru -NoNewWindow | Out-Null
```
