### ISSUE TITLE
Текст сообщения об ошибке

### ISSUE THREAD

**Issue by atolstykh** [shtrih-m/fr_drv_ng#54]
Метод classic_interface возвращает код ошибки, например, -1 или -115. Как получить текстовое описание ошибки?

**Comment by olefard** [comment]
Вызвать Get_ResultCodeDescription()

**Comment by atolstykh** [comment]
Там английский вариант, а русский?

**Comment by swex** [comment]
Текст зависит от того какая в системе локаль. Так же можно использовать переменную окружения 
`FR_DRV_LANG=ru` но ее нужно назначить до линковки библиотеки. Т.к. локаль в драйвере инициализируется статически.
