### ISSUE TITLE
Использования драйвера в C#

### ISSUE THREAD

**Issue by mongusheb** [shtrih-m/fr_drv_ng#55]
Здравствуйте!

Получится ли использовать драйвер в C#?

**Comment by swex** [comment]
Здравствуйте, мы не использовали и не знаем использовал ли кто-то.
Для генерации оберток под java и python используется [swig](http://www.swig.org).
см. доку для C# [здесь](http://www.swig.org/Doc3.0/CSharp.html).
В сборках есть интерфейсный файл для swig - classic_interface.i. Но под c# придется доработать напильником:
1. Свойства объекта выносятся в "свойства" только для python, для java используются геттеры и сеттеры.
2. Конвертер std::time_t в родной для языка формат времени написан вручную.
3. Конвертер std::vector<uint8_t> в родной массив байт тоже нужно написать.
