### ISSUE TITLE
Поддержка передачи данных в ОФД при подключении по bluetooth

### ISSUE THREAD

**Issue by AlexUtopia** [shtrih-m/fr_drv_ng#56]
Добрый день
Подскажите пожалуйста, есть ли в этом драйвере поддержка передачи фискальных документов в ОФД при подключении к кассе по bluetooth? Если такая поддержка имеется то как её активировать (на кассе и в драйвере)?

ЗЫ В доке по Штрих-Нано-Ф сказано так (см. скрин) (ссылка на доку https://exam.shtrih-m-partners.ru/assets/materials/ShTRIKh_NANO_F_IE.pdf).
ЗЫ2 К примеру, касса АТОЛ 11Ф также умеет работать по bluetooth и их библиотека libfptr умеет самостоятельно организовывать передачу данных в ОФД

![image](https://user-images.githubusercontent.com/12418284/55469155-8b1ce100-560d-11e9-9964-e9a94a52c155.png)

**Comment by swex** [comment]
да, это возможно. Есть свойство `AutoEoD`, которое включает обмен в параллельном потоке.
Так же есть метод `OFDExchange`, позволяет выполнить обмен вручную

**Comment by AlexUtopia** [comment]
Отлично! Спасибо за развёрнутый ответ.
Я так понимаю что данная фича есть прямой наследник фичи из драйверов "прошлого" поколения (построенных по технологии COM-объекта) где имеется возможность "передачи данных в ОФД при помощи драйвера" (поправьте меня если я привёл неверную аналогию).
Как активировать см. сриншоты
![image](https://user-images.githubusercontent.com/12418284/55473544-a4c32600-5617-11e9-945c-a3487d13d258.png)
![image](https://user-images.githubusercontent.com/12418284/55473559-adb3f780-5617-11e9-8038-7096f80836fb.png)

При этом активируется некий поток который в поллинге производит фоновый обмен с кассой на предмет отправки очередного фискального документа в ОФД. Среди этого обмена фигурируют официально недокументированные команды FF30 / FF31 / FF32 / FF33. Нам хотелось бы получить их описание, если это возможно

**Comment by swex** [comment]
Да, держите.
[ПротоколККТ 1.16.zip](https://github.com/shtrih-m/fr_drv_ng/files/3038529/1.16.zip)

**Comment by AlexUtopia** [comment]
спасибо!

**Comment by illeniumnr** [comment]
Здравствуйте, есть ли возможность для Штриха Лайт 02Ф обновить ПротоколККТ с версии 1.14 на версию 1.16 ?

**Comment by swex** [comment]
Протокол транспортного уровня "альтернативный(версия 2.0)" - нет. В остальном команды актуальные.
