### ISSUE TITLE
PrintBarCode() 55

### ISSUE THREAD

**Issue by vaburmistrov** [shtrih-m/fr_drv_ng#57]
Добрый день, касса ШТРИХ СМАРТПОС-Ф, настроена, вызываю методы 
Set_BarCode(...) передаю 13 цифр
PrintBarCode()
Получаю ответ 55 ККТ: Команда не поддерживается в данной реализации или при данных настройках
Подскажите, как распечатать на этой кассе EAN 13

**Comment by swex** [comment]
посмотрите [пример](https://github.com/shtrih-m/fr_drv_ng_examples/blob/master/classic_interface/main.cpp#L188) скорее всего вы не выставили `BarcodeType`

**Comment by vaburmistrov** [comment]
В этом методе не говорится о BarcodeType, но с указанием та же ошибка

https://github.com/shtrih-m/fr_drv_ng/wiki/Methods#group___base_methods_1gae0cf3dbe4168e844d0a146545021ba81

**Comment by vaburmistrov** [comment]
Set_BarCode(receipt.getLoyaltyClientId());
Set_LineNumber(500);
Set_BarcodeType(5);
Set_BarWidth(2);
Set_BarcodeAlignment(classic_interface.TBarcodeAlignment.baCenter);
Set_PrintBarcodeText(1);
Set_FontType(150);
Set_SwapBytesMode(1);
Set_LineSwapBytes(false);
PrintBarcodeLine();

При таком коде -9: Ошибок нет. Но штрихкод не печатает

**Comment by swex** [comment]
можно лог?

**Comment by vaburmistrov** [comment]
[classic_interface_0xb804e5c0    ] [T] FeedDocument() ok
[classic_interface_0xb804e5c0    ] [T] Set_BarCode(`0000000000857`)
[classic_interface_0xb804e5c0    ] [T] Set_BarCode() ok
[classic_interface_0xb804e5c0    ] [T] Set_LineNumber(`500`)
[classic_interface_0xb804e5c0    ] [T] Set_LineNumber() ok
[classic_interface_0xb804e5c0    ] [T] Set_BarcodeType(`5`)
[classic_interface_0xb804e5c0    ] [T] Set_BarcodeType() ok
[classic_interface_0xb804e5c0    ] [T] Set_BarWidth(`2`)
[classic_interface_0xb804e5c0    ] [T] Set_BarWidth() ok
[classic_interface_0xb804e5c0    ] [T] Set_BarcodeAlignment(`baCenter`)
[classic_interface_0xb804e5c0    ] [T] Set_BarcodeAlignment() ok
[classic_interface_0xb804e5c0    ] [T] Set_PrintBarcodeText(`1`)
[classic_interface_0xb804e5c0    ] [T] Set_PrintBarcodeText() ok
[classic_interface_0xb804e5c0    ] [T] Set_FontType(`150`)
[classic_interface_0xb804e5c0    ] [T] Set_FontType() ok
[classic_interface_0xb804e5c0    ] [T] Set_SwapBytesMode(`1`)
[classic_interface_0xb804e5c0    ] [T] Set_SwapBytesMode() ok
[classic_interface_0xb804e5c0    ] [T] Set_LineSwapBytes(`false`)
[classic_interface_0xb804e5c0    ] [T] Set_LineSwapBytes() ok
[classic_interface_0xb804e5c0    ] [T] PrintBarcodeUsingPrinter()
[classic_interface_0xb804e5c0    ] [D] PrintBarcodeUsingPrinter() fail
[classic_interface_0xb804e5c0    ] [E] Not supported
[classic_interface_0xb804e5c0    ] [T] ReadLastErrorDescription()
[TcpSocketIO_0xb802b220          ] [D] -> 02 01 6B 6A
[TcpSocketIO_0xb802b220          ] [D] <- 06 02 0C 6B 00 CE F8 E8 E1 EE EA 20 ED E5 F2 86
[TcpSocketIO_0xb802b220          ] [D] -> 06
[ProtocolV1_0xb7eb5c10           ] [D] command 6B return code: 0 execution took 1ms
[ProtocolV1_0xb7eb5c10           ] [D] commands total: 71, succeed: 71, failed: 0, avg. exec time: 156ms
[classic_interface_0xb804e5c0    ] [T] ReadLastErrorDescription() ok
[classic_interface_0xb804e5c0    ] [T] Get_ErrorDescription()
[classic_interface_0xb804e5c0    ] [T] Get_ErrorDescription() -> `Ош

**Comment by vaburmistrov** [comment]
[classic_interface_0xb8050020    ] [T] Set_BarCode(`0000000000864`)
[classic_interface_0xb8050020    ] [T] Set_BarCode() ok
[classic_interface_0xb8050020    ] [T] Set_LineNumber(`500`)
[classic_interface_0xb8050020    ] [T] Set_LineNumber() ok
[classic_interface_0xb8050020    ] [T] Set_BarcodeType(`5`)
[classic_interface_0xb8050020    ] [T] Set_BarcodeType() ok
[classic_interface_0xb8050020    ] [T] Set_BarWidth(`2`)
[classic_interface_0xb8050020    ] [T] Set_BarWidth() ok
[classic_interface_0xb8050020    ] [T] Set_BarcodeAlignment(`baCenter`)
[classic_interface_0xb8050020    ] [T] Set_BarcodeAlignment() ok
[classic_interface_0xb8050020    ] [T] Set_PrintBarcodeText(`1`)
[classic_interface_0xb8050020    ] [T] Set_PrintBarcodeText() ok
[classic_interface_0xb8050020    ] [T] Set_FontType(`150`)
[classic_interface_0xb8050020    ] [T] Set_FontType() ok
[classic_interface_0xb8050020    ] [T] Set_SwapBytesMode(`1`)
[classic_interface_0xb8050020    ] [T] Set_SwapBytesMode() ok
[classic_interface_0xb8050020    ] [T] Set_LineSwapBytes(`false`)
[classic_interface_0xb8050020    ] [T] Set_LineSwapBytes() ok
[classic_interface_0xb8050020    ] [T] PrintBarcodeLine()
[BarcodeRenderer_0xa11ed7c8      ] [D] rendering 1D barcode
[BarcodeRenderer_0xa11ed7c8      ] [D] data: 0000000000864
[BarcodeRenderer_0xa11ed7c8      ] [D] type: 5
[BarcodeRenderer_0xa11ed7c8      ] [D] reverseBytes: false
[BarcodeRenderer_0xa11ed7c8      ] [D] height: 50
[BarcodeRenderer_0xa11ed7c8      ] [D] width: 95
[BarcodeRenderer_0xa11ed7c8      ] [D] scale: 2
[BarcodeRenderer_0xa11ed7c8      ] [D] linesHeight: 500
[BarcodeRenderer_0xa11ed7c8      ] [D] scaledWidth: 190
[BarcodeRenderer_0xa11ed7c8      ] [D] text position: 1
[BarcodeRenderer_0xa11ed7c8      ] [D] text font: 150
[classic_interface_0xb8050020    ] [D] PrintBarcodeLine() fail
[classic_interface_0xb8050020    ] [E] unknown font

**Comment by vaburmistrov** [comment]
[classic_interface_0xb80495a8    ] [T] Set_BarCode(`0000000000895`)
 [classic_interface_0xb80495a8    ] [T] Set_BarCode() ok
 [classic_interface_0xb80495a8    ] [T] PrintBarCode()
 [TcpSocketIO_0xb803ea28          ] [D] -> 02 0A C2 1E 00 00 00 59 00 00 00 00 8F
 [TcpSocketIO_0xb803ea28          ] [D] <- 06
 [TcpSocketIO_0xb803ea28          ] [D] <- 02 02 C2 37 F7
 [TcpSocketIO_0xb803ea28          ] [D] -> 06
 [ProtocolV1_0xb8053800           ] [D] command C2 return code: 55 execution took 8ms
 [ProtocolV1_0xb8053800           ] [E] Command is not supported
 [ProtocolV1_0xb8053800           ] [D] commands total: 71, succeed: 70, failed: 1, avg. exec time: 164ms
 [TcpSocketIO_0xb803ea28          ] [D] -> 02 02 6B 37 5E
 [TcpSocketIO_0xb803ea28          ] [D] <- 06 02 4E 6B 00 CA CA D2 3A 20 CA EE EC E0 ED E4 E0 20 ED E5 20 EF EE E4 E4 E5 F0 E6 E8 E2 E0 E5 F2 F1 FF 20 E2 20 E4 E0 ED ED EE E9 20 F0 E5 E0 EB E8 E7 E0 F6 E8 E8 20 E8 EB E8 20 EF F0 E8 20 E4 E0 ED ED FB F5 20 ED E0 F1 F2 F0 EE E9 EA E0 F5 F3
 [TcpSocketIO_0xb803ea28          ] [D] -> 06
 [ProtocolV1_0xb8053800           ] [D] command 6B return code: 0 execution took 2ms
 [ProtocolV1_0xb8053800           ] [D] commands total: 72, succeed: 71, failed: 1, avg. exec time: 162ms
 [classic_interface_0xb80495a8    ] [D] PrintBarCode() fail
 [classic_interface_0xb80495a8    ] [E] ККТ: Команда не поддерживается в данной реализации или при данных настройках

**Comment by swex** [comment]
а что за `FontType` 150?
FontType - это номер шрифта. Кол-во шрифтов можно получить методом `GetFontMetrics`

**Comment by vaburmistrov** [comment]
это помогло, спасибо
