### ISSUE TITLE
Поддержка команд FF330-FF33

### ISSUE THREAD

**Issue by AlexUtopia** [shtrih-m/fr_drv_ng#60]
Подскажите, пожалуйста, начиная с какой версии прошивки (прошивок) поддерживаются команды 0xFF30-0xFF33?
ЗЫ имею ввиду как прошивки для "нормальных" ККМ, так и для модернизированных

**Comment by dr-begemot** [comment]
Скажите, что это за команды и где можно прочитать о них?
В документации https://www.shtrih-m.ru/%D0%9F%D1%80%D0%BE%D1%82%D0%BE%D0%BA%D0%BE%D0%BB%D0%9A%D0%9A%D0%A2_%D0%A4%D0%9D.pdf о них почему-то ни слова :/

**Comment by swex** [comment]
Вот актуальный протокол. Там есть и FF30+ [ПротоколККТ 1.16.docx](https://github.com/shtrih-m/fr_drv_ng/files/3227103/1.16.docx)

**Comment by dr-begemot** [comment]
О, большое спасибо!
