### ISSUE TITLE
Тег 1228

### ISSUE THREAD

**Issue by vaburmistrov** [shtrih-m/fr_drv_ng#61]
Добрый день, передаю тег 1228 ИНН из 10 символов, возвращается код ошибки 51 Некорректные параметры в команде <0x00330021: длина строки должна быть 12 символов
http://www.consultant.ru/document/cons_doc_LAW_214339/5db67c6361c1182977e4b231a87d2c6caedd59e2/
По приказу должны поддерживаться оба формата

**Comment by olefard** [comment]
Надо дополнить ИНН пробелами справа до 12 символов(см. тег 1228 в таблице 5 приказа).

**Comment by vaburmistrov** [comment]
Решило проблему, спасибо
