### ISSUE TITLE
DataMatrix

### ISSUE THREAD

**Issue by vaburmistrov** [shtrih-m/fr_drv_ng#63]
Добрый день, тестируем через офд такском
driver.Set_MarkingType(5);
driver.Set_GTIN(00000046218070);
driver.Set_SerialNumber(<_*2Q>j);
Ошибок не выдаёт, на чеке и в офд информации нет, с чем может быть связано?

**Comment by swex** [comment]
Здравствуйте, что за устройство? Нужен лог.
Посмотрите [пример](https://github.com/shtrih-m/fr_drv_ng_examples/blob/master/classic_interface/main.cpp#L360)

**Comment by vaburmistrov** [comment]
Спасибо, увидел ошибку на нашей стороне, неверный порядок команд driver.FNSendItemCodeData()
driver.FNOperation()
