### ISSUE TITLE
Проблемы с методом Set_ConnectionURI на Windows

### ISSUE THREAD

**Issue by groleore** [shtrih-m/fr_drv_ng#64]
Не работает пример для classic_interface.
При вызове метода  Set_ConnectionURI бросается следующее исключение:
`Unhandled exception at 0x6F81282E (vcruntime140.dll) in classic_interface_example.exe: 0xC0000005: Access violation reading location 0x000876D6.`
Если вызвать Connect без Set_ConnectionURI, то вернется код ошибки -1, что логично.
**Окружение**
Visual Studio 2017
cmake version 3.14.4
fr_drv_ng_windows_i386_1.4.4-7-gec19fc4 (dynamic, со static проблемы начинаются на 
этапе линковки)
![shtrih_error](https://user-images.githubusercontent.com/22003075/59098763-e62ec500-8929-11e9-90e2-852adcdce28f.png)

**Comment by swex** [comment]
Библиотека релизная, а отладка линкуется с дебажным рантаймом.

Можно переключить пример на использование релизного рантайма. Отладка останется, падения не будет.
 - в CMakeLists.txt дописать:
```
string(REGEX REPLACE "/MDd" "/MD" CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG}")
```
 - или в студийном проекте выставить:  
 Properties/С++/Code Generation/Runtime Library=Multi-threaded DLL (/MD)

**Comment by groleore** [comment]
@swex Спасибо, помогло.

**Comment by Kombaev** [comment]
@swex спасибо огромное, очень помогли !!!
