### ISSUE TITLE
Подцепить драйвер к QT

### ISSUE THREAD

**Issue by zaoozik** [shtrih-m/fr_drv_ng#65]
Здравствуйте, пытаемся подцепить драйвер к проекту на QT56, ничего не выходит. Был ли опыт у Вас? Можете посодействовать?
ВТИ-Сервис, Курск.

**Comment by zaoozik** [comment]
Подключаем хидер к проекту, 
подключаем либы

```
INCLUDEPATH += "$$PWD/lib/shtrih/x86_64/"
LIBS += "$$PWD/lib/shtrih/x86_64/libcppbase_fr_drv_ng.so"
LIBS += "$$PWD/lib/shtrih/x86_64/libqclassic_fr_drv_ng.so"
```

В коде вызываем создание объекта classic_interface

```
classic_interface ci;
      ci.Set_ConnectionType(classic_interface::TConnectionType::Tcp);
      ci.Set_UseIPAddress(true);
      ci.Set_IPAddress("192.168.0.1");
      ci.Set_TCPPort(12345);
      ci.Set_Timeout(4848);
      ci.Set_ProtocolType(1);
      int ret = ci.Connect()
```

Вылезает ошибка

`error: undefined reference to `classic_interface::classic_interface()'`

**Comment by swex** [comment]
нужно добавить в проект 
`qclassic_interface.h` и `QClassicFrDrvNg`,
и линковать с 
```qmake
LIBS += -lcppbase_fr_drv_ng
LIBS += -lqclassic_fr_drv_ng
```
вот пример cmake проекта:
```cmake
cmake_minimum_required(VERSION 3.1)

project(qclassic_ui LANGUAGES CXX)

set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_INSTALL_RPATH "$ORIGIN")
set(CMAKE_BUILD_WITH_INSTALL_RPATH ON)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

include_directories(qclassic_fr_drv_ng)
find_package(Qt5 COMPONENTS Core REQUIRED)
link_directories(${CMAKE_BINARY_DIR}/qclassic_fr_drv_ng)

add_executable(${PROJECT_NAME} "main.cpp" )
target_link_libraries(${PROJECT_NAME} Qt5::Core  qclassic_fr_drv_ng)

```

**Comment by zaoozik** [comment]
спасибо!

**Comment by DowJhob** [comment]
c qmake реально заставить работать?

**Comment by swex** [comment]
> c qmake реально заставить работать?

Конечно! А что не получается?
```qmake
LIBS += -lcppbase_fr_drv_ng
LIBS += -lqclassic_fr_drv_ng
INCLUDEPATH+= //путь с заголовочным из релиза
```

**Comment by DowJhob** [comment]
LIBS += -L$$PWD/./ -lcppbase_fr_drv_ng
LIBS += -L$$PWD/./ -lqclassic_fr_drv_ng
 INCLUDEPATH += $$PWD/.  classic_interface и qclassic лежат тут же вместе с проектом11.12.2019, 22:01, "Alexey Mednyy" <notifications@github.com>:
c qmake реально заставить работать?

Конечно! А что не получается?
LIBS += -lcppbase_fr_drv_ng
LIBS += -lqclassic_fr_drv_ng
INCLUDEPATH+= //путь с заголовочным из релиза

**Comment by DowJhob** [comment]
`LIBS += -L$$PWD/./ -lcppbase_fr_drv_ng`
`LIBS += -L$$PWD/./ -lqclassic_fr_drv_ng`
`INCLUDEPATH += $$PWD/. `
 classic_interface и qclassic лежат тут же вместе с проектом

**Comment by swex** [comment]
какое окружение, что выдаёт компилятор?
у меня на linux вот так:
```qmake
QT -= gui
CONFIG += c++11 console
CONFIG -= app_bundle
SOURCES += \
        main.cpp

QMAKE_LFLAGS += "-Wl,-rpath,\'\$$ORIGIN\'"
LIBS += -L$$PWD/./
LIBS += -lqclassic_fr_drv_ng
```
```c++
#include <QClassicFrDrvNg>
#include <QCoreApplication>
#include <QDebug>
#include <QTimer>

static void checkResult(int result)
{
    if (result) {
        qDebug() << "command failed with error" << result;
    }
}

int main(int argc, char* argv[])
{
    QCoreApplication a(argc, argv);
    QClassicFrDrvNg ci(&a);
    ci.Set_ConnectionURI("tcp://192.168.137.111:7778?timeout=30000&protocol=v1&enq_mode=1&ack_timeout=1000");
    checkResult(ci.Connect());
    QTimer::singleShot(0, &a, QCoreApplication::quit);
    return a.exec();
}

```

**Comment by DowJhob** [comment]
C:\Users\User\Documents\fiscal-service\main.cpp:19: ошибка: undefined reference to `QClassicFrDrvNg::QClassicFrDrvNg(QObject*)' окружение из коробки12.12.2019, 12:35, "Alexey Mednyy" <notifications@github.com>:какое окружение, что выдаёт компилятор?
у меня на linux вот так:
QT -= gui
CONFIG += c++11 console
CONFIG -= app_bundle
SOURCES += \
        main.cpp

QMAKE_LFLAGS += "-Wl,-rpath,\'\$$ORIGIN\'"
LIBS += -L$$PWD/./
LIBS += -lqclassic_fr_drv_ng
#include <QClassicFrDrvNg>
#include <QCoreApplication>
#include <QDebug>
#include <QTimer>

static void checkResult(int result)
{
    if (result) {
        qDebug() << "command failed with error" << result;
    }
}

int main(int argc, char* argv[])
{
    QCoreApplication a(argc, argv);
    QClassicFrDrvNg ci(&a);
    ci.Set_ConnectionURI("tcp://192.168.137.111:7778?timeout=30000&protocol=v1&enq_mode=1&ack_timeout=1000");
    checkResult(ci.Connect());
    QTimer::singleShot(0, &a, QCoreApplication::quit);
    return a.exec();
}

**Comment by DowJhob** [comment]
на линухе достаточно 
```
LIBS += -L$$PWD
LIBS += -lqclassic_fr_drv_ng
```
под вынь не работает

**Comment by olefard** [comment]
> под вынь не работает

Как именно не работает? Какие ошибки выдает?

Пример выше собирается и подключается к ККТ под windows(Qt 5.13.1 MSVC2017 32bit).

**Comment by DowJhob** [comment]
mingw73*64 undefined reference

**Comment by DowJhob** [comment]
в примере выше предлагали подключить cppbase,  так вот в линухе история таже, он не подключается, с куклассик онли худо-бедно ккм на связь выходит

**Comment by olefard** [comment]
> mingw73*64 undefined reference

Не находится конструктор QClassicFrDrvNg. Он лежит в qclassic_fr_drv_ng.
Если qclassic_fr_drv_ng прописан в LIBS и на его отсутствие не ругается, то по-видимому с мингв ничего не выйдет. Под windows собираем студией.

> в примере выше предлагали подключить cppbase, так вот в линухе история таже, он не подключается, с куклассик онли худо-бедно ккм на связь выходит

Только не cppbase, а classic_interface. куклассик работает через него. С ним тоже все должно собираться и работать. Какие ошибки с classic_interface?

**Comment by DowJhob** [comment]
он его не находил как файл, что логино, я не глянул что у него имя дополнено версией и ему нужен симлинк, сделал копию с нужным именем и он нашелся.

В итоге для классик интерфейс нужен цппбэйз,
для КУклассик нужен классик, так?

**Comment by olefard** [comment]
> В итоге для классик интерфейс нужен цппбэйз,
> для КУклассик нужен классик, так?

Да.

**Comment by DowJhob** [comment]
и описывать всю цепочку необязательно, достаочно верхней библы, классик или кулассик?

**Comment by olefard** [comment]
Достаточно верхней.
Но если полезут ненайденные странные символы, содержащие classic_interface и cppbase, лучше добавить.

**Comment by DowJhob** [comment]
msvc2017 падает на Set_IPAddress

**Comment by olefard** [comment]
А что собираете Debug или Release?
В настройках С++/Runtime Library поставьте в Multi-threaded DLL(/MD).

**Comment by DowJhob** [comment]
я в крейторе собираю, `QMAKE_CXXFLAGS_DEBUG += /MDd` не помогает

**Comment by olefard** [comment]
Не /MDd,  попробуйте /MD

**Comment by DowJhob** [comment]
не, не помогает
