### ISSUE TITLE
Тег 1008

### ISSUE THREAD

**Issue by dimailn** [shtrih-m/fr_drv_ng#67]
Здравствуйте!

Устанавливаем почту для отправки чека таким образом

```java
   Set_CustomerEmail("mail@example.com")
   FNSendCustomerEmail()
```

При этом в ОФД видно, что чек не содержит тега 1008, с чем это может быть связано?

**Comment by swex** [comment]
загадка, давайте лог.

**Comment by dimailn** [comment]
Прощу прошения, все работает корректно
