### ISSUE TITLE
Driver

### ISSUE THREAD

**Issue by arubsov** [shtrih-m/fr_drv_ng#68]
Я успешно установил драйвер,но сама касса(лайт 01ф) так и не опрелделяется в системе(Ubuntu),не подскажете в чем может быть дело,как заставить систему определить устройство как ttyUSB????

**Comment by swex** [comment]
По usb касса может работать в двух режимах: 
1. (rndis)usbnet - появляется в системе как сетевое устройство
2. usbserial - появляется в системе как виртуальный COM порт
Выбрать режим работы можно в таблице 21,1,9.

Что в `dmesg` когда подключаете кассу?

**Comment by arubsov** [comment]
[ 5304.085968] usb 2-1: new full-speed USB device number 7 using uhci_hcd
[ 5304.283981] usb 2-1: New USB device found, idVendor=18d1, idProduct=4ee4, bcdDevice= 1.00
[ 5304.283985] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 5304.283987] usb 2-1: Product: RNDIS    
[ 5304.283990] usb 2-1: Manufacturer: NXP
[ 5304.283992] usb 2-1: SerialNumber: SHM001
[ 5304.303320] rndis_host 2-1:1.0 eth0: register 'rndis_host' at usb-0000:00:1d.0-1, RNDIS device, 00:60:37:6b:55:5d
[ 5304.359067] rndis_host 2-1:1.0 enx0060376b555d: renamed from eth0
[ 5304.390344] IPv6: ADDRCONF(NETDEV_UP): enx0060376b555d: link is not ready

**Comment by arubsov** [comment]
После переключения режима касса определилась,в Тест Драйвере Штрих из под Wine касса видна,полет нормальный,вот вопрос будет ли она передавать данные в ОФД без включенного режима RNDIS?

**Comment by swex** [comment]
В этом репозитории осуществляется поддержка драйвера, по общим настройкам ККТ это Вам в поддержку.
Следует почитать **общее руководство по работе и настройке ККТ**. 
Для передачи данных в ОФД на ККТ должен быть интернет. Организовать можно след. способами:
1. RNDIS - USB  
2. Ethernet - RJ45
3. PPPoS - COM порт, работа в режиме сервера или клиента PPPoS
4. Если не хочется организовывать маршрутизацию пакетов на рабочем месте(NAT), для всех опций доступна так же работа через SOCKS5 прокси.
