### ISSUE TITLE
Встречное предложение, предоплата и постоплата

### ISSUE THREAD

**Issue by JetFlynn** [shtrih-m/fr_drv_ng#69]
Добрый день, подскажите, как указать в чеке эти способы оплаты? То есть Set_Summ1 отвечает за сумму наличными, Set_Summ2 за безналичные, а как указать сумму встречного предложения, предоплаты и постоплаты?

**Comment by swex** [comment]
Добрый день.
Подобные вопросы лучше задавать [здесь](https://forum.shtrih-m-partners.ru)
[см. подобный вопрос](https://forum.shtrih-m-partners.ru/index.php?topic=33209)
Так же смотрите документацию к методам драйвера [FNCloseCheckEx](
https://github.com/shtrih-m/fr_drv_ng/wiki/Methods#group___base_methods_1ga8f0dab763204209edd8f164f9ef5493b) и [FNOperation](https://github.com/shtrih-m/fr_drv_ng/wiki/Methods#group___base_methods_1ga213cfe07a2309cb0bfc00ca58f984ab4), а именно [PaymentTypeSign](https://github.com/shtrih-m/fr_drv_ng/wiki/Properties#group___properties_1gadd0f8ac33dacda1e13622262994e253d)

**Comment by JetFlynn** [comment]
Спасибо!
