### ISSUE TITLE
Получение данных из таблицы ФН

### ISSUE THREAD

**Issue by susloparov77** [shtrih-m/fr_drv_ng#7]
Здравствуйте, считываем из таблицы ФН:
    ci->Set_ModelParamNumber(classic_interface::DPE_FsTableNumber);
    checkResult(ci->ReadModelParamValue());
    auto fsTableNumber = ci->Get_ModelParamValue();
Как дальше получить:
1) Как получить адрес магазина
2) ИНН Магазина
3) Название магазина

**Comment by olefard** [comment]
```
int field = 
  9; // Адрес магазина
  2; // ИНН магазина
  7;//Название магазина

ci->Set_TableNumber(fsTableNumber);
ci->Set_FieldNumber(field);
ci->Set_RowNumber(1);
checkResult(ci->ReadTable());
auto value = ci->Get_ValueOfFieldString();
```

**Comment by susloparov77** [comment]
Спасибо
