### ISSUE TITLE
Отправка тегов с типом VLN

### ISSUE THREAD

**Issue by romaashka** [shtrih-m/fr_drv_ng#70]
Добрый день.
Необходимо передавать теги 1215, 1216, 1217 и др.
Согласно документации их тип VLN и необходимо заполнять TagValueBin.
Printer.TagNumber = 1215;
Printer.TagType = 3;
Printer.TagValueBin = ?? - как преобразовать сумму в строку? в каком виде?
Printer.FNSendTag();

**Comment by olefard** [comment]
Теги 1215, 1216, 1217 передаются через свойства Summ14, Summ15, Summ16 при вызове метода FNCloseCheckEx.

А вообще теги типа VLN передаются так:
```
Printer.TagNumber = 1215;
Printer.TagType = 3;
Printer.TagValueInt = 10000; // = 100р, суммы передаются в копейках
Printer.FNSendTag();
```

**Comment by romaashka** [comment]
Большое спасибо!
