### ISSUE TITLE
Тексты сообщения об ошибке

### ISSUE THREAD

**Issue by groleore** [shtrih-m/fr_drv_ng#74]
Можно ли где-то найти список всех ошибок драйвера на русском?

**Comment by swex** [comment]
Конечно, во вложении протокол, там же есть и список ошибок.
[ПротоколККТ 1.16.zip](https://github.com/shtrih-m/fr_drv_ng/files/3505610/1.16.zip)

**Comment by groleore** [comment]
Большое спасибо за помощь!
