### ISSUE TITLE
Нет версии под iOS

### ISSUE THREAD

**Issue by bogban** [shtrih-m/fr_drv_ng#75]
Здравствуйте!

Столкнулся с проблемой. Клиенты используют только iPad, а версии драйвера под iOS найти в списке ваших релизов не удалось.

Не могли бы вы собрать версию и под iOS (желательно не выше 9.3), либо выслать исходники, чтобы я собрал сам?

**Comment by swex** [comment]
Здравствуйте, это редкий запрос, мало кто работает с ККТ с устройств Apple.
Т.к. проект разрабатывался с прицелом на кроссплатформенность собрать его не трудно, но исходники мы не выдаём.

[Вот](https://yadi.sk/d/c9KqQv1NFIcSaQ) я ради эксперимента собрал, использовал https://github.com/leetal/ios-cmake с опцией -DPLATFORM="OS" (armv7, armv7s, arm64)
я не знаю специфики линковки под iOS, но на сколько я понял, cmake мне сгенерил динамическую библиотеку, которая внутри содержит все 3 архитектуры.

> под iOS (желательно не выше 9.3)

Даже не знаю под какую версию у меня собралась библиотека.  Не вижу таких опций в ios-cmake...

Если это то что нужно - добавим сборку в CI.

PS: Если нужна сборка под MacOS то это можно

**Comment by bogban** [comment]
Спасибо большое!  Библиотеки подошли. 
Удалось слинковать с нашим ПО под ios.
Тестирование на iPad прошло успешно.
