### ISSUE TITLE
Тег 1187

### ISSUE THREAD

**Issue by dimailn** [shtrih-m/fr_drv_ng#76]
Как правильно устанавливать тег 1187?

Пробую так, через таблицы

```java
            Set_TableNumber(13)
            Set_RowNumber(1)
            Set_FieldNumber(14)
            Set_ValueOfFieldString(paymentPlace)
            checkResult(WriteTable())
```

Ошибок нет, но и на чек это никак не влияет. Может как-то быть связано с параметрами регистрации?

**Comment by swex** [comment]
Чтобы можно было передать 1187, необходимо чтобы при регистрации этот тег отсутствовал.

**Comment by dimailn** [comment]
Пытаюсь не заполнять в отчёте о регистрации, выдает ошибку: Некорректные данные в поле: [1187] Место расчетов

**Comment by swex** [comment]
Какой аппарат, через какую программу (версию) регистрируете?

**Comment by dimailn** [comment]
Большой Смартпос, Фискал мастер 2.2.1

**Comment by swex** [comment]
С версии [ФМ 2.2.3](https://yadi.sk/d/JhxMAQTHT8Ym1w) эти поля не обязательные

**Comment by dimailn** [comment]
FF06h Ошибка ККТ: Ошибка в TLV(теге, длине или данных)

Кассовое ядро 34865

**Comment by swex** [comment]
Нужен лог чека

**Comment by dimailn** [comment]
А в фискал мастере его можно как-то получить? Это при отчете о регистрации

**Comment by dimailn** [comment]
Нашел, в логах кассового ядра - не передан обязательный тег 1187 "место расчетов"

**Comment by swex** [comment]
Теги 1009 и 1187 должны быть пустыми при регистрации.
Если не удается зарегистрировать кассу - давайте логи. Лог FM можно собрать, например, через adb logcat.
Далее в чеке:
если в кассу развозной торговли записать в таблицу 1009 и 1187
если в таблице вытереть 1009 и 1187, то можно передать их тегами

**Comment by dimailn** [comment]
После повторного сброса ФМ принял пустые поля, спасибо
