### ISSUE TITLE
FDPrintDocument через java

### ISSUE THREAD

**Issue by wiesgin** [shtrih-m/fr_drv_ng#77]
Добрый день,
пробуем на java вызвать команду FDPrintDocument. Приходит ответ -12 (Not Supported). Возможно проблема в dll и там отсутствует указанный метод.

**Comment by swex** [comment]
да, такого метода нет, есть `FNPrintDocument`, но он не реализован.
Можно получить документ как строку, методом `FNGetDocumentAsString`, и потом распечатать его построчно самостоятельно.
