### ISSUE TITLE
Применение скидок

### ISSUE THREAD

**Issue by bogban** [shtrih-m/fr_drv_ng#78]
Подскажите, пожалуйста, как применять скидки на товары? Если нам известна общая сумма скидки по чеку.
Необходимо в чеке печатать цены уже с учётом скидок, а так же сами скидки.

Применение Discount() возвращает ошибку 64: Переполнение диапазона скидок.

// Пример вызова метода Discount
// ... конец цикла по товарам
  m_pCi->Set_Summ1(10000);
  m_pCi->Set_Tax1(0);
  m_pCi->Set_Tax2(0);
  m_pCi->Set_Tax3(0);
  m_pCi->Set_Tax4(0);
  m_pCi->Discount();

// ... формирование сумм оплаты

  m_pCi->Set_Summ1(100000); 
  m_pCi->Set_RoundingSumm(0);
  m_pCi->FNCloseCheckEx();

**Comment by olefard** [comment]
Метод Discount с онлайн-кассами не работает.
Разбивать скидку на товары у себя в программе и передавать в ККТ цену товара с учетом скидки. А величину скидки печатать текстом.

**Comment by bogban** [comment]
Понятно, спасибо за ответ.
