### ISSUE TITLE
Сборка под iOS

### ISSUE THREAD

**Issue by bogban** [shtrih-m/fr_drv_ng#79]
Здравствуйте!
Я уже обращался по поводу сборки для iOS в этой задаче:
https://github.com/shtrih-m/fr_drv_ng/issues/75

Вы собрали динамические библиотеки .dylib, которые замечательно работали при отладке на устройстве, но при выкладке в App Store обнаружилось, что политика Apple не допускает подключения динамических библиотек.

В связи с этим, не могли бы вы собрать framework для подключения в iOS?

**Comment by bogban** [comment]
Есть ли какой-то прогресс?

**Comment by swex** [comment]
Сейчас нет ресурсов для этого. Нужно изучить матчасть, что собственно требуется чтобы из динамической библиотеки сделать "фреймворк" iOS? Что мешает вам на своей стороне это сделать?

**Comment by bogban** [comment]
Не из нее, а вместо нее)
Вот у CMake есть опция FRAMEWORK.
Возможно, ее можно прописать и в leetal/ios-cmake с опцией -DPLATFORM="OS", как и в 75 тикете.

**Comment by bogban** [comment]
https://drive.google.com/drive/folders/1syLdtG85NaLGHX4Mi5Aj4DZn695fj_xP?usp=sharing

Вот как собрано у АТОЛ

**Comment by bogban** [comment]
@swex , прошу прощения за навязчивость, но очень нужно решить эту проблему поскорее.
Пожалуйста, пересоберите библиотеку или все-таки скиньте исходники в личку, чтобы я тоже попробовал это сделать.

**Comment by swex** [comment]
@bogban вот [это оно](https://yadi.sk/d/_9MUx3bzAGzWkQ)?

**Comment by bogban** [comment]
Да, похоже на то, спасибо. Проверю и отпишусь

**Comment by bogban** [comment]
https://drive.google.com/open?id=1iSZTFvozacHXHCOGcdiL2w0mArUDYFu-

Я изменил настройки для файлов Info.plist, и все заработало.
Сначала из бинарного формата преобразовал их в xml 1.0,
после этого при деплое xcode начал ругаться на поля, там не было CFBundleIdentifier, CFBundleVersion, CFBundleShortVersionString.
Еще на всякий случай поменял CFBundleDevelopmentRegion и убрал какой-то ключ, связанный с signing, там были знаки вопроса.
После этого все задеплоилось.
Большое спасибо!
