### ISSUE TITLE
Денежные регистры

### ISSUE THREAD

**Issue by susloparov77** [shtrih-m/fr_drv_ng#8]
GetCashReg и GetCashRegEx, можете дать кусочек кода как правильно извлекать данные
через денежные регистры GetCashReg и GetCashRegEx? Мне нужно получить сумму в денежном ящике?

**Comment by olefard** [comment]
```
int regNumber = 241;// сумма в денежном ящике
ci->Set_RegisterNumber(regNumber)
checkResult(ci->GetCashReg());
auto value = ci->Get_ContentsOfCashRegister();
auto regName = ci->Get_NameCashReg();// можно посмотреть имя регистра
```

Кроме того для суммы в денежном ящике есть отдельный метод:
```
checkResult(ci->ReadCashDrawerSum());
auto value = ci->Get_Summ1();//сумма в денежном ящике
```

**Comment by swex** [comment]
На ККТ будет выполнена одна и та же команда. Разница только в интерфейсе на стороне пользователя драйвера.

**Comment by olefard** [comment]
> А в чем разница между первым и вторым?
Да, разницы абсолютно нет. Внутри второго метода вызывается код из первого. Просто первый привел как пример работы с регистрами.

**Comment by susloparov77** [comment]
Спасибо
