### ISSUE TITLE
Сборка под Android

### ISSUE THREAD

**Issue by trufanov-w** [shtrih-m/fr_drv_ng#80]
Здравствуйте.
Мы используем Ваши сборки библиотек под ios, android, linux и windows
При сборке приложения с библиотеками под андроид, выдается ошибку JNI, пытаясь вызвать метод usbcdcacmhelper
Вот полный текст:
jni detected error in application: jni newglobalref called with pending exception java.lang.classnotfoundexception: didn't find class "ru.shtrih_m.fr_drv_ng.android_util.usbcdcacmhelper" on path: dexpathlist

Под другие ОС все собирается нормально.

**Comment by swex** [comment]
смотрите [пример](https://github.com/shtrih-m/fr_drv_ng_examples/tree/master/classic_fr_drv_ng_android_example) под android, необходима библиотека `android_util_fr_drv_ng-release.aar` она есть в сборках
