### ISSUE TITLE
Чек Коррекции (FNOpenCheckCorrection)

### ISSUE THREAD

**Issue by rulweb** [shtrih-m/fr_drv_ng#82]
Здравствуйте, реализован ли метод FNOpenCheckCorrection?
Если реализован какие условия нужны для его использования?

Сейчас при вызове мне пишет ошибку:

> -12; Не поддерживается в данной версии драйвера

Версия драйвера: 1.4.4-10-g5347239

**Comment by surfernsk** [comment]
> справка для реализованных методов доступна в заголовочном файле classic_interface.h в формате doxygen. Заголовочный в сборках рядом с нативными библиотеками.

Используйте:
 ```
FNBeginCorrectionReceipt or FNBeginCorrectionReceipt2
FNBuildCorrectionReceipt or FNBuildCorrectionReceipt2
