### ISSUE TITLE
LoadGraphics512

### ISSUE THREAD

**Issue by t0pd3v1c3** [shtrih-m/fr_drv_ng#83]
Здравствуйте. Каким образом можно пользоваться загрузкой графики через LoadGraphics512?
В документации нет информации по ней.

**Comment by surfernsk** [comment]
Внимательно посмотрите в classic_interface.h 

> 

    //! @brief Загрузка графики 512
    //!
    //! @par Используемые свойства:
    //!  - #Password - пароль оператора
    //!  - #GraphBufferType - Тип графического буфера
    //!  - #LineLength - Длина линии 1…40 для GraphBufferType == 0; 1…64 для GraphBufferType == 1
    //!  - #FirstLineNumber - Номер начальной линии  1…1200 для GraphBufferType == 0; 1…600 для
    //!  GraphBufferType == 1
    //!  - #LineNumber - Количество последующих линий  1…1200 для GraphBufferType == 0; 1…600 для
    //!  GraphBufferType == 1
    //!  - #LineData - данные, размер должен быть равен LineNumber * LineLength
    //!
    //! @return Код ошибки
    //!
    int LoadGraphics512();
