### ISSUE TITLE
Значение markingType для обуви

### ISSUE THREAD

**Issue by JetFlynn** [shtrih-m/fr_drv_ng#84]
Здравствуйте, в wiki написано: "
int MarkingType

Тип маркировки товара

Может принмать значения: 2 - Изделия из меха 3 - Лекарственные препараты 5 - Табачная продукция".
А какое значение markingType для обуви?

**Comment by olefard** [comment]
Для обуви 5408

**Comment by olefard** [comment]
Для обуви надо передавать 0x444d

https://честныйзнак.рф/upload/iblock/34f/Protokol_informatsionnogo_obmena_OFD.pdf
В нем на странице 21 описан состав тега 1162. Для GS1 DataMatrix(используется в маркировке обуви) передается 444dh

И еще [здесь](https://честныйзнак.рф/upload/%D0%A0%D0%B5%D0%BA%D0%BE%D0%BC%D0%B5%D0%BD%D0%B4%D0%B0%D1%86%D0%B8%D0%B8_%D0%BF%D1%80%D0%B8_%D1%80%D0%BE%D0%B7%D0%BD%D0%B8%D1%87%D0%BD%D0%BE%D0%B9_%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8.pdf).

Изделия из меха: MarkingType = 0x5246
Лекарственные препараты: MarkingType = 0x444d
Табачная продукция: MarkingType = 0x444d
