### ISSUE TITLE
Выравнивание текста при печати через PrintString

### ISSUE THREAD

**Issue by bogban** [shtrih-m/fr_drv_ng#85]
Здравствуйте!
Возник вопрос - можно ли как-то выравнивать произвольный текст, печатаемый на чеке?
Я нашел метод Set_Printing_Alignment, но он, похоже, ни на что не влияет.

**Comment by surfernsk** [comment]
Данный метод не реализован. (отсутствует описание)

**Comment by olefard** [comment]
> можно ли как-то выравнивать произвольный текст, печатаемый на чеке?
Драйвер не выравнивает. Только самим, добавляя при необходимости пробелы в начало строки.

> Я нашел метод Set_Printing_Alignment, но он, похоже, ни на что не влияет.
Это свойство использовалось при печати подкладного документа.
