### ISSUE TITLE
Не корректно пишется таблица 18.1.9

### ISSUE THREAD

**Issue by antkym** [shtrih-m/fr_drv_ng#86]
+ /opt/shtrih/cli/console.sh write 18.1.9 '301766,Москва,Донская улица 128'
Value is out of range
+ /opt/shtrih/cli/console.sh kkt-reg-begin 2
+ /opt/shtrih/cli/console.sh kkt-rereg-report 1.1.3

Если писать через Restore tables записывается - Донская улица 128.

**Comment by swex** [comment]
1. нужен лог
2. на актуальной версии тоже?

**Comment by antkym** [comment]
Приложил лог.
[fr_drv.log](https://github.com/shtrih-m/fr_drv_ng/files/3808339/fr_drv.log)

**Comment by swex** [comment]
1. обновите тест до актуальной версии
2. нужен лог от запуска теста, т.к. в этом логе нет аргументов командной строки

**Comment by antkym** [comment]
Какой путь к этому логу?

**Comment by swex** [comment]
```c++
//! @brief Логгирование в драйвере глобальное и включено всегда.
//!
//! Управление происходит через следующие переменные окружения <br>
//! * FR_DRV_DEBUG_CONSOLE - если определено весь вывод лога будет на stderr <br>
//! * FR_DRV_LOG_PATH - путь файла лога(по умолчанию fr_drv.log в рабочей директории)<br>
//! * FR_DRV_LOG_FILE_COUNT - кол-во ротаций(по умолчанию 2)<br>
//! * FR_DRV_LOG_PART_SIZE - размер части в байтах (по умолчанию 1024 * 1024 * 10)<br>
//! * FR_DRV_LOG_FLAGS - флаги логгирования, битовая маска со следующими ключами(по умолчанию
//! всё включено)
//!
//!     * 1 << 0 - логгировать обмен
//!     * 1 << 1 - логгировать каждый read/write в IoLayer, иначе аккумулировать
//!     * 1 << 2 - логгировать отладку протокола
//!     * 1 << 3 - логгировать статистику протокола
//!     * 1 << 4 - логгировать отладку функций-утилит
//!     * 1 << 5 - логгировать отладку вызовов интерфейсов верхнего уровня (classic,upos, итд)
```

**Comment by antkym** [comment]
С каким ядром драйвер работает? Обновил выдает ошибку
FATAL: kernel too old
Наша система
4.9.110-x5 #3 SMP Tue Sep 25 00:09:48 MSK 2018 i686 GNU/Linux

**Comment by swex** [comment]
с 4.9 точно работает.
Вы какую сборку берете? Попробуйте `i486_ok`
