### ISSUE TITLE
Обертка под C#

### ISSUE THREAD

**Issue by Rustamer** [shtrih-m/fr_drv_ng#87]
Хотелось бы видеть также нативную обертку под .NET Framework / .NET CORE,  т.к. сейчас увы приходится использовать старый закрытый драйвер и COM-компоненты. Спасибо.

**Comment by swex** [comment]
для генерации python и java биндингов используется [swig](http://www.swig.org/)
с C# проблем быть не должно. [смотрите доку](http://www.swig.org/Doc4.0/CSharp.html) и генерируйте как-то так:
```bash
swig -c++ -csharp classic_interface.i
```
сам файл `classic_interface.i` лежит в архивах со сборками.

**Comment by waltzofwoe** [comment]
Если Ваша платформа - Windows, то вы можете использовать C++/CLI, чтобы использовать в .NET  проектах этот драйвер как есть. Никаких специальных оберток не требуется.
