### ISSUE TITLE
приходит ошибка после печати чека: java.lang.RuntimeException: error, bad return code: -1 (Inout error) 

### ISSUE THREAD

**Issue by natalia-kuznetsova** [shtrih-m/fr_drv_ng#89]
[log-2019-11-14 (3) (1).txt](https://github.com/shtrih-m/javapos_shtrih/files/3955596/log-2019-11-14.3.1.txt)
При проведении операции на 790,00 руб (заказ "order_number":"F-19-1114-851786-00001-00007") оплата происходила по карте MIR Credit
После одобрения успешной операции появляется ошибка:
17:43:31.665 [RxComputationScheduler-4] ERROR c.i.printerlib.shtrihm.ShtrihM - Exception
java.lang.RuntimeException: error, bad return code: -1 (Inout error) 
Подскажите почему может возникнуть данная проблема?

**Comment by swex** [comment]
Переместил проблему из javapos репо в этот, кажется, вы используется этот драйвер. Что это за библиотека? Почему-то в представленных логах нет вызовов драйвера?

**Comment by olefard** [comment]
Ошибка -1 - нет связи с кассой.
Какой таймаут задаете перед вызовом Connect? Попробуйте его увеличить.
