### ISSUE TITLE
при вызове метода FNCloseCheckEx() приходит ошибка 94 (ККТ: Неверная операция).

### ISSUE THREAD

**Issue by natalia-kuznetsova** [shtrih-m/fr_drv_ng#90]
При проведении операции на 330,00 руб заказ F-19-1114-851786-00001-00006
Исходя из логов произошла ошибка при проведении операции: java.lang.RuntimeException: error, bad return code: 94 (ККТ: Неверная операция)
После чего, исходя из скринов по операции произошла автоотмена

Аналогочная ошибка при проведении операции на 850,00 руб (заказ F-19-1114-851786-00001-00005)

есть проблема, при вызове метода FNCloseCheckEx() приходит ошибка 94 (ККТ: Неверная операция). Это из-за чего может происходить?

**Comment by olefard** [comment]
Ошибка 94 может возникать, если открыт чек одного типа, а операции делаются другого. Например открыт чек прихода, а операции делаются расхода.

Хорошо бы увидеть лог драйвера.
