### ISSUE TITLE
Как работают сигналы: ECRModeChange и ConnectedChange?

### ISSUE THREAD

**Issue by DowJhob** [shtrih-m/fr_drv_ng#91]
Коннекте испускается только при установке связи, при разрыве ничего, при смене режима со 2го на 4ый и снова на 2ой сигнала нет, на 4ый есть, в линукс вообще этого сигнала нет

**Comment by swex** [comment]
речь, я так понимаю, идёт о `QClassic`, свойства меняются не сами собой, а только при запросах. Соотв. чтобы, например,  свойство `ECRMode` поменялось - нужно вызвать один из методов, который модифицирует `ECRMode` - `GetECRStatus` или `GetShortECRStatus`.  

То же касается и `Connected`. Если выполнить `Disconnect` - `Connected` станет `false`

Сам объект ничего не делает в фоне и не меняет свойства без участия пользователя. Те эти сигналы, просто вспомогательная Qt специфичная обёртка чтобы не перечитывать `вручную` **все** модифицируемые методом свойства.

**Comment by DowJhob** [comment]
сам то ккт асинхронен? или после каждой команды нужно ждать ответ до выдачи следующей?

**Comment by swex** [comment]
> сам то ккт асинхронен?

нет, всё синхронно когда метод возвращается, уже все свойства просигналят.

**Comment by DowJhob** [comment]
не, я про в чистом виде, если я с помощью сокета буду слать команды на низком уровне, могу ли я слать команды не ожидая подтверждения исполнения, а с помощью readyRead  читать ответы асинхронно и парсить их отдельно?

**Comment by swex** [comment]
Сам протокол синхронный, разумеется вы можете использовать readyRead, на низком уровне, но вы не сможете подать следующую команду, пока не получите ответ на предыдущую. Нет смысла реализовывать обмен асинхронно в основном цикле событий. Если хотите чтобы GUI не спал, лучше вытащить работу с ККТ в фоновый поток.
