### ISSUE TITLE
Планируется ли драйвер для взаимодействия 1С с оборудованием штриха под Linux?

### ISSUE THREAD

**Issue by vlad-github79** [shtrih-m/fr_drv_ng#92]
Здравствуйте.

Собственно, сабж. Если да, то когда?

Спасибо!

**Comment by swex** [comment]
Здравствуйте!
Да, 1С Native API драйвер сейчас в разработке. Думаю, ориентироваться можно на февраль.

**Comment by vlad-github79** [comment]
Супер! Спасибо большое!

**Comment by surfernsk** [comment]
Здравствуйте.
Есть новости о 1С Native API драйвере?

**Comment by swex** [comment]
Первый публичный релиз доступен в релизах по [ссылке](https://github.com/shtrih-m/fr_drv_ng/releases/download/1.5.0/one_s_fr_drv_ng1.5.0.zip).
