### ISSUE TITLE
Версия тулчейна

### ISSUE THREAD

**Issue by ivan-vl-kasyanov** [shtrih-m/fr_drv_ng#93]
Здравствуйте!

Скажите пожалуйста, на какой версии тулчейна была собрана версия 1.4.4-13 под ОС MS Windows? Спасибо!

**Comment by swex** [comment]
Собирается с актуальным MSVC 2017 на данный момент это 15.9.18. Оно, кажется, обратно совместимо с MSVC 2015. Поэтому нужен vcredist 2015 или 2017.

**Comment by ivan-vl-kasyanov** [comment]
А какова была версия самого MSVC? Последняя версия для 2017 – 14.16, последняя для 2019 – 14.24 (на 15.01.2020).

**Comment by swex** [comment]
```cmd
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27034 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.
```
