### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by deepfunction** [shtrih-m/fr_drv_ng#95]
Здравствуйте! Пытаюсь собрать пример на джаве в линуксе x86-64. Библиотеки so и jar добавил, как в инструкции. И получаю такую ошибку:

Exception in thread "main" java.lang.UnsatisfiedLinkError: ru.shtrih_m.fr_drv_ng.classic_interface.classic_fr_drv_ngJNI.new_classic_interface()J
at ru.shtrih_m.fr_drv_ng.classic_interface.classic_fr_drv_ngJNI.new_classic_interface(Native Method)
at ru.shtrih_m.fr_drv_ng.classic_interface.classic_interface.<init>(classic_interface.java:45)
at example.main(example.java:17)

Подскажите, пожалуйста, что не так.

**Comment by swex** [comment]
Где лежат *.so? Java не может найти их. Убедитесь что нативные библиотеки лежат где-то в java.library.path

**Comment by deepfunction** [comment]
В java.library.path положил libclassic_fr_drv_ng.so, libclassic_fr_drv_ng.so.1.4, libcppbase_fr_drv_ng.so,  libcppbase_fr_drv_ng.so.1.4.0.918, libqclassic_fr_drv_ng.so и jar-ник classic_java_fr_drv_ng-1.4.1.jar, который в проекте был в папке lib. Что-то упустил?

**Comment by swex** [comment]
стоп, а почему jar версии 1.4.1? Нужно 1.4.4 из архива fr_drv_ng_java_wrappers из [актуального релиза.](https://github.com/shtrih-m/fr_drv_ng/releases)

**Comment by deepfunction** [comment]
Так, в понедельник попробую, спасибо!

**Comment by deepfunction** [comment]
Да, собрался, спасибо! Теперь падает на checkResult(ci.Connect()); error:error, bad return code: -1 Надо еще что-то поставить? Или сonnectionURI не тот? А как узнать куда коннектится? У нас тут штрих-on-line по usb.

**Comment by swex** [comment]
`ConnectionURI`, по USB ККТ может работать в двух режимах:
1. cdcacm - usbserial ищите в логах ядра какой порт оно выдало для ККТ 
2. rndis - usbnet должен появиться сетевой интерфейс, установите в нем статический айпи из подсети 192.168.137.* у ККТ по умолчанию IP: 192.168.137.111 порт 7778
