### ISSUE TITLE
Универсальный код для поля markingType

### ISSUE THREAD

**Issue by groleore** [shtrih-m/fr_drv_ng#96]
Здравствуйте. С 1 марта 2020 года ККТ и кассовое ПО должны соответствовать изменениям в ФФД. Теперь для всей продукции, маркированой GS1 DataMatrix, должно передаваться значения поля markingType = 0x44 0x4d. Есть несколько вопросов:
1) Будут ли на бумажном чеке какие пометки, что товар маркированный? Например так: https://partner.atol.ru/files/userfiles/Chek_bumazhnyy_elektronnnyy.jpg? Такие пометки обязательны или достаточно наличия заполненного тэга 1162 в электронном чеке?
2) Какая должна быть версия прошивки ФР и какая версия драйвера для корректной работы с новой формой маркировки? На форуме писали, что нужно ждать новую прошивку для корректной валидации нового типа маркировки товара?

**Comment by olefard** [comment]
> Будут ли на бумажном чеке какие пометки, что товар маркированный? 

На обновленных прошивках будет печататься [М]

> Такие пометки обязательны или достаточно наличия заполненного тэга 1162 в электронном чеке?

По приказу ФНС с 1 марта пометки обязательны.

> Какая должна быть версия прошивки ФР и какая версия драйвера для корректной работы с новой формой маркировки? На форуме писали, что нужно ждать новую прошивку для корректной валидации нового типа маркировки товара?

Если передавать готовый тег 1162, то драйвер можно не обновлять. Версию прошивки ФР пока сказать не могу.

На днях должна выйти версия драйвера с методом FNSendItemBarcode.
Тогда работа с маркированным товаром будет выглядеть таким образом:
```
...
ci.FNOperation();

// передается непосредственно код маркировки
ci.Set_BarCode("010460406000600021N4N57RSCBUZTQ\u001d2403004002910161218\u001d1724010191ffd0\u001d
92tIAF/YVoU4roQS3M/m4z78yFq0fc/WsSmLeX5QkF/YVWwy8IMYAeiQ91Xa2z/fFSJcOkb2N+uU
Umfr4n0mOX0Q==");
ci.FNSendItemBarcode();
```
