### ISSUE TITLE
Отладка печати фискальных чеков

### ISSUE THREAD

**Issue by ayarosh0** [shtrih-m/fr_drv_ng#99]
Здравствуйте. Можно ли отладить печать фискальных чеков на устройстве без ФН?
При вызове OpenCheck  я получаю ошибку 48 - No answer from FN. Возможно отключение проверки ФН?
Обычные строки печатаются без проблем

Лог:
V/fr_drv_ng: [2020-03-06 12:02:49.689] [4821] [classic_interface_0x77d1647480  ] [T] Set_CheckType(`0`)
V/fr_drv_ng: [2020-03-06 12:02:49.689] [4821] [classic_interface_0x77d1647480  ] [T] Set_CheckType() ok
V/fr_drv_ng: [2020-03-06 12:02:49.689] [4821] [classic_interface_0x77d1647480  ] [T] OpenCheck()
D/fr_drv_ng: [2020-03-06 12:02:49.690] [4821] [BtSerialIO_0x77eb5d4180         ] [D] -> 8F 08 00 15 00 8D 01 00 00 00 00 4A EE
D/fr_drv_ng: [2020-03-06 12:02:51.622] [4821] [BtSerialIO_0x77eb5d4180         ] [D] <- 8F
D/fr_drv_ng: [2020-03-06 12:02:51.622] [4821] [BtSerialIO_0x77eb5d4180         ] [D] <- 04 00 15 00 8D 30 C4 F4
D/fr_drv_ng: [2020-03-06 12:02:51.622] [4821] [ProtocolV2_0x77eb773dc0         ] [D] command 8D return code: 48 execution took 1932ms
E/fr_drv_ng: [2020-03-06 12:02:51.622] [4821] [ProtocolV2_0x77eb773dc0         ] [E] No answer from FN
D/fr_drv_ng: [2020-03-06 12:02:51.622] [4821] [ProtocolV2_0x77eb773dc0         ] [D] commands total: 22, succeed: 19, failed: 3, avg. exec time: 118ms
D/fr_drv_ng: [2020-03-06 12:02:51.623] [4821] [classic_interface_0x77d1647480  ] [D] OpenCheck() fail
E/fr_drv_ng: [2020-03-06 12:02:51.623] [4821] [classic_interface_0x77d1647480  ] [E] No answer from FN
V/fr_drv_ng: [2020-03-06 12:02:51.623] [4821] [classic_interface_0x77d1647480  ] [T] Get_ResultCode()
V/fr_drv_ng: [2020-03-06 12:02:51.623] [4821] [classic_interface_0x77d1647480  ] [T] Get_ResultCode() -> `48`
V/fr_drv_ng: [2020-03-06 12:02:51.623] [4821] [classic_interface_0x77d1647480  ] [T] Get_ResultCodeDescription()
V/fr_drv_ng: [2020-03-06 12:02:51.623] [4821] [classic_interface_0x77d1647480  ] [T] Get_ResultCodeDescription() -> `No answer from FN`
E/SHTRICHHH: 48: No answer from FN
V/fr_drv_ng: [2020-03-06 12:02:51.624] [4821] [classic_interface_0x77d1647480  ] [T] Disconnect()
I/fr_drv_ng: [2020-03-06 12:02:51.624] [4821] [ProtocolV2_0x77eb773dc0         ] [I] disconnect()

**Comment by swex** [comment]
Нет, без ФН не получится.

**Comment by ayarosh0** [comment]
Можно ли будет печатать чеки без регистрации ФН?

**Comment by swex** [comment]
Тоже нет. ФН по разному себя ведёт в зависимости от параметров фискализации. Поэтому нет, никак. Для отладки чеков нужен ФН.

**Comment by ayarosh0** [comment]
Спасибо
